### ISSUE TITLE
add units to desi_spectro_calib files

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1017]
Review all calib files in desi_spectro_calib and make sure they have correct units.  Future us will thank present you.

BUNIT is the keyword to use for images; TUNITnn is the keyword to use for table columns.

`astropy.units.Unit(str)` is useful for checking whether the unit you are using follows standards (e.g. "e/s" vs. "e/sec" vs. "electron/sec" vs. "electrons/s" vs. ...)

**Comment by julienguy** [comment]
So we will set the following BUNIT values:
 - master bias: "adu"
 - master dark: "electron/s"
 - pixel flat: ""
 - pixel mask: ""
 - preprocessed image: "electron"
 
and change the codes to produce those accordingly.

**Comment by julienguy** [comment]
Working on it in branch 'bunit'. Also committing modifications to existing files in calibration repo. I am not touching for now fits files or code that could interfere with bias+dark work (in PR #1013).

**Comment by sbailey** [comment]
updated in desi_spectro_calib.  closing ticket.
