### ISSUE TITLE
compress desi_spectro_calib files

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1021]
gzip compress calibration files in desi_spectro_calib to reduce the size of individual checkouts.  The integer pixmasks gzip very well since they are mostly zeros.

Also convert all biases, darks, and pixflats from double to float and gzip them, which provides 3-4x savings (normally floats don't compress well, but these do reasonably well).

Also remember to update all yaml files to change *.fits -> *.fits.gz .

We've had some trouble with large batch commits to svn, so consider automating this to update and commit files one by one (and make sure that the old .fits file is removed from svn trunk, not just that the .fits.gz is added).

**Comment by julienguy** [comment]
doing pixmask (conversion to int16 then gzip)

**Comment by julienguy** [comment]
* pixmask: 65M (some 130M!) -> ~40K
* pixflat: 260M -> ~93M (float64 to float32+gzip)
* bias: 137M -> ~30M (float64 to float32+gzip)
* dark: 137M -> ~40M (float64 to float32+gzip)

**Comment by julienguy** [comment]
All calib files have been converted and compressed.
Changes to the code done in PR #1022 and PR #1023 .
