### ISSUE TITLE
The rawimage size in test_preproc.py is far from reality

### ISSUE THREAD

**Issue by zkdtc** [desihub/desispec#1024]
In test_preproc.py, line 68-72, the simulated raw image size is hard coded to 500\times 400+50overscan,resulting 1100\times 900 image which is far from the real 4k\times4k image. Propose to change it to a real image, or change to a simulated image more closer to real size.

**Comment by weaverba137** [comment]
Some combination of @sbailey & @tskisner worked on that code, so assigning to them.  I can say though that based on comments in the code the choice appears to have been deliberate, possibly for performance reasons.

**Comment by sbailey** [comment]
The test image is purposefully smaller than 4k x 4k so that tests run faster.  This does require a workaround for the "measure the readnoise from the data region" in PR #1041 but @zkdtc has already added that.  Closing this ticket.
