### ISSUE TITLE
desi_preproc sys.exit(code) != unix error code when using multiprocessing

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1037]
For some reason, the error code returned by bin/desi_preproc via sys.exit(code) does not match the value that unix interprets as the error code when using multiprocessing even if everything succeeded.

e.g. using the preproc_returncode branch which has some extra debug printouts and explicit `pool.close()` and `pool.join()` calls:
```
<cori> desi_preproc -n 20200315 -e 55611 --cameras b0,r0,z0 --outdir .
INFO:preproc.py:196:main: Processing 3 cameras with 3 multiprocessing processes
...
desi_preproc calling sys.exit(0)
0
<cori> echo $?
1
```
Note the extra "0" after the final "desi_preproc calling sys.exit(0)" -- I don't know where that is coming from but it might be a clue.

However, this doesn't occur when not using multiprocessing:
```
<cori> desi_preproc -n 20200315 -e 55611 --cameras b0,r0,z0 --outdir . --ncpu 1
INFO:preproc.py:205:main: Not using multiprocessing for 3 cameras
...
desi_prepoc calling sys.exit(0)
<cori temp> echo $?
0
```

Since this only occurs with multiprocessing, I suspect that there is some resource that is not being properly released within the Pool processes and that is triggering an error upon exit, but I'm not sure what that is or how to find it.  I also tried using the Pool as a context manager instead of using explicit close/join and that also didn't work.

This fortunately doesn't impact the pipeline which calls desi_preproc one camera at a time and thus bypasses multiprocessing (the parallelism over cameras is handled by MPI at a higher level).  But it is a little irritating for things like the integration test which incorrectly thinks that desi_preproc has failed if it is called on multiple cameras with multiprocessing enabled.

Any ideas @weaverba137 or others?

**Comment by weaverba137** [comment]
[The documentation for `sys.exit()`](https://docs.python.org/3.8/library/sys.html?highlight=sys.exit#sys.exit) gives some pretty clear clues:

* `sys.exit()` does not actually terminate the program. It raises `SystemExit`.
* An overly permissive `except` could catch this error, or it gets involved in an incomplete `finally` clause.
* `sys.exit()` returns 1 to the operating system if it is called with anything besides an integer or `None`.

One place to start would be to eliminate all
```python
try:
    #...
except:
    #...
```
That catch all possible exceptions, and which are discouraged anyway.

**Comment by sbailey** [comment]
Ah ha!  Very good!  It was the last hint of the documentation that was the problematic case.  When using multiprocessing, `desispec.scripts.preproc.main` was returning `num_failed = np.sum(failed)` which is a `numpy.int64`, whereas the non-multiprocessing version was accumulating the number of failures in a genuine `int`.  Ensuring that `preproc.main` always returns a vanilla `int` makes it work.  Thanks @weaverba137 .  PR forthcoming.
