### ISSUE TITLE
Absolute symlinks in reductions are invalid on other filesystems

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#1051]
The daily reductions (desi/spectro/redux/daily) contain absolute symlinks such as:
```
exposures/20201214/00067768/stdstars-0-00067768.fits -> /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201214/00067744/stdstars-0-00067744.fits
```
These links are not valid on any other filesystem, such as the NOIRLab Mirror.  These should be changed to relative links.  In this example:
```
exposures/20201214/00067768/stdstars-0-00067768.fits -> ../00067744/stdstars-0-00067744.fits
```
would be valid anywhere.

**Comment by sbailey** [comment]
Fixed in PR #1056.  Closing.

**Comment by weaverba137** [comment]
I have to reopen this issue, because the daily reductions *still* contain absolute symlinks that are invalid on the Tucson mirror.  Here's an example:

```
dashboard/links/202101/arc-20210106-00071034-a0123456789-37715282.log -> /global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/night/20210106/arc-20210106-00071034-a0123456789-37715282.log
```

Please thoroughly review *all* symlink creation code and make sure *all* symlinks are relative.  Please also fix all existing absolute symlinks.

**Comment by sbailey** [comment]
@zkdtc could you update the dashboard code to only use relative links instead of absolute links, and search all desispec code for `os.symlink` calls for other places that may need absolute -> relative fixes?  Thanks.

**Comment by sbailey** [comment]
@zkdtc can you take care of converting the absolute links in the dashboard into relative links (or otherwise confirm that it no longer generates absolute links)?  From an earlier comment, e.g.

```
dashboard/links/202101/arc-20210106-00071034-a0123456789-37715282.log -> /global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/night/20210106/arc-20210106-00071034-a0123456789-37715282.log
```

Thanks

**Comment by zkdtc** [comment]
Sure~

**Comment by zkdtc** [comment]
In desi_proc_dashboard, the ln command uses absolute directory now. Below is an example: 
" ln -s /global/cfs/cdirs/desi/spectro/redux/cascades/run/scripts/night/20210116/poststdstar-20210116-00072716-a0123456789-39626671.log /global/cfs/cdirs/desi/www/users/zhangkai/new/links/202101/poststdstar-20210116-00072716-a0123456789-39626671.log "

**Comment by weaverba137** [comment]
@sbailey, I was going to close this issue as something we'd fixed a long time ago, but then I thought I'd check.  Turns out this is not fixed.  There are still about 23,000 absolute symlinks in the daily reductions, in the `calibnight` and `exposures` directories. The absolute symlinks in the `exposures` directories predate this ticket, *but* many of them link to `/global/project/projectdirs/desi`.  However the remaining absolute symlinks in the `calibnight` were created *long after* this ticket. So we actually need to go in and check the code for creating symlinks in `calibnight`.

**Comment by akremin** [comment]
Hi Ben,

If you can point me to the most recent examples, I'm happy to investigate.
I did a quick search and didn't immediately find any in 2023.

Best,
Anthony

**Comment by weaverba137** [comment]
Thanx, the complete list is in `~desi/jobs/symlinks-13729862.log`.

**Comment by weaverba137** [comment]
There aren't any from *2023*, but there are some from December 2022, which is still long after this ticket was created.

**Comment by akremin** [comment]
There is good news here. There are no exposures/ files since 2020, which were created before the work in this ticket. All calibnight's were one-off links made by humans because there were no valid calibrations available on the given night. This is sometimes done in daily to improve the processing, which would otherwise use less up-to-date files in svn. I will add additional documentation to the daily processing wiki page to detail that these should always be relative links.

**Comment by weaverba137** [comment]
@akremin, thank you, that's what I was expecting.  Do you want to fix these symlinks, or should I?

**Comment by akremin** [comment]
If you have code to do it, please go ahead if you wouldn't mind. I would have to write a script, but can do so if you would be in the same situation.

**Comment by weaverba137** [comment]
OK, no problem.

**Comment by weaverba137** [comment]
But I will at least wait until a break in processing before actually changing anything.

**Comment by akremin** [comment]
Thank you, Ben. I don't think there would be any conflicts as we are looking at old calibnight's or very old science exposures in the daily processing, but you are also welcome to wait if you wish. Today we have a few night's to process, so there may not be a break until after working hours.

**Comment by weaverba137** [comment]
I still have testing to do, so I probably wasn't going to be able to make changes this afternoon anyway.

**Comment by weaverba137** [comment]
I'm glad I tested.  Some of the symlinks have the form:
```
INFO: absolute symlink: /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20191207/00030974/psf-z2-00030974.fits -> /global/project/projectdirs/desi/spectro/desi_spectro_calib/trunk/spec/sp2/psf-sm3-z-science-slit-20191108.fits
ERROR: No target found for /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20191207/00030974/psf-z2-00030974.fits
```
This is actually a broken link, and the problem isn't that it's linked to `project/projectdirs` (that can be easily fixed), it's that `desi_spectro_calib/trunk/spec/sp2` doesn't exist!

However `desi_spectro_calib/trunk/spec/sm3/psf-sm3-z-science-slit-20191108.fits` does exit.

Is it safe to assume that if `spec/spX` doesn't exist then always replace `spec/spX` with `smX` in the file name?

**Comment by akremin** [comment]
@julienguy should weigh in here because sp2 used to refer to sm3 but now refers to sm5, and I don't remember the history behind that. At the time this file was created (2019) I think you're correct that it was sm3 (based on the file name linked to in the broken link).

The sp2 directory was moved under `/spec/old/sp2`, which is what broke the link. Clearly the `/old/` signifies that there was a reason for the move, but at the same time, this is old data that used that "old" file when it was processed.

I think pointing to either version of the file is okay, but since this is old data that presumably used the now deprecated file,  I would point to the `/old/` version.

**Comment by weaverba137** [comment]
While the `desi_spectro_calib` symlinks are being investigated, I can go ahead and replace the links in `calibnight` as well as some other links in `exposures` where the target of the link is unambiguous.

**Comment by weaverba137** [comment]
@julienguy, thank you for looking into that. I agree, but for now, we just want to clean up these historical links.

**Comment by weaverba137** [comment]
All absolute symlinks should now be fixed.
