### ISSUE TITLE
Skip bad exposures in the workflow

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1055]
Allow the user to give a list or point to a file that lists bad exposures for a given night. The workflow should skip over those exposures.

**Comment by sbailey** [comment]
Implemented in PR #1057 with new `desi_daily_proc_manager` options `--ignore-expid-list` and `--ignore-expid-file`.  We still need to implement a standardized external speclog product for tracking bad exposures and cameras that will apply to all future productions.
