### ISSUE TITLE
Verify stdstar and fluxcalib selection criteria for standard stars

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1066]
There was an edge case in the Dec 18th data where the we were able to calculate standard stars across exposures, but had all three exposures fail to use them for calibrations with errors saying there was no stars that passed cuts. This is likely the correct behavior, but it is worth verifying that these cuts are appropriate.

Details:
On 20201218, for tile 80620, we observed three observations. These had enough standard stars to perform the joint fitting of standard stars but fails for individual exposure flux calibration on all three exposures with the error: `ERROR:fluxcalibration.py:121:main: cuts discarded all stars`, for all 3 cameras of petal 6. 

This occurs for all three exposures, which indicates that the flux calibration is making more stringent cuts on the standard stars. 

Exposures: 68675, 68676, 68677

Example command:
`desi_compute_fluxcalibration --infile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/frame-r6-00068675.fits --sky /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/sky-r6-00068675.fits --fiberflat /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20201218/fiberflatnight-r6-20201218.fits --models /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/stdstars-6-00068675.fits --outfile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/fluxcalib-r6-00068675.fits --delta-color-cut 0.1`

Output:
```
INFO:fluxcalibration.py:72:main: desi_compute_fluxcalibration --infile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/frame-r6-00068675.fits --fiberflat /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20201218/fiberflatnight-r6-20201218.fits --sky /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/sky-r6-00068675.fits --models /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/stdstars-6-00068675.fits --chi2cut 0.0 --chi2cut_nsig 0.0 --delta_color_cut 0.1 --outfile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/fluxcalib-r6-00068675.fits --highest_throughput 0
INFO:fluxcalibration.py:74:main: read frame
INFO:fluxcalibration.py:81:main: apply fiberflat
INFO:fiberflat.py:721:apply_fiberflat: starting
INFO:fiberflat.py:750:apply_fiberflat: done
INFO:fluxcalibration.py:88:main: subtract sky
INFO:sky.py:1203:subtract_sky: starting with apply_throughput_correction = True and zero_ivar = True
INFO:sky.py:1230:subtract_sky: done
INFO:fluxcalibration.py:95:main: compute flux calibration
INFO:fluxcalibration.py:106:main: Apply cut |delta color|<0.1
ERROR:fluxcalibration.py:121:main: cuts discarded all stars
 Inputs
  /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/frame-r6-00068675.fits
  /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/sky-r6-00068675.fits
  /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20201218/fiberflatnight-r6-20201218.fits
  /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/stdstars-6-00068675.fits
 Outputs
  /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/fluxcalib-r6-00068675.fits
INFO:util.py:97:runcmd: Tue Dec 22 14:05:47 2020
CRITICAL:util.py:99:runcmd: FAILED desi_compute_fluxcalibration --infile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/frame-r6-00068675.fits --sky /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/sky-r6-00068675.fits --fiberflat /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20201218/fiberflatnight-r6-20201218.fits --models /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/stdstars-6-00068675.fits --outfile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201218/00068675/fluxcalib-r6-00068675.fits --delta-color-cut 0.1
```

**Comment by sbailey** [comment]
@julienguy @akremin and @sbailey discussed this and agreed that the fluxcalib cuts can legitimately be tighter than the stdstar cuts to exclude bad stdstar fits.  PR #1070 prints more informative messages about what is being cut and why, but these appear to be legitimate cases for cutting out standards.  Closing this ticket.
