### ISSUE TITLE
Dec 14th fibermap file generation still causing stdstar faiures

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1067]
On 20201214 there were a number of exposures transferred with fiberassign files with zero-values columns for targeting bits. These were meant to be solved with manual changes to the input data at NERSC. It appears to have worked in some cases, but not others. It's possible it's user error, but I removed all old files from preproc and exposures directories, ran on master versions of the code. and verified that new versions of the files do exist and have non-zero target columns.

There are 5 total exposures experiencing this problem, composing two complete tiles:

Tile 80605: ExpIDs 67710, 67711, 67712, 67713
Tile 80606: ExpIDs 67733

Example of a failing command:
`desi_fit_stdstars --delta-color 0.1 --frames /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201214/00067710/frame-b0-00067710.fits /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201214/00067710/frame-r0-00067710.fits /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201214/00067710/frame-z0-00067710.fits --skymodels /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201214/00067710/sky-b0-00067710.fits /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201214/00067710/sky-r0-00067710.fits /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201214/00067710/sky-z0-00067710.fits --fiberflats /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20201214/fiberflatnight-b0-20201214.fits /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20201214/fiberflatnight-r0-20201214.fits /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20201214/fiberflatnight-z0-20201214.fits --starmodels /global/cfs/cdirs/desi/spectro/templates/basis_templates/v3.2/stdstar_templates_v2.2.fits --outfile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20201214/00067710/stdstars-0-00067710.fits`

Output:
```
ERROR:fluxcalibration.py:65:isStdStar: No standard stars found in SV1_DESI_TARGET
WARNING:fluxcalibration.py:68:isStdStar: Using FA_TYPE to find standard stars instead
ERROR:stdstars.py:181:main: no STD star found in fibermap
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_fit_stdstars", line 20, in <module>
    stdstars.main(args)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/scripts/stdstars.py", line 182, in main
    raise ValueError("no STD star found in fibermap")
ValueError: no STD star found in fibermap
```

I was also able to duplicate it in a separate test prod with the following:
`desi_proc -n 20201214 -e 67710 --batch`

**Comment by sbailey** [comment]
Indeed, rerunning `assemble_fibermap -n 20201214 -e 67710 -o fibermap-00067710.fits`:
```
INFO:fibermap.py:405:assemble_fibermap: Night 20201214 spectro expid 67710
INFO:fibermap.py:406:assemble_fibermap: Raw data file /global/cfs/cdirs/desi/spectro/data/20201214/00067710/desi-00067710.fits.fz
INFO:fibermap.py:407:assemble_fibermap: Fiberassign file /global/cfs/cdirs/desi/spectro/data/20201214/00067710/fiberassign-080605.fits.orig
...
```
Oops: it is finding `fiberassign-080605.fits.orig` (old, incorrect) before it is finding `fiberassign-080605.fits.gz` (new, correct).  I'll update `assemble_fibermap` ...
