### ISSUE TITLE
bootcalib : add options for flexibility in desi_bootcalib.py

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#107]
Add options to only extract traces with a continuum frame, or only do wavelength solution with a arc lamp frame (using a psf file as input for the trace locations) ...

We need a code to be able to run with a single exposure for quick analysis.

**Comment by profxj** [comment]
Please indicate which type of output you would like in the first case (traces only).

**Comment by julienguy** [comment]
The same PSF format as the currently implemented one in the output of desi_bootcalib.py
 * two HDUs for X and Y
 * WAVEMIN WAVEMAX in header 
 * legendre coefficient for each fiber as an ImageHDU

This format is convenient for : boxcar (tested), row by row extraction, and refined specex psf fit (tested)

**Comment by profxj** [comment]
Ok, and I will assume a dummy wavelength solution (the fits are 
in wavelength and we have none) ranging from 0 to ny.
