### ISSUE TITLE
fibermap headers lose the targets provenance in the original fiberassign files

### ISSUE THREAD

**Issue by moustakas** [desihub/desispec#1076]
This is a cross-post issue related to https://github.com/desihub/fiberassign/issues/300.

In order to figure out which target catalogs were used to build a given `fiberassign` file one cannot use the `fibermap` file that the spectroscopic pipeline delivers.

E.g., 
```
fahdr = fitsio.read_header('/global/cfs/cdirs/desi/spectro/data/20201216/00068291/fiberassign-080605.fits')
fmhdr = fitsio.read_header('/global/cfs/cdirs/desi/spectro/redux/daily/tiles/80605/20201216/spectra-0-80605-20201216.fits', 'FIBERMAP')

fahdr['TARG']
  '/global/cfs/cdirs/desi/target/catalogs/dr9/0.47.0/targets/sv1/resolve/dark/'

fmhdr['TARG']
  KeyError: 'unknown record: TARG'
```

I think the issue is the `io.fibermap.assemble_fibermap` script (https://github.com/desihub/desispec/blob/master/py/desispec/io/fibermap.py#L350) but I'm not 100% certain.

It's not a bug per se but it's really annoying!

**Comment by araichoor** [comment]
for information, I now add the following information in the fiberassign-TILEID.fits.gz zeroth-extension header (here for 080623):

GFA     = '/data/target/catalogs/dr9/0.47.0/gfas'                               
SKY     = '/data/target/catalogs/dr9/0.47.0/skies'                              
SKYSUPP = '/data/target/catalogs/gaiadr2/0.47.0/skies-supp'                     
TARG    = '/data/target/catalogs/dr9/0.47.0/targets/sv1/resolve/dark/'          
FAFLAVOR= 'sv1elg  '                                                            
OUTDIR  = '/software/datasystems/users/raichoor/fiberassign-test/desi-sv1-2020&'
CONTINUE  '1218/   '                                                            
PMTIME  = '2020-12-19T00:00:00.000'                                             
RUNDATE = '2020-03-06T00:00:00'                                                 
SCTARG  = 'STD_WD,ELG,BGS_FAINT'                                                
OBSCON  = 'DARK|GRAY|BRIGHT'                                                    
COMMENT = 'PRIORITY_INIT=2000 and NUMOBS_INIT=1 for BGS_FAINT'                  
COMMENT = 'PRIORITY_INIT=3000 and NUMOBS_INIT=1 for ELG'                        
COMMENT = 'PRIORITY_INIT=10000 and NUMOBS_INIT=1 for STD_WD'                    

the first tiles I designed have slightly less info (no PMTIME, SCTARG, COMMENT).

**Comment by sbailey** [comment]
The fibermap files inherit their header keywords from the input spectroscopic data file, but it would be useful to propagate a few of these header keywords from fiberassign files too.

@geordie666 is it algorithmically possible to map target entries to what file they came from?  e.g. RELEASE seems to encode part of the information, but I'm not sure if we've retained enough to determine (no)resolve, dark/bright, and desitarget version number.

**Comment by geordie666** [comment]
All of the necessary information is in the headers of the original target files. So, yes, it's algorithmically possible, although a little unwieldy. For example:

```
import os 
import fitsio 
from desitarget.io import find_target_files 
from desiutil import depend 

# ADM read in the header of an example target file.
infn = "$TARG_DIR/dr9/0.47.0/targets/main/resolve/dark/targets-dark-hp-148.fits" 
hdr = fitsio.read_header(infn, "TARGETS") 

# ADM this could be more elegant (i.e. we could actually allow gitver to be passed to the find_target_files() function). 
gitver = depend.getdep(hdr, 'desitarget-git')
os.system("git checkout {}".format(gitver))

# ADM all of the other elements of the filename can be built on-the-fly.
dr = depend.getdep(hdr, 'photcat') 
survey = hdr["SURVEY"] 
obscon = hdr["OBSCON"].split("|")[0] 
hp = hdr["FILEHPX"] 
resolve = hdr["RESOLVE"] 
supp=hdr["SUPP"] 
outfn = find_target_files("$TARG_DIR", dr=dr, flavor="targets", survey=survey, obscon=obscon, hp=hp, resolve=resolve, supp=supp)

# ADM now check the built filename corresponds to the input filename.
print(infn, outfn, infn == outfn)                                                                                                                                                                  

$TARG_DIR/dr9/0.47.0/targets/main/resolve/dark/targets-dark-hp-148.fits $TARG_DIR/dr9/0.47.0/targets/main/resolve/dark/targets-dark-hp-148.fits True
```

**Comment by sbailey** [comment]
@geordie666 it sounds like the information is in the *target* file to derive its own location, but those keywords aren't propagated to fiberassign or fibermap.  I think the GFA / SKY / SKYSUPP / TARG keywords with paths are equivalent, though those also need to be propagated to fibermap, and it sounds like for older fiberassign files the provenance back to the original target files is lost (in the files themselves).

Is there any extra value in propagating desitarget-git, photcat, SURVEY, OBSCON, RESOLVE, FILENSIDE, FILENEST and SUPP into the fiberassign file too?

**Comment by geordie666** [comment]
I don't know that there's _extra_ value in propagating those keywords, I'm just operating under the assumption that it's useful to propagate all of the keywords that were used to build filenames.

**Comment by araichoor** [comment]
if that helps the discussion:

- as said, I create in the fiberassign-TILEID.fits.gz 0-th header the GFA / SKY / SKYSUPP / TARG keywords, which report the directories used to generate the files that are given as input to fiberassign; as Stephen says, I think those contain *all* the information, no? e.g.:
    TARG = '/data/target/catalogs/dr9/0.47.0/targets/sv1/resolve/dark/'
[will update the kpno/nersc point discussed elsewhere]
so it looks to me that there is no need to propagate those desitarget keywords in fiberassign-TILEID.fits.gz (desitarget-git, photcat, SURVEY, OBSCON, RESOLVE, FILENSIDE, FILENEST and SUPP)

- OBSCON: one has to be careful here, because there also is an obscon in the fiberassign routines, which sets in which conditions the considered tile can be observed; I currently set all possible conditions for the sv1 tiles, e.g.:
    OBSCON  = 'DARK|GRAY|BRIGHT'
the desitarget-OBSCON appears in my TARG keyword.

- previous fiberassign files (e.g. https://desi.lbl.gov/svn/data/tiles/trunk/067/fiberassign-067142.fits): I also understand it s not possible to algorithmically track back the input desitarget folders...
