### ISSUE TITLE
dashboard: drop OTHER exposures, maybe ZEROs

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1089]
In the processing dashbaord, don't show rows for exposures with OBSTYPE=OTHER.

Consider dropping OBSTYPE=ZEROs too, at least until we are actually processing ZEROs to make a nightly bias.

**Comment by zkdtc** [comment]
Finished.

**Comment by zkdtc** [comment]
Revision included in PR #1127 to merge desi_proc_dashboard branch.
