### ISSUE TITLE
dashboard: different colors for 0/0, 0/n, m/n, n/n

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1091]
Within a row of the processing dashboard, highlight steps differently for:
 * 0/0 - this type of exposure isn't supposed to produce this file anyway
 * 0/n - no outputs
 * m/n - partial outputs
 * n/n - all outputs that should exist do exist

The goal it to make it easier/faster to see what step is failing and not be distracted by 0/0 or n/n entries.

**Comment by zkdtc** [comment]
Revision included in PR #1127 to merge desi_proc_dashboard branch.
