### ISSUE TITLE
spectra with flux ~0 and extremely small uncertainties (blanc)

### ISSUE THREAD

**Issue by segasai** [desihub/desispec#1100]
Hi, 

While looking at blanc data, I came upon this file 
/global/project/projectdirs/desi/spectro/redux/blanc/tiles/65008/20200314/coadd-8-65008-20200314.fits

and it's zero-th fiber for example. 

For some reasone the spectrum has a plenty of parts where both the spectrum and the uncertainty are extremely small. 
See for example the error-spectrum in the r-arm for 0th fiber (I only plot notmasked pixels):
![qq](https://user-images.githubusercontent.com/109513/104384372-41269600-5529-11eb-92a6-603dee54fca9.png)

This problem seems to persist across many spectra as far as I can see, which suggests to me, flux-calibration as a cause ? Or am I doing something wrong ? 

      S

**Comment by segasai** [comment]
![qq_117148](https://user-images.githubusercontent.com/109513/104514507-45b28380-55e9-11eb-807f-f97f55e98d7d.png)
![qq_226405](https://user-images.githubusercontent.com/109513/104515682-084ef580-55eb-11eb-80d2-f08a2e1e1e4f.png)
another couple of examples from the coadd (the exact image info is in the title)

**Comment by julienguy** [comment]
I am working on it. There are 2 exposures with very low transmission.

**Comment by julienguy** [comment]
I think it is solved in a PR to be submitted.
I reran the flux calibration for SP8 for this tile for 2020/03/14 and redid the coadd. It's there: 
`/project/projectdirs/desi/spectro/redux/jguy/tiles/65008/20200314/coadd-8-65008-20200314.fits`
@segasai  can you please check it?

**Comment by julienguy** [comment]
I am also going to rerun the 2 other examples.

**Comment by segasai** [comment]
Yes, it seems fine. Before to be able to still go through this file, I've had to clip the indivudal pixel uncertainties not be too small comparing to the median, and I was reporting if I had to clip too many pixels. Now none of that seems happening.

**Comment by segasai** [comment]
Thank you!

**Comment by julienguy** [comment]
After code fix, tile-80618-20201220-fiber-3396
![coadd-6-80618-20201220-fiber-3396](https://user-images.githubusercontent.com/5192160/105115246-4df13f80-5a7d-11eb-920a-279a84f726e4.png)

**Comment by julienguy** [comment]
And tile-70003-20200224-fiber-3215
![coadd-6-70003-20200224-fiber-3215](https://user-images.githubusercontent.com/5192160/105118337-0ec5ed00-5a83-11eb-8ba2-f63425ed1f35.png)
