### ISSUE TITLE
Bad fluxcalib vectors for SV1 blanc exposures

### ISSUE THREAD

**Issue by dkirkby** [desihub/desispec#1103]
I have done some QA on all of the blanc-processed exposures of SV1 (defined as EXPIME > 100, FLAVOR=science, NIGHT>=20201201, PROGRAM='SV*') and flagged a few, all from 20201222, with suspicious fluxcalib vectors:
 - 69453: b bad
 - 69458: b bad
 - 69400: b,r,z bad
 - 69416: b,r,z bad

I flagged these as having a fluxcalib ivar > 1e10 after doing an ivar-weighted coadd over spectrographs, but I haven't dug deeper to find the origin of the problem.

I also identified 4 exposures from 20201216 which appear to be outliers in flux*ivar, but I am not sure yet if these are real problems:
 - 68265
 - 68266
 - 68272
 - 68273

There is more detective work to do here, but it might already be worth making sure that these four 20201222 exposures are not used to build any VI products.

**Comment by julienguy** [comment]
Indeed. I am going to rerun the fluxcalib for these exposures using the code change of PR #1116.

**Comment by julienguy** [comment]
I have checked 69400,69416,69453,69458 are now ok (test prod in /global/cfs/cdirs/desi/spectro/redux/jguy)

**Comment by julienguy** [comment]
68265,68266,68272,68273 do not have calibration issues. I don't see any obvious issue in the cframes either. So I am closing this issue but don't hesitate to reopen it if I missed something.
