### ISSUE TITLE
bad chunk of spectra in Blanc in tile 80618

### ISSUE THREAD

**Issue by segasai** [desihub/desispec#1108]
Hi, 

While fitting for radial velocities in Blanc I've encountered a bad chunk of spectra
in spectra-6-80618-20201220.fits
Attaching the B_FLUX extension
![qq](https://user-images.githubusercontent.com/109513/104857212-cbe30880-590e-11eb-92f9-ac1f08f3ea9e.png)

Those spectra have crazy values and variances.

(I also assume that I am doing the right thing by submitting messages about these spectra here)

One clear way these bad spectra are highlighted in my code is that they have a lot of pixels (hundreds in each spectrum) where variance is much lower than the median variance (which normally shouldn't happen). that could be one of QA tests in principle.

**Comment by julienguy** [comment]
Solved with PR #1116 . See `/project/projectdirs/desi/spectro/redux/jguy/tiles/80618/20201220/coadd-6-80618-20201220.fits`
![Screenshot from 2021-01-19 18-42-12](https://user-images.githubusercontent.com/5192160/105120008-4a15eb00-5a86-11eb-999d-02ca2fb07519.png)
