### ISSUE TITLE
Need to remove nightwatch related exception from qextract function

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1128]
Can we please remove this exception raised for traceset that do not have 500 fibers?

It is still useful to look back at data obtained with the test slit. The code mention it breaks nightwatch but this should be fixed in nightwatch, not by raising an exception in desispec preventing to extract test data !
https://github.com/desihub/desispec/blob/8be7ff3b56c037fbac4917374902ab391b33ea14/py/desispec/qproc/qextract.py#L66

**Comment by sbailey** [comment]
Agreed, this should be handled on the Nightwatch side.  OK to remove that check from desispec.

**Comment by sbailey** [comment]
Fixed in PR #1131, closing.
