### ISSUE TITLE
Don't include "today" in dashboard when specifying nights

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1143]
This was something I added back in miniSV-2, but has since become a nuisance. When you give a list or single value using "--nights", it automatically appends the current day to that list. I have a new (external) way to do that for the daily processing and it isn't useful or relevant when used for re-processing.

**Comment by zkdtc** [comment]
Disabled by commenting out three lines of code.

**Comment by sbailey** [comment]
implemented in PR #1152, thanks; closing.
