### ISSUE TITLE
Calibration systematics identified in fiberid 2600-2700

### ISSUE THREAD

**Issue by astro-blue** [desihub/desispec#1158]
I just want to report that I found a  (relatively) common failure for the spectro-calibration in Blanc reduction. Somehow, fiberid around 2660 - 2690 tend to have bad spectro-reduction which drives the best fit.
The green histogram in Figure 1 shows that fiberID distribution of bad spectra (either with redshifts inconsistent with VI or with bad quality flagged by VI) but with deltachi2>100 for spectra with ~3500s exposure time.
As can be seen, there is a spike around fiber id 2600.
Figure 2 shows the spectra in z-arm for those bad spectra with fiber id (2660-2690). You can see that they all have a same calibration feature. 
![Figure_1](https://user-images.githubusercontent.com/8175013/109383041-e0a7b880-791e-11eb-8706-6061cf9799fc.png)
![Figure_2](https://user-images.githubusercontent.com/8175013/109383046-e43b3f80-791e-11eb-937d-ac7e08068721.png)
This effect is also found in other types of sources and in other tiles. 
Here are some examples

TARGETID, TILEID, Type, Redrock_z, fiberid
39627706823869675 80606 GALAXY 0.9752497297728839 2669
39627706823870511 80606 GALAXY 0.9725350919774016 2686
39627706823872577 80606 GALAXY 1.357213968687588 2666
39627706823873603 80606 GALAXY 0.9744368558270753 2680
39627706823875518 80606 GALAXY 1.087761123869701 2665
39627712859473332 80606 GALAXY 0.9714257920120779 2679
39627712859474409 80606 GALAXY 0.9741583689393872 2672
39627712859476373 80606 GALAXY 0.9746116291651751 2674
39627712859477271 80606 GALAXY 0.9704810677449396 2668
39627712859477493 80606 GALAXY 0.9750924487088715 2670
39627712859479897 80606 GALAXY 0.9737774737020615 2671
39633354911384800 80608 GALAXY 0.9700683799661511 2669
39633354911386203 80608 GALAXY 1.2887301755289262 2663
39633354911386705 80608 GALAXY 0.9700525567222783 2666
39633354911387057 80608 GALAXY 0.9743482111077703 2680
39633354911387262 80608 GALAXY 0.9754951712781478 2681
39633354911388130 80608 GALAXY 1.0209737332702224 2665
39633358170359704 80608 GALAXY 0.9735287509638376 2672
39633358170360436 80608 GALAXY 0.970460840209167 2678
39633358170360571 80608 GALAXY 1.5138059933281964 2664
39633358170361487 80608 GALAXY 0.9726610016169913 2668
39633358170362177 80608 GALAXY 0.9694352833398874 2675
39633358174552524 80608 GALAXY 0.9700300861478697 2671

**Comment by julienguy** [comment]
This is due to poorly masked dead columns in the z5 CCD.
![Screenshot from 2021-03-05 10-44-30](https://user-images.githubusercontent.com/5192160/110167064-0fec7880-7daa-11eb-823a-765c5aec64d2.png)

**Comment by julienguy** [comment]
New pixmask pixmask-sm9-z-20210305.fits.gz , with 2 new bad fibers: 164,165 (in addition to 342) recorded in calib yaml file.
Need to run a new extraction to verify that this solves this issue.

**Comment by sbailey** [comment]
I'm leaving this open and assigning to Fuji project for followup.  @astro-blue identified fiber 2680 as particularly problematic in Denali, which used the new pixmask and bad fiber list.  I think this is the same effect as issue #1172.

**Comment by sbailey** [comment]
From @astro-blue study of Denali redshifts inconsistent with visual inspections:
![image](https://user-images.githubusercontent.com/218471/126695138-c416bb73-a96e-46ba-a1b0-fcce38dd6888.png)

**Comment by sbailey** [comment]
Fixed (or at least improved) with better fiber masking bookkeeping in PR #1429; closing this ticket.
