### ISSUE TITLE
Need to recompute bias+dark model for SM9-z5

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1172]
In the area around the band of bad pixels (x in 1401:1412) at the top and bottom of the CCD
 the dark current model is negative, resulting in positive values and an artificial glow after dark subtraction.
I have masked in the file pixmask-sm9-z-20210305.fits.gz the values<-0.04(*extime) , but there are tails remaining.
See for instance https://nightwatch.desi.lbl.gov/20210304/00079216/preproc-z5-00079216-4x.html

**Comment by sbailey** [comment]
Reassigning to Fuji and adding ccd label

**Comment by sbailey** [comment]
@julienguy has this been fixed in your latest calib updates (and can be closed) or otherwise is it as good as it's going to get for Fuji (left open but removed from Fuji project)?

**Comment by julienguy** [comment]
We cannot fix this one. The pattern evolves with exposure time. I am going to flag the fibers.
