### ISSUE TITLE
flux calib tests failing on master

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#118]
I just pushed a change to etc/cron_dailytest.sh to master, and the travis test reported a failure of the flux calibration tests:

https://travis-ci.org/desihub/desispec/jobs/111545817
```
======================================================================
FAIL: test_match_templates (desispec.test.test_flux_calibration.TestFluxCalibration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/desispec/py/desispec/test/test_flux_calibration.py", line 102, in test_match_templates
    self.assertTrue(np.all(bestid>-0.1)) # test if fitting is done, otherwise bestid=-1
AssertionError: False is not true
```
The tests pass on my laptop and are completely unrelated to the cronjob script update.  The tests use numpy.random without fixing the seed, so it is possible that this is a rare case, but we should still fix it. 

High priority: debug and fix this.

**Comment by sbailey** [comment]
I have rerun this test multiple times on both travis and my laptop and have not reproduced the failure.  It could still be a corner-case bug revealed by some random inputs but not others, but I don't see anything obvious from the code.  Keep an eye out for this, but I'll close this issue for now.

**Comment by sbailey** [comment]
This cropped up again:
https://travis-ci.org/desihub/desispec/jobs/112140398
```
======================================================================
FAIL: test_match_templates (desispec.test.test_flux_calibration.TestFluxCalibration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/desispec/py/desispec/test/test_flux_calibration.py", line 104, in test_match_templates
    self.assertTrue(np.all(bestid>-0.1)) # test if fitting is done, otherwise bestid=-1
AssertionError: False is not true
```

@gdhungana please review the flux calibration code and its test code, and see if you can tell why this test is intermittently failing.

**Comment by gdhungana** [comment]
Apparently, I was able to reproduce that once in 20 test run. I will check this soon.

**Comment by sbailey** [comment]
PR #121 may have fixed this, but it isn't obvious why.  50 iterations of the test didn't fail, so closing ticket again.
