### ISSUE TITLE
tile on different dates with inconsistent targets

### ISSUE THREAD

**Issue by AlexGKim** [desihub/desispec#1202]
I was of the understanding that the targets of a given tile are immutable.  This is not the case.

The spectra in 
/global/project/projectdirs/desi/spectro/redux/daily/tiles/80740/20210306/coadd-9-80740-20210306.fits
has TARGETID 2305843037844026401

The spectra in the same tile
/global/project/projectdirs/desi/spectro/redux/daily/tiles/80740/20210228/coadd-9-80740-20210228.fits
does not have the above target.

**Comment by sbailey** [comment]
This is indeed surprising, and traces back to even the original fiberassign files for the same tile on those two nights being different!?!  Break the glass and pull the emergency lever.  @araichoor can you track down the history of the fiber assignment for tile 80740?

In /global/cfs/cdirs/desi/spectro/data
```
from astropy.table import Table
fa1 = Table.read('20210228/00079069/fiberassign-080740.fits.gz', 'FIBERASSIGN')                                                                 
fa2 = Table.read('20210306/00079547/fiberassign-080740.fits.gz', 'FIBERASSIGN')
2305843037844026401 in fa1['TARGETID']  # False
2305843037844026401 in fa2['TARGETID']  # True
len(set(fa1['TARGETID']) - set(fa2['TARGETID']))  # 1374, this should be 0!
```

**Comment by djschlegel** [comment]
Now that's a horrible operational mistake.  We re-designed that tile on 2021-03-4 even though it had already gotten observations on 2021-02-28.  My suggestion is (1) Anand, double-check that this didn't happen anywhere else, and (2) Anthony, mark the first two exposures (expid 79069-79070) as bad.  As it turns out, those first two exposures were basically useless anyway, so pretending they don't exist is one way to finesse our way out of this.  (A side note that we don't expect to be re-designing tiles in the future; this was being done to pick up additional petals.)

**Comment by araichoor** [comment]
I confirm David s statement... let me check for all exposures. apologies for that.

**Comment by araichoor** [comment]
two other tiles (80726, 80741) got observations on 2021-02-28, but have been re-designed on 2021-03-04.
apparently, I totally screwed up that day, with ignoring 2021-02-28 observations.

so the list of "affected" exposures is:
# TILEID NIGHT EXPID
#
80726 20210228 79072
80726 20210228 79073
80726 20210228 79074
80726 20210304 79277
80726 20210304 79279
80726 20210306 79549
80726 20210306 79550
#
80740 20210228 79069
80740 20210228 79070
80740 20210306 79547
80740 20210306 79548
#
80741 20210228 79066
80741 20210228 79067
80741 20210228 79068
80741 20210306 79554
80741 20210306 79555

maybe as David suggests we could mark the above 2021-02-08 expids as "bad"?
on 2021-02-28, the transparency ranges fro 0.80 to 0.95 and the seeing from 1.2" to 3.4".

**Comment by akremin** [comment]
Do we want to remove the processed data from 2021-02-28 in daily? I can flag them so they don't come up in new productions, but that is distinct from what is already on disk. I would have to (and am happy to) also delete the redshifts and the processed spectra from the daily directory

**Comment by AlexGKim** [comment]
My vote as a backend user would to have these removed from daily.  My code and other's scrub the filesystem to pull out data, in the absence of a database.

**Comment by akremin** [comment]
@AlexGKim I have removed the spectra and redshifts for the 8 exposures on 20210228 in the daily directory and flagged them so they won't be used in future productions. Thank you for identifying this and raising the issue.

@araichoor are you satisfied that you've caught all there is to find here?

**Comment by weaverba137** [comment]
Is there anything that needs to be done in terms of removing files from KPNO, NERSC, etc., possibly from directories outside of spectro/redux/daily?

**Comment by sbailey** [comment]
@weaverba137 if it doesn't happen automagically, resyncing daily/exposures/20210228 to Tucson would be helpful (if the NOIRlab mirror has recovered their disk situation), but no need to do anything for the raw data or nightwatch directories at NERSC or KPNO.  We'll treat these like any other bad exposures and flag them in the processing to ignore.

**Comment by weaverba137** [comment]
@sbailey, indeed, the updates to the daily reductions should already happen automatically.

**Comment by araichoor** [comment]
@akremin : yes, I did check against all exposures present in sv1-exposures.fits, so restricting to sv1 science tiles.
 maybe an extra sanity check would be to verify I didn t miss any sv1 science exposures: would you have at hand an exhaustive list of the sv1 science exposures?

**Comment by akremin** [comment]
I think Julien's tsnr-exposures.fits file is now an exhaustive list (where data flagged as bad are given tsnr2=0). It has EXPID and TILEID which you might have to cross-match with your tile catalog to know what program it was observed under. It has columns for e.g. FAFLAVOR but I'm not sure if those additional columns are fully implemented (I see a lot of 'UNKOWN' values).

**Comment by araichoor** [comment]
well, unless I mistake there are a bunch of exposures not present in tsnr-exposures.fits (153 here; probably crappy ones, but still):
```
>>> tsnr=fits.open("/global/cfs/cdirs/desi/spectro/redux/daily/tsnr-exposures.fits")[1].data
>>> sv1=fits.open("/global/cfs/cdirs/desi/survey/observations/SV1/sv1-exposures.fits")[1].data
>>> len(sv1) # number of sv1 exposures in sv1-exposures.fits
1754
>>> np.in1d(tsnr["TILEID"], sv1["TILEID"]).sum() # tsnr exposures corresponding to sv1 tiles
1601
>>> (np.in1d(tsnr["TILEID"], sv1["TILEID"]) & (~np.in1d(tsnr["EXPID"], sv1["EXPID"]))).sum() # sv1 tsnr exposures not in sv1-exposures.fits
0
```

**Comment by akremin** [comment]
Okay it's possible the update to pick up ignored/bad exposures is only used for new data and the old ones weren't folded in. Or there is a legitimate issue to investigate. We should speak to Julien about that offline and I can help dig into this as well.

In the meantime -- if you already have an exhaustive list for sv1, are you asking about non-sv1 exposures or did you just not trust your list? If you just want non-sv1 exposures then I'd still use the tsnr file because it contains the exposures the pipeline cares about. if others have the wrong tile but are flagged and ignore for other reasons, I think that is a less pressing issue (though we should flag them for both eventually).

**Comment by araichoor** [comment]
happy to interact offline on the exposure list.
I just wanted to be sure that I didn t miss any sv1 exposures in my sv1-exposures.fits
I ve not checked cmx nor sv0 exposures, but I guess there is no reason for that to happen there (no redesign).
and I guess you d have catch it in andes, blanc, cascades (the night 2021-02-28 is post-cascades)

**Comment by akremin** [comment]
Great, I have moved the discussion of exposures tables off-list. It sounds like we are confident that this is resolved, so I will close this issue. Thanks everyone for the quick effort on this.
