### ISSUE TITLE
document conda installation for spectro pipeline 2016a

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#126]
Document conda installation procedure for all code needed for spectro pipeline 2016a, starting from something like
```
conda create -n desi2016a python=2.7 astropy=1.1.1 scipy=0.17.0
```
Include documentation about what environment variables need to be set and how to run the code on a laptop.

HARP+specex for PSF estimation may be the trickiest part of this.  Note that only a subset of HARP needs to be installed for this, so make that clear.

**Comment by weaverba137** [comment]
This is now somewhat a duplicate of #170.

**Comment by weaverba137** [comment]
This is a duplicate of #170, which should be closed later today.
