### ISSUE TITLE
Strange single broad-line spectrum, an extraction artifact?

### ISSUE THREAD

**Issue by AlexGKim** [desihub/desispec#1262]
There is a spectrum that doesn't match my limited knowledge of astronomical objects.  It may be real but I suspect it could be an extraction artifact.

` plot_spectra -i /global/project/projectdirs/desi/spectro/redux/denali/tiles/pernight/80635/*/coadd-4-80635-*.fits -t 39627628532992432  --rebin 4`

![image](https://user-images.githubusercontent.com/880156/116946528-35252800-ac2f-11eb-8cca-2fd91aa4560b.png)

**Comment by AlexGKim** [comment]
Another example

`plot_spectra -i /global/project/projectdirs/desi/spectro/redux/denali/tiles/pernight/80635/*/coadd-4-80635-*.fits -t 39627628537186687  --rebin 4`

**Comment by sbailey** [comment]
This looks like another case of fidicials being on; see #1168.

Action items:
  * track down which exposures have the bump but weren't already flagged as bad
  * check neighboring fibers on the focal plane (e.g. with flux in 4400-4800 vs. x,y)
  * flag exposures as bad

**Comment by moustakas** [comment]
For the record, both of these examples are present in Everest as well. Not sure how we're handling these in Fuji, if at all.

**Comment by sbailey** [comment]
There is contamination on night 20210102 expids 70543 - 70545, but not on 20210105 exps 70931-32 for the same tile 80635.

Action: flag 20210102 expids 70543 - 70545 as bad

Note that petal 3 on 20210105 had bad positioning, and is already flagged as bad in the exposure tables.

@akremin 

Not fiberflatted at all, but median of frame counts 4400 - 4800 A on two different nights for same tile:
![image](https://user-images.githubusercontent.com/218471/150881272-4827141e-edc4-4566-8776-29b3c3bacd47.png)
![image](https://user-images.githubusercontent.com/218471/150881335-06abf521-6843-41a1-bcba-b5ae9f4a3975.png)

**Comment by akremin** [comment]
Expids 70543 - 70545 on 20210102 are now marked as bad
