### ISSUE TITLE
Inquiry on TARGETID coadds

### ISSUE THREAD

**Issue by AlexGKim** [desihub/desispec#1286]
There are targetids that appear in multiple tiles.  I am curious what the plan is for their cumulative coadds in the internal production. Or will that coadd occur post-production?

**Comment by moustakas** [comment]
@AlexGKim I believe this question has been answered in at least the last couple data releases: coadds of the same targets on the same tiles observed on different nights exist as `cumulative` coadds, while coadds of the same targets observed on different nights and potentially different tiles now exist as `healpix` coadds.
