### ISSUE TITLE
new FIBERSTATUS bit for poor positioning

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1295]
Add a new FIBERSTATUS bit for poor positioning (e.g. 50 < r < 100 microns) that propagates through as a warning bit but isn't treated as an ivar=0 NODATA case like r>100 microns.  Also update redrock to set a ZWARN bit for these "bad but not necessarily catastrophic" cases.

**Comment by julienguy** [comment]
implemented in PR #1302
