### ISSUE TITLE
qproc_compute_fiberflat fails if all rows (or columns?) have ivar==0

### ISSUE THREAD

**Issue by moustakas** [desihub/desispec#1299]
The `z5` camera has been throwing an error the last few nights with the following error log--
  https://nightwatch.desi.lbl.gov/20210607/00091457/qproc-z5-00091457-logfile.html

The trouble appears to be here, where the code is expecting at least one (or more) pixels with non-zero ivar--
  https://github.com/desihub/desispec/blob/master/py/desispec/qproc/qfiberflat.py#L58

**Comment by sbailey** [comment]
Fixed by PR #1306
