### ISSUE TITLE
resample_flux doesn't conserve flux

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#13]
desispec.interpolation.resample_flux() doesn't conserve flux, while the docstring says that it does.  py/test/test_resample.py contains a failing unit test to show this.

python py/desispec/test/test_resample.py

**Comment by rainwoodman** [comment]
I had wrote a conserving version of this at

https://github.com/rainwoodman/lyamock/blob/master/lib/splat.py#L36

(I just called it splat).

I hope you can find this somewhat useful. Mine doesn't do ivar though.

**Comment by moustakas** [comment]
I mentioned this elsewhere (or maybe over email) but there's also some stuff that Bolton has written (included in redmonster?).

**Comment by julienguy** [comment]
See the pull request  Fix interpolation #24 
(google tells me it"s complicated to link a github issue with a pull request, if someone finds a simple practical solution, please share).
