### ISSUE TITLE
sky model file name does not match datamodel

### ISSUE THREAD

**Issue by dkirkby** [desihub/desispec#131]
The following line in `io.meta.findfile()`:
```
sky = '{specprod_dir}/exposures/{night}/{expid:08d}/sky-{camera}-{expid:08d}.fits',
```
does not match the naming scheme in the datamodel:

https://github.com/desihub/desidatamodel/blob/master/doc/DESI_SPECTRO_REDUX/PRODNAME/exposures/NIGHT/EXPID/skymodel-CAMERA-EXPID.rst

Probably the datamodel should be updated.

**Comment by weaverba137** [comment]
This is fixed in the latest data model.
