### ISSUE TITLE
20210218 bad flat exposure 76737 means we can't use flats on that night

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1342]
It appears the dome lights were turned on in the final flat exposure 76737 on 20210218. That means we can't use that set of flats for calibrations because we need 3 for cosmic ray removal.

Without a set of calls, the pipeline will default back to SVN. For Everest we are instead sym-linking the previous night, which is more representative.

We should decide and implement the proper default before Fuji for what to do in these cases.

**Comment by akremin** [comment]
The flat sequence has been flagged, but as of now the default in the code is still to use SVN. We need to decide what to do in Fuji @sbailey .

**Comment by julienguy** [comment]
I think it's fine now that we have the humidity correction in place. But it might be worth trying on one exposure.

**Comment by akremin** [comment]
We will proceed with SVN + humidity correction in Fuji, but will scrutinize the reductions to verify that we're happy with it. If necessary we can always rerun using an earlier night's `fiberflatnight`'s like we did in `Everest`.
