### ISSUE TITLE
wacky results for fiber 3589, likely amplifier issue(?)

### ISSUE THREAD

**Issue by ashleyjross** [desihub/desispec#1346]
<img width="730" alt="Screen Shot 2021-07-22 at 3 18 05 PM" src="https://user-images.githubusercontent.com/14100086/126697066-9ebc0027-b0ae-4c22-a595-fc13fc9a1cc8.png">
Plot from Ting-Wen's webpage: https://tingwenlan.notion.site/VI-SV-Cascades-Denali-Summary-8e5de06b10124dca9574d324b1bb0b66#d21a060a5da54210a4c6673ed854f9ab

Many zwarn = 0 results for this fiber but wacky N(z) (e.g., almost all LRG at z=1)

**Comment by julienguy** [comment]
Explained by variable bright column. See https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=6430. Mitigation in PR #1371 .

**Comment by sbailey** [comment]
Cases like this are now identified and flagged (albeit not perfectly).  Closing ticket.  Please re-report new cases that aren't well masked for further investigation.
