### ISSUE TITLE
COADD_NUMNIGHT and COADD_NUMTILE wrong when some input data is bad

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1349]
As discovered by @armengau, COADD_NUMNIGHT and COADD_NUMTILE are wrong when some of the input is masked (they report number of nights/tiles considered, not the number actually used in the coadd after quality filtering), while COADD_NUMEXP is correct.

Example:

\# A random healpix/coadd in SV3:

f = '/global/cfs/cdirs/desi/spectro/redux/everest/healpix/sv3/dark/99/9994/coadd-sv3-dark-9994.fits'
sp = desispec.io.read_spectra(f)
tid=39633162703211005

w1,= np.where(sp.exp_fibermap['TARGETID']==tid)
sp.exp_fibermap['NIGHT','EXPID', 'TILEID', 'FIBERSTATUS'][w1]                                                                               
        NIGHT   EXPID TILEID FIBERSTATUS
         int32   int32 int32     int32   
        -------- ----- ------ -----------
        20210410 84238    356         512
        20210417 85213    361           0
        ==> 2 exposures from different tiles/nights, one with bad fiberstatus.

w2, = np.where(sp.fibermap['TARGETID']==tid)
sp.fibermap['COADD_NUMEXP', 'COADD_NUMNIGHT', 'COADD_NUMTILE', 'COADD_FIBERSTATUS'][w2]                                                           
        COADD_NUMEXP COADD_NUMNIGHT COADD_NUMTILE COADD_FIBERSTATUS 
        int16    int16   int16   int32
        ------------ -------------- ------------- ----------------- 
        1               2                2               0 
        ==> Why do COADD_NUMEXP and NUMNIGHT/NUMTILE differ ?
        I would naively expect NUMNIGHT/NUMTILE = 1, if for this target a single exposure was used in the coadd.

**Comment by moustakas** [comment]
Fixed in #1616.
