### ISSUE TITLE
coadding camera is slow

### ISSUE THREAD

**Issue by moustakas** [desihub/desispec#1365]
I haven't dug to find the bottleneck(s), but `desispec.coaddition.coadd_cameras` is painfully slow (3-4 seconds for a `Spectra` object with a single galaxy). This issue doesn't affect the pipeline but it does affect downstream analysis with `fastspecfit` and work by at least one GQP WG member.

**Comment by sybenzvi** [comment]
@moustakas, this also affects the transient pipeline, which requires coaddition across the cameras. I'll see if I can profile it and make some headway.

**Comment by sybenzvi** [comment]
Prompted by @sbailey, I got around to running a line profiler. When running `coadd_cameras` on one spectrum, 98% of the execution time is spent on two lines checking the alignment of the camera wavelength grids (see [here](https://github.com/desihub/desispec/blob/a407ce88ca6c30bdc8a36f7202ebba874f836b0c/py/desispec/coaddition.py#L496)) and then repeating the same expensive calculation at the start of coaddition (see [here](https://github.com/desihub/desispec/blob/a407ce88ca6c30bdc8a36f7202ebba874f836b0c/py/desispec/coaddition.py#L533)). When calling `coadd_cameras` on a full petal, these two lines still take up 45% of the execution time.

The line profile for coadding one spectrum is attached.

[coadd_camera_prof.py.001.lprof.txt](https://github.com/desihub/desispec/files/7004067/coadd_camera_prof.py.001.lprof.txt)

**Comment by sybenzvi** [comment]
I added a unit test to check the new calculation. I should have written the test before submitting PR #1377, but I did check offline that the also test passes with the old `coadd_cameras` code, so I'm confident about the changes.

**Comment by moustakas** [comment]
Done in #1377. Thanks @sybenzvi!
