### ISSUE TITLE
Update bad exposure cuts to reflect steeper fall-off in survey speed with airmass

### ISSUE THREAD

**Issue by schlafly** [desihub/desispec#1375]
Current automatic bad exposure cuts mark an exposure as bad if its zenith-corrected speed is less than half of the minimum speed for which we intend to choose tiles for a given program.  This zenith-corrected speed is currently computed as if the only contribution to longer observations with airmass comes from atmospheric transparency.  In fact, the seeing gets worse as airmass increases, and the sky gets brighter as well, and both of these terms are larger than the contribution to slower survey speed from the atmospheric throughput (at least in the r band).

I've advocated that we move to airmass^1.75 for the scaling of the exposure time necessary to reach a fixed signal to noise in place of the current 1/(atmospheric transparency)^2.  We are planning on adopting this in the ETC and the offline pipeline should as well.  I have updated the SurveySpeed wiki here:
https://desi.lbl.gov/trac/wiki/SurveyOps/SurveySpeed
accordingly.

**Comment by akremin** [comment]
This was resolved with PR #1413
