### ISSUE TITLE
tilepix.json shouldn't include dithfocus tiles

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1379]
everest/healpix/tilepix.json includes dithfocus tiles 80770 - 80781 that weren't processed to redshifts and aren't included in everest/tiles-everest.fits.  These test tiles shouldn't be in tilepix.json, and tilepix.json and tiles-{specprod}.fits should have the same tiles, and all of those should match what is actually on disk in healpix/{survey}/{faprgrm}/

Action: review code that generated tilepix.json, determine why dithfocus tiles were included, and figure out how to exclude them.

**Comment by araichoor** [comment]
in case it helps: one should be able to identify dither tiles with requesting the presence of a "ISDITH" keyword in the 0-th extension header (which regular tiles won t have).

**Comment by moustakas** [comment]
Fixed in #1614.
