### ISSUE TITLE
Switch from EFFTIME_ELG to EFFTIME_LRG

### ISSUE THREAD

**Issue by schlafly** [desihub/desispec#1388]
We plan to switch from EFFTIME_ELG to EFFTIME_LRG.  This issue intends to track that plan.  That means that the daily exposures file needs to compute EFFTIME_LRG (presently I see TSNR2_LRG but no corresponding EFFTIME), and that the EFFTIME_SPEC column needs to be filled out with this quantity for future dark tiles.

Related to this issue, but only tangentially, we need to decide if we want to change what the ETC is calculating.  If we do nothing the ETC will continue to use the ELG source profile for computing the FIBERFRACs.

For my two cents, this is fine---it continues to play a compromise role between the QSO profile and the larger galaxy profiles.  But it means that there will be some good-seeing tiles where the ETC ~correctly thinks we're done, but the offline pipeline wants us to come back and integrate some more, which isn't ideal.

**Comment by araichoor** [comment]
I ve posted on DoCDB slides looking at this for the Main/ELG_LOP selection: https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=6455.

**Comment by julienguy** [comment]
This issue is addressed in the PR #1417.
Note I have recalibrated the EFFTIME for LRGs based on the main survey tiles (everest data release). This is a change of 1.5% with respect to the value used by @araichoor .
