### ISSUE TITLE
tiles -> tiles-specstatus update script

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1420]
We need a script that takes the tile processing status (tsnr, efftime, ...) in daily/tiles.csv and propagates it into the surveyops/ops/tiles-specstatus.ecsv file for followup with human QA inspection, afternoon planning, etc. while not stepping on the QA related columns USER, QA, OVERRIDE, and ZDONE.  I'm working on this script, but documenting a few choices and questions here:

Any *new* TILEID rows in `tiles` should be added to `specstatus`, with USER='none', QA='none', OVERRIDE=0, and ZDONE='false'.

Any existing TILEID with ZDONE='false' and tiles['LASTNIGHT'] > specstatus['LASTNIGHT'] should also be updated for the non-qa columns.

But what about cases where ZDONE='true' but for whatever reason we got more data anyway such that tiles['LASTNIGHT'] > specstatus['LASTNIGHT']?  Should we freeze the `specstatus` row to reflect the status at the time the QA was done, even if more data have arrived (and thus have `tiles` and `specstatus` get out of sync for those TILEID), or should we go ahead and update the non-qa columns like EFFTIME_SPEC to reflect the current processing state even if QA was already finished and the tile was released?

I'm inclined to *not* check+update every row every time just in case the TSNR or EFFTIME calculation changed a little and impacted every tile, and leave that for a special case update.  The script could still support it, but I don't think that should be default so that under normal use any updates to tiles-specstatus.ecsv reflect changes due to new data and nothing else.

@julienguy, opinions?

**Comment by julienguy** [comment]
I think we should report in the table changes of LAST_NIGHT and the various timing values EFFTIME_ETC EFFTIME_SPEC ...
but not alter the QA VI columns (ZDONE QA USER OVERRIDE). We may add another column that records the value of LAST_NIGHT when the QA VI has been done (like QA_NIGHT).

**Comment by geordie666** [comment]
I think what Julien suggest is OK, but note that MTL interprets `LASTNIGHT` to mean "the final processed date for the redshifts". Operationally, I'm not sure that matters, though (provided `LASTNIGHT` continues to have a unique correspondence with observations of a tile being complete).

**Comment by geordie666** [comment]
More context: I think the most important aspect is that `LASTNIGHT` continues to denote the directory for the MTL-final redshifts (as in `$DESI_SPECTRO_REDUX/daily/tiles/cumulative/$TILEID/$LASTNIGHT/`). To be clear, I don't think anything Julien is suggesting would change that, so everything should be OK.
