### ISSUE TITLE
update z7 bad pixel mask

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1422]
Update the z7 bad pixel mask for data starting in September 2021.  e.g. from the 1200s dark night 20210909 expid 99365, there are bad pixels leaking out of the current mask:

![image](https://user-images.githubusercontent.com/218471/135020747-69c0e432-ad97-4842-afcb-eb5171b36a30.png)

See desispec/bin/desi_compute_mask_dark, and focus on 1200s dark exposures from Sept 2021, since some of the features are leaking charge that grow with exptime and would not be sufficiently masked based upon shorter darks.

**Comment by julienguy** [comment]
done
