### ISSUE TITLE
Drop negative TARGETID and SKY* targets from healpix-based coadds

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1433]
Currently the healpix-based coadds propagate all TARGETIDs, including the negative TARGETIDs that arise from stuck positioners not being able to point at a normal DESI target.  These are ~20% of the targets in the healpix files and are nearly useless.  I suggest that we drop them from the healpix-based spectra, coadds, and redrock files.

I also suggest that we drop SKY, SUPP_SKY, and BAD_SKY targets from the healpix groupings.  Custom studies that want to use sky fibers could/should use tile-based data instead.

Any objections?

**Comment by moustakas** [comment]
I agree that this is a sensible idea.

**Comment by djschlegel** [comment]
Has anyone checked with the LyA group.  Most relevant would be if LyAF systematics expect to use these (though I think they'd be identical to the tile-based sky spectra, since these skies don't repeat on different tiles).

**Comment by stephjuneau** [comment]
In my opinion, it doesn't sound robust to have to use both healpix- and tile-based coadds with the knowledge that in the long term we might end up with only the healpix-based coadds. I think it would be useful to keep at least the small percentage of sky fibers that end up having a serendipitous object if they pass through RR and are found to have a valid spectrum/redshift in the zpix-* files. Lastly, I wonder whether they could be used to compute approximate sky spectra until we have proper sky models on a per-coadded-spectrum basis? We just had a discussion about the importance of knowing the sky when stacking DESI spectra (with @moustakas @biprateep, @weaverba137 and others) this morning, and this seems relevant.

**Comment by sbailey** [comment]
Point of clarification: these are sky-subtracted sky-spectra and sky-subtracted whatever-the-stuck-fiber-was-pointing-at, *not* directly sky spectra.  i.e. it's useful for studying systematics of sky subtraction residuals, but not useful for studying the actual sky spectra that were subtracted.

Stuck positioners have a unique TARGETID per tile, so the zpix spectra don't contain any information that isn't already identical in the per-tile cumulative grouping.  Since LSS uses the cumulative per-tile coadds+redshifts, we plan to retain those in future prods in addition to the healpix ones (perexp and pernight may get dropped, but not cumulative).

Pre-identified sky fibers might be re-used on other tiles and thus could be differently coadded in healpix tiles, but they were specifically selected because nothing was there in the imaging data, so any serendipitous spectra would be a transient where the shorter timescale per-tile spectra would be more useful than a healpix coadd anyway.

We do need to followup with LyA about this since there might be a big convenience factor to using healpix for everything not not mixing and matching directory structures for sky-fiber systematics studies.  @alxogm @andreufont et al?  Is this worth 20% extra disk space?

**Comment by sbailey** [comment]
I'm not convinced that we'll really use these healpix-based sky spectra, but erring on the side of keeping data products, we'll keep these for Fuji.  If they never get used we may drop them for DA1 (Kilimanjaro?)
