### ISSUE TITLE
parallelize redmonster wrapper

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#144]
Background: redmonster isn't parallelized and as a result some test bricks can't finish within the 30 minute NERSC debug queue time limit, which makes it a pain to debug the pipeline end-to-end.

To do: update desispec.zfind.redmonster.RedMonsterZfind to wrap parallelism around redmonster using the python subprocess module.  This involves splitting the inputs into N subsets of spectra, processing each independently through redmonster, and then stitching the results back together.

Alternative: fork redmonster, parallelize it, and submit a pull request to redmonster itself on bitbucket.  Check with @timahutchinson and Adam Bolton first to make sure they would accept such a PR.

**Comment by moustakas** [comment]
Done in #150.

**Comment by tskisner** [comment]
Actually, in the current pipeline, we use MPI to parallelize the calls to redmonster.  See the main function here:

https://github.com/desihub/desispec/blob/master/py/desispec/scripts/zfind.py

For many productions (depends on the number of bricks) we can fit zfind into the debug queue.

**Comment by moustakas** [comment]
Thanks for the added info -- I was just cleaning up stale issues!
