### ISSUE TITLE
FIBER_X=FIBER_Y=0.0 but FIBERSTATUS=0 too

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1447]
Arjun reported the case of 20210110/00071721 where many fibermap entries have FIBER_X == FIBER_Y == 0.0, while also having FIBERSTATUS==0, i.e. no warning bits set despite the obviously wrong FIBER_X, FIBER_Y.  I traced this back to the input coordinates file /global/cfs/cdirs/desi/spectro/data/20210110/00071721/coordinates-00071721.fits which has 3307 targets with FIBER_X == FIBER_Y == FIBER_DX == FIBER_DY == 0.0 .  These didn't trigger a FIBERSTATUS positioning error because we were using FIBER_DX, FIBER_DY rather than also checking FIBER_X and FIBER_Y.

The poor fiber location measurements are somewhat understandable given the state of the FVC image from which they were measured:

![image](https://user-images.githubusercontent.com/218471/137425889-fbb86a8d-d810-4b7c-b50b-4bcb1ceb9698.png)

Nominally FIBER_X == FIBER_Y == 0.0 should trigger FIBERSTATUS bit MISSINGPOSITION, which is treated equivalently to known bad positioning >100 microns where BADPOSITION is set.  In those cases ivar is set to 0 at the cframe level, resulting in no redshifts and the ZWARN NODATA bit being set so that they aren't used for MTL updates.  This is is in contrast to offsets 30-100 microns which get FIBERSTATUS POORPOSITION and ZWARN POORDATA but leave it to TSNR2 values for whether QA rejects the fiber for MTL updates.

The nominal reasoning is that if a fiber is known to be completely off target, or completely unknown where it is, we should save the user from themselves by forcing ivar=0 instead of tempting them to use a bogus spectrum if they forget to check the FIBERSTATUS bitmask.  But sometimes we second guess that choice...

**Comment by djschlegel** [comment]
This is tile 80713 on M31, which was re-designed and re-observed as tile 80715 without those NaNs.  See: https://desi.lbl.gov/trac/wiki/SurveyOps/TileDesigns#a80713-80716-M31 .  The re-design was indeed to prevent passing NaNs to PlateMaker, etc.

Note that tile 80713 was only observed for an effective exposure time of 758 sec, then we observed the replacement tile 80715 for effective time 1906 sec.
