### ISSUE TITLE
Potential inconsistencies in top-level exposures-SPECPROD.fits file

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#1462]
I've been using the `everest/exposures-everest.fits` file on the assumption that it contains *all* of the exposures that comprise `everest` and *only* the exposures that comprise `everest`.  However, this assumption appears to be unwarranted.  For example, there are exposures in `everest/preproc` that do not appear in the exposures file.  These may well be calibration exposures, but it raises the question of how *exactly* the exposures file is created, and where is that documented?

For example, is it possible, even in principle, for an exposure to appear in a zcatalog file (as part of any type of spectrum), and not be in the exposures file?  Conversely, is it possible for an exposure to appear in the exposures file, but *not* in any redshift catalog?

Another consistency question has to do with survey-program.  Since the redshift catalog is divided by survey and program, one would expect that the survey and program values in the exposures file exactly match the exposures that appear in those respective redshift catalog files.  However, some exposures have `survey = 'cmx'` or `survey = 'unknown'` (see 20201214/00067678 for an example of the latter).  Where do these exposures appear in the redshift catalogs, if at all?

For reproducibility, I'm using `program = desispec.io.meta.faflavor2program(exposures['FAFLAVOR'])` to define the program value.

**Comment by weaverba137** [comment]
Thank you @akremin!

**Comment by weaverba137** [comment]
@akremin, @sbailey, revisiting this in the `f5`/`fuji` era.  The `exposures-f5.fits` no longer contains `SURVEY = 'unknown'`, however, there is a new `'special'` survey.  Is `special` going to appear in a separate redshift catalog?

**Comment by weaverba137** [comment]
For completeness, here is how `SURVEY`, `FAPRGRM` break down in the `exposures-f5.fits` file:
```python
{
'cmx': ['elg', 'lrgqso', 'm33'],
'main': ['bright', 'dark'],
'special': ['bright', 'dark'],
'sv1': ['bgsmws', 'dc3r2', 'elg', 'elgqso', 'lrgqso', 'lrgqso2', 'scndcosmos', 'scndhetdex', 'ssv', 'unwisebluefaint', 'unwisegreen'],
'sv2': ['dark'],
'sv3': ['backup', 'bright', 'dark'],
}

**Comment by weaverba137** [comment]
Sorry, I forgot to apply `faflavor2program`.  This looks pretty good:
```python
{
'cmx': ['dark', 'other'],
'main': ['bright', 'dark'],
'special': ['bright', 'dark'],
'sv1': ['bright', 'dark', 'other'],
'sv2': ['dark'],
'sv3': ['backup', 'bright', 'dark'],
}

**Comment by sbailey** [comment]
yes, survey="special" will remain as a catch-all for special tiles that we don't want to get mixed up with the main survey, but aren't a big enough activity to garner a unique survey name of their own, and they will be sequestered off into their own redshift catalog.

In your list above, I would expect a few additional (survey, program) combinations to eventually appear, like (main,backup) and (main,other).

**Comment by weaverba137** [comment]
I believe all of the inconsistencies have been resolved in `fuji` + `guadalupe`.
