### ISSUE TITLE
desispec support for test stand data

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#148]
The spectrograph tests will be done with specific setups. 
- Either a single fiber or the full testslit (with one fiber per bundle)
- With various light sources (inc. several arc lamps)

Because of this, some modifications/enhancements have to be done to the pipeline. They are developed in the branch 'teststand' of desispec.
Status 
- desi_bootcalib can fit only a subsample of fibers without much trouble which is good 
- currently it fails with a modified lamp setup but this is probably not a difficulty (working on it)
- specex works fine as well

**Comment by julienguy** [comment]
desi_bootcalib running on branch teststand with expected teststand arc spectrum.
(I modified the routine bootcalib.id_arc_lines)

**Comment by julienguy** [comment]
New algorithm developed for matching arc lines (using pairs of triplets). Tested on both BOSS arcs used in standard sims and teststand data (code pushed in branch teststand).

**Comment by weaverba137** [comment]
Did the recent merge with the teststand branch fix this issue?

**Comment by julienguy** [comment]
Because this branch is now merged, the branch can be deleted and the issue closed for now.
More things will come up later, but we can then reopen an issue.
