### ISSUE TITLE
20210105 and 20210220 test exposures to flag

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1491]
Running this through a Fuji ticket so that we don't lose track of it: these test exposures should be flagged as OBSTYPE=other (or test?) and LASTSTEP=ignore in the reference exposure tables in prep for Fuji:

Night 20210105 exposures 70921-70925 : system checkout exposures that should have been OBSTYPE=other.

Night 20210220 exposures 77103 and 77106: middle-of-the-day 10 second exposures claiming to be focus dithers.

Please comment and close ticket when this is done.

**Comment by akremin** [comment]
Thanks I'll add this to my list for Fuji cleanup. 

I will note that `OBSTYPE` is defined by the raw data and not something I ever intended to edit in the exposure tables. It could be done with proper commenting, but at the end of the day the "ignore" is the actionable information.

**Comment by sbailey** [comment]
OK, fine to mark as LASTSTEP=ignore and leave OBSTYPE alone, though perhaps with a comment that the raw data OBSTYPE should have been "other" instead of "science".

**Comment by akremin** [comment]
I think the first should include exp 70926 as well. I am including that is those I'm marking as bad. It has the same system checkout program description and exposure times.

Done using the following commands in the master file specprod (not listed for security through obscurity):
`desi_edit_exposure_table -n 20210105 -e 70921-70926 -c LASTSTEP -v ignore --include-comment="system checkouts not science" --overwrite-value`
`desi_edit_exposure_table -n 20210220 -e "77103,77106" -c LASTSTEP -v ignore --include-comment="test exps" --overwrite-value`
