### ISSUE TITLE
flag 20210110 exp 71724 as bad

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1494]
tile 80670 night 20210110 exp 71724 had terrible positioning across the entire focal plane.  We already flagged 8/10 petals as bad positioning, but the remaining two are still so bad that we don't make it to cframes anyway and end up with EFFTIME_SPEC=0.0 .  There are other good exposures for this tile; please flag this one as LASTSTEP=ignore.

Associating with Fuji so that we don't lose track of this.

**Comment by akremin** [comment]
Done using:
`desi_edit_exposure_table -n 20210110 -e 71724 -c LASTSTEP -v ignore --include-comment="terrible positioning" --overwrite-value`
