### ISSUE TITLE
tile QA plotting fails on backup tiles

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1496]
e.g.
```
desi_tile_qa -n 20211125 -t 42263
...
INFO:tsnr.py:1158:tsnr2_to_efftime: for tracer bgs SNR2TIME=0.140000
WARNING: leap-second auto-update failed due to the following exception: RuntimeError('Cache is locked after 5.01 s. This may indicate an astropy bug or that kill -9 was used. If you want to unlock the cache remove the directory /global/homes/d/desi/.astropy/cache/download/py3/lock. Lock claims to be held by process .') [astropy.time.core]
No handles with labels found to put in legend.
no cutout from viewer after 15s, stopping the wget call
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tile_qa", line 216, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tile_qa", line 158, in main
    entry = func(**func_arg)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tile_qa", line 66, in func
    figfile = make_tile_qa_plot(outfile, specprod_dir)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/tile_qa_plot.py", line 1048, in make_tile_qa_plot
    ratio_nz = n_valid / nref_valid
ZeroDivisionError: float division by zero
```

It was able to make the tile-qa*.fits file, it is just crashing on making the plots, apparently due to not having a reference n(z) distribution to use.

While fixing this specific case, it would be helpful to fix it more generally such that if the survey/program/flavor doesn't have a reference n(z), it still proceeds with making some plot instead of crashing.

**Comment by araichoor** [comment]
ugh, sorry.
I just forgot to exclude that case (as there is no point to look at a n(z) for backup, which is just stars).

I cannot dig more now, I ll be away from computer all day long.
but I think it should work to add a condition discarding main/backup tiles in this line:
https://github.com/desihub/desispec/blob/576502fe52e72ecda02c0f31146015f9c05f7dd0/py/desispec/tile_qa_plot.py#L984-L985

doing the following should work (sorry I cannot test-validate-make PR)
```
if (hdr["SURVEY"] == "main") & (hdr["FAPRGRM"].lower() != "backup"):
```

so just main/bright and main/dark should be considered for plotting a n(z).

**Comment by julienguy** [comment]
just made the change suggested by Anand

**Comment by araichoor** [comment]
thanks!
