### ISSUE TITLE
Add 1 sec FLAT for testing CCD CTE QA

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1499]
To help catch CCD CTE problems (like DESI trac issue 887) sooner than later:

1. Add a 1 sec FLAT to daily cals
2. Have spectro pipeline preprocess it but *not* use it for making fiberflats
3. Add new QA script to use those pre-processed 1-sec flats to look for CTE problems.
  * /global/homes/s/sjbailey/desi/dev/ccd/plot-amp-cte.py may be a starting point (but not along sufficient since it it focused on plotting a specific range of columns, not generally detecting the problem for all CCDs across all columns)

(1) and (2) need to be done in coordination; (3) can come later, in fact easiest after (1) and (2) are done such that there is an example exposure to work with.

**Comment by akremin** [comment]
This is resolved with pull request #1507
