### ISSUE TITLE
write unit tests

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#15]
Most desispec code does not have unit tests.  Write some stub tests for most code, perhaps spinning off additional pull requests for others to fill in particular tests.  Even super basic tests to confirm that functions don't raise exceptions when given valid inputs would be useful -- the dogwood spectral production run found several such problems by running the full pipeline; tests could catch those before bothering with batch jobs.

**Comment by dkirkby** [comment]
Have we standardized on a unit testing framework?  I have only used the built-in unittest module, but the py.test framework (http://pytest.org/latest/) looks more developer friendly and also supports higher-level functional tests.

What versions of python are tests required to pass on?  What tool will we use to automate running the test suite on all supported versions?  Online tools like Jenkins or Travis-CI will do this automatically whenever a new commit is pushed back to github. However, they have the downside that you don't know you broke something until it is already in the wild - developers would need to run local tests first to avoid this (e.g., with tox https://testrun.org/tox/latest/).

**Comment by sbailey** [comment]
Please use the built in unittest framework, following the desispec.test.test_fiberflat as a guideline.  py.test could be a reasonable alternative, though we'd have to discuss the "are the benefits worth the additional dependency?" tradeoff.  I wrote the first tests using unittest primarily because it was "good enough" while also being built in to python itself.  If there are strong py.test proponents out there, speak up.

python versions: 2.7.x, though I'm not sure which values of x.  We should include 2.7.9, and probably 2.7.8 and 2.7.7.  Not sure about prior to that.  But not 2.6.x and not 3.x (yet).

Ditto with numpy and scipy: unless some recent version includes a crucial bug fix, let's try to support any reasonably recent version and not always require the latest and greatest release.

Automation: after we get our tests organized, I like the idea of using Travis.  At first glance it looks nicer than Jenkins.  If someone has first hand experience with both, please let us know your thoughts.

Right now some tests are grouped with the code they are testing, while others are grouped in desispec.test.test_*  I think I prefer the former while initially writing a new module, and then porting to the latter for long term maintenance.  We should group these into a single desispec.test.test() function that runs all of them, and everyone should run that before pushing changes.

FYI, I'm making progress on related issue #22 which runs a daily raw data to redshifts integration test on edison in a cronjob.  I have it working on my laptop and am now sorting out edison environment issues.  NERSC has been using Jenkins and that could be used if we need to get fancier than a bash script in a cronjob.  I'll send out more details when that is working.

**Comment by weaverba137** [comment]
I have extensive experience with Travis, & I like it.

**Comment by weaverba137** [comment]
@dkirkby said, "However, they have the downside that you don't know you broke something until it is already in the wild", but I don't think that's actually much of a problem.  The nice thing about Travis is that it can run tests on any *branch*, & you can catch errors in the branch before they are merged into master & tagged.  Similarly, you make sure your latest commit passes Travis before tagging.

**Comment by sbailey** [comment]
We have reasonable basic coverage for unit tests and the Travis integration is great.  The weak point is the scripts in bin/ which take 30-40 min to test via the integration test, which is run nightly (when edison scratch is working, unlike the past few days...).  Closing ticket.
