### ISSUE TITLE
daily cals dependencies afterany -> afterok

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1500]
Previously I had advocated that daily processing should fall back to default cals (psf, fiberflat) if the nightly cals failed so the pipeline would proceed and we would have *something* in the morning for the science exposures.  In practice, that is never what we want and proceeding just creates more cleanup to do.  I hearby Officially Change My Mind:

change the nightly processing dependency chain to match the reprocessing dependency chain to use "afterok" instead of "afterany", so that if a step fails the other steps don't run without specific action.

**Comment by akremin** [comment]
Resolved with PR #1502
