### ISSUE TITLE
Mark EXPID 24773/106202 as bad

### ISSUE THREAD

**Issue by schlafly** [desihub/desispec#1506]
TILEID 24773 is marked bad in QA, due to high turbulence on exposure 106202.  But 106202 is seen as good in exposures-daily.csv, so NTS will not get more time on 24773.

We need to:
- mark 106202 as bad
- this causes EFFTIME = 0 in exposures-daily.csv
- update the processing of tile 24773 (maybe just delete?)
- set QA = none in tiles-specstatus.csv.
- let this get reobserved and re-VIed as normal when future good observations are available.

**Comment by akremin** [comment]
The exposure was flagged in the exposure_table, processed files removed, and exposures/tiles files rerun to reflect the absence of good data for this exposure. They now show 0.0s `EFFTIME_SPEC`.
