### ISSUE TITLE
flag retired tile 80713 exposures as LASTSTEP=ignore

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1513]
Tile 80713 observed on 20210110 had messed up fiber positions (input NaNs from fiberassign resulting in output FIBER_X=FIBER_Y=0 from platemaker).  This tile has been retired and the targets were re-observed as tile 80715, but we accidentally included it in everest.

@akremin please flag these exposures as LASTSTEP=ignore so that they won't be included in Fuji:
```
TILEID  NIGHT   EXPID
------ -------- -----
 80713 20210110 71721
 80713 20210110 71722
 80713 20210110 71723
```

Related to #1447

**Comment by akremin** [comment]
Done in the master exposure tables using the follow:
`desi_edit_exposure_table -n 20210110 -e "71721-71723" -c LASTSTEP -v ignore --include-comment="improper fiberassing positions"`
