### ISSUE TITLE
refactor how pipeline planning is done

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#152]
Ted is organizing a summary of this, but getting a ticket in place.

Refactor the pipeline planning to make it easier to:
* see what will run and what files will be generated ahead of time
* track what has run / succeeded / failed and why
* (re)run subsets of the processing

The current pipeline doesn't plan a step until it can see what was produced by the previous step.  Refactor that to pre-organize the relationships between exposures (e.g. which arcs/flats flow into which psfs which should be used by which exposures).  These can expanded on the fly to know what should be run and what files should exist.

**Comment by tskisner** [comment]
Here is a first draft summary of a recent discussion about the improvements planned for this next round.  @sbailey - is there anything in here that I missed or got wrong from our discussion?
[pipeline_improve_2016b_v1.pdf](https://github.com/desihub/desispec/files/209245/pipeline_improve_2016b_v1.pdf)

**Comment by sbailey** [comment]
Distilling out a few key points:

The pipeline will have a "dependency graph" of how the exposures are related, analogous to the BOSS spPlan* files.

Unlike BOSS, only the pipeline wrapper uses that file in order to generate the options for the functions/commands to run.  The functions/commands themselves (e.g. desi_extract_spectra.py) do *not* use the dependency graph.

To save on python startup times, the pipeline mpi wrappers will call functions, not spawn scripts.  For human development convenience, scripts will also exist to wrap those same functions.  The key question then becomes how to keep those two routes to calling the functions in sync.  The proposal here is to move all sys.argv / argparse usage into the functions such that the scripts look like:
```
#!/usr/bin/env python
import sys
import desispec.blatfoo
sys.exit(desispec.blatfoo())
```
Any argparsing goes in desispec.blatfoo() itself, and the mpi code would look like
```
sys.argv = ['blatfoo', '--input', '/path/to/file', '--output', '/path/to/another/file', '-n', '1']
desispec.blatfoo()
```
This is the method recommended in desitemplate, though I have previously argued against this approach since it obfuscates the scripts.  It does have the benefit that if you add another option in `desispec.blatfoo()`, you only have to change the mpi pipeline wrapper and not the vanilla wrapper too.  It also allows the testing coverage tools to see what happens inside the script (which was the previous reason that others had advocated this approach).

However, I would still want `desispec.blatfoo()` to basically just parse the args, maybe do a little file I/O, and then call a "real" algorithm function — the algorithm function should remain well separated so that it can be re-used and tested without having to always pass in options via mucking with sys.argv which feels like an ugly hack.  If another option gets added, I'm not sure we're really reduced the number of places that have to change, vs. just moved around which places they are.

Green light to proceed with the dependency graph and mpi wrappers.  I'm still on the fence about whether those wrappers should much with sys.argv as the way of passing info in to the functions (to keep it absolutely in sync with the vanilla command line wrappers), or if they should both use argparse and then directly call an algorithm function with normal options.

**Comment by sbailey** [comment]
Regarding what to do if a step fails:

> If a given processing step throws an exception, the subgraph containing the parent and child nodes of the step will be written to disk as part of the log. Alternative 1: we could also just log which node of the larger dependency graph failed, and extract the subgraph later during followup investigations. Alternative 2: since we have a thin commandline tool for each processing step (see #1 above), we could just log the commandline to pass to that tool.

Alternative 2 seems much more straightforward to use: dump to the log the command I should run to reproduce the failure.  I like that much better than dumping references to nodes in some graph, or subgraphs.

**Comment by tskisner** [comment]
In the current plan, the dependency graph tracks connections between exposures.  However, when tracking success / failure for some steps, we check this status at the individual frame level.  It seems like we should either:  (A) include individual frames at appropriate places in the dependency graph or (B) consider one frame failure as a failure for the whole exposure.  Thoughts?

**Comment by sbailey** [comment]
One frame failure should not block downstream processing of frames that did succeed, i.e. don't kill the entire exposure due to a single frame failure.

I don't think that necessarily implies that the primary dependency graph must track things at the frame level.  That could be expanded on-the-fly similar to the concept of expanding what actual commands should be run and what files will exist.  It just means that success/failure is tracked at the expanded level, not at the exposure level.

If a frame is missing from the input raw data, that should be treated differently from a mid-stream failure.  We want to notice the case of a missing input frame, but that isn't recoverable in the same way as a mid-stream failure that should be flagged and maybe could be fixed.

**Comment by tskisner** [comment]
If we are tracking failures at the "expanded" level, then it seems much 
easier to just include the frame-level information in the graph.  Also 
if we want to do things like select only one spectrograph we can 
trivially prune a graph to include only that information- rather than 
carrying around extra information like "only use spectrograph 3".

**Comment by sbailey** [comment]
Good point about the pruning.  Let's try that — keeping the graph at the frame level instead of the exposure level.

**Comment by tskisner** [comment]
Here is a related question, mostly for @sbailey  and @julienguy.  When calling specex for PSF fitting, we can either use subprocess to call specex_desi_psf_fit, OR we can take that code, make it a function, and call it using ctypes directly.  Since specex is writing files directly and not returning data, the only benefit I see to using ctypes would be to avoid spawning a process (and the fragility that can cause).  Since ctypes can't detect when an exception is thrown, we don't get any extra robustness to detecting failures.  Any strong opinions?

**Comment by sbailey** [comment]
I vote *not* using ctypes for now, and keep doing what we've been doing of
spawning a process to run specex.  We can revisit that if it actually
becomes a problem, but right now it isn't a problem and isn't worth a
refactor compared to the other work we need to do.

Stephen
