### ISSUE TITLE
desi_run_night --survey option

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1531]
Add a `desi_run_night --survey` option so that we can split fuji (cmx,sv1,sv2,sv3) from guadalupe (main) during the transition period.  I'll submit a PR soon that does this, but I'm filing this ticket to document the nights of overlap between sv and main:
```
20210512     sv1 sv3 main
20210513     sv1 sv3 main
20210517         sv3 main
20210518         sv3 main
20210521         sv3 main
20210529 cmx     sv3 main
20210610         sv3 main
```
interleaved between those are nights with only SURVEY=main.

After that but still within the timeframe of fuji/guadalupe are some nights with SURVEY=special:
```
20210615 main special
20210627 main special
20210705 main special
20210706 main special
20210708 main special
20210709 main special
```
@araichoor @schlafly @djschlegel can you please identify those tiles and whether they should go with fuji (to become public with SVDA) or with guadalupe (processed at the same time as fuji but held in reserve until the DA1 release).  The default would be to keep them with guadalupe/DA1 to minimize the number of nights that we have to process in both.

**Comment by schlafly** [comment]
FWIW, the survey = special tiles with 20210615 <= NIGHT <= 20210709 are bright tiles, TILEID 80978 - 80981.  According to
https://desi.lbl.gov/trac/wiki/SurveyOps/TileDesigns
these correspond to some "test" tiles for horrible weather (978, 979) and to ToO test tiles (980, 981).  The horrible weather tiles have some value for setting speed threshholds but IMO need not delay anything.  Transient group would need to weigh in on 980, 981.

**Comment by sbailey** [comment]
Also: my bookkeeping was based upon the current pipeline exposure tables, falling back to FA_SURV when the SURVEY column was not present in those tables.  This brings up cases like tile 81100, which in the fiberassign file has FA_SURV='main' and SURVEY='special', which I think means it uses main survey targets, but was a special test tile that shouldn't be considered a main survey tile (but got lumped into my main survey accounting for the moment).

I hope we can define 20210610 as the last night of SV, and any tiles observed after that (main or special or even cmx dithers) will be part of guadalupe/DA1.

**Comment by sbailey** [comment]
for the record, from @djschlegel on #survey-ops slack:
> Those first two nights of May 12+13 are before the start of the main survey.  There were no main survey tiles those nights.

update: that was from a bookkeeping bug where was falling back to FA_SURV if SURVEY wasn't available in the exposure files, forgetting that we could have SURVEY=special FA_SURV=main tiles.

> The other 5 nights in that list (May 17 to June 10) do have SV3 tiles that should be included in SVDA/fuji, and I can confirm it is only those 5 nights.  The handful of special tiles after that date don’t need to be in fuji.
>[special tiles observed during the transition period May 17 - June 10] can go in guadalupe/DA1.  (They are only fiberassign tests and dither tiles, which have continued after that date on Jun 15, Jun 27, Jul 5, …)

Summarizing:
* after the new exposure tables are ready with a SURVEY column, I will regenerate the lists of which tiles on which nights go with fuji vs. guadalupe and David will cross check
* PR #1533 implemented the `desi_run_night --surveys ...` feature
* Between 20210517 and 20210610 cmx and sv1/2/3 tiles will go with Fuji/SVDA, and all others will go with Guadalupe/DA1.
* Any cmx (dither) or special tiles observed after 20210610 through 20210709 will be part of Guadalupe/DA1

I'm going to close this ticket now since it was originally about adding the --surveys option; I'll reopen tickets/emails/slack for final vetting of what gets run with what prod.
