### ISSUE TITLE
vetting science exposures with missing TILEID

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1545]
Housekeeping in prep for Fuji:

@djschlegel please vet the following exposures that are missing TILEID in the headers:

```
night 20201214 exposures [67797, 67798, 67799]
night 20210113 exposures [72206, 72207, 72208, 72209, 72210, 72211, 72212, 72213, 72214, 72215, 72216, 72217, 72218, 72219, 72220, 72221, 72222, 72223, 72224, 72226, 72228, 72229, 72230, 72231, 72235, 72236, 72239, 72242, 72243]
night 20210114 exposures [72382, 72383, 72384, 72385, 72386, 72387, 72388, 72391, 72392, 72393, 72394, 72395, 72396, 72397, 72398, 72399, 72400, 72401, 72402, 72403, 72404, 72405, 72406]
night 20210211 exposures [75279, 75280, 75282, 75284, 75285, 75286, 75288, 75290, 75291, 75293, 75301, 75303, 75304]
night 20210218 exposures [76786, 76788, 76794]
night 20210219 exposures [76926, 76941, 76945, 76949, 76952, 76956, 76960, 76964, 76968, 76972, 76976, 76980, 76984, 76988, 76992, 76996, 77000, 77004, 77008, 77012, 77016, 77020, 77024, 77028, 77032, 77036, 77040, 77044, 77048, 77052]
night 20210223 exposures [77639, 77640, 77641, 77661, 77662, 77663, 77687, 77688, 77689]
night 20210331 exposures [82808]
```

I suspect that all of them were system checkout tests or other custom observations that we can drop from further processing, but please check if any of these are valid that should be preserved.

Detail: I came across these because they had negative TILEID in @akremin new exposure tables in PR #1537 ; I think that can only arise due to a missing TILEID keyword in the raw data.  If you find that any of them *do* have a TILEID in their headers, let us know.

**Comment by djschlegel** [comment]
Suggested LASTSTEP for each of these exposures below:
night 20201214 exposures [67797, 67798, 67799] ignore -- daytime tests
night 20210113 exposures 72206-72243 skysub -- twilight sky data
night 20210114 exposures 72382 ignore
night 20210114 exposures 72383-72406 fluxcal -- TILEID 80674 test of fibers staying on target
night 20210211 exposures 75279-75304 skysub -- measure scattered light from bright stars
night 20210218 exposures 76786,76788,76794 ignore -- failed tests of focus dither
night 20210219 exposures 76926-77689 ignore -- failed tests of focus dither
night 20210223 exposures 77639-77641,77661-77663,77687-77689 ignore -- tests of ambient light
night 20210331 exposures 82808 ignore

**Comment by akremin** [comment]
These are now reflected in the exposure tables. Thank you for doing the assessments David.
