### ISSUE TITLE
desi_run_night and 20210205 arc/flat out-of-order

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1560]
Related to #1439 (Update calibration handling in desi_run_night), but calling this out into a separate ticket because we may need to deal with this by hand for Fuji:

On night 20210205 the arcs and flats were taken out-of-order (flats were taken before arcs).  Because desi_run_night processes them in order (like nightly processing), it generates a set of fiberflatnight using the default PSF from desi_spectro_calib, and then generates a set psfnight that weren't used for the fiberflatnight, creating an inconsistent state for calibnight/20210205 .

Options for Fuji:
  1. run 20210205 biasnight + dark + arcs by hand, then run flats, double check before running sciences
  2. fix the current logic to "look ahead" before picking arcs/flats (i.e. #1439)
  3. update the exposure_tables directories to have a yaml/json file listing explicitly which exposures should be used for arcs -> psf and flats -> psf, then use that. 

I think (3) is the best long-term fix, but may take longer to implement than we have time for for Fuji.  (2) may also take too long.  (1) is a pain but may be the pragmatic choice.

**Comment by akremin** [comment]
I have come up with an in-elegant work around for Fuji. The `desi_run_night` script doesn't know anything about exposure ordering. It processes the exposures as they are ordered in the exposure table. What I've done is move the arcs to before the flats. This breaks the traditional exposure table ordering of increasing expid, which I don't like and don't want to keep long-term. This does, however, buy time to fix this properly after Fuji is launched.

I have tested this and `desi_run_night` now processed the arcs first, then the flats depend on the `psfnight` generated from those arcs.

My opinion of the correct solution is a modification of (3), but I think it needs to wait until after Fuji. What we need is a "CALIBRATOR" column in the exposure tables, which actually already exists in the processing tables to designate what had been used in a production for calibrations. We just need to add this column and use e.g. Fuji or Everest to do a first assignment, then have humans make changes as needed. Once the code knows exactly what sets of exposures it needs then the ordering of dark -> arcs -> flats is simple to implement.
