### ISSUE TITLE
discard nightly bias if BADAMP set

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1562]
amp r1A was in a bad state on 20201217 from exposures 68341 though 68405 (inclusive), covering the ZEROs, 5min DARK, and ARCs, and then it was fixed before the FLATs began with exposure 68416.

All of the bad exposures already have BADAMPS=r1A set, but biasnight-r1-20201217.fits.gz is generated anyway and is junk, polluting preprocessing of later exposures, e.g. causing the flats to fail.  Fix desi_compute_nightly_bias so that if a BADAMP is set for a given camera, it won't use that ZERO (and in this case there won't be enough good ZEROs and the nightlybias won't be generated for r1, which is better than having a junk one).

Note: badcolumns (from DARK) and psf (from ARC) are correctly skipped due to the bad amp.

**Comment by akremin** [comment]
This should be solved with PR #1570
