### ISSUE TITLE
Overestimated background between fiber blocks caused by bright stars

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1580]
As predicted, the estimate of the background between fiber blocks is sensitive to bright stars.
The worst configuration occurred in 20220107/00117268 camera b7, for a backup exposure,
with 2 bright stars on fibers 324 and 325 (+3500) , biasing the background estimate in the space
between the two fibers, and leading to negative sky fiber residuals.

![preproc-b7-00117268](https://user-images.githubusercontent.com/5192160/148812046-02cc6872-2eba-4fc8-91d7-d1d7947db18c.png)
(blue is with `desi_preproc` option `--bkgsub-for-science`, orange without)
(see motivation for this option in PR #1551 )

**Comment by sbailey** [comment]
desi_preproc uses the non-traceshifted default PSF model from DESI_SPECTRO_CALIB to identify the locations between the bundles, which makes it maximally sensitive to any shifts causing the inter-bundle boxcar extraction to get closer to the fibers.  Using a traceshifted PSF would be ideal.  However, chicken-and-egg: desi_compute_trace_shifts uses a preproc image as input, but here we'd want a traceshifted PSF to use as input to preproc...  Using the nightly PSF is close to ideal (matching the shifted PSF to ~0.02 pixels).

For this case, the shifted PSF differs from the default PSF by ~1.5 pixels, compared to a ~15.8 pixel separation between fibers 324 and 325 (+3500), so I doubt that using a shifted PSF would by itself be sufficient to avoid the wings from the bright stars, but it could be part of the solution.

**Comment by sbailey** [comment]
fixed by #1581.
