### ISSUE TITLE
flag 20210314 split test exposures as bad

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1591]
the following exposures on 20210314 are tests for doing exposure splits on the same tile; these should be flagged as LASTSTEP=ignore (they are failing in the f5 test run due to not finding any good sky fibers):

80468, 80469, 80474, 80475, 80481, 80482

@akremin

**Comment by sbailey** [comment]
Several more from 20210314 to add to the list:

80458, 80459, 80460, 80461

There were tile 80607 which was observed many times on other nights, they just didn't get "Test" in their program name during the testing on 20210314.

**Comment by sbailey** [comment]
Wow, 20210314 was quite a night.

Also drop exp 80478.

**Comment by sbailey** [comment]
20210314 exp 80502 flag petals 5 and 6 as bad.  This is the exposure from issue #1527 where the coordinates file is missing some columns and we have to guess, but on petal 5 half the fibers are BADPOSITION, and on petal 6 they are all BADPOSITION, which probably means that large swaths of canbusses actually failed to move.  Petal 1 is suspect but let's leave it in:
![image](https://user-images.githubusercontent.com/218471/149429827-fb22e6ca-acca-4990-9be8-9636416f36db.png)

**Comment by akremin** [comment]
Pi day was not kind to us in 2021, clearly.

> 80468, 80469, 80474, 80475, 80481, 80482

Done

> Several more from 20210314 to add to the list:
> 
> 80458, 80459, 80460, 80461

Done

> ~Also drop exp 80478.~
> 
> UPDATE: just flag BADCAMWORD=a6,

Done

> 20210314 exp 80502 flag petals 5 and 6

Done
