### ISSUE TITLE
streamline io.read_* outputs

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#16]
Most of the desispec.io.read_* functions return an inconveniently long tuple of outputs.  Using it interactively almost always requires looking up the arguments to figure out which arguments are which.  e.g.

    flux, ivar, wave, resolution_data, header = io.read_frame(filename)

Update these to return lightweight classes instead that contain the equivalent member variables, e.g.

    spectra = io.read_frame(filename)
    plot(spectra.wave, spectra.flux[0])

My style preference is for these to be super-lightweight classes that are basically syntactic sugar compared to just returning dictionary with keys of "wave", "flux", "ivar", etc.  They could provide some minimal convenience functions, but the intention is that these are *not* containers for core algorithms. They should expose the raw numpy arrays just like the current io.read_* routines return raw numpy arrays.

This change will break a lot of code, so it might be best to wait for basic functional unit tests to be in place first.  After making the change, if it breaks code that wasn't caught by a test, that should be added as a test too.

**Comment by weaverba137** [comment]
Looks like you want an instance returned by [namedtuple()](https://docs.python.org/2/library/collections.html#collections.namedtuple).

**Comment by sbailey** [comment]
I'll submit a pull request for this soon.  In the end I didn't use namedtuple() because I wanted to have a small amount of functionality in these classes, e.g. checking shape consistency between flux and ivar.  namedtuple() does match the original issue request (and is nifty, thanks for pointing it out), but the scope slightly shifted during implementation.

**Comment by sbailey** [comment]
Addressed by PR #47 .  Closing issue.
