### ISSUE TITLE
20201222/69401 needs BADCAMWORD=a6

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1600]
Tile 80617 night 20201222 expid 69401 has bad petal 6 positioning but isn't yet flagged as BADCAMWORD=a6 in the exposure tables:
![image](https://user-images.githubusercontent.com/218471/150032747-973dc1c6-46f7-4e18-8663-b012197d34a4.png)
(the previous two exposures of that tile are correctly flagged as BADCAMWORD=a6, and petal 0 has enough good fibers let's keep it).

Suggested action:
```
desi_edit_exposure_table -n 20201222 -e 69401 -c BADCAMWORD -v a6 --include-comment "bad petal pos a6"
```

<HR/>

Related, heads up: exposures 69402-69404 (and beyond...) are flagged as BADCAMWORD=a3 which is correct because nearly every fiber has FIBER_X/Y DELTA_X/Y as NaN, though Nightwatch make them look almost ok:
![image](https://user-images.githubusercontent.com/218471/150032967-07a756ef-a1b4-46ba-8f5b-e9ef4833bf57.png)
i.e. when evaluating historic nightwatch plots for positioning failures, watch out for apparent saturating at 0 and not just a bunch of yellow.  No action needed on those exposures, they are already flagged correctly.

**Comment by akremin** [comment]
This has been flagged in the exposure tables and I believe I saw a nightwatch ticket for better coloring of NaN's, so I'll close this ticket.
