### ISSUE TITLE
20210217 test exposures for LASTSTEP=ignore

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1601]
20210217 exposures 76356, 76358, 76394 are mid-day test exposures that need to be flagged as LASTSTEP=ignore.  Other test exposures around then are already flagged as ignore due to aborted exposure times.  Suggested commands:
```
desi_edit_exposure_table -n 20210217 -e 76356 -c LASTSTEP -v ignore --include-comment "test exposure"
desi_edit_exposure_table -n 20210217 -e 76358 -c LASTSTEP -v ignore --include-comment "test exposure"
desi_edit_exposure_table -n 20210217 -e 76394 -c LASTSTEP -v ignore --include-comment "test exposure"
```

One the same night, exposures 76481 and 76483 are split exposure tests that should be LASTSTEP=ignore instead of skysub (other split exposure tests adjacent to those are already flagged as ignore):
```
desi_edit_exposure_table -n 20210217 -e 76474:76483 -c LASTSTEP -v ignore --include-comment "split exposure test" --overwrite-value
```

**Comment by akremin** [comment]
These are now done. The commands provided would have worked, though in reality I used one command for the first three and shortened the comments slightly.
