### ISSUE TITLE
coadded spectra when missing one camera

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1604]
Quasar has valid blue and red camera spectra in 'spectra' file but not in coadded file.

```
plot_spectra -i $DESI_SPECTRO_REDUX/f5/tiles/pernight/139/20210410/spectra-5-139-20210410.fits -t 39627945043561608 --rebin 4 --redrock $DESI_SPECTRO_REDUX/everest/tiles/pernight/139/20210410/redrock-5-139-20210410.fits

plot_spectra -i $DESI_SPECTRO_REDUX/f5/tiles/pernight/139/20210410/coadd-5-139-20210410.fits -t 39627945043561608
```
It is fully justified to have the NIR part of the spectra flagged as bad because the spectrum is affected by known defects in CCD z5, but the good B and R data should be in the coadd. In this example, we should have been able to fit its redshift. 

![Screenshot from 2022-01-20 10-16-02](https://user-images.githubusercontent.com/5192160/150397736-cf081267-3d88-46fb-95a7-4dd464968515.png)

**Comment by sbailey** [comment]
Fixed in PR #1605.
