### ISSUE TITLE
Improve fiberflat vs humidity correction

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1615]
For some fibers, the fiber flat humidity correction has a broadband component that is biasing the calibration.
The following figure shows the fiberflat humidity correction for  20210514/00088361 b7 .
There is a offset for several fibers among which fiber 3797.

![Screenshot from 2022-01-21 16-29-26](https://user-images.githubusercontent.com/5192160/150616715-76f7cf74-1c8a-4810-95a5-0601b5b84329.png)

**Comment by moustakas** [comment]
@julienguy I was taking a look at this ticket to see if it was anything easy I could help out with.

Forgive me if I'm missing something super-simple (or if you already have a solution in mind), but can you explain a bit more the problem you're seeing? I checked this calibration with
```
desi_compute_humidity_corrected_fiberflat --use-sky-fibers -o test.fits \
  -i /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20210514/00088361/frame-b7-00088361.fits \
  --fiberflat /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20210514/fiberflatnight-b7-20210514.fits 
```
and I got the image in the left-hand ds9 panel (which should match your screenshot, above, although  there are some differences perhaps related to how the images are scaled). Meanwhile, the image on the right is the original `fiberflatnight`, which looks pretty similar. (I haven't looked at many of these fiberflats, so maybe this looks OK or maybe it doesn't?).

I'll poke around the humidify model itself next but I wanted to get your thoughts and let you know I had looked at this briefly.


<img width="1030" alt="Screen Shot 2022-01-21 at 9 41 27 PM" src="https://user-images.githubusercontent.com/1431820/150621840-72992d00-94e5-49b5-a4e9-1d1890230b35.png">

**Comment by julienguy** [comment]
The problem is that the correction itself (the ratio of the new flat / nightly flat) has a broadband component for some fibers. On your plot, we do see the variation of transmission from fiber to fiber, which is expected to be independent of humidity.
