### ISSUE TITLE
Science exposures with no program name but seem plausible as genuine

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1622]
The following 5 exposures were taken without program name, which is common among "test" exposures. However, they are longer exposure times with other indicators that make them seem plausible as real science data:

```
NIGHT,EXPID,TILEID,OBSTYPE,LASTSTEP,EXPTIME,EFFTIME_ETC,SURVEY,FA_SURV,FAPRGRM,EBVFAC,AIRMASS,TARGTRA,TARGTDEC,MJD-OBS
20210304,79287,80695,science,all,142.7492,-99,unknown,sv1,unknown,1.237527583,1.273408,141.493071,69.507991,59278.28669
20210304,79289,80697,science,all,269.8221,-99,unknown,sv1,unknown,1.036541311,1.027218,144.99783,32.374941,59278.30271
20210304,79293,80697,science,all,195.814,-99,unknown,sv1,unknown,1.036541311,1.051051,144.99703,32.374851,59278.31821
20210308,79741,80721,science,all,133.7501,-99,unknown,sv1,unknown,1.115801492,1.010584,114.539342,39.381091,59282.17688
20210308,79749,80721,science,all,500.0686,-99,unknown,sv1,unknown,1.115801492,1.03374,114.537392,39.38101,59282.20747													
```

**Comment by djschlegel** [comment]
I would suggest marking all expid 79279-79296 (inclusive) on 20210304 as test or bad.  Those were split exposure tests, and add up to only a very small effective time on tiles that have plenty of good observations.

The same is true for expid 79739-79749 on 20210308 (which have some zeros mixed in the middle).  Thick clouds mean no useful time anyway on these split tests.

**Comment by akremin** [comment]
Thank you very much. Those exposures are now set to be ignored in the exposure tables.
