### ISSUE TITLE
Fuji: 20201220 exp 69082 - 69085 corrupted coordinates input

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1640]
Night 20201220 exposures 69082 - 69085 (tileid 80618) has corrupted coordinates files without meaningful positioning info.  For everest we plowed forward with assemble_fibermap and dummy values:
```
...
ERROR:fibermap.py:499:assemble_fibermap: Missing DX_0 in /global/cfs/cdirs/desi/spectro/data/20201220/00069084/coordinates-00069084.fits
ERROR:fibermap.py:510:assemble_fibermap: Missing VISITIDS header keywords to find earlier coordinates file
ERROR:fibermap.py:513:assemble_fibermap: Missing spotmatch FLAGS_CNT_0 in /global/cfs/cdirs/desi/spectro/data/20201220/00069084/coordinates-00069084.fits; no positioner offset info
ERROR:fibermap.py:606:assemble_fibermap: Unable to find useful coordinates file; proceeding with fiberassign + dummy columns
```
but now we are more strict about using positioner offsets for TSNR, selecting stars, skies, etc. and this is a fatal error for Fuji.  These 4 exposures should be flagged as LASTSTEP=ignore, cleanup the processing tables, and then resubmit 20201220.  This tile was observed on 5 other good exposures on this night, many times on other nights.

**Comment by akremin** [comment]
For additional information these are labeled as "twilights" in the user-defined "PROGRAM" keyword.

They are now flagged.

There were other observations before these exposures which were being jointly fit to it. So it's not as simple as excising files/jobs. I've removed the entire tile and resubmit the tile to get the correct standard star fitting behavior, etc.

I resubmitted using: 
`NIGHT=20201220; desi_run_night -n $NIGHT --proc-obstypes="science" --tiles="80618" --system-name="cori-knl" --append-to-proc-table &>>${DESI_SPECTRO_REDUX}/${SPECPROD}/logs/${NIGHT}.log`

(after using `--dry-run-level=3` with the same command to confirm that it would do the proper thing).
