### ISSUE TITLE
Fuji: 20210106 exp 71126 sp1 bad: no valid stdstars

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1641]
20210106 exp 71126 (tile 80660) sp1 has no good standard stars and should be flagged as bad.  Note that sp3 is already flagged as bad due to positioning failures for the entire petal; sp1 also has bad positioning for a subset of the petal (but enough to take out all the standard stars).  This exp/petal is also missing from Everest.

Cleanup is a bit tricky because existing Fuji jobs already include a012456789 (no 3), but we want it to have a02456789 (without 1 or 3) for this exposure.

![image](https://user-images.githubusercontent.com/218471/151860516-21a1fc6f-1e58-44c1-a838-74cd270dea7b.png)

**Comment by akremin** [comment]
Updated the exposure tables with:
`desi_edit_exposure_table -n 20210106 -e 71126 -c BADCAMWORD -v "a1" --append-string --include-comment="No valid stdstars on sp1"`

Then removed the relevant jobs from the processing table. After, I resubmitted the tile with:
`NIGHT=20210106; desi_run_night -n $NIGHT --proc-obstypes="science" --tiles="80660" --system-name="cori-knl" --append-to-proc-table &>>${DESI_SPECTRO_REDUX}/${SPECPROD}/logs/${NIGHT}.log`

Note this intentionally submitted the jobs to the `realtime` queue. You'd want `--queue="regular"` to submit it to the regular queue.
