### ISSUE TITLE
Fuji: bookkeeping on 202104xx with missing cameras

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1645]
@akremin please check the job bookkeeping for night 20210417.

Update: I had been looking at the daily dashboard, not the fuji dashboard, causing confusion about the state of jobs vs. files on disk.  Removing extraneous confusion to focus on the problem:

Night 20210417 expid 85210 has proccamword=a01234567b8r8 due to saturation on z8 and bad positioning on a9.

desi_proc skips desi_select_calib_stars because it is still looking for the "missing" stdstars-8-00085210.fits, which then causes a chain of failures for desi_compute_fluxcalibration due to missing calibstars-00085210.csv resulting in no cframe files and no redshifts.

This is related to #1225, and if the pipeline camera dependency logic is still messed up for this case we may need to cleanup and resubmit jobs by hand, and punt pipeline logic updates to post-fuji.

**Comment by akremin** [comment]
Issue #1225 is related, but was primarily addressing cases where all cameras had coverage on at least one exposure such that the full wavelength range was spanned. That was fixed in PR #1402 .

This comes about because z8 has no good exposures. In the past we have tossed out the entire petal in these instances because we can't do the standard star fitting without the full wavelength range.

Unless we think future improvements will allow std fitting with just b+r, I suggest we flag the entire petal in this case as well.

**Comment by sbailey** [comment]
20210420 exposures 85635 (tile 341) and 85636 (tile 314) appear to be a similar situation, where the pipeline is blocking downstream jobs based on missing a stdstar file shouldn't be there due to zcam saturation events.

**Comment by akremin** [comment]
Thanks. Any comments on my question/suggestion? I will apply the same decision making to all of these.

For the record: It is unfortunate that `desi_select_calib_stars` takes down an entire tile because of a missing camera, but technically it has to as every petal of every (jointly fit) exposure is supposed to have a vote. Luckily PR #1402 at least makes us robust to issues where a camera is missing on only a subset of exposures.

**Comment by julienguy** [comment]
desi_select_calib_stars should not take down an entire tile because of a missing camera in any situation. if it does we need to change the code.

**Comment by sbailey** [comment]
I'll look into this more.  It looks like my fix in #1225 worked for the case where a camera was missing from one exposure but present for another exposure of the same tile, but has incorrect dependency logic for the case of missing a camera when that tile was only observed on a single exposure.

desi_select_calib_stars is fine with a missing petal if we don't incorrectly tell it that the petal exists.  The bug is upsteam logic telling it to expect a file that isn't there.

**Comment by sbailey** [comment]
The pipeline should/could do better in the case of a single bad camera by not calling desi_proc_joint_fit for stdstars with partial spectrographs, but the end product is the same as flagging the entire petal as bad: we don't get redshifts for that petal in either case.  It's not immediately clear to me where to intercept that in the pipeline logic to call desi_proc_joint_fit and poststdstar jobs with the subset of complete spectrographs.

So for the purposes of Fuji, @akremin let's do the pragmatic thing you suggested of just flagging the entire petal as bad, cleanup, and resubmit.  Post-Fuji we can investigate more elegant solutions for handling future cases of single bad cameras (it wouldn't recover these cases, but it might make bookkeeping cleaning of what we're flagging for what reason).

Summarizing what needs to be flagged as bad and resubmitted:
  * 20210417 85210 BADCAMWORD=a89  (a8 for z8 saturation, a9 for bad positioning)
  * 20210420 85635 BADCAMWORD=a4 (due to z4 saturation)
  * 20210420 85636 BADCAMWORD=a26 (due to z2 and z6 saturation)

**Comment by sbailey** [comment]
Related, but a slightly different problem:

20210221 tile 80708 had a z2 saturation on its first exposure 77430, but ok on its second 77431.  The pipeline could generate stdstars for all 10 petals, but because the first exposure was missing z2, the pipeline called desi_proc_joint_fit with a013456789b2r2 instead of the full a0123456789.

In this case I don't think flagging 77430 a2 as bad would work since then the pipeline still wouldn't pickup the good a2 on the second exposure.  I think we'll need to cleanup this one by hand, but will discuss with @akremin first.

I double checked and the other exposures listed in the previous comment are all single exposures of single tiles, so flagging the full petal as bad and resubmitting would work.

**Comment by sbailey** [comment]
Two more cases needing cleanup due to zcam saturation on the first exposure but not the second:

20210309/79877 z8 saturated, though 20210309/79878 has z8 ok but stdstar fit was called with a01234579b8r8

20210309/79885 z2 and z8 saturation; following exp of tile ok; but stdstar fit a0134579b28r28

**Comment by akremin** [comment]
This was done as part of cleanup for the reservation last week. 

The petals below have had their exposure tables updated, science files removed, and poststdstar jobs and redshifts re-run.

> Night 20210417 expid 85210 has proccamword=a01234567b8r8 due to saturation on z8

Done

> 20210420 exposures 85635 (tile 341) and 85636 (tile 314)

Done

> * 20210318 80961 BADCAMWORD=z8 (due to z8 saturation)

Done



The nights/tiles/exposures were rerun after updates to the standard star fitting code merged in PR #1658 . The jobs failed originally so no cleanup was required. All files are now up to date and correct.

> 20210221 tile 80708 had a z2 saturation on its first exposure

Done

> 20210309/79877 z8 saturated, though 20210309/79878 has z8 ok but stdstar fit was called with a01234579b8r8
> 
> 20210309/79885 z2 and z8 saturation; following exp of tile ok; but stdstar fit a0134579b28r28
> 
> 20210203/74464 z0 saturation, ok in 20210203/74465, ...

Done, Done, and Done

> 20210309 tile 80691 first exp 79863

Done
