### ISSUE TITLE
Fuji: 20210420 exp 85637 sp4 bad positioning

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1648]
20210420 exp 85637 petal 4 had bad positioning, leading to no standard stars passing cuts.  This petal should be flagged as bad and removed, then relaunched.  This is blocking redshifts for tile 369 on that nights.

![image](https://user-images.githubusercontent.com/218471/152243330-2511f1dd-be6b-45a7-8c5c-6f3f3aa5b4e3.png)

@akremin

**Comment by akremin** [comment]
Flagged with:
`desi_edit_exposure_table -n 20210420 -e 85637 -c BADCAMWORD -v a4 --append-string --include-comment="Bad positioning on p4"`

Removed relevant processing table entries from table and sp4 files from prod. Then ran:
`NIGHT=20210420; desi_run_night -n ${NIGHT} --tiles="369" --system-name="cori-knl" --append-to-proc-table &>>${DESI_SPECTRO_REDUX}/${SPECPROD}/logs/${NIGHT}.log &`
