### ISSUE TITLE
Fuji: 20210420 expid 85616 tile 88 bad

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1651]
20210420 expid 85616 (tile 88) had bad positioning across all petals, leading to downstream stdstar selection failures.  This entire exposure should be flagged as bad and removed (LASTSTEP=ignore).  This tile was re-observed on 20210429 with good exposures.

![image](https://user-images.githubusercontent.com/218471/152256279-184fc917-3671-4d0a-b2de-6acad84c3456.png)

**Comment by akremin** [comment]
This exposure was marked to ignore in the exposure table, the `preproc` and `exposures` files removed, and the scripts were removed. No redshifts were yet generated.
