### ISSUE TITLE
Fuji: 20210130 exp 73731-73732 no good std on sp5

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1653]
Tile 80720 on night 20210130 exp 73731-73732 has no good stdstars on sp5 leading to stdstar job failures.  Please flag that petal as bad and resubmit.

**Comment by akremin** [comment]
A mystery: petal 2 also reports no standard stars on this tile but strangely that petal succeeded for standard stars. Fiberassign png: https://data.desi.lbl.gov/desi/target/fiberassign/tiles/trunk/080/fiberassign-080720.png

After flagging sp5 and rerunning, sp2 then failed flux calibration. 

Flagging sp2 now and rerunning again.

**Comment by akremin** [comment]
Sp2 files were removed and the exposures were rerun yet again. This time the flux calibration succeeded on the remaining 7 petals.
