### ISSUE TITLE
Four nights in Fuji and Guadalupe without biases or badcolumn files

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1661]
There are four nights in Fuji + Guadalupe that do not have enough "calib zeros". Since the biases and bad column identification are performed in the same script, the bias calculation exits and prevents the bad column identification from occurring either.

The darks are available for three of the four nights, but are not run in any of the nights because of the bias code exiting.

Additionally, we could consider reducing the minimum number of zeros from 20 to 18 to accommodate three of the nights. The fourth night (20210629) we will have to decide if non "calib zeros" could be used. Using non "calib zeros" is a potential concern because zeros from special tests or afternoon zeros run before hardware re-initialization may then be used.

All of these nights have already been processed in Fuji+Guadalupe, but vetting should be done and an assessment made as to whether we should rerun using biases from a smaller set of zeros, having create the bad column identifications, or both.

Nights in Fuji:

- **20210422** - 21 zeros taken but after discarding first 2 there weren’t enough to compute biases (19 is less than 20). There is a "calib dark" but code exits before it gets there.
- **20210331** - 20 zeros taken but after discarding first 2 there weren’t enough. There is a "calib dark" but code exits before it gets there.

Nights in Guadalupe:

- Night **20210519**: 18 zeros were taken, so not enough for biases.  No darks, so we can't produce badcolumns in any event.
- **20210629** has dark sequences and zeros associated with it but no "calib dark" or "calib zeros". We would use a “dark seq” dark thanks to a recent PR, but the bias code only uses "calib zeros" and exits before it gets to bad column identification.

**Comment by julienguy** [comment]
I would lower the min threshold to N=15 zeros (while still using more when available).
the total noise rms is then increased by sqrt(1+1/15) /sqrt(1+1/20)) =  0.8% which is very small.

For 20210629, it would be great to be able to declare zeros as good for calib in the exposures table.

**Comment by sbailey** [comment]
@julienguy thanks.  Could you also confirm that the remaining zeros on those nights are ok?  i.e. not getting a complete set of zeros might indicate some other problem with the data leading to canceling the sequence, i.e. it might be more than just a question of statistics.

> For 20210629, it would be great to be able to declare zeros as good for calib in the exposures table.

Unfortunately I think that requires a code update to allow those zeros, but we could do that (as an option to not change previous runs).

**Comment by julienguy** [comment]
- zeros in 20210331 are ok
- zeros in 20210422 are ok
- zeros in 20210519 should be ignored (CCD not well stabilized for at least 10 of them), we should use the default zeros
- zeros in 20210629 are good but a software modification is needed to tell the code to use them

**Comment by sbailey** [comment]
I ran nightly bias + badcol for 20210629 using tag 0.51.5 after merging PR #1662, and then relaunched that night.  We're proceeding with cleanup using tag 0.51.4 to minimize the number of tags in downstream products, even though 0.51.5 is equivalent.

I think that addresses the nights in this ticket, so closing.
