### ISSUE TITLE
Fuji: 20210218: sp3 bad positioning all exp

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1663]
Petal 3 had bad positioning for all science exposures on night 20210218.  These should be flagged as BADCAMWORD=a3 for exposures 76796-76826, then cleanup and resubmit.

**Comment by akremin** [comment]
This was done as part of cleanup for the reservation last week. All sp3 science files were removed, post-stdstar jobs and redshifts run, and exposure tables updated.
