### ISSUE TITLE
Fuji: desi_tile_qa crashes on some sv1 data

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1670]
I'm not sure we care about tile_qa for SV1-era data, but filing a ticket with details anyway:

desi_tile_qa crashes on some sv1 data.  There could be a variety of reasons, but at least one example is:
```
desi_tile_qa -g cumulative -t 80605 -n 20210205
...
ERROR:tile_qa.py:93:compute_tile_qa: missing /global/cfs/cdirs/desi/spectro/data/20210205/00067710/fiberassign-080605.fits
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.6/bin/desi_tile_qa", line 267, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.6/bin/desi_tile_qa", line 196, in main
    entry = func(**func_arg)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.6/bin/desi_tile_qa", line 62, in func
    fiberqa_table , petalqa_table = compute_tile_qa(night,tileid,specprod_dir,exposure_qa_dir,group=group)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.6/lib/python3.9/site-packages/desispec/tile_qa.py", line 94, in compute_tile_qa
    raise FileNotFoundError("missing {}".format(fafn))
FileNotFoundError: missing /global/cfs/cdirs/desi/spectro/data/20210205/00067710/fiberassign-080605.fits
```
In early data the fiberassign file could appear in an earlier expid than the spectrograph exposure.  If we want to support this case, `desispec.io.fibermap.find_fiberassign_file(night, expid, tileid)` has logic to walk back in time looking for a matching fiberassign file for that tile.  But I'm not sure it's worth it.

I'll also attach a file from @araichoor with missing tile-qa output from fuji.

Comments welcome about how hard we should try to recover these.

**Comment by sbailey** [comment]
File from @araichoor with tile-qa failures:

[tmp-tileqa-fuji.txt](https://github.com/desihub/desispec/files/8037163/tmp-tileqa-fuji.txt)

**Comment by araichoor** [comment]
from a quick look at the 80605 data, I m confused why the code looks for night=20210205 for that expid=67710, which was observed on night=20201214.
let me understand the code here..

**Comment by sbailey** [comment]
Yeah, I was just noticing that too.  find_fiberassign_file won't help in this case...

**Comment by araichoor** [comment]
if I m correctly reading the code:
this line, which is inside a loop on expids:
https://github.com/desihub/desispec/blob/3c6efb8c917811a3082dafdb56f9f68d79511e0c/py/desispec/tile_qa.py#L87
uses for `night` the input argument one (here the latest night for the tile, used in the cumulative), i.e. not the night for the expid.

whereas it looks like one should rather do something like:
```
expid_night = fmap["NIGHT"][fmap["EXPID"] == expid][0]
fafn = findfile("fiberassign", night=expid_night, expid=expid, tile=tileid)
```

I m not sure why this crash didn t happen before.
maybe because we never ran this routine on an early tile where the `GOALTIME` keyword was not in the header?

**Comment by araichoor** [comment]
I confirm that none of the 148 tiles from `tmp-tileqa-fuji.txt` -- ie with a missing tile-qa* file -- have the GOALTIME keyword, so it s likely that is the cause for those missing files.

shall I go ahead and open a PR with a fix like I suggest?
if so, shall I start from the fuji branch?

**Comment by sbailey** [comment]
Yes, please start from the latest fuji branch, create a new branch off of that, and make updates + a PR from there.  Thanks.
