### ISSUE TITLE
For computing EFFTIME for fiber rejection purposes, use median tile E(B-V) rather than per-fiber E(B-V)

### ISSUE THREAD

**Issue by schlafly** [desihub/desispec#1685]
We reject fibers when they have low effective time.  Some contributions to the effective time are things that change from observation to observation, but others do not.  High E(B-V) fibers will never be observed at low E(B-V), so marking those fibers as bad doesn't really help to eventually get those fibers a good observation.  In extreme cases, we end up rejecting entire petals because of high E(B-V) on a substantial fraction of the petal.

Here's an example case where we lost a patch of fibers at higher E(B-V):
https://github.com/desihub/desisurveyops/issues/25

It would be good to change the EFFTIME computation for fiber rejection purposes to use the median tile E(B-V) rather than the individual fiber E(B-V)s.

**Comment by julienguy** [comment]
fixed in pr #1722
