### ISSUE TITLE
Fuji: missing tile-qa* files (as of 15 Feb, 9:30am Pacific)

### ISSUE THREAD

**Issue by araichoor** [desihub/desispec#1686]
Based on exposures-{fuji,guadalupe}.fits files, I've checked (on 15 Feb, 9:30am Pacific) for missing tile-qa* files in the pernight/ and cumulative/ folders.
I find missing files for 2 pernight/ reductions, and for 129 cumulative reductions.

The list (*fits and *png) is here: [tmp-tileqa-fuji.txt](https://github.com/desihub/desispec/files/8073524/tmp-tileqa-fuji.txt)

I note that all are 80xxx tiles (so no SV3 tile); it could be that the tile-qa routines crash for those tiles.

**Comment by sbailey** [comment]
Moving #1687 over to here and closing that ticket:

```
desi_tile_qa -n 20210115 -t 80715 --outdir .
...
ERROR:tile_qa.py:109:compute_tile_qa: could not identify prog
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.8/bin/desi_tile_qa", line 267, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.8/bin/desi_tile_qa", line 196, in main
    entry = func(**func_arg)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.8/bin/desi_tile_qa", line 62, in func
    fiberqa_table , petalqa_table = compute_tile_qa(night,tileid,specprod_dir,exposure_qa_dir,group=group)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.8/lib/python3.9/site-packages/desispec/tile_qa.py", line 110, in compute_tile_qa
    raise ValueError("could not identify prog")
ValueError: could not identify prog
```

**Comment by araichoor** [comment]
Re-writing here what I just posted on #1687 which has been closed while I was typing...

The crash in #1687  is at the step trying to recover or guess GOALTIME.
Those two tiles have the following fiberassign header values:
```
# TILEID FAFLAVOR TARG
80715 sv1m31 DESIROOT/target/catalogs/gaiadr2/0.48.0/targets/sv1/resolve/supp
80718 sv1rosette DESIROOT/target/catalogs/gaiadr2/0.50.0/targets/sv1/resolve/supp
```
Those  indeed are not handled by the current code, which uses the basename of TARG to guess the program.
I didn t handle this "supp" case.

I m not sure how to fix that.
Shall I just set GOALTIME=0 for any not-handled cases?
Or would it be even better to replace that part of the code with using the same recipe as in other places in desispec?
Those are listed here: https://github.com/desihub/desispec/issues/1649#issuecomment-1029513529

If useful, the exposures for those two tiles (from `/global/cfs/cdirs/desi/spectro/redux/fuji/exposures-fuji.fits`):
```
 NIGHT   EXPID TILEID      EXPTIME         EFFTIME_SPEC    GOALTIME MINTFRAC   SKY_MAG_R_SPEC  
 int32   int32 int32       float64           float64       float64  float64       float64      
-------- ----- ------ ----------------- ------------------ -------- -------- ------------------
#
20210115 72498  80715      900.04296875  768.1716918945312      0.0      0.9  21.15979279118737
20210115 72499  80715 900.0303344726562  701.9066162109375      0.0      0.9 21.133449396562614
20210115 72500  80715  900.039306640625 337.13275146484375      0.0      0.9  21.10905382123766
#
20210130 73720  80718 300.0876770019531  9.124605178833008      0.0      0.9 19.745111904124467
20210130 73721  80718 300.0907897949219   9.46870231628418      0.0      0.9 19.718588774760807
20210130 73727  80718 600.0631103515625  10.96377944946289      0.0      0.9 19.560143374976036
20210130 73728  80718 600.0503540039062  5.903741359710693      0.0      0.9 19.378241376920943
```

**Comment by sbailey** [comment]
The "same recipe as in other places in desispec" is unfortunately an organically grown mess of if/then/else distributed throughout multiple functions in the tsnr afterburner code, i.e. it's not easy to extract the recipe for here.

I would like to fix this in the future by fixing the inputs so that all tiles from the start know their SURVEY, FAPRGRM, GOALTIME, etc. but it's too late for that for Fuji.  For the purposes of Fuji tile-qa of non-sv3 non-main tiles, I think it would be fine to use GOALTIME=0.0 as a default when unknown (as long as that doesn't additionally trigger some divide-by-zero mess).  Otherwise if these are the only two tiles impacted, you could even hardcode their answer based on TILEID.

Please spot check some of the 129 cumulative missing tile-qa for whether they were just job timeouts, or something deeper that needs to be fixed.

**Comment by araichoor** [comment]
About the 129 other missing tile-qa:
Those all are because the code is looking for the fiberassign-TILEID.fits.gz file in the wrong place:
```
raichoor@cori05:~> grep rror /global/cfs/cdirs/desi/spectro/redux/fuji/tiles/cumulative/80624/20210109/logs/tile-qa-80624-thru20210109.log | grep -v raise
FileNotFoundError: missing /global/cfs/cdirs/desi/spectro/data/20210109/00070514/fiberassign-080624.fits
```
I believe this should be fixed by this PR https://github.com/desihub/desispec/pull/1672.
The PR has been merged on Feb, 10; but the code for those 129 failures was run on Feb. 8, before that.
So, re-running the code should work.

**Comment by sbailey** [comment]
All of these have been rerun; please open a new ticket with details if any additional missing tile-qa files are identified.
