### ISSUE TITLE
Document all installation instructions needed to run integration tests.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#170]
This is a meta-issue that depends on several other existing issues.

* desihub/desidatamodel#6
* desihub/desidatamodel#7
* desihub/desidatamodel#8
* desihub/desiutil#29
* #18 

Concurrently with these other issues being worked on, we need to

* [Update NERSC account instructions](https://desi.lbl.gov/trac/wiki/Computing/Software/Using).
* Add high-level documentation on running the pipeline (defined for the purposes of this issue as being able to run integration tests).

**Comment by sbailey** [comment]
FYI, the final step of running the integration tests is:
```
# from python
from desispec.test.integration_test import integration_test
integration_test()

# or from command line within desispec directory
python py/desispec/test/integration_test.py
```
(it is a module that has a if __name__ == '__main__' for running it...)

At minimum this will require desispec, desisim, desiutil, speclite, specter, desitarget, and redmonster, and a copy of the basis templates from NERSC /project/projectdirs/desi/spectro/templates/basis_templates/v2.1/ and probably a bunch of environment variables (identifying and documenting those is part of this task).

Those other issues are related, but shouldn't be viewed as blocking factors since it is possible to install the code and run the integration tests today, though I'd have to start over from scratch to work out all the details of what is actually necessary.

**Comment by weaverba137** [comment]
#176 also needs to be included in this meta-issue.

**Comment by weaverba137** [comment]
Some important questions before I close this:

1. Does the pipeline actually depend on specsim?  I've successfully run the integration test without it apparently.
2. This item lists a few other open issues that should be closed before this can really be declared done: #18, desihub/desidatamodel#6 & desihub/desiutil#29.  For the third one, the outstanding item is integrating my integration test scripts with the main one.  But the other two require input from other people.

**Comment by sbailey** [comment]
specsim: the integration test uses pieces of desisim that do not require specsim; however we are planning on refactoring those pieces to make use of specsim features in the future, so you might as well leave that dependency in there.  Note: the spectro pipeline itself doesn't need specsim, this is only for generating the inputs for the integration test.

Regarding the other tickets, it seems the title of this ticket is out of sync with its contents.  "Document all installation instructions needed to run integration tests" doesn't require the datamodel documentation tasks in #18 and desihub/desidatamodel#6, and desihub/desiutil#29 (Integration and Test Infrastructure at NERSC) is related, but also somewhat different than documenting how to install the code and run the integration tests.

Should this ticket be retitled, or can we close it out while creating a separate documentation milestone/meta-issue to track group the others?

**Comment by weaverba137** [comment]
@sbailey, that is true.  I think we can close #18 and desihub/desiutil#29 quickly which just leaves #18 on its own.

I will keep specsim in the instructions.  I'm just waiting for any addition comments on the instructions before closing this.

**Comment by weaverba137** [comment]
PS, In my previous comment I meant to say "which just leaves desihub/desidatamodel#6 on its own."

**Comment by weaverba137** [comment]
https://desi.lbl.gov/trac/wiki/Pipeline/Install is the official place for this documentation.  It has been tested by people other than the author.  For additional documentation problems, open a new issue.
