### ISSUE TITLE
readonly desi user/pass for DB access

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1707]
For the prototype fuji and guadalupe database loads, please add a read-only access using the standard desi collaboration user/pass (the current read-only access uses a different username/password that only a few of us know).

Adding the standard desi user/pass would likely have the side effect of collaboration end users adding it to their .pgpass file, which I think is ok (they probably already have it in their .netrc file with an equivalent level of "security").  If that is a bad idea then let's document why that is bad and keep a separate different readonly user/pass for the DB.

To be clear: this is only for the read-only access.  The read/write access for loading the DB absolutely should have a different user/pass.

**Comment by weaverba137** [comment]
The `desi` user now exists for `nerscdb03.nersc.gov` database `desidev`, with the standard password.  For the record, these additional SQL commands are required to allow `desi` to view a particular schema (`f5` for example):
```sql
GRANT USAGE ON SCHEMA f5 TO desi;
GRANT SELECT ON ALL TABLES IN SCHEMA f5 TO desi;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA f5 TO desi;
```
I'll have to add this to the database loading script, which is straightforward.
