### ISSUE TITLE
tiles in Everest not in Fuji nor Guadalupe

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1718]
For the record, I have checked all the tiles in Everest that are not in Fuji nor Guadalupe, and they are all purposefully discarded for poor data quality reasons, or were dithprec, dithfocus, or dithlost tiles without redshifts.  The poor data quality ones were:

```
TILEID SURVEY FAPRGRM LASTNIGHT
int64   str7   str16    int64  
------ ------ ------- ---------
 80713    sv1     m31  20210110
   348    sv3  backup  20210428
 81096    sv2    dark  20210429
 21116   main  bright  20210608
  1767   main    dark  20210613
 20852   main  bright  20210620
  2704   main    dark  20210627
  2786   main    dark  20210627
 20802   main  bright  20210629
 20833   main  bright  20210704
 20855   main  bright  20210705
 20250   main  bright  20210706
 20307   main  bright  20210707
 21273   main  bright  20210708
  1825   main    dark  20210708
 20218   main  bright  20210709
  2976   main    dark  20210709
```
I have not checked all of the files in Rongpu's list of missing files, but these purposefully discarded tiles explain the vast majority of them.

@schlafly please double check that all of the main survey tiles have been retired and replaced or are otherwise still in the queue (albeit with a pretty old focal plane model for the fiberassign and we should consider retiring them).  We've done that cross check exercise before, but Guadalupe is a more closely vetted more authoritative set of final good/bad tiles for early main survey, so let's check again.

**Comment by schlafly** [comment]
These are all retired.

```
>>> tmain = Table.read('/global/homes/s/schlafly/desiproject/users/schlafly/surveyops3/trunk/ops/tiles-main.ecsv')
>>> np.all(tmain[np.isin(tmain['TILEID'], [1767, 2704, 2786, 1825, 2976, 21116, 20852, 20802, 20833, 20855, 20250, 20307, 21273, 20218])]['IN_DESI'] == 0)
True
```
