### ISSUE TITLE
Document how daily integration tests are submitted

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#176]
I can't find the document that describes how to set up a crontab file and the mechanics of how the daily integration test is submitted (what batch queue, which NERSC host, etc.).

**Comment by sbailey** [comment]
I have added basic test documentation at https://desi.lbl.gov/trac/wiki/Pipeline/Testing .  For the nightly integration test, the short version is that they are run on edison01 and cori01 login nodes at 3am using crontab entries like:
```
0 3 * * * /bin/bash -lc "source /project/projectdirs/desi/software/edison/desispec/master/etc/cron_dailytest.sh"
```
