### ISSUE TITLE
qso afterburners should write via a temporary file

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1764]
The qso afterburners should first write to a temporary filename, and then only upon success rename the file to the final filename.  This protects us against cases like fuji/tiles/pernight/80733/20210208/qso_qn-1-80733-20210208.fits where the job timed out after opening the file but before writing it, leaving a blank fits file behind.  We didn't catch this until recently (see desihub/desiBackup#25), because previously we were checking for the existence of files, not their validity.

the standard pipeline files follow this pattern:
```
from desispec.io.util import get_tempfilename
tmpfile = get_tempfile(filename)
table.write(tmpfile)
os.rename(tmpfile, filename)
```
so that the final correct output name will only exist if the job successfully wrote the entire file.

Note: The reason for using `get_tempfilename` instead of just `tmpfile = filename+'.tmp'` is that it creates a temporary filename with the same extension, e.g. '.fits' or '.fits.gz' so that code like `table.write(...)` can auto-derive the format to use.

**Comment by echaussidon** [comment]
HI Stephen, 

I will do it next week!

**Comment by echaussidon** [comment]
I fix the problem and make a PR. 

Edmond
