### ISSUE TITLE
ZCAT_NSPEC type inconsistency

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#1777]
`ztile-` and `zpix-` files always have the column `ZCAT_NSPEC` with type `int16`.  Somehow the `zall-` files change that to `int64`.  This is inconsistent with the data model, among other things.  Is there a specific reason for this?  It seems that for every other column, the `zall-` file preserves the type, so this is a real standout.

Although one could imagine many possible exposures of the same object, will that every *really* exceed the size of signed `int16`?  This motivates the question: why do `SV_NSPEC` or `MAIN_NSPEC` need to be `int32`, which is not consistent with `ZCAT_NSPEC` in the `ztile-` and `zpix-` files, *nor* consistent with `ZCAT_NSPEC` in the `zall-` files.

**Comment by stephjuneau** [comment]
Hi @weaverba137 , I think we can set all the *_NSPEC columns to type `int16`. I added @Ragadeepika-Pucha as an assignee as she wrote the code for generating the zall- files.

**Comment by weaverba137** [comment]
That's fine, thank you!

**Comment by weaverba137** [comment]
@sbailey has this been fixed in the DR1 patching?

**Comment by sbailey** [comment]
> @sbailey has this been fixed in the DR1 patching?

Not yet, but we should.  I added it to the DR1 Patching project. @Ragadeepika-Pucha are you available to fix this? It may just need adding a `dtype=np.int16` somewhere in `desispec.zcatalog.create_summary_catalog`.

**Comment by stephjuneau** [comment]
@sbailey I sent you a message to close the loop on this.

**Comment by sbailey** [comment]
It sounds like Raga is likely not available in the short term to work on this; if anyone else could help I would appreciate it.

**Comment by LNapolitano** [comment]
Pull request: https://github.com/desihub/desispec/pull/2103

**Comment by sbailey** [comment]
fixed by #2103, thanks!
