### ISSUE TITLE
desi_night_qa --html_only recreates plots, not just html

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1783]
`desi_night_qa --html_only ...` still calls `create_dark_pdf`, `create_badcol_png`, and loops over all of the exposures for sframes, apparently doing much more than just "only regenerate the nightqa-{NIGHT}.html page" like the docstring says.  For some debugging it would be helpful to restore that `--html_only` fast functionality.

It would also be helpful to have an option that would only recompute missing outputs, while not recomputing output plots that already exist.

These aren't high priority, but would be nice to have.

**Comment by araichoor** [comment]
This is addressed in the merged PR https://github.com/desihub/desispec/pull/1795: shall I close the issue?
