### ISSUE TITLE
night_qa relative output path bug

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1784]
If desi_night_qa is given a relative output path, it produces incorrect links to the images in the wrapper html.  e.g.
```
cd $DESI_SPECTRO_REDUX/$SPECPROD
desi_night_qa -n 20220527 -o nightqa/20220527/ --html_only
```
produces in nightqa/20220527/nightqa-20220527.html links like:
```
<iframe src='nightqa/20220527/dark-20220527.pdf' width=100% height=100%></iframe>
```
it should just be src='dark-20220527.pdf' since that file is in the same output directory as nightqa-20220527.html .

An absolute output path works by generating an absolute link, but that pins the directory in place and means we can't move it and have the links still work.  e.g.
```
desi_night_qa -n 20220527 -o $DESI_SPECTRO_REDUX/$SPECPROD/nightqa/20220527/ --html_only
```
produces links like
```
<iframe src='https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20220527/dark-20220527.pdf' width=100% height=100%></iframe>
```

Given that nightqa-20220527.html and all of its necessary plots are all in the same output directory, I think better practice would be for the link to be relative without any path, i.e.
```
<iframe src='dark-20220527.pdf' width=100% height=100%></iframe>
```
then if for whatever reason we move the entire directory (e.g. for a data release...) the html wrapper will continue to point to the correct images in their new location.

**Comment by araichoor** [comment]
This is addressed in the merged PR https://github.com/desihub/desispec/pull/1795: shall I close the issue?
