### ISSUE TITLE
exposure dashboard color code night summary rows

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1786]
desi_proc_dashboard output color codes the rows of individual exposures to make it easy to see when something is missing, but the collapsed nightly rows do not have any color coding, making it easy to miss when one night is missing some files, e.g.
![image](https://user-images.githubusercontent.com/218471/171734970-b06426c3-2376-45c0-8578-7f805d6987d7.png)
It would be helpful if 20210928 was flagged more prominently as missing files.

This is optional for Himalayas, but it sure would be nice...

**Comment by akremin** [comment]
This was completed with PR #1845 1845
