### ISSUE TITLE
arc failure dependencies afterany vs. afterok

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1791]
Daily processing jobs submitted via `desi_daily_proc_manager` are robust to individual arc PSF fit failures by having the psfnight job dependencies as "afterany", e.g. from /global/homes/d/desi/daily/logfiles/daily-20220421.log:
```
INFO:procfuncs.py:476:submit_batch_script: Submitted /global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/night/20220421/psfnight-20220421-00131174-a0123456789.slurm
with dependencies --dependency=afterany:58092832:58092836:58092840:58092843:58092845 and reservation=None. Returned qid: 58092856
```

However, production runs submitted via `desi_run_night` have a stricter "afterok" dependency requirement, e.g. from himalayas/run/logs/20220421.log:
```
INFO:procfuncs.py:474:submit_batch_script: Submitted /global/cfs/cdirs/desi/spectro/redux/himalayas/run/scripts/night/20220421/psfnight-20220421-00131174-a0123456789.slurm
with dependencies --dependency=afterok:59500347:59500351:59500354:59500358:59500361 and reservation=None. Returned qid: 59500364
```

I think the reasoning was that we didn't want individual arc failures to immediately completely block the daily processing, to relieve the evening load on the spectro pipeline operations person (thus daily using "afterany").   At the same time, we did want the exposure tables to eventually reflect what should succeed, so we left the production requirement as "afterok".

In practice, because the nightly processing is robust to individual failures, we haven't been strict about flagging individual PSF failures as bad in the exposure tables, but then that causes the production to fail on that night.

Impacted nights/exposures in Himalayas:
```
20211005 / 103082
20211011 / 103739 - 43
20211013 / 104057
20211022 / 105575
20211026 / 106160 - 63
20211106 / 107597, 107599
20211113 / 108588
20211201 / 111643
20211205 / 112469
20211210 / 113177
20211222 / 115111
20220104 / 116737
20220107 / 117169
20220111 / 118000
20220207 / 121662
20220216 / 122481
20220403 / 128513
20220410 / 129928
20220421 / 131177
20220524 / 136530
```
(that was taken from the dashboard webpage by hand, so I don't immediately know which cameras were failing or if there are patterns).

This is < 0.1% of the individual arc frames having an unexpected failure, but it ends up impacting ~10% of the nights.

Note that on 20211026, 4 out of 5 exposures had a PSF failure; and on 20211011, 5 out of 5 had a failure so something different may be happening on the data for those nights.

Options:
  1. update procedures to regularly flag PSF failures as bad in the exposure tables, either as part of morning pipeline vetting or as an expected part of running productions.
  2. update `desi_run_night` to also use `afterok` to allow productions to proceed like daily, and then post-facto update processing table when productions notice missing files.
      * although this might initially be easiest, the failures leave per-bundle temporary files behind for debugging and general log message cruft and extra distractions tracking down whether "47/48 complete" is a harmless PSF failure or a missing science file.
  3. update desi_fit_psf to be more robust

**Comment by sbailey** [comment]
A common (but not only) source of these failures was r8 during October 2021, when it was not in a good state, often leading to amp A being masked:
![image](https://user-images.githubusercontent.com/218471/171966850-d121cc37-5489-4077-967d-6bb85c808685.png)

**Comment by akremin** [comment]
My two cents is to keep `desi_run_night` the way it is and to account for these problematic data in the data records (`exposure_tables`). It is true that the failures are sometimes code-dependent, for instance I see many new failures in `himalayas` that didn't fail in daily. However, I think these situations typically point to questionably passable data anyway. 

In general I think it is good to continue with the practice of having the input `exposure_tables` representing the expected outputs. This helps with quality assurance and monitoring as well as documenting the current understanding of our full dataset. The goal of "practice prods" like `himalayas` are in part to identify these kinds of issues in the data and/or code. 

My thoughts on this may change if it continues to be a recurring issue.

**Comment by akremin** [comment]
In an SVN checkout of the exposure tables I went ahead and flagged the bad r8A amplifiers for only the exposures that failed in himalayas. I will push it later today after the rest of the changes are in place.

The following is a list:

```
night, expid, BADAMP
20211011, 103739, r8A
20211011, 103740, r8A
20211011, 103741, r8A
20211011, 103742, r8A
20211011, 103743, r8A
 
20211013, 104057, r8A
 
20211022, 105575, r8A
 
20211026, 106160, r8A
20211026, 106161, r8A
20211026, 106162, r8A
20211026, 106163, r8A
 
20211028, 106399, r8A
20211028, 106400, r8A
``` 

I also removed:  `20211026, 106164, r8A`   since the other 4 arcs failed on 20211026 and I didn't like the idea of a problematic amplifier being processed with only one exposure (so no medians/averaging).

The result of this is that 20211011 and 20211026 will have to use default psf's for camera r8.

**Comment by akremin** [comment]
I also flagged the following two exposures as having badamps (these were also failures in himalayas):

```
night, expid, BADAMPS
20211106, 107597, z6D
20211106, 107599, z6D
```

**Comment by akremin** [comment]
The following I couldn't identify an obvious cause for the crashes. I've flagged the entire cameras so that the production can proceed without these failures, but they may warrant further investigation:

```
night, expid, BADCAMWORD
20211113, 108588, z0

20211201, 111643, r4
 
20211205, 112469, r4
 
20211210, 113177, r4
 
20211222, 115111, r0
  
20220104, 116737, r2
```

**Comment by sbailey** [comment]
Not all crashes are understood, but it's also unlikely that we'll investigate them since they aren't blocking nights, so I'm closing this issue.
