### ISSUE TITLE
standardize GPU options

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1799]
We're accreting a variety of methods to trigger GPU usage, e.g. `desi_fit_stdstars --use-gpu`, `desi_proc --gpuextract` (while apparently missing an option to enable stdstar GPU usage from desi_proc), and `desispec.fluxcalibration.use_gpu` auto-deciding.  I suggest that we standardize GPU options and usage as:

* if a GPU is available, it is used by default without having to specify options
* if a GPU is not available, the code uses CPU by default without having to specify options
* a `--no-gpu` option would opt-out of using the GPU even if available (mainly for testing).  On a CPU node, `--no-gpu` is not required, and if specified it is just a no-op.
* For high-level pipeline wrappers (e.g. desi_run_night), the `--system-name` (e.g. "perlmutter-gpu, perlmutter-cpu") triggers whether the jobs are resourced and submitted to GPU or non-GPU nodes without requiring additional GPU-specific options from the user.
* For high-level pipeline wrappers, I don't think we need to add per-step options (e.g. extract with GPUs but don't use them for stdstars).  We can add that level of granularity later if we find we really need it.
* Low-level algorithmic steps (extraction, stdstars, fluxcalibration) should provide `--no-gpu` hooks too to be able to turn them off when running that single step (and that is what the high-level wrappers would pass forward from their `--no-gpu` option).

i.e. I'm suggesting that the default should be to automatically use a GPU if available but also work on CPU nodes without requiring options either way, while still providing a way to turn off GPU use if needed for debugging.

Let's take the auto-decide logic from `desispec.fluxcalibration.use_gpu` and wrap that in a utility function for all steps to use.

Note: specter and redrock may be a special case since they are intended to be DESI-agnostic toolkits that shouldn't depend upon DESI code, so the automatic GPU usage selection might get replicated there, or they may have a different explicit opt-in/opt-out.  TBD.

**Comment by marcelo-alvarez** [comment]
Most if not all of these should be resolved by #1901.
