### ISSUE TITLE
review code/datamodel consistency

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#18]
Check all fits files in NERSC:/project/projectdirs/desi/spectro/redux/sjb/dogwood/

  * Is there a corresponding desiDataModel entry? (that's in svn, not github)
  * Is the file consistent with the data model?  Focus on HDUs first, then keywords.
  * If not, either update the data model to match the file, or update the code to write a file matching the data model.  Both might change.  Make sure that desispec.io.read/write* and test/test_io.py remain in sync with any changes.

desiDataModel/bin/generate_model is a useful script for creating a new data model for files that don't have one yet.

**Comment by dkirkby** [comment]
Here are two datamodel inconsistencies copied from `doc/coadd.rst`:
* The brick filenames have the format brick-{band}-{expid}.fits, where band is one of [rbz], which differs from the current data model (which is missing the {band}).
* Bricks contain a single wavelength grid in HDU2, the same as current CFRAMES, but different from the CFRAME data model (where HDU2 is a per-object mask).

**Comment by sbailey** [comment]
Thanks.  When you find inconsistencies in the data model with code you wrote, please go ahead and directly fix the data model (this applies to everyone).

**Comment by sbailey** [comment]
I updated the entries for the inconsistencies @dkirkby mentioned.  Added missing fiberflat.  Data model for stdstars and calib are still missing.  Multiple data models are still light on the details.

**Comment by weaverba137** [comment]
The automation needed to do this is being tracked in desihub/desidatamodel#7.

**Comment by weaverba137** [comment]
PS, I will be defining 'consistency' for the purposes of closing this and related issues in terms of dc3 data.

**Comment by weaverba137** [comment]
So we have in fact reviewed and reported on the consistency of dc3c data with the data model.  Now we still need to actually fill in the content to make these consistent.

**Comment by weaverba137** [comment]
The other issues in the Pipeline 2016a Milestone should be closed within a day or so, meaning this will be the *last* open issue in Pipeline 2016a.
