### ISSUE TITLE
fatal PSF errors on 20210523

### ISSUE THREAD

**Issue by marcelo-alvarez** [desihub/desispec#1811]
During processing of arcs 89828 and 89829 for 20210523, PSF fitting for camera r0  has a fatal error, i.e.:
```
% rundir=/global/cfs/cdirs/desi/spectro/redux/guadalupe/run/scripts/night/20210523
% grep FATAL $rundir/arc*log
/global/cfs/cdirs/desi/spectro/redux/guadalupe/run/scripts/night/20210523/arc-20210523-00089828-a0123456789-54473367.log: 
  FATAL ERROR (other std) ERROR r0-00089828-05: problem with brent dchi2 = -4.75318e+23 (at line 1583 of file /global/u1/d/desi/build/specex-0.8.4/src/specex_psf_fitter.cc)
/global/cfs/cdirs/desi/spectro/redux/guadalupe/run/scripts/night/20210523/arc-20210523-00089829-a0123456789-54473368.log: 
  FATAL ERROR (other std) ERROR r0-00089829-05: problem with brent dchi2 = -6.06265e+22 (at line 1583 of file /global/u1/d/desi/build/specex-0.8.4/src/specex_psf_fitter.cc)  
```
In the guadalupe production (with desispec/0.51.13), these arc jobs returned SUCCESS and the rest of the exposures were processed. Due to the changes I made in https://github.com/desihub/desispec/pull/1751, however, these two arc jobs now fail for that night. 

@julienguy @sbailey please comment on what should be done for this night and, if it's not an isolated issue, how we should handle this type of error going forward.

**Comment by sbailey** [comment]
@marcelo-alvarez we should flag this exposure as BADCAMWORD=r0 in the exposure_tables svn and then move on for processing without it.

Mentioning @akremin to keep him in the loop

**Comment by marcelo-alvarez** [comment]
> @marcelo-alvarez we should flag this exposure as BADCAMWORD=r0 in the exposure_tables svn and then move on for processing without it.
> 
> Mentioning @akremin to keep him in the loop

@sbailey thanks. This also is apparently happening for z3 on exposure 93532 on 20210613:
```
% rundir=/global/cfs/cdirs/desi/spectro/redux/guadalupe/run/scripts/night/20210613
% grep FATAL $rundir/arc*log
/global/cfs/cdirs/desi/spectro/redux/guadalupe/run/scripts/night/20210613/arc-20210613-00093532-a012345678-53982733.log:
  FATAL ERROR (other std) ERROR z3-00093532-11: problem with brent dchi2 = -1.63227e+22 (at line 1583 of file /global/u1/d/desi/build/specex-0.8.4/src/specex_psf_fitter.cc) 
```

I will flag BADCAMWORD=r0 for 89828 and 89829, BADCAMWORD=z3 for 93532, and then rerun those two nights.

**Comment by akremin** [comment]
`BADCAMWORD=z3` for 93532 was already flagged in svn (presumably after `guadalupe` was released), but `BADCAMWORD=r0` for 89828 and 89829 were not flagged and should have been. They failed in `himalayas` as well, so I have flagged them in the svn tables.
