### ISSUE TITLE
Improve fluxcalibration.compute_flux_calibration

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#182]
fluxcalibration.compute_flux_calibration gives a biased result, probably because of the initial clipping with the median calib. One also needs to evaluate the bias introduced by the prior.

example (DC3e exposure 6, for standard stars) 
![calib-std-00000006](https://cloud.githubusercontent.com/assets/5192160/15177171/0f9d6ff2-176f-11e6-9d67-3f481797ac50.png)

**Comment by julienguy** [comment]
The previous plot was the ratio of the calibrated measured flux to the simulation truth, which includes the ratio between the true spectrum and the chosen standard star model.
 
The biases introduced in the routine fluxcalibration.compute_flux_calibration are given by the ratio of the calibrated measured flux to the chosen standard star model shown in the following figure. They are smaller on the blue end (3500A) but similar on the other edges of cameras.

![ratio](https://cloud.githubusercontent.com/assets/5192160/15179879/90b54c36-177e-11e6-9e66-4f156f2eb5bc.png)

**Comment by julienguy** [comment]
I'm working on it

**Comment by julienguy** [comment]
Solved with PR compute_flux_calib.
Following figure is the ratio of calibrated measured flux to the chosen standard star model.
(There is however still some work needed to improve the choice of stellar models).
![ratio-std-3](https://cloud.githubusercontent.com/assets/5192160/15187109/1bc657a4-17a0-11e6-9242-89fd30d6db83.png)

**Comment by sbailey** [comment]
fixed via PR #183.  It is always a pleasure to watch Julien attack a problem and fix it quickly.
