### ISSUE TITLE
Report on CTE software correction

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1826]
Report on CTE software correction
List of CTE issues copied from https://docs.google.com/spreadsheets/d/1UGJ901XFZxi0XmgV6BV2X7gvhbw5W5XdS9rvObWIfvw/edit#gid=0

<google-sheets-html-origin><style type="text/css"></style>

SPECTRO | CAMERA | AMPLIFIER | OFFCOLS (as in yaml file) | BEGIN (first detection) | END (when fixed with readout) | SOFT Corr. | Test night/expid | Readout change | COMMENT
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
SM1 | R4 | D | 2057-4114 | 2020/03/15 | 2020/11/09 | YES | None | from default_lbnl_20190717.cfg to LBNL-PE-21-20201109.cfg | https://desi.lbl.gov/trac/ticket/593
SM1 | R4 | A | 782-2057 | 2021/07/04 | 2021/10/15 | YES | 20211014/00104277 | from LBNL-PE-21-20210128.cfg to LBNL-PE-21-20211015.cfg |  
SM1 | R4 | B | 2057-2220 | 2021/11/26 | None | NO | None | no change |  
SM6 | Z3 | B | 2057-3250 | 2021/11/26 | 2021/12/02 | YES | 20211201/00111748 | from default_lbnl_20210128.cfg to M1-60_lbnl_20211202.cfg | https://github.com/desihub/desisurveyops/issues/6
SM6 | Z3 | C | 1668-2057 | 2022/04/23 | 2022/05/31 | YES | 20220530/00137383 | from M1-60_lbnl_20211202.cfg to M1-60_lbnl_20220531.cfg | https://desi.lbl.gov/trac/wiki/InstOpsPages/VersionHistory
SM10 | R1 | D | 2057-3715 | 2021/07/04 | 2021/10/15 | YES | 20211014/00104277 | from default_lbnl_20210128.cfg to M1-26_lbnl_20211015.cfg | https://github.com/desihub/desispec/issues/1534 and https://desi.lbl.gov/trac/ticket/887
SM10 | R1 | D | 2057-3715 | 2021/12/15 | 2022/01/04 | YES | 20220103/00116573 | from M1-26_lbnl_20211015.cfg to M1-26_lbnl_20220104.cfg | https://desi.lbl.gov/trac/wiki/InstOpsPages/VersionHistory
SM10 | Z1 | C | 545-2057 | 2021/11/30 | 2022/01/07 | YES | 20220105/00116876 | from default_lbnl_20210128.cfg to M1-35_lbnl_20220107.cfg (M1-35_lbnl_20220104.cfg used between 20220104 and 20220107) | https://desi.lbl.gov/trac/wiki/InstOpsPages/VersionHistory
SM10 | Z1 | C | 545-2057 | 2022/02/17 | 2022/06/02 | YES | 20220601/00137699 | from M1-35_lbnl_20220107.cfg to M1-35_lbnl_20220602.cfg | https://desi.lbl.gov/trac/wiki/InstOpsPages/VersionHistory

In the following are validation plots with 1 dark time exposure for each period (see the 'test night/expid' column above).
When two plots are present: left is from the 'daily' prod , right is from the test prod with the recent changes (committed) to the calibration repository and the code changes from PR #1825 . When only one plot is present, it is from the test prod.

![sframe-r4-00104277](https://user-images.githubusercontent.com/5192160/185244947-48e7a9fc-f6dc-4327-b804-d706cb73eafb.png)
![sframe-z3-00111748](https://user-images.githubusercontent.com/5192160/185244749-9cb8ca66-7760-44ae-87ad-0a19e78f3215.png)
![sframe-z3-00137383](https://user-images.githubusercontent.com/5192160/185244753-6a36dd49-fceb-49e0-8802-796a4de6b115.png)
![sframe-r1-00104277](https://user-images.githubusercontent.com/5192160/185245420-a98c9441-31ff-4a8a-85b4-0a9a418e94fa.png)
![sframe-r1-00116573](https://user-images.githubusercontent.com/5192160/185245453-9444185f-2171-44eb-864f-9fe7ea7aedb3.png)
![sframe-z1-00116876](https://user-images.githubusercontent.com/5192160/185245514-080a976f-224e-4c50-8484-837500e2f5ee.png)
![sframe-z1-00137699](https://user-images.githubusercontent.com/5192160/185245526-9966b474-a6fc-4bfe-8528-70c79ef058b1.png)

One can see an improvement for images where the CTE issue is visible. The extra horizontal bands are probably due to imperfect bright columns correction in the test prod which is an independent effect and should probably be ignored here.

**Comment by julienguy** [comment]
Each plot above is the sky residuals in the sky fibers with a rebinning along wavelength to reduce the noise in order to detect small offsets.  The script used for the plot is `/global/cfs/cdirs/desi/users/jguy/cte-for-DR1/plot-sframe.py`.

**Comment by julienguy** [comment]
The modifications to the calibration repository consist in adding configurations with keywords of the form OFFCOLSX: 'BEGIN:END' where X is the amplifier ID (A,B,C or D) and BEGIN:END mark the CCD columns affected by the CTE issue. When this keyword is present in the calibration configuration, the sky subtraction code fits for a common offset for all the fibers/wavelength in the affected CCD region. This offset is added to sky model (while accounting for flat fielding). It is then subtracted as part of the sky subtraction process. One can find more explanation in the original PR #1571 .

**Comment by sbailey** [comment]
Thanks for this report for the record.  IIUC this is informational only and no further action needs to be taken on this ticket, so I'm associating it with DR1/Iron and closing it.
