### ISSUE TITLE
Improve wavelength calibration adjustment on sky lines

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1827]
The wavelength calibration adjustment on sky lines may be improved with a median filtering of the spectra prior to the cross-correlation of the measured spectra and the model sky spectrum. This improvement is striking for one exposure/camera which wavelength calibration failed as reported in https://github.com/desihub/desisurveyops/issues/45 . The trace shift is measured for each fiber independently in several intervals along the spectrum. And then averaged with outlier rejection. There are much fewer outliers if the spectra have been median-filtered for the test exposure/camera which suggests this could be an improvement for the wavelength calibration in general.

This is implement in desispec branch traceshift-median-filter .
This takes a bit more CPU time but more importantly it should be tested on a large data sample (with for instance radial velocities comparison).

**Comment by segasai** [comment]
Hi Julien, do you have preference for the dates of the data taken ? I.e. fuji/guadalupe/daily ? 
The best exposures for my previous tests were usually fuji (pre-main survey) tiles with a large number of stars and many repeats.

**Comment by julienguy** [comment]
Fuji data is fine. Please suggest a list of exposures that would be a good sample to validate this change. Ideally a fair number of stars with accurate external radial velocities.

**Comment by segasai** [comment]
The best tile to compare with Gaia RV's is 80613, it has 1327 stars in common (counting individual exposures)
These are the EXPIDs 81831 81832 81833 81834 81835 68657 69042 68658 68659 69043 69044 69431 69045 69429 69430 69432 69433 69605 69606 69607 69608 69225 69226 69227 69228 69229 69230 69609 69610 69611

The stars with Gaia RVs will be very very bright 13-15 mag and RVs will be accurate to better than 1 km/s.
for APOGEE the best tile is  80738 with  ~ 1300 matches counting repeats.
These are the EXPID 83010 83011 83748 77579 77803 79308 79309 76663 79310 79311 80971 76661 77434 76662 83448 76314 77435 83166
These will be tad fainter.

**Comment by julienguy** [comment]
Starting running in /global/cfs/cdirs/desi/spectro/redux/traceshift-median-filter/ .

**Comment by segasai** [comment]
Thanks. I've looked there, but I can't see any spectra- files there only sframes. With spectra-*fits , I could easily run my RV code for the subset of stars we care about.

**Comment by julienguy** [comment]
@segasai , the spectra from tile 80613 are in /global/cfs/cdirs/desi/spectro/redux/traceshift-median-filter/ .

**Comment by segasai** [comment]
@julienguy  I'm not sure I can see any significant difference in terms of offsets wrt Gaia. Here are old measurements (based on fuji): (median/MAD)

B -2.43 3.14
R 0.63 3.12
Z 1.14 2.78
Here are the new ones:
B -1.98 5.28
R 0.70 2.84
Z 1.16 2.82

**Comment by julienguy** [comment]
Thanks. I am going to run the other tile. If your results are confirmed, we would probably not apply this PR because it does not improve much and could on the contrary cause other issues.

**Comment by segasai** [comment]
In the blue things got significantly worse actually 
![image](https://user-images.githubusercontent.com/109513/186149509-cbe540a8-2a08-498d-a7d1-5b9d35ad7bc9.png)
in other arms it's mostly the same. 

BTW Is the current wavelength correction procedure still using the SDSS sky spectrum ? 
I remember it has all sorts of stuff in it while it really just should have a handful of emission lines sitting on top of zero background.

**Comment by segasai** [comment]
How easy it is to run with the different spec-sky.dat ? 
I.e. I have one where I basically zero-out everything but the emission lines something like this (black vs red)
![image](https://user-images.githubusercontent.com/109513/186704691-dfc59435-8551-4752-9abe-09693ff36779.png)

**Comment by julienguy** [comment]
I am happy to rerun the tile mentioned in this thread with a new sky spectrum for the wavelength adjustment. Let's continue this offline.

**Comment by segasai** [comment]
Moving on from yesterday, my proposal is to
* add a high-pass filter here https://github.com/desihub/desispec/blob/main/py/desispec/trace_shifts.py
* replace the new template https://github.com/desihub/desispec/blob/main/py/desispec/data/spec-sky.dat by the one from DESI + high pass filter applied and noise truncated.
* Select a few tiles/exposures in dark/bright/backup with the most external radial velocities to do testing (see below)
It would be great if  anyone can suggest a better way to do reprocessing other than 
desi_proc -e 83005 --night 20210401 to save computing time, as otherwise it was a bit too slow. 

* I also haven't yet studied the  logic in the trace_shifts, to see if the code can behave gracefully in the blue where there is not much signal in the blue (i.e. we're are in the bright time) and then just adopt zero dy shift.


10 backup tiles with the most detections in the SoS catalog (counting repeated exposures)
42493 4442
40576 4340
40237 4146
40061 3669
43033 3305
42250 3294
42734 3233
40481 3199
40505 3048
43025 2760


10 bright tiles with the most detections in the SoS catalog (counting repeated exposures)
80658 1531
80618 1513
80643 1103
80663 1072
80662 1069
80656 942
80651 870
80659 859
80613 840
80644 839

10 dark tiles with the most detections in the SoS catalog (counting repeated exposures)
80895 644
80705 485
80706 471
80873 470
80684 468
80669 462
80692 435
80882 422
80609 316
80681 294

**Comment by sbailey** [comment]
@segasai I think the "simplest" way to run multiple tiles over multiple nights without rerunning arcs/flats is
```
# set $DESI_SPECTRO_REDUX/$SPECPROD to be an output directory that you want, then

# link to the iron calibnight and exposure_tables
cd $DESI_SPECTRO_REDUX/$SPECPROD
ln -s $CFS/desi/spectro/redux/iron/calibnight
ln -s $CFS/desi/spectro/redux/iron/exposure_tables

# use exposures-iron.csv to derive which tiles were observed on which nights,
# then run those nights filtering by only the tiles you want, e.g.
desi_run_night -n 20211125 --tiles 42250 --z-submit-types cumulative
desi_run_night -n 20211206 --tiles 42250 --z-submit-types cumulative
desi_run_night -n 20211218 --tiles 42250 --z-submit-types cumulative
desi_run_night -n 20220206 --tiles 40237 --z-submit-types cumulative
desi_run_night -n 20220210 --tiles 43033,43025 --z-submit-types cumulative
desi_run_night -n 20220227 --tiles 43033,43025,40237 --z-submit-types cumulative
desi_run_night -n 20220302 --tiles 43025,43033 --z-submit-types cumulative
desi_run_night -n 20220303 --tiles 42734 --z-submit-types cumulative
desi_run_night -n 20220310 --tiles 40237 --z-submit-types cumulative
desi_run_night -n 20220315 --tiles 40237,40061 --z-submit-types cumulative
desi_run_night -n 20220318 --tiles 40505 --z-submit-types cumulative
desi_run_night -n 20220319 --tiles 42493 --z-submit-types cumulative
desi_run_night -n 20220325 --tiles 40061 --z-submit-types cumulative
desi_run_night -n 20220412 --tiles 40061 --z-submit-types cumulative
desi_run_night -n 20220418 --tiles 42493,40481 --z-submit-types cumulative
desi_run_night -n 20220422 --tiles 40061 --z-submit-types cumulative
desi_run_night -n 20220426 --tiles 42734 --z-submit-types cumulative
desi_run_night -n 20220511 --tiles 42493,40505,40481 --z-submit-types cumulative
desi_run_night -n 20220513 --tiles 42493 --z-submit-types cumulative
desi_run_night -n 20220515 --tiles 40505 --z-submit-types cumulative
desi_run_night -n 20220518 --tiles 40576,40576,40576,40576 --z-submit-types cumulative
desi_run_night -n 20220522 --tiles 40576 --z-submit-types cumulative
desi_run_night -n 20220612 --tiles 40481 --z-submit-types cumulative
```

That should submit a bunch of 'tilenight' jobs to do the processing through cframes, and 'ztile' jobs to do the coadding and redshifts.  It should be smart enough to only submit the ztile job for the last night that a tile was observed.  You can also use `--z-submit-types pernight` if you want the pernight coadds and redshifts.  However, it isn't smart enough to know that the ztile jobs need to wait for previous nights to finish, so depending upon the luck of the queue they may run prematurely and crash.  You can recover those with
```
desi_resubmit_queue_failures -n NIGHT
```
(that also works for resubmitting any other job failures that aren't our fault, e.g. I/O timeouts).

Other useful tools for tracking the state of a prod are `desi_proc_dashboard` and `desi_job_graph`, both of which create webpages to track if stuff is done.

Caveat: I tried a dry run version of those and it looked ok, but I haven't tried running the actual jobs so I might be missing something in those instructions.  If that doesn't work, please ping me on Slack and we'll sort it out.

**Comment by sbailey** [comment]
Great!  For the record: If you are starting with cframes and don't need spectra/coadds/redrock files, then indeed `--no-redshifts` is good.  If you use spectra instead of cframe files (same info, different formatting, combining multiple exposures into a single file), then you have to run redshift too, since `--no-redshifts` also means "don't group into spectra files or coadd either".
