### ISSUE TITLE
Add existence of biasnight files to nightly QA

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1839]
Currently the nightqa webpages "calibnight" section includes checks that the psfnight and fiberflatnight files exist.  Please add to that a check that the "biasnight-CAMERA-NIGHT.fits.gz" files exist.

Context: these should exist if we took the standard calib ZEROs, but that is occasionally skipped when there is an instrument problem at the beginning of the night and we are rushed to get on sky.  That's ok, but we want to be aware that it happened and not accidentally go a week without calib ZEROs without noticing.

@araichoor could you add this?  Thanks.

**Comment by araichoor** [comment]
yes, sure, will do.

**Comment by sbailey** [comment]
Implemented in PR #1841.  Closing.
