### ISSUE TITLE
Integration tests use DESIMODEL but don't insist that it be set.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#184]
Integration tests use the value of `DESIMODEL`, but the `check_env()` function does not require that it be set.

Line 120 of integration_test.py:

```python
 psffile = '{}/data/specpsf/psf-{}.fits'.format(os.getenv('DESIMODEL'), channel)
```

There are probably other environment variables in this situation.  For example the use of `STD_TEMPLATES` really is optional, but its default value is based on `DESI_ROOT` and that is also not checked by `check_env()`.

**Comment by tskisner** [comment]
I had already added this to the list of required variables in the new
integration test I am working on in a branch.  I can close this once that
new version becomes "the" integration test.

**Comment by weaverba137** [comment]
I thought this was supposed to be fixed in the refactor branch, but it looks like this is still a problem.

**Comment by tskisner** [comment]
It is fixed in the new integration test, which is in the next and final 
merge.  This final merge will rip out all the old pipeline code, 
replace the integration test, and hopefully solve our scaling issues.

**Comment by weaverba137** [comment]
Which branch?

**Comment by tskisner** [comment]
It is not pushed yet.  Once I get things working locally I'll rebase to 
wherever master is at before pushing.  Trying to avoid rebasing 
publicly pushed branches...

Look, if this is a holdup, it is a one-line change to the old 
integration test which will be thrown away shortly.  We can just make 
the change in master if you want to close the ticket.

compare line 39 of:

https://github.com/desihub/desispec/blob/master/py/desispec/test/integration_test.py

to line 43 of:

https://github.com/desihub/desispec/blob/master/py/desispec/test/newintegration_test.py

**Comment by weaverba137** [comment]
It's not a hold up, I just assumed that the previously-merged refactor branch was the branch you were talking about.

**Comment by weaverba137** [comment]
This has been fixed for a while, so closing.
