### ISSUE TITLE
nightly bias auto-fallback to using non-calib ZEROs

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1840]
Currently `desi_compute_nightly_bias` will only use CALIB ZEROs, and not other ZEROs taken during the night e.g. as part of a dark sequence or system tests.  This can be overridden by hand by including `--anyzeros`.

This is a problem for the automated pipeline on nights like 20210629 which didn't have CALIB ZEROs, but did have enough other ZEROs taken as part of the dark sequences that night.  Currently the pipeline fails at the ccdcalib step and requires manual intervention to proceed.

Suggestion after talking with @akremin : default to using CALIB ZEROs only, but if there aren't enough of those then automatically extend to also use non-CALIB ZEROs.  This is different than the previous state that would automatically mix CALIB and non-CALIB ZEROs; the suggestion here is to only do that if necessary, but do it without requiring human intervention.

**Comment by akremin** [comment]
Resolved with #1857
