### ISSUE TITLE
add support for read-only CFS mount

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1842]
On Cori and Perlmutter compute nodes, `/dvs_ro/cfs/cdirs` is a read-only mount of `/global/cfs/cdirs` with potentially significantly better read-performance.  Due to its aggressive caching, this should only be used for files that are "done", not for files that might be re-opened and updated within the same job (which we in general don't do — once the file exists at its final name, we are done with it).  Downside: on Cori this mount is only available from compute nodes, not login nodes.  On Perlmutter it might be available from both but it's down for maintenance so I can't check right now.

Suggested implementation:
* Define a new optional environment variable `$DESI_ROOT_READONLY` in the desitree module.
* Add an option to `desispec.io.findfile(..., readonly=False)`
  * Upon first invocation with `readonly=True` and if `$DESI_ROOT_READONLY` is set, test for the existence of that mount point and cache the answer for subsequent calls.
  * if `$DESI_ROOT_READONLY` is not set or the mount point doesn't exist (e.g. Cori login node), proceed with default read-write behavior.
* If the read-only mount exists, and the default read-write file location starts with `$DESI_ROOT`, then substitute the prefix `$DESI_ROOT` with `$DESI_ROOT_READONLY`.
  * i.e. generate the read-only path upon request, but only if that mount actually exists
* Application code can then be adapted to add `findfile(..., readonly=True)` for cases where it is requesting the path to an input file, e.g. raw data or a frame for reading.
* Any unconverted application code would continue to get the `/global/cfs/cdirs/desi...` read-write path, which will continue to work as-is.

@weaverba137 @akremin @dmargala @lastephey @marcelo-alvarez comments?

**Comment by weaverba137** [comment]
I can't think of obvious problems with this, but I would suggest that as part of this we make sure that the unit test coverage of `desispec.io.findfile()` is 100%.

**Comment by sbailey** [comment]
implemented in PR #1856.  Closing.
