### ISSUE TITLE
desi_zfind now broken on BOSS bricks

### ISSUE THREAD

**Issue by ngbusca** [desihub/desispec#185]
The new head version of desi_zfind doesn't run anymore on boss bricks (it used to). The logic of the input arguments also seems broken: -b is a required flag, so it doesn't accept the multiple channels. The three 'r','b','z' channels are again hardcoded (unlike in the previous version).

**Comment by tskisner** [comment]
This was likely my fault when converting zfind from optparse to argparse.  I will investigate.

**Comment by tskisner** [comment]
Does the latest commit f21627154bb64aeb69986fe157596bfbf9078b56 fix things?

**Comment by ngbusca** [comment]
Nope :^(

[in: ] desi_zfind brick-b-4199p000.fits brick-r-4199p000.fits -o toto.fits
INFO:zfind.py:64:main: Reading bricks
Traceback (most recent call last):
  File "/Users/ngbusca/Boulot/DESI/github/desispec/bin/desi_zfind", line 8, in <module>
    zfind.main(args)
  File "/Users/ngbusca/Boulot/DESI/github/desispec/py/desispec/scripts/zfind.py", line 74, in main
    raise RuntimeError('Exactly 3 brickfiles should be given, or use --brick')


and

[in: ] desi_zfind --brick brick-b-4199p000.fits brick-r-4199p000.fits -o toto.fits
INFO:zfind.py:64:main: Reading bricks
Traceback (most recent call last):
  File "/Users/ngbusca/Boulot/DESI/github/desispec/bin/desi_zfind", line 8, in <module>
    zfind.main(args)
  File "/Users/ngbusca/Boulot/DESI/github/desispec/py/desispec/scripts/zfind.py", line 68, in main
    raise RuntimeError('Give -b/--brick or input brickfiles but not both')            
RuntimeError: Give -b/--brick or input brickfiles but not both

**Comment by tskisner** [comment]
Ah, ok, so in the case of specifying the files manually, you want to allow arbitrary numbers of bands.  I removed that check in the latest commit to master just now.

**Comment by moustakas** [comment]
I ran into the exact same issue just this morning.  Changing ```required=True``` to ```required=False``` on the ```--brick``` argparse input solves this issue.  I started a branch but I will be changing a few other things (e.g., more optional inputs to redmonster), so feel free to fix this on master @tskisner if you haven't already.

**Comment by tskisner** [comment]
@moustakas it is already fixed in master (I believe).  Just awaiting confirmation from @ngbusca

**Comment by ngbusca** [comment]
@tskisner @moustakas It's working now, thanks!

**Comment by tskisner** [comment]
fixed by 28468f1285391f7297c127dfecd5ba1f024dbc4f
