### ISSUE TITLE
Why does the integration test include desitarget when there is no dependency on desitarget?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#187]
The nightly integration test includes an update and module load of desitarget, but desispec has no dependency on desitarget whatsoever.  I did `grep -r desitarget py` and found zero results.  Is the dependency indirect?

If there really is no dependency at all, then we can de-prioritize enhancing desitarget's pip-install capability (especially installing data files) relative to desispec and specter.

**Comment by sbailey** [comment]
desitarget is used by desisim when doing the pixel-level simulations as the first step of the integration tests.  (Note: this does mean that for the integration tests desispec depends upon desisim; eventually that could be factored out into a separate package, but let's not get into that refactor now).

To make sure we aren't chasing in the wrong direction: for the "document installation on anaconda" task, I'm fine with that instructions being based on git clone + python setup.py install.  pip installations are a lower priority that that.  Or perhaps the same issue of data directories affects both.

**Comment by weaverba137** [comment]
@sbailey, there seems to be a slight misconception that I need to clear up.  When I do `pip install git+https://github.com/desihub/desispec...`  that is *exactly equivalent* to doing `git clone ...; git checkout ...; python setup.py install`.  When I say 'pip installable' that is identical to saying `git clone + python setup.py install`able.  If that is still unclear, please explain the specific source of the confusion.

**Comment by sbailey** [comment]
That's clear and that is fine.  I was previously unsure if pip install was running "python setup.py install" under the hood or not.
