### ISSUE TITLE
emlinefit 1+z factors

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1876]
Double check 1+z factors in `desispec.emlinefit.emlines_gaussfit()` and correct as needed; desihub/fastspecfit#86 says that it is wrong (numerator vs. denominator leading to being off by (1+z)^2).

We need this for the Iron run, and ideally ASAP so that it can be included in the Himalayas redshift runs that we are launching soon (maybe even tomorrow?).

**Comment by araichoor** [comment]
the fix is simple.
however, I m waiting for @moustakas investigation result on that.

**Comment by moustakas** [comment]
Here's an update on my code, so `emlinefit` will need the same fix. This was a really dumb bug on my part, sorry.
  https://github.com/desihub/fastspecfit/issues/86#issuecomment-1286300278
