### ISSUE TITLE
desi_run_night default CPU+GPU support not using GPUs?

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1881]
desi_run_night CPU vs. GPU job selection doesn't quite work yet, I think:

`desi_run_night --system-name perlmutter-gpu ...` will submit all jobs to GPU nodes, even jobs that can't yet use a GPU, e.g. arcs.  For GPU-enabled jobs, it includes `desi_proc / desi_proc_tilenight --gpuspecter --gpuextract` and `redrock --gpu ...` so that the GPUs are used.  The non-GPU jobs on GPU nodes still work, but it isn't optimal.

`desi_run_night` without specifying a system name submits arcs, ccdcalib, and nightlybias to CPU nodes and other jobs to GPU nodes.   However, it doesn't instruct the GPU jobs to actually use the GPUs and thus it appears that they would still run in CPU-only mode.  I haven't actually tried letting these jobs run to avoid wasting GPU resources, so it is possible that I'm mis-interpreting what would happen if they ran.

Semi-related: even on Perlmutter CPU nodes `desispec.workflow.batch.default_system` returns "perlmutter-gpu".  Since calling `desi_proc` without `--system-name` triggers a call to `default_system`, this results in confusing log messages about guessing perlmutter-gpu even though the job is on a CPU node and couldn't use a GPU even if it wanted to.

Review what behavior is treated as default and update such that jobs submitted to GPU nodes will use GPUs and jobs that can't use a GPU get submitted to a CPU node by default.

While we're at it: in addition to arc, ccdcalib, and nightlybias, other jobdesc that can't use GPUs yet are nightlyflat, psfnight, and badcol.

Examples for testing:
```
# all job scripts have --constraint=gpu (even arcs) and desi_proc jobs have --gpuspecter --gpuextract
desi_run_night -n 20210220 --z-submit-types pernight --use-tilenight --system-name perlmutter-gpu -q regular --dry-run-level 1

# some jobs --constraints=cpu and others --constraint=gpu, but gpu jobs don't have --gpuspecter --gpuextract
# or --system-name so it appears the would run in CPU mode instead of GPU mode
desi_run_night -n 20210221 --z-submit-types pernight --use-tilenight -q regular --dry-run-level 1
```

**Comment by akremin** [comment]
For the record I intentionally implemented the arcs to CPU nodes such that it only does that if you don't explicitly specify a system name. It seemed wrong to override a user-defined value. I can see your viewpoint here though. This may be a case where we make the code smart enough to correct a user input which is clearly inaccurate (as long as we remember to remove that later when we can use GPU's). Or we could specify just "perlmutter" and have the code auto set the "-cpu" or "-gpu", but that would require more surgery since the code typically doesn't touch the `system_name` if it's set.

For your request to add additional jobs to the cpu-only someone just needs to add them to the list in the check here: https://github.com/desihub/desispec/blob/c3c8740bfbee7f918f2ff03c98f86eaa3646b4fa/py/desispec/workflow/batch.py#L56

**Comment by sbailey** [comment]
Clarifying: if the user specifies `--system-name` then I think we should use that for all jobs, even if non-optimal.  i.e. I agree with you that we shouldn't override an explicit choice from the user.

The case the needs to be fixed is where the user does *not* specify `--system-name` and it auto-picks which jobs to send where.  It currently makes the right choice for what to send where (other than minor updates for nightlyflat and psfnight), but IIUC it isn't propagating the right `desi_proc`, `desi_proc_tilenight` and `redrock` options to actually use the GPUs on the jobs that it sends to the GPU nodes.

Thanks for pointing out the line for where to add CPU-only jobdesc items.

**Comment by sbailey** [comment]
I discussed this with Anthony and am working on a fix, but likely won't converge before Perlmutter goes down in 6 minutes.

Another item is that the `desi_proc_joint_fit` wrapper of `desi_fit_stdstars` isn't including the `--use-gpu` option so that step also appears to not be using GPUs, even when `--system-name=perlmutter-gpu`.

Also see #1799 about the need to standardize GPU options.
