### ISSUE TITLE
desi_run_night --use-tilenight doesn't work if only one science exposure

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1889]
`desi_run_night --use-tilenight ...` doesn't work if a night has a single science exposure with no calibrations preceeding it.  This is admittedly an artificial case that I don't think we have in real data, but it is useful for testing (and I think would be triggered if trying to run a single tile while exclusing cals).  Examples in test prod `/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/tilenight`, dry-run "submitted" with
```
for NIGHT in 20221021 20221025 20221026; do
    desi_run_night --use-tilenight -q regular --z-submit-types None --all-tiles --dry-run-level 1 -n $NIGHT &> run/logs/$NIGHT.log
done
```

Cases:
1. 20221021 : single science exposure, preceded by cals<br>**result**: that tile is submitted
2. 20221025: single science exposure and nothing else<br>**result**: that tile is *not* submitted
3. 20221026: two science exposures and nothing else<br>**result**: both are submitted

The second case (single tile not getting submitted) is because desispec.scripts.submit_night only goes though a single iteration of the etable loop and line 349 never gets a chance to have `lasttype` not None:
```
        if lasttype is not None and ((curtype != lasttype) or (curtile != lasttile)):
            ....
            submit_tilenight_and_redshifts(...)
```

I haven't figured out case 3 yet (given that case 2 was dropping a tile, I was expecting case 3 to drop one tile and submit the other...).

@marcelo-alvarez @akremin please take a look.  I'm assigning this to Himalayas and Iron in case it is a symptom of a more significant corner case that could affect real data.  If we confirm that it only applies to tests cases, we could remove it from those projects (but I'd still like to get it fixed sooner than later to support test runs of a single tile).

**Comment by marcelo-alvarez** [comment]
@sbailey although we have not (to my knowledge) confirmed explicitly that this issue only applies to test cases and does not affect real data, it seems likely given the lack of activity here since the fall. 

I suggest that we address this as the refactoring in #2021 and/or #2024, i.e. *after* Perlmutter becomes the default system for daily processing.
