### ISSUE TITLE
What is the official method for setting log levels on the command line?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#189]
`desispec.log` allows the log level to be set by the `DESI_LOGLEVEL` environment variable, but, in my experience at least, the standard method to change the log level is to pass `--verbose` or `--debug` on the command line.  A random sampling of command-line scripts reveals that some do not accept a `--debug` option at all, or, if they do, `--debug` does not actually change the log level.

So the question can be rephrased as, is `DESI_LOGLEVEL` the only officially-supported method to change the log level (and should be better documented as such)? Or, should we be encouraging and documenting the use of `--debug` to change the log level in addition?

**Comment by sbailey** [comment]
`$DESI_LOGLEVEL` should work no matter what.

Scripts can optionally include a `--verbose` option to override `$DESI_LOGLEVEL`; it should be the same as setting `DESI_LOGLEVEL=debug`.  It is just a convenience option to avoid mucking with environment variables, setting them back to their original value, etc. if you just temporarily want to turn on debug-level logging for a script.

In some places we've used `--debug` for more than just debug-level logging, e.g. to drop into an ipython prompt at the end of a script for more plotting, debugging, etc. before actually exiting.  Let's keep `--debug` reserved for more extreme stuff like that, and not just for "print more stuff along the way".
