### ISSUE TITLE
desi_run_night tilenight not submitting all tiles

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1914]
There are several bugs in the `desi_run_night --use-tilenight ...` job submission logic resulting in tiles not getting submitted for processing.

All of these can be tested on Perlmutter with e.g.
```
[pick a $DESI_SPECTRO_REDUX/$SPECPROD testdir wherever you like, then]
svn checkout https://desi.lbl.gov/svn/data/exposure_tables
mkdir -p run/logs
export NIGHT=20210130 && desi_run_night --dry-run-level 1 -n $NIGHT &> run/logs/$NIGHT-submit.log
[inspect run/logs/$NIGHT-submit.log for the exposures in question...]
...
```

### Case 1: non-contiguous exposures for a tile

e.g. night 20210130 tile 80718, observed on exposures 73720, 73721, 73727, 73728 .  In the gap of those exposure sequences, tiles 80637 (exp 73722,73723) and 80636 (exp 73724,73725,73726) were observed.  This seems to confuse the "do I have all the exposures for this tile?" logic resulting in tile 80718 not getting submitted for any of the exposures, and not even being mentioned in the submission log.

### Case 2: tile observed before a single bad exposure

e.g. night 20210320 tile 80875, observed on exposures 81197,81198.  This was followed by tile 80702 exposure 81201, but bad weather was rolling in and that exposure was flagged as LASTSTEP=ignore.  This also seems to confuse the "do I have all the exposures for this tile?" logic resulting in tile 80875 (the last good tile) not being submitted.

### Case 3: cause unknown

Night 20210328 tile 80724 exp 82608 (warning: confusingly similar tiles and exposure IDs in this date range) is not submitted for some reason, but I don't yet see why.
```
EXPID TILEID  EXPTIME  LASTSTEP BADCAMWORD BADAMPS
----- ------ --------- -------- ---------- -------
82600  80644  300.0704      all         a6      --
82601  80644  300.0701      all         a6      --
82602  80722  759.9373      all         a6      --
82603  80722  817.0967      all         a6      --
82605  80618  973.0255      all         a6      --
82608  80724   655.945      all        a67      --    <<< not submitted, other tiles are.
82614  80740  300.0701      all         a6      --
82621  80651  917.0278      all         a6      --
82622  80651  809.9943      all         a6      --
82623  80651 1974.3561   ignore         --      --
82624  80742 1057.0218      all         a6      --
82625  80742 1073.0599      all         a6      --
```

Cases like this (undiagnosed, there may be more than one cause):
```
NIGHT     TILEID  EXPID
20210328  80724   82608
20210430  81097   86750
20210628  20514   96465
20220107  23046   117273
20220129  41257   120695
20220221  25880   123283
```

**Comment by sbailey** [comment]
For Case 1, I confirmed that it is also a problem for `desi_run_night --no-use-tilenight ...`, and that using `desi_run_night --tiles 80718 --append-to-proc-table ...` does **not** trick it into processing that missing tile correctly.  i.e. I don't know a work around to process this without resorting to manually running desi_proc_tilenight etc outside of the context of the pipeline wrappers (or fixing this bug).

However, it is not a problem with desispec/0.51.13 used with Fuji — it both exists with fuji, and repeating the dry run test with desispec/0.51.13 generates the correct jobs including tile 80718.  i.e. although the problem impacts both tilenight and non-tilenight, it appears to have been introduces as part of the updates to support tilenight.

On Monday let's evaluate a re-write of this logic to be less like desi_daily_proc_manager, which uses the order that exposures/tiles arrive to trigger launching jobs (so that we can keep up throughout the night), and do something like this instead (which takes advantage of knowing about all exposures on a night before doing anything):
  1. submit ccdcalib / bias / badcol depending upon the existence of enough zeros and/or 300 sec dark
  2. submit arcs + psfnight
  3. submit flats + nightlyflat
  4. for each science tile present in the exposure tables:
     * identify all good exposures for that tile regardless of their order
     * submit tilenight; or prestdstar+stdstar+poststdstar jobs for those exposures for that tile
     * submit redshift jobs for that tile

**Comment by sbailey** [comment]
To do: check if some of these are just tiles that haven't been QA approved and shouldn't be launched anyway (unless --alltiles option is set, which it isn't by default for non-daily production runs).

**Comment by akremin** [comment]
This does indeed appear to be due to the introduction of quality cuts into `desi_run_night` for nearly all of these cases. This was introduced in PR #1843.

```
In [1]: from desispec.scripts.submit_night import get_completed_tiles

In [3]: get_completed_tiles()
INFO:submit_night.py:502:get_completed_tiles: specstatus_path not defined, setting default to /global/cfs/cdirs/desi/survey/ops/surveyops/trunk/ops/tiles-specstatus.ecsv.
Out[3]: array([    1,     2,     3, ..., 83234, 83235, 83236])

In [4]: completed_tiles = set(get_completed_tiles())

In [5]: test_tiles = [80718, 80875, 80724, 81097, 20514, 23046, 41257, 25880]

In [6]: for tile in test_tiles:
   ...:     print(f"Is tile {tile} complete? {tile in completed_tiles}")

Is tile 80718 complete? False
Is tile 80875 complete? False
Is tile 80724 complete? False
Is tile 81097 complete? False
Is tile 20514 complete? False
Is tile 23046 complete? False
Is tile 41257 complete? True
Is tile 25880 complete? False
```

I will follow up with 41257, which does surprise me and can't be explained away with the others.

**Comment by akremin** [comment]
I have verified that all tiles listed above except 41257 are not submitted with the standard `desi_run_night` flags, but are submitted if we use `--all-tiles`. We instituted the quality cuts on purpose for these productions, so I don't think we want to do that, but I confirm that it is due to these cuts and that the script logic is correct.

For 41257 it looks to me as though it was problematic for processing on 20220129. It was processed twice and removed twice by `desi_purge_tilenight` as evidenced by the following entries in archived processing tables: 

```
kremin@cori21:/global/cfs/cdirs/desi/spectro/redux/himalayas/processing_tables> grep ",41257," *
processing_table_himalayas-20211218.csv:114627|,science,41257,20211218,,all,|,a0123456789,0,211218095,,prestdstar,59303381,1653286487,COMPLETED,,211218019|,59302915|,59303381|
processing_table_himalayas-20211218.csv:114627|,science,41257,20211218,,all,|,a0123456789,0,211218096,,stdstarfit,59303408,1653286490,COMPLETED,,211218095|,59303381|,59303408|
processing_table_himalayas-20211218.csv:114627|,science,41257,20211218,,all,|,a0123456789,0,211218097,,poststdstar,59303421,1653286493,COMPLETED,,211218096|,59303408|,59303421|
processing_table_himalayas-20220129.csv.20221006_16h14m:120695|,science,41257,20220129,,all,|,a0123456789,0,220129040,,prestdstar,59805104,1654231788,COMPLETED,,220129019|,59805067|,59805104|
processing_table_himalayas-20220129.csv.20221006_16h14m:120695|,science,41257,20220129,,all,|,a0123456789,0,220129041,,stdstarfit,59805107,1654231793,COMPLETED,,220129040|,59805104|,59805107|
processing_table_himalayas-20220129.csv.20221006_16h14m:120695|,science,41257,20220129,,all,|,a0123456789,0,220129042,,poststdstar,63182718,1664513914,SUBMITTED,,220129041|,59805107|,59805108|59818484|61923299|62984642|63182718|
processing_table_himalayas-20220129.csv.20221013_13h26m:120695|,science,41257,20220129,,all,|,a0123456789,0,220129040,,prestdstar,59805104,1654231788,COMPLETED,,220129019|,59805067|,59805104|
processing_table_himalayas-20220129.csv.20221013_13h26m:120695|,science,41257,20220129,,all,|,a0123456789,0,220129041,,stdstarfit,59805107,1654231793,COMPLETED,,220129040|,59805104|,59805107|
processing_table_himalayas-20220129.csv.20221013_13h26m:120695|,science,41257,20220129,,all,|,a0123456789,0,220129042,,poststdstar,63389751,1665164827,SUBMITTED,,220129041|,59805107|,59805108|59818484|61923299|62984642|63182718|63389751|
```

When I load the default environment for himalayas and run:
`desi_run_night --dry-run-level=3 -n 20220129 --append-to-proc-table`

it shows that it would submit exposure 120695 for processing and then submit tile 41257 for redshifting. This implies to me that the scripts crashed when run and were removed in the hopes of cleaning things up and fixing it. I do see the exposure has `EFFTIME_SPEC` of 0.0 in daily for 120695, so it likely isn't good.

I'm comfortable enough with this explanation that I will close this ticket and open a new ticket for flagging exposure 120695 of tile 41257.
