### ISSUE TITLE
Inconsistent types in desispec.io.photo.(tractor|target)phot_datamodel

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#1925]
There is at least one type inconsistency in `desispec.io.photo.tractorphot_datamodel` versus `desispec.io.photo.targetphot_datamodel`.  This was first noticed in moustakas/desi-photometry#8.
All columns will now need to be re-examined for consistency.

**Comment by weaverba137** [comment]
@moustakas, I think this may have been fixed.  Could you please check?

**Comment by moustakas** [comment]
Yes, this was fixed. Thanks.
