### ISSUE TITLE
Travis tests do not include dependencies needed to run desispec pipeline

### ISSUE THREAD

**Issue by tskisner** [desihub/desispec#193]
In order to run the spectroscopic pipeline, we need desiutil, speclite, HARP (serial only), specex, and specter.  If we wish to test the pieces of the pipeline that use those packages, they need to be installed during travis tests.  This is the current reason that travis tests fail on the master branch.  On a local machine with those dependencies installed, tests work fine.  I am investigating how to debug travis tests without pushing many tiny changes to .travis.yml and travis_env_common.sh.  The only recommendations I have seen so far is the fork the repo for testing and set up a new travis-CI test against that.

**Comment by weaverba137** [comment]
Travis tests will run on branches.  There is no need to do a full fork.

**Comment by tskisner** [comment]
sure- was just trying to keep the main repo history from being cluttered with a ton of single line pushes while I am testing travis.  But I guess I could squash those into one "real commit" when making a pull request...

**Comment by tskisner** [comment]
Looks like the linux tests are being run on a 4-year old OS (Ubuntu 12.04) with an old version of gcc (4.6.3) which does not support C++11 (required for HARP / specex).  Since we are using container based builds:

https://docs.travis-ci.com/user/ci-environment/

we don't have any options but to try to make the HARP configure script detect the old compiler and attempt to use the older version of "-std=c++0x".  I will also test the ubuntu 14.04 environment just to see if it works (though it has a longer boot time).

**Comment by tskisner** [comment]
Almost have this working, but it is slow to build everything.  @weaverba137 do we have any requirements on how fast the travis build needs to complete?  If it takes 5-10 minutes, does that have any bad consequences?

**Comment by weaverba137** [comment]
We do not have any specific requirements on Travis test time.  I'm inclined to think that a little bit of a wait is not a bad thing.

Speaking of waiting, let's not *rush* to get this fixed.  It is entirely possible that we can fix some of these compile delays by installing Ubuntu packages.  The Travis tests already do this, in the
```yaml
addons:
    apt:
        packages:
```
section.

Also we can simplify the install process somewhat by using astropy/ci-helpers.  desimodel and specter are already using this.

**Comment by tskisner** [comment]
yes, I was just looking at this, and will replace cfitsio with the ubuntu package.  I think I will also build some harp packages to speed up the install, which is the dominant time now.

**Comment by weaverba137** [comment]
Fixed by #194.
