### ISSUE TITLE
failure of 158488 b4 in prestdstar

### ISSUE THREAD

**Issue by marcelo-alvarez** [desihub/desispec#1940]
Even after the fix implemented in #1927 was made on the daily branch, the error associated with a non-empty vector, i.e. 
```
grep -h Error /global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/night/20221216/prestdstar-20221216-00158488-a0123456789-65145512.log
    raise TypeError("expected non-empty vector for x")
ERROR:util.py:158:runcmd: TypeError: expected non-empty vector for x
OSError: FITSIO status = 104: could not open the named file
```
occurred for exposure 158488 in the prestdstar step. I have not yet determined if it is the same cause as for #1927, however. 

I will mark cameras a4 bad for this exposure and reprocess.

**Comment by julienguy** [comment]
Hi, I cannot reproduce the bug. The code works fine when I run it from a cori login node with the latest desispec main and DESI_SPECTRO_CALIB. I think we should just rerun this one.

```
export SPECPROD=daily
export DESI_SPECTRO_CALIB=/global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk

desi_preproc -i ~/data/20221216/00158488/desi-00158488.fits.fz --cam b4

desi_compute_trace_shifts -i ./preproc-b4-00158488.fits.gz --psf /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20221216/psfnight-b4-20221216.fits --degxx 2 --degxy 0 --degyx 2 --degyy 0 --sky --outpsf psf-b4-00158488.fits
```

@marcelo-alvarez can you please try it.

**Comment by akremin** [comment]
Currently the daily pipeline is run with the `daily` branch on Cori (because zproc is inefficient on Cori without gpus). This points to another difference in the code between `daily` and `main`. @marcelo-alvarez do you have cycles to look into that?

**Comment by marcelo-alvarez** [comment]
@julienguy @akremin I am looking at this now to see if see if the error occurs with the commands above using desispec/daily

**Comment by marcelo-alvarez** [comment]
I ran the above with desispec/daily and there was no crash. Almost certainly what happened is that when I updated to the latest version of desispec/daily and reran, I did not delete the preproc file, which still had the NaNs in it, so the pipeline crashed again at the same point. 

Thanks @julienguy for checking on this and suggesting the correct solution, which I missed initially because I just pulled and re-ran without starting over.

@akremin I will now reprocess this tile on cori by removing all petal 4 files for exposure 158488 and tile 5181, and rerunning prestdstar, stdstar, poststdstar and coadd-redshifts, so as not to re-run the other 9 petals unnecessarily. Please let me know if there is anything that needs to be done to the processing tables to leave this night in a more intelligible state for future investigation / processing in daily.

**Comment by marcelo-alvarez** [comment]
The processing of 5181 was successful (by running `desi_purge_tilenight` instead of reprocessing only petal 4 data, after consulting with @akremin).
