### ISSUE TITLE
Determine whether any changes to main need to be propagated to daily

### ISSUE THREAD

**Issue by marcelo-alvarez** [desihub/desispec#1949]
The daily branch - not main - is being used for daily processing. 

Changes committed to main since [96b7567](https://github.com/desihub/desispec/commit/96b7567b23af4010146b109dcfecaaf19b03f450) are [not currently reflected in daily](https://github.com/desihub/desispec/compare/daily...main).

Are there any commits that have been made to main (other than [76fc382](https://github.com/desihub/desispec/commit/76fc3822450630e7751a96ffe2a7328c7c7ca919), which was included "by hand" in #1939) that include changes that need to be made for daily processing? 

Mentioning others who committed changes to main that are not reflected in daily: @julienguy @Waelthus @weaverba137 @akremin @sbailey.

**Comment by akremin** [comment]
We are now back to using `main` for daily operations, so we no longer need to track this.
