### ISSUE TITLE
tile_qa_plots.get_expids_efftimes I/O efficiency

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1951]
`desispec.tile_qa_plots.get_expids_efftimes` can be quite slow for sv1 tiles with lots of exposures.  e.g. tile 80617 takes 6m50s to generate tile-qa*.png, compared to redrock running in <1 minute.  This can lead to job timeouts when the I/O system is bogged down from other users.

A major factor is that it reads nexp*10*3 cframe files to get the SCORES table.  It would be more I/O efficient to read these from the SCORES table of the spectra files, since that file is already being opened to read the FIBERMAP and it already contains the concatenation of all of the SCORES tables from the input cframe files (row-matched with the concatenated FIBERMAP table).  Even that is still pretty slow because the spectra files are gzipped (sorry, Julien) and fitsio unzips the entire file to read the tables, but it is still better to read 10 files instead of nexp*10*3 files.

If for some reason it is still necessary to read from the original cframe files instead of the spectra files, another I/O speedup would be to read the EXP_FIBERMAP from the coadd*.fits files since it appears to only be used to get the NIGHT and EXPIDs and the non-compressed smaller coadd files are much faster to read than the spectra files.

Detail: the coadd files also have coadded SCORES, which would be much faster to read than the spectra SCORES, but I think the tile-qa plots need the non-coadded SCORES values.

A more invasive optimization would be to add optional MPI support to also read the 10 spectra files in parallel.  Unfortunately this would need to be MPI not just multiprocessing, since the redshift jobs now bundle all the steps in an MPI wrapper and MPI+multiprocessing doesn't work well together on Perlmutter.

**Comment by araichoor** [comment]
sorry for that :)

as you ve understood, the goal is to get the per-exposure efftime_spec (mimicking what s done for the `exposures-PROD.fits` file, which does not exist at this point), so it cannot be done from the `coadd` files.

I ve given a quick look a simple optimization, along your suggestion of only using the `spectra` files: for this `TILEID=80617` example, it reduces the computing time by ~2/3 (from 780s to 250s).

would that be good enough? shall I go ahead and make a PR?

ps: when exploring the files I realized that the list of (EXPID, NIGHT) can also be inferred from the `INFIL???` keywords in the `spectra` files header; this allows one instantaneously get that list; though, one still needs to read the per-camera `TSNR2` columns, i.e. open the `spectra` files.

**Comment by sbailey** [comment]
@araichoor thanks, a 780s -> 250s speedup is worth it for a PR.

Although EXPID,NIGHT could be inferred from the INFIL??? keywords, that seems much more fragile to parse than getting it from the fibermap.  Given that you need to open the spectra files anyway to get the TSNR values from the SCORES table, let's continue using the FIBERMAP.  And I think you need the fibermap anyway to know which rows of the SCORES tables go with which exposures (they are row matched).  The main trick is to open the file once and get both tables so that the un-gzipping only happens once.

I believe all of this should produce bitwise identical output, just run faster.  If that's not the case, let's revisit why they are different and whether it is worth the effort.

**Comment by araichoor** [comment]
thanks for the feedback.
I ll work on that (and I ll ignore the `INFIL???` header keywords).

small question: shall I make the PR to "main" or "daily"? "main"?

**Comment by sbailey** [comment]
Let's do "daily", though if you have already started on "main" that's ok too.  The speedup mainly matters for SV tiles with lots of exposures, but it would have a small improvement for daily ops too.  After merging into daily, we can merge daily into main (but we don't do the reverse of merging main into daily since the whole point of daily is to protect ops on Cori from perlmutter/Iron focused main).

**Comment by sbailey** [comment]
implemented in PR #1954; closing ticket.
