### ISSUE TITLE
Fix problematic entries in tpcorrparam file in z5 and r4

### ISSUE THREAD

**Issue by schlafly** [desihub/desispec#1960]
z5 and r4 have problematic tpcorrparam calibration entries because the values used in computing the calibration files used were affected by the bad columns on z5 and the poor CTE on r4.  This was fine while we had those fibers flagged, but since replacing the spectrographs we don't want to use those contaminated values.

I've addressed this by setting the tpcorrparam MEAN entries to be 1 and the PCA entries to be nominal for the affected fibers:
z5: 164:175
r4: 250:272
I've also further changed the tpcorrparam SPATIAL entries to be 1/0 as appropriate for r4; the z5 values look basically okay and I have not touched them.

I've placed updated files in DESI_SPECTRO_REDUX/schlafly/desi_spectro_calib but have not yet committed them.  The new files are clearly an improvement.  e.g.,
![image](https://user-images.githubusercontent.com/1417841/211064018-7353494f-c5bf-4923-b8b0-ccec4ff5a4e0.png)
(note reduced black bands around fiber 2250).

The improvement in z5 is much more subtle, but is still barely noticeable around fiber 2670 as a black band in daily that is removed in the new processing.
![image](https://user-images.githubusercontent.com/1417841/211065013-38ac8858-63d4-48b9-95ef-99b73c9f9133.png)
Much more importantly, we've also added sector offsets to z5 since daily, which is the more significant improvement in this comparison.

I processed these images via:
```
export SPECPROD=daily
desi_compute_sky -i /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20221223/00159730/frame-r4-00159730.fits.gz --fiberflat /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20221223/00159730/fiberflatexp-r4-00159730.fits.gz  --adjust-wavelength --adjust-lsf --pca-corr /global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk/spec/sm1/skycorr-pca-sm1-r4.fits --fit-offsets  --skygradpca /global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk/spec/sm1/skygradpca-sm1-r4.fits --tpcorrparam /global/cfs/cdirs/desi/spectro/redux/schlafly/desi_spectro_calib/trunk/spec/sm1/tpcorrparam-sm1-r4.fits -o sky-r4-00159730-new.fits.gz
desi_process_exposure --infile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20221223/00159730/frame-r4-00159730.fits.gz --fiberflat /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20221223/00159730/fiberflatexp-r4-00159730.fits.gz  --cosmics-nsig 6 --sky sky-r4-00159730-new.fits.gz  --no-sky-line-throughput-correction --no-xtalk --outfile sframe-r4-00159730-new.fits.gz


desi_compute_sky -i /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20221223/00159730/frame-z5-00159730.fits.gz --fiberflat /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20221223/00159730/fiberflatexp-z5-00159730.fits.gz  --adjust-wavelength --adjust-lsf --pca-corr /global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk/spec/sm9/skycorr-pca-sm9-z5.fits --fit-offsets  --skygradpca /global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk/spec/sm9/skygradpca-sm9-z5.fits --tpcorrparam /global/cfs/cdirs/desi/spectro/redux/schlafly/desi_spectro_calib/trunk/spec/sm9/tpcorrparam-sm9-z5.fits -o sky-z5-00159730-new.fits.gz
desi_process_exposure --infile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20221223/00159730/frame-z5-00159730.fits.gz --fiberflat /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20221223/00159730/fiberflatexp-z5-00159730.fits.gz  --cosmics-nsig 6 --sky sky-z5-00159730-new.fits.gz  --no-sky-line-throughput-correction --no-xtalk --outfile sframe-z5-00159730-new.fits.gz
```
I have not yet checked these in because my new reduction has more masked fibers than the daily reduction.  That doesn't seem like it can be related to my change, but I don't know what else changed, so I'm delaying taking action until I understand that.
![image](https://user-images.githubusercontent.com/1417841/211065837-017a3d96-e5c5-4271-bac0-dcb6d5d68337.png)

**Comment by schlafly** [comment]
With @sbailey 's fixes to my invocation above (ugh, thank you!), I no longer see extra masking.  I can no longer reproduce the failure here, so I guess we could merge?

**Comment by sbailey** [comment]
Agreed.  I fixed a "new" vs. "std" copy-and-paste typo in the above instructions, and with that change was unable to reproduce the extra masking (both at the mask!=0 level, and the ivar=0 level).  These changes look good.  Let's go ahead and merge (where I think that means @schlafly committing his changes to DESI_SPECTRO_CALIB and us updating the svn checkout at NERSC and KPNO)

**Comment by schlafly** [comment]
I've committed this to desi_spectro_calib, r1067.  I've "svn up"ed at NERSC and KPNO to bring this into the daily processing. 
 Closing.
