### ISSUE TITLE
desi_zproc_dashboard overfull accounting bug

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1974]
desi_zproc_dashboard flags an entry as "overfull" if it finds more files than it expected.  However, it appears to only consider the current night exposure table in the accounting, ignoring previous nights that might be relevant in the case of cumulative redshifts.

e.g. tile 80626 was observed on 20210110 with BADCAMWORD=a3, and on 20210203 with BADCAMWORD=a03.  The cumulative redshifts for 20210203 can include petal 0 because it was successfully observed on 20210110 even if it was flagged bad on 20210203, but it can't include petal 3 because it was bad on both nights.  However, desi_zproc_dashboard apparently only expects 8 petals and reports it as overfull because there are 9 petals present in the output.

I think this is a known issue, but I couldn't find an associated ticket so I'm filing this and associating it with Iron.

**Comment by akremin** [comment]
It is a known issue, but I can't find an associated ticket either so thank you for making one. This is on my radar to clean up along with several other `desi_zproc_dashboard` updates.

**Comment by sbailey** [comment]
A more subtle case that how a false positive overfull can mask real failures:

Tile 82406 was observed on 20211030 and 20211115 with all 10 spectrographs, and on 20211118 with only 2 good petals.  It should be able to produce 10 petals of cumulative output.  However, emlinefit is failing on 2 petals and only producing 8 outputs.  But the dashboard still thinks that is overfull since it is only looking for 2 petals of output and so it gets flagged as purple overfull instead of red failure.

**Comment by sbailey** [comment]
fixed in PR #2285. closing
