### ISSUE TITLE
arc jobs not cleanly recovering from mid-job failures

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1980]
Iron 20211001 arc expid 102547 initially failed due to a transient I/O failure reading input preproc files; see
iron/run/scripts/night/20211001/arc-20211001-00102547-a0123456789-4852456.log, e.g.
```
ERROR:specex.py:338:fitframe: FAILED: MPI ranks 161-180 on camera z1
ERROR:specex.py:340:fitframe: FAILED: desi_compute_psf --input-image /dvs_ro/cfs/cdirs/desi/spectro/redux/iron/preproc/20211001/00102547/preproc-z1-00102547.fits.gz --input-psf /dvs_ro/cfs/cdirs/desi/spectro/redux/iron/exposures/20211001/00102547/shifted-input-psf-z1-00102547.fits --output-psf /global/cfs/cdirs/desi/spectro/redux/iron/exposures/20211001/00102547/fit-psf-z1-00102547.fits
ERROR:specex.py:341:fitframe: [Errno 5] Input/output error: '/dvs_ro/cfs/cdirs/desi/spectro/redux/iron/preproc/20211001/00102547/preproc-z1-00102547.fits.gz'
```

Resubmitting the job didn't cleanly recover, and failed with different errors in the second log run/scripts/night/20211001/arc-20211001-00102547-a0123456789-4868394.log, e.g.
```
ERROR:specex.py:323:fitframe: FAILED: commands for camera r6 not found for MPI group rank 15 and world rank 276
```

It appears that all of the successful PSFs from the first iteration confused the MPI rank bookkeeping of the second submission, causing it to report failure even though it had succeeded in writing the previously failing PSFs.

For the purposes of Iron I need to cleanup the data files and re-run, but the above logs will still be there.

**Comment by sbailey** [comment]
@marcelo-alvarez I think the test would be:
1. take the outputs from a previously successful arc exposure processing
2. remove one of the psf files
3. rerun the arc*.slurm script

My understanding of the previous failure was that when the script woke up in step (3) and allocated work to ranks, but the presence of a partial set of successful PSFs confused the bookkeeping leading to a fake failure.

**Comment by marcelo-alvarez** [comment]
@sbailey thanks, it's clear now.
