### ISSUE TITLE
NaNs in tiles-daily.ecsv EFFTIME

### ISSUE THREAD

**Issue by schlafly** [desihub/desispec#1988]
There are three tiles with NaNs as EFFTIME in the tiles-daily.ecsv file.  Afternoon planning was taking these seriously and was at risk of sending NaNs to the ICS when deciding how much time was needed to complete a tile.  It is now zeroing the effective time on the affected exposures, but I'm not sure if this is correct.  We should fix this.

```
TILEID SURVEY PROGRAM FAPRGRM  FAFLAVOR   NEXP EXPTIME ... ELG_EFFTIME_DARK BGS_EFFTIME_BRIGHT LYA_EFFTIME_DARK GOALTYPE MINTFRAC LASTNIGHT
int64   str7    str6   str16    str19    int64 float64 ...     float64           float64           float64        str7   float64    int64  
------ ------ ------- ------- ---------- ----- ------- ... ---------------- ------------------ ---------------- -------- -------- ---------
 42395   main  backup  backup mainbackup     1   602.0 ...              nan                nan              nan   backup     0.85  20230119
 26064   main  bright  bright mainbright     2  1937.2 ...              nan                nan              nan   bright     0.85  20230119
 21513   main  bright  bright mainbright     4  3634.8 ...              nan                nan              nan   bright     0.85  20230120
```

**Comment by araichoor** [comment]
for what is worth, those three tiles are identified/mentioned in this issue: https://github.com/desihub/desispec/issues/1978, where the nans in tsnr2 (hence efftime) make the tile_qa_plot routine crash.

**Comment by schlafly** [comment]
Ah, good, closing as a duplicate of 1978, but I'll add that the urgency there is more than we had appreciated.

**Comment by araichoor** [comment]
"_It is now zeroing the effective time on the affected exposures, but I'm not sure if this is correct._"
=>
during the surveyops call, a suggestion was to use the `EFFTIME_ETC` for those exposures (though we acknowledge this implies extra coding).
as zeroing the EFFTIME may theoretically lead to over-exposed tiles in case we can recover the exposures.
if useful, here is a list of the current exposures for those tiles:

```
 NIGHT   EXPID  TILEID  FAFLAVOR  EXPTIME EFFTIME_ETC EFFTIME_SPEC
 int64   int64  int64    str19    float64   float64     float64   
-------- ------ ------ ---------- ------- ----------- ------------
20230119 163835  26064 mainbright   920.6        89.4          nan
20230119 163836  26064 mainbright  1016.6        91.7        101.6
20230119 163837  21513 mainbright  1042.3        71.5         84.0
20230119 163838  21513 mainbright  1413.2        67.3          0.0
20230119 163839  21513 mainbright   638.3        42.1          nan
20230119 163860  42395 mainbackup   602.0        11.7          nan
20230120 164021  21513 mainbright   541.0        48.3         55.5
```
tiles 26064 and 21513 could potentially be done if we can recover the exposures.

**Comment by schlafly** [comment]
I'd really rather we fix the NaNs or remove the rows from exposures-daily.  I consider the current AP behavior sub optimal but an adequate safeguard against times when the offline pipeline gives a result that is clearly bogus.  It isn't clear to me in general if EFFTIME_ETC is a better estimate than 0 in weird cases where something breaks in the offline pipeline---though I'm happy to hear that in this case we expect to be able to recover the data.
