### ISSUE TITLE
add checksums and code versions to output files

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#20]
All io.write* functions should use the checksum=True option when writing FITS files to automatically add DATASUM and CHECKSUM keywords to the headers.

Add code versions to the headers.  This may require some creative naming to keep within 8 characters.
Make this semi-optional.  e.g. if desimodel is configured, include a VDSIMODEL keyword with the desimodel version that is set up.  If it isn't set up, don't crash (e.g. writing a frame file doesn't actually require desimodel).  Codes that might be considered for caching their version number:
  * desispec
  * desimodel
  * desisim
  * redmonster
  * specex
  * harp

Note: some (all?) of those may not actually provide a version.  Fix that too if needed.

**Comment by rainwoodman** [comment]
I wonder if the first 8 chars of git sha hash can serve the purpose?

**Comment by sbailey** [comment]
Yes.  Here is a snippet of code from [desiUtil](https://desi.lbl.gov/trac/browser/code/tools/desiUtil/trunk/py/desiUtil/install/git_version.py) that returns the results of `git describe --tags --dirty --always` .  If you have a tag you get a nice clean tag number; if you have a checkout of some random commit you get the hash.

    def git_version(git='git'):
        """Use ``git describe`` to generate a version string.
        Parameters
        ----------
        git : str, optional
            Path to the git executable, if not in :envvar:`PATH`.
        Returns
        -------
        git_version : str
            A version string.
        """
        from subprocess import Popen, PIPE
        myversion = '0.0.1.dev'
        try:
            p = Popen([git, "describe", "--tags", "--dirty", "--always"], stdout=PIPE)
        except EnvironmentError:
            return myversion
        out = p.communicate()[0]
        if p.returncode != 0:
            return myversion
        return out.rstrip()

desiUtil also has similar code for parsing svn versions.  The original intention was for code to use desiUtil for standard version parsing, but that got deprecated at some point where there were problems installing desiUtil and it seemed silly to break code over a dependency just for getting a version number.

**Comment by weaverba137** [comment]
In terms of FITS header keyword names, we came up with a solution in the DECam Legacy Survey pipeline.  It is similar to how table column names and types are defined.  For example:

```
DEPNAM01= 'astropy'
DEPVER01= '1.0.4'
DEPNAM02= 'astrometry_net'
DEPVER02= '3.1.4.1.5.9'
```

**Comment by sbailey** [comment]
That is great.  Let's use that.

**Comment by sbailey** [comment]
Fleshing out some ideas prior to implementing...

### Code dependencies ###

tracked like Ben suggested above:
```
DEPNAM01= 'astropy'
DEPVER01= '1.0.4'
DEPNAM02= 'astrometry_net'
DEPVER02= '3.1.4.1.5.9'
```
I propose that these are 0-indexed not 1-indexed like the example, but the parsing code should be robust to either choice.  Starting at nn>1 is not allowed, however (makes parsing code easier if it knows that if DEPNAMnn isn't in the header and nn>1 it can stop looking...)

Add utility functions to make working with these easier:
```
#- Adds DEPNAMnn/DEPVERnn, or updates existing DEPVERnn; modifies meta
#- meta is dict-like header keyword object, e.g. FITS header or plain dict
io.meta.add_code_dependency(meta, codename, version)

#- Removes all DEPNAMnn/DEPVERnn keywords from meta
io.meta.clear_code_dependencies(meta)

#- Parses dependencies and returns dict with key/value = codename/codever
io.meta.get_code_dependencies(meta)
```

### File dependencies ###

Similarly track input file dependencies.  Since our paths can get quite long, strip off a prefix and keep those separately
```
RAWDIR='/project/projectdirs/desi/spectro/sim/alpha-5/'
REDUXDIR='/project/projectdirs/desi/spectro/redux/sjb/dogwood/'
INFIL000='{RAWDIR}/20150101/fibermap-00000002.fits'
INFIL001='{REDUXDIR}/20150101/frame-b2-00000002.fits'
```
Notes:
  * 3-digit nnn; BOSS thought 2 digits would be sufficient but got bitten on the coadd for one test plate with many many exposures...
  * Other naming options:
    * RAWDIR -> DATADIR?  RDATADIR?
    * some other way of separating out the common prefixes?
  * Should still allow absolute paths in case a test case input didn't come from a common prefix; FITS might truncate those if especially long

Add utility functions similar to the above to help manage these:
```
#- Adds INFILnnn=infile to meta
#- meta is dict-like header keyword object, e.g. FITS header or plain dict
io.meta.add_input_file(meta, infile)

#- Removes all INFILnnn from meta
io.meta.clear_input_files(meta)

#- Parses input files and returns list of fully expanded filepaths of input files
io.meta.get_input_files(meta)
```

### Other notes ###

We tend to pass forward the headers from the primary input, e.g. from pix to frame to cframe.  We should make sure to use `clear_code_dependencies()` and `clear_input_files()` so that we don't propagate dependencies from earlier stages.

The code dependencies could be automatically added by the `io.write_*` routines.  It seems like the input file dependencies will have to be added earlier by the code that reads in those files and calls the algorithms.

**Comment by sbailey** [comment]
Transferring this issue to the Pipeline v0.0 milestone.  It is optional for that software release, but it would be really nice to get in there.  Ideally this also would involve adding utility functions to desiutil for managing the DEPVER** keywords (add, remove, check if one is set...)

**Comment by sbailey** [comment]
DATASUM and CHECKSUM were added in PR #212.
Code dependencies were added in PR #220.
The remaining item here is file dependencies, but that is tracked separately as part of the pipeline planning.  I will leave this issue as closed, but if we think we need to track file dependencies differently, let's open a separate ticket dedicated to that.
