### ISSUE TITLE
pkg_resources deprecated; use importlib.resources instead

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2018]
We use `pkg_resources` in multiple places throughout the desi code repos, e.g. to find configuration files or yaml files for bitmasks.  Apparently that is now deprecated; see https://setuptools.pypa.io/en/latest/pkg_resources.html, which I learned about from esheldon/fitsio#360

We don't get that message using our latest desiconda environment at NERSC (python 3.10.8 with setuptools 65.6.3).

The suggested alternative is `importlib.resources`

@weaverba137 heads up

**Comment by moustakas** [comment]
@sbailey I can take this ticket, but do you want me to wait until after #2154 and #2155 are merged since I'll be touching many of the same files?
