### ISSUE TITLE
Slurm script for a tile TILEID not generated with desi_run_night --tiles TILEID

### ISSUE THREAD

**Issue by marcelo-alvarez** [desihub/desispec#2026]
The command
```
desi_run_night --dry-run-level 1 -n 20230210 --z-submit-types None --tiles 5627 --proc-obstypes SCIENCE --laststeps "skysub,all"
```
doesn't generate a tilenight slurm script for the requested tile, 5627.

This issue was first discovered by @sbailey in #2015. I suggest that we address this as the refactoring in #2021 and/or #2024, i.e. after Perlmutter becomes the default system for daily processing.

**Comment by akremin** [comment]
Can you elaborate on this issue? Rerunning tiles with `--tiles` is a routine part of the daily workflow when rerunning data. If there is a workaround, then we can discuss the use of the workaround as a stop-gap, but otherwise I don't think we can delay this to a future rewrite.

**Comment by marcelo-alvarez** [comment]
@akremin when running the following in an empty directory on Perlmutter:
```
source /global/common/software/desi/desi_environment.sh main
DESI_SPECTRO_REDUX=$PWD
SPECPROD=testprod
mkdir $SPECPROD
ln -s $CFS/desi/spectro/redux/daily/exposure_tables $DESI_SPECTRO_REDUX/$SPECPROD
desi_run_night -n 20230210 --z-submit-types None --tiles 5627 --proc-obstypes SCIENCE --laststeps "skysub,all"
```
no `$SPECPROD/run` directory is created.

I don't know why this is happening, but I'm surprised it hasn't come up during reprocessing on Perlmutter on days when Cori was down. I haven't looked into this, but if you find a workaround as a stop-gap, please go ahead and submit a PR for it; I agree that there is no need to delay this to a future rewrite. Thanks.
