### ISSUE TITLE
psfnight job can incorrectly claim success

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2039]
The psfnight job can have individual PSFs completely fail while still having the job claim SUCCESS and exit cleanly, which confuses job dependency tracking.  e.g. [$CFS/desi/spectro/redux/daily/run/scripts/night/20230509/psfnight-20230509-00179797-a0123456789-8611036.log](https://data.desi.lbl.gov/desi/spectro/redux/daily/run/scripts/night/20230509/psfnight-20230509-00179797-a0123456789-8611036.log):
```
ERROR:proc_joint_fit.py:220:main: Rank 16 specex.meanpsf failed for psfnight-r6-20230509.fits
ERROR:proc_joint_fit.py:223:main: Traceback (most recent call last):
  File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/proc_joint_fit.py", line 218, in main
    desispec.scripts.specex.mean_psf(psfs, psfnightfile)
  File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/specex.py", line 470, in mean_psf
    psf=fits.open(input)
  File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/astropy/io/fits/hdu/hdulist.py", line 214, in fitsopen
    return HDUList.fromfile(
  File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/astropy/io/fits/hdu/hdulist.py", line 482, in fromfile
    return cls._readfrom(
  File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/astropy/io/fits/hdu/hdulist.py", line 1222, in _readfrom
    raise OSError(
OSError: No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True
...
INFO:proc_joint_fit.py:655:main: All done at Wed May 10 07:36:36 2023
SUCCESS: done at Wed 10 May 2023 07:36:37 AM MST
```

**Comment by akremin** [comment]
My memory is a bit fuzzy but I believe the logic was that psfnight does it's own check that there are at least 3 psf's available for each camera, which is the smallest number we are comfortable using. The psfnight code is supposed to return FAILED if any of the cameras do not meet this threshold. All flat jobs depend on `afterok:<psfnightjobid>`, so a failure there would bring down the remainder of the night's jobs (as desired).

I.e. this allowed the pipeline to proceed if one camera (or even an entire exposure) was slow to compute or hung, with psfnight there as an additional safety net to ensure that when most arcs failed we were failing.

In modern times, we almost always rerun the night to use all psf's, so I am comfortable changing the logic here to `afterok`.

**Comment by sbailey** [comment]
Clarifying: afterany/afterok is a related by separate issue.  What I was trying to document here was that regardless of why the psfnight job ran, it had multiple ranks fail to produce output but still ending with "SUCCESS" and a job exit code of 0.  Changing afterany -> afterok would have prevented this job from running, which is what I would have wanted in this particular case, but regardless of that it seems that if the job fails to produce all of its intended output, the psfnight job itself should fail (and thus prevent flats from proceeding with the wrong PSFs).

**Comment by sbailey** [comment]
And the same for fiberflatnight, e.g. https://data.desi.lbl.gov/desi/spectro/redux/daily/run/scripts/night/20230512/nightlyflat-20230512-00180255-a0123456789-8720904.log only suceeded on 10/30 nightly flats, but the job still exited cleanly with "SUCCESS: done at Fri 12 May 2023 10:29:37 PM MST"

**Comment by MikeLampton** [comment]
Unsubscribe me .... I retired years ago... Mike
