### ISSUE TITLE
redmonster crash on zero fluxes

### ISSUE THREAD

**Issue by ngbusca** [desihub/desispec#204]
@timahutchinson 

When running redmonster on the zdc2 bricks, I get a crashe when some of the spectra have zero flux. I've traced the problem to file 

redmonster/python/redmonster/physics/zfinder.py

when a flux is zero for a given spectrum, the fits are skipped (zwarning set to unplugged) but the lists  sn2_data, f_nulls and chi2_null aren't increased in size . In this case, for the following fiber, the code tries to index these lists past their size.

I've tried the following git diff, but then other problems show up further down (seemingly in zpicker2.py)

diff --git a/python/redmonster/physics/zfinder.py b/python/redmonster/physics/zfinder.py
index 314ccf8..aa2c581 100644
--- a/python/redmonster/physics/zfinder.py
+++ b/python/redmonster/physics/zfinder.py
@@ -133,6 +133,9 @@ class ZFinder:
             # zwarning flags and don't bother with doing fit
             if len(n.where(specs[i] != 0.)[0]) == 0:
                 self.zwarning[i] = int(self.zwarning[i]) | flag_val_unplugged
+               self.sn2_data.append(0)
+               self.chi2_null.append(-1)
+               self.f_nulls.append(0)
             else: # Otherwise, go ahead and do fit
                 for ipos in xrange(self.npoly):
                     bvec[ipos+1] = n.sum( poly_pad[ipos] * data_pad[i] *

**Comment by timahutchinson** [comment]
I'll look into this first thing tomorrow morning.

**Comment by moustakas** [comment]
@timahutchinson Has this been fixed?

**Comment by timahutchinson** [comment]
Yes, I believe it was fixed.
