### ISSUE TITLE
MEAN_FIBER_RA,MEAN_FIBER_DEC: mean computed with some non-valid values

### ISSUE THREAD

**Issue by araichoor** [desihub/desispec#2046]
Copy-pasting https://desisurvey.slack.com/archives/C2AT2NEHY/p1684528715042649:

the issue is that in some exposures, `FIBER_{RA,DEC}=0` for whatever reason, and apparently `MEAN_FIBER_{RA,DEC}` uses those in the computation, hence ending with ~non-sense values..
example with one fuji file:
```
fn = "/global/cfs/cdirs/desi/spectro/redux/fuji/zcatalog/zpix-sv3-dark.fits"
d, e = Table.read(fn, "ZCATALOG"), Table.read(fn, "EXP_FIBERMAP")
sel = (d["COADD_FIBERSTATUS"] == 0) & (np.abs(d["MEAN_FIBER_RA"] - d["TARGET_RA"]) > 1)
sel.sum()
d["TARGETID", "COADD_FIBERSTATUS", "TARGET_RA", "MEAN_FIBER_RA", "COADD_NUMEXP"][sel][:5]
```

returns:

```
4096
     TARGETID     COADD_FIBERSTATUS     TARGET_RA        MEAN_FIBER_RA    COADD_NUMEXP
      int64             int32            float64            float64          int16    
----------------- ----------------- ------------------ ------------------ ------------
39627805364850503                 0 150.17318166142363 137.65874163244868           12
39627811404647604                 0 150.15253184951817 131.38347189564968            8
39627805369044515                 0 150.40749740772065 138.83769495536356           13
39627811408841765                 0 150.39695082153526 125.33080368119363            6
39627805369042455                 0  150.3238465769502 120.25908829660841            5
```

and if I take as example the first targetid `39627805364850503`, `expid=87354` is the culprit.
the ra is 11/12*150~137.
```
tid = d["TARGETID"][sel][0]
e[e["TARGETID"] == tid]["TARGETID", "FIBERSTATUS", "PLATE_RA", "FIBER_RA", "EXPID", "NIGHT", "TILEID", "FIBER"]

     TARGETID     FIBERSTATUS      PLATE_RA           FIBER_RA      EXPID  NIGHT   TILEID FIBER
      int64          int32         float64            float64       int32  int32   int32  int32
----------------- ----------- ------------------ ------------------ ----- -------- ------ -----
39627805364850503           0 150.17318166142363 150.17318168112703 83714 20210406      1   153
39627805364850503           0 150.17318166142363 150.17318168112703 83715 20210406      1   153
39627805364850503           0 150.17318166142363 150.17318168112703 83716 20210406      1   153
39627805364850503           0 150.17318166142363 150.17315777179238 85185 20210417      6   195
39627805364850503           0 150.17318166142363 150.17314192209815 85186 20210417      6   195
39627805364850503           0 150.17318166142363 150.17319785211862 86612 20210429      7   159
39627805364850503           0 150.17318166142363  150.1731776529425 86731 20210430      8    93
39627805364850503           0 150.17318166142363  150.1731776529425 86732 20210430      8    93
39627805364850503           0 150.17318166142363 150.17318568499311 87353 20210505     11   188
39627805364850503           0 150.17318166142363                0.0 87354 20210505     11   188
39627805364850503           0 150.17318166142363   150.173158004558 87593 20210507    442   497
39627805364850503           0 150.17318166142363   150.173158004558 87594 20210507    442   497
```

this small test kind of assesses that is the reason: if I further restrict to targetids which have FIBER_RA!=0, I don t get any more discrepancy:
```
black_tids = np.unique(e["TARGETID"][e["FIBER_RA"] == 0])
sel2 = (sel) & (~np.in1d(d["TARGETID"], black_tids))
sel2.sum() # => returns 0
```

**Comment by stephjuneau** [comment]
@araichoor do you know how many targets in Fuji suffer from this issue?

**Comment by araichoor** [comment]
I think I find 15k-20k according if I apply or not the COADD_FIBERSTATUS=0 cut.
I identify those with `(e["FIBER_RA"] == 0) & (e["FIBER_DEC"] == 0)` in the `EXP_FIBERMAP` extension.
and those are in: zpix-sv1-bright, zpix-sv1-other.fits, and zpix-sv3-dark.fits only.

note that I only checked the `zpix*fits` catalogs.
here s the code:

```
fns = sorted(glob("/global/cfs/cdirs/desi/spectro/redux/fuji/zcatalog/zpix*.fits"))
for i, fn in enumerate(fns):
    d, e = Table.read(fn, "ZCATALOG"), Table.read(fn, "EXP_FIBERMAP")
    dubious_tids = np.unique(e["TARGETID"][(e["FIBER_RA"] == 0) & (e["FIBER_DEC"] == 0)])
    if dubious_tids.size > 0:
        cfsok = d["COADD_FIBERSTATUS"] == 0
        isdubious = np.in1d(d["TARGETID"], dubious_tids)
        dras, ddecs = np.abs(d["TARGET_RA"] - d["MEAN_FIBER_RA"]), np.abs(d["TARGET_DEC"] - d["MEAN_FIBER_DEC"])
        for sel, lab in zip(
            [isdubious, (isdubious) & (d["COADD_FIBERSTATUS"] == 0), ~isdubious],
            ["dubious", "dubious_cfs0", "not_dubious"]
        ):    
            print("{}\t{}\t{}\t{:.2f}\t{:.2f}".format(os.path.basename(fn), lab, sel.sum(), dras[sel].max(), ddecs[sel].max()))
```
returns:

```
# FN SAMPLE NOBJ DRA_MAX DDEC_MAX
zpix-sv1-bright.fits	dubious	        5000	36.20	0.55
zpix-sv1-bright.fits	dubious_cfs0	4236	36.20	0.54
zpix-sv1-bright.fits	not_dubious	234057	0.24	0.04	# <= sanity check
#
zpix-sv1-other.fits	dubious	       9000	122.76	28.20
zpix-sv1-other.fits	dubious_cfs0	7304	122.76	28.20
zpix-sv1-other.fits	not_dubious	134464	0.08	0.04	# <= sanity check
#
zpix-sv3-dark.fits	dubious	        4981	75.91	1.88
zpix-sv3-dark.fits	dubious_cfs0	4096	75.90	1.88
zpix-sv3-dark.fits	not_dubious	857966	0.12	0.04	# <= sanity check
```

**Comment by araichoor** [comment]
btw, in my test above, I should also have checked for DRA_MIN and DDEC_MIN for the dubious cases: I confirm those min. values are dubious (ie DRA_MIN > 5).

I guess that we don t want to change any catalog so close to the release: couldn t we just add this as a known issue, with providing a list of the affected TARGETIDs?

**Comment by stephjuneau** [comment]
Hi @araichoor (Cc @weaverba137, @geordie666, @sbailey), looking into the difference between TARGET_RA and MEAN_FIBER_RA and my naive expectation would be that those would be very similar to within a fraction of an arcsecond given the DESI fibers are only 1.5" in size. While this is try for the vast majority, the number with deviations larger than +/- 2.5" is ~500k in EDR, and after only considering OBJTYPE='TGT' and ZWARN=0, the number goes down to 112k which is still quite significant compare to the ~15k-20k with extreme differences on the degree scale. Here are two plots for dRA = TARGET_RA - MEAN_FIBER_RA with the top panel in degrees(!) and the bottom panel in arcsec. Is this expected? 
<img width="338" alt="image" src="https://github.com/desihub/desispec/assets/26126576/8e3b0d58-7fa1-4fbf-88d9-ec7f3b1b5ab9">

**Comment by stephjuneau** [comment]
Hmmm so the cases with abs(dRA)>1" have suspiciously high values of STD_FIBER_RA 

<img width="341" alt="image" src="https://github.com/desihub/desispec/assets/26126576/f6e14333-4f21-4acb-aa87-1cee2c5a7ea0">

**Comment by araichoor** [comment]
for what is worth, for book-keeping, in the code, the FIBER_RA,DEC=0 seem to be set here, when there s no platemaker information: 
https://github.com/desihub/desispec/blob/751f3fdaccdec45d8e7a1bc319b4f981995d7878/py/desispec/io/fibermap.py#L855-L861
