### ISSUE TITLE
DESI_BASIS_TEMPLATES or mention the test data 

### ISSUE THREAD

**Issue by rainwoodman** [desihub/desispec#207]
The integration test needs DESI_BASIS_TEMPLATES to run. It is not mentioned in desispec documentation. A google search suggests installing https://github.com/desihub/desisim-testdata may help -- but would be nice if this is actually mentioned in the README file or in the error message of desispec's integration test.

**Comment by sbailey** [comment]
Agreed with the basic point.  For the record, desisim-testdata is sufficient for basic testing, but not for actually using desispec for real work, which requires a full copy of the templates, e.g. at NERSC `/project/projectdirs/desi/spectro/templates/basis_templates/v2.2` .  This is mentioned at https://desi.lbl.gov/trac/wiki/Pipeline/Install but the documentation in desisim itself should be more helpful about that.

**Comment by rainwoodman** [comment]
What about adding a section in README with a link to https://desi.lbl.gov/trac/wiki/Pipeline/Install in each piece of the pipeline software?

**Comment by weaverba137** [comment]
The documentation here addresses this problem: https://desi.lbl.gov/trac/wiki/Pipeline/Install#SetNecessaryEnvironmentVariablesandData
If this is insufficient, please open a new issue with specific concerns.
