### ISSUE TITLE
Explore Jenkins infrastructure at NERSC for integration tests.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#208]
In order to help close desihub/desiutil#29, I am opening a separate issue to track Jenkins development at NERSC.  The primary contact at NERSC is Douglas Jacobsen dmjacobsen@lbl.gov.

**Comment by sbailey** [comment]
I don't think NERSC will ever deploy Jenkins as a primary service.  Travis + NERSC cronjobs are doing fine for now.  Closing.
