### ISSUE TITLE
Does fibermap table need an INDEX column?

### ISSUE THREAD

**Issue by dkirkby** [desihub/desispec#214]
(I am copying this from my email inbox so it doesn't get lost.  The original was [desi-data 1887].)

Can you clarify the roll of the INDEX column that you add to the fibermap table when creating the brick files (in desispec.brick.BrickBase)?  The comment is "Index of this object in other HDUs", but it appears that it is always just the row number.  Is there ever a case where the fibermap needs to be out of order compared to the other HDUs such that the index tracking would be necessary?

If the brick fibermap can always be row-matched to the FLUX, IVAR, etc. HDUs, then it seems simpler to define that it is row matched and drop the INDEX column.

This question came up when Nicolas was creating brick files from BOSS data and wondering what to fill in for the INDEX column.  I think the answer for the current code is np.arange(numspectra).

**Comment by sbailey** [comment]
The conclusion was that that wasn't needed and it was removed awhile ago and it didn't break anything that we have noticed, so I'm closing this ticket.

**Comment by sbailey** [comment]
Reopening; it appears that the INDEX column is still there and doesn't need to be.

**Comment by sbailey** [comment]
Reclosing; INDEX is gone.
