### ISSUE TITLE
potential upper vs lower case conflict in camera name in the header

### ISSUE THREAD

**Issue by gdhungana** [desihub/desispec#215]
Generating pix file from raw image using pixsim-desi using --preproc option has the camera in upper case in the header. e.g 'R0', while earlier, direct generation of pix files (not through raw and then preprocess), it was lower case like 'r0'. This is resulting the bootcalib to not be able to find the lamp lines for that camera as it requires lower case name convention. As a cross check, using camera=header["CAMERA"].lower() in line 183 of desispec/scripts/bootcalib.py solved the issue from the top level, and there are certainly other ways to fix this. This happened in particular, while using python 2.7.6, and may not be the case for later versions.  But I thought I'd open an issue.

**Comment by sbailey** [comment]
Thanks for bringing this up.  I chatted with Klaus and we agreed to standardize on the keyword CAMERA having lowercase names, e.g. b0, r1, z9 and not B0, R1, Z9.  The latest master of desisim/desispec does this, though I haven't looked up which commit fixed it.  It wouldn't hurt for anything reading in a camera name to pass it through .lower()  just in case, but in principle that shouldn't be necessary.

I'll submit a PR in a moment that adds some .lower() calls in case a file was previously generated with upper case names or if a user passes in a upper case camera name to one of the routines.

**Comment by gdhungana** [comment]
@sbailey Sorry for delay. Yes the latest master already seems to have fixed that particular issue but this seems to be even more explicit. I did generate run some simulation +QL pipeline yesterday and all ran fine. As long as it is lower, we are all okay on the QL front as well. Please proceed with merging and close this as you do so. Thanks.
