### ISSUE TITLE
MgII afterburner broken due to recent redrock change

### ISSUE THREAD

**Issue by moustakas** [desihub/desispec#2167]
@sbailey I'm surprised we haven't seen this crash in the daily pipeline yet, but I'm fairly certain that https://github.com/desihub/redrock/pull/271 broke the MgII after-burner by removing the `template_dir` argument of `redrock.find_templates` (see [here](https://github.com/desihub/redrock/pull/271/files#diff-cb77484e5becf510c166b87f21fcfc65025d126948a8409bba13bc49af75d729L196)), which is used by `desispec.mgii_afterburner.load_redrock_templates` [here](https://github.com/desihub/desispec/blob/main/py/desispec/mgii_afterburner.py#L46). 

I can easily fix this in a PR but there are a few different ways of doing so. First, do you want me to fix this in `redrock` or `desispec`? And if in `redrock`, do we want to add backwards compatibility for the `template_dir` argument?

**Comment by akremin** [comment]
@moustakas the pipeline hadn't tripped over it because we have had bad weather recently and haven't had any science data since the change. 

I think we should proceed with modifying the mgii code in desispec given that Stephen's change was probably an intentional refactor.

I will submit a PR and self merge.

**Comment by akremin** [comment]
This is fixed via desispec in PR #2168

**Comment by sbailey** [comment]
Ugh, apologies for breaking this with a cosmetic fix as part of the Redrock templates refactor.  Thanks to the attention/debugging from @moustakas and @abhi0395 and for the weekend fix from @akremin .  My penance shall be to write a unit test that would have caught the incompatibility in the first place.
