### ISSUE TITLE
qproc not using fallback option for calibrations in 2-ch readout

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desispec#2203]
In tests of 2-ch CCD mode starting on 20240324, `qproc` raised exceptions for r4, r6, r7, and z7 due to calibration darks not being found. However, @julienguy created new darks in `DESI_SPECTRO_CALIB` and `qproc` should have found and used those since it has the `--fallback-on-dark-not-found` option enabled.

The error was "fixed" at KPNO using the following steps:

- unset `DESI_SPECTRO_DARK`
- undefined `DESI_SPECTRO_DARK` in `${DESI_PRODUCT_ROOT}/modulefiles/desispec/main` and `${DESI_PRODUCT_ROOT}/modulefiles/desimodules/main`.
- restarted the `nwctl` daemon

Processing is proceeding normally at KPNO but exceptions are still being raised at NERSC for the 2-ch mode.

The option `--fallback-on-dark-not-found`should cause `qproc` to transparently find the right calibration files in `DESI_SPECTRO_CALIB` and not raise exceptions even if calibrations are not present in `DESI_SPECTRO_DARK`. The cause is under investigation.

**Comment by Waelthus** [comment]
one (maybe obvious) thing to note here: when we use that fallback option, all DARK/BIAS frames will be taken from the DESI_SPECTRO_CALIB defaults, instead of using more recent darks. 
On NERSC things seem to run nominally again, picking up the DESI_SPECTRO_DARK calibs. If you point me to where things didn't fall-back when a working DESI_SPECTRO_CALIB was there, but not the correct DESI_SPECTRO_DARK dark/bias models I'll happily look at why the fallback fails...

**Comment by sybenzvi** [comment]
Noting here that I have updated `DESI_SPECTRO_DARK` at KPNO and re-enabled the environment variable for qproc.

I confirm that when `DESI_SPECTRO_DARK` is defined, `qproc` does not find the appropriate calibration data in `DESI_SPECTRO_CALIB`. It only worked at KPNO once I rsynced `DESI_SPECTRO_DARK` from NERSC.

**Comment by Waelthus** [comment]
ok, I think I found a potential cause, namely when `raw.py` inits a new calibfinder after the actual preprocessing happened. Can you test the PR?

**Comment by sybenzvi** [comment]
> ok, I think I found a potential cause, namely when `raw.py` inits a new calibfinder after the actual preprocessing happened. Can you test the PR?

Yes, trying now.

**Comment by Waelthus** [comment]
ah, but that error is different. Added the option to inits in qproc as well in the PR, but if there's more things appearing it might be easier to reverse the meaning and make only the offline pipeline call an option to let things fail...
Anyway, you can test again, but I'll not be available until tomorrow morning CET.
