### ISSUE TITLE
rz7 has bad CTE starting in ~January 2024

### ISSUE THREAD

**Issue by schlafly** [desihub/desispec#2215]
r7 and z7 have fairly significant CTE for which we could do a better job.  As a reminder, we do the following things for CTE:
1. Nothing.
2. Constant offset applied to affected area in sky subtraction.  (OFFCOLS in the DESI_SPECTRO_CALIB yaml files)
3. CTE modeling & subtraction (CTECOLS in the DESI_SPECTRO_CALIB yaml files)

We are currently treating these petals with option (2).  We could change to option (3), but that uses a CTE "transfer" function that isn't great for r7 and z7.  Anand and I looked at a more complicated CTE transfer model and were able to get a better correction, but we would only want to turn it on on these devices.  That means expanding the CTE calibration file data model to allow the specification of different transfer functions, and expanding the yaml files to allow specifying a transfer function.

**Comment by sbailey** [comment]
Fixed by new models implemented in PR #2221
