### ISSUE TITLE
Identify when Fiber 3987 stopped working. It no longer passes light as of 04/09 and likely for some period before that

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2225]

**Comment by julienguy** [comment]
This fiber was lost during the summer 2021. I am adding it to the list of broken fibers in DESI_SPECTRO_CALIB.
Fiber 3986 also got a low transmission but can still be used (relative transmission value of 0.45).
 
```
ds9 /global/cfs/cdirs/desi/spectro/redux/daily/preproc/20210702/00096960/preproc-b7-00096960.fits /global/cfs/cdirs/desi/spectro/redux/daily/preproc/20210916/00100436/preproc-b7-00100436.fits
```
![Screenshot from 2024-04-26 09-34-59](https://github.com/desihub/desispec/assets/5192160/335606a2-2c74-41c8-b6ca-1266294be0ce)

**Comment by julienguy** [comment]
Updated `$DESI_SPECTRO_CALIB/spec/sm8/sm8-{b,r}.yaml` . It was already set as broken in `sm8-z.yaml`.

**Comment by moustakas** [comment]
@ashleyjross I don't see this fiber in the list of veto'd bad fibers for the LSS analysis--
https://data.desi.lbl.gov/desi/survey/catalogs/Y1/LSS/iron/unique_badfibers.txt

Just a note.

**Comment by ashleyjross** [comment]
It appears this fiber is associated with a positioner we had only been using for stuck sky. (All targetids are negative in the iron tiles redshift catalog.)

3986 also became only used for stuck sky. The last night that it had a positive targetid was 20211015 and 2514/2720 of its targetids are negative in the iron tiles redshift catalog.
