### ISSUE TITLE
Include 3 and 10 s flat fields in desi_fit_cte_night

### ISSUE THREAD

**Issue by schlafly** [desihub/desispec#2227]
Currently this bit of code passes the 1 and 120 s flats to the desi_fit_cte_night script
https://github.com/desihub/desispec/blob/4f8da2232f984349ea7f6a9d448a696bc1378adb/py/desispec/scripts/proc_night.py#L656-L663
We now additionally take 3 and 10 s flats; it would be good to make these available to desi_fit_cte_night as well by including these exposure ids.

**Comment by akremin** [comment]
This was solved in PR #2221
