### ISSUE TITLE
tune tilenight vs. numexp jobtime

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2237]
Jura tilenight jobs with many exposures are timing out, e.g. tiles 80721 and 80687 on 20210305.  Review the jobtime vs. number of exposures scaling and adjust.

**Comment by weaverba137** [comment]
Here is a preliminary analysis of job runtime versus number of exposures for two job types in `k1`. The code to reproduce the plot will be posted shortly.

![k1_job_runtime](https://github.com/user-attachments/assets/3ca2c908-e80f-463d-a33c-3e3a84b5ee87)

**Comment by weaverba137** [comment]
Code and data are posted to `$DESI_ROOT/users/bweaver/k1`. There is a Jupyter Notebook, the above PNG figure and a CSV file with the data in the figure.

**Comment by sbailey** [comment]
Thanks; using `desispec.workflow.desi_proc_funcs.determine_resources(ncameras=30, jobdesc='tilenight', nexps=nexps, system_name='perlmutter-gpu')`, I overlaid the tilenight runtimes (black squares) with the default tilenight job runtime limit (red line):

![Image](https://github.com/user-attachments/assets/6426eddf-137b-4d54-a1ea-cef7d1138efa)

It looks like our model is conservative and the timeouts from Jura were just bad luck.

For the non-trend in the ztile cumulative jobs, my interpretation is that the runtime is *not* dominated by the coaddition and QA steps, which could vary with runtime, but instead are dominated by steps that fit the coadd (e.g. redrock and afterburners), since those steps don't depend upon the number of input exposures.  I think the apparent extra scatter of the n=1 compared to n=2 and n=3 is just that there are far more n=1 points and thus we can sample the tail more effectively.  For ztile cumulative jobs, our default max runtime is 25 minutes independent of nexp.
