### ISSUE TITLE
Deal with varying readnoise in SM6 b3.

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#2249]
SM6 b3 has had a peculiar noise since the beginning of the survey with the noise level jumping from 3.5 to 9 electrons for some rows.
We haven't done anything about it so far, but it would be an improvement to measure and record this increased readnoise for the affected CCD rows.

![Screenshot from 2024-05-10 14-04-03](https://github.com/desihub/desispec/assets/5192160/25689c6b-e7a9-4cf7-a02e-4f7c9dabbf36)

**Comment by akremin** [comment]
Closed with PR #2314
