### ISSUE TITLE
N(z) K-S test to identify bad fibers in jura

### ISSUE THREAD

**Issue by rongpu** [desihub/desispec#2283]
Repeat the exercise in issue #1946, I have identified the following 15 fibers in jura with K-S test p-value less than 1e-4 for either BGS (14 fibers) or LRG (10 fibers):
466, 551, 552, 553, 725, 1008, 1098, 3234, 3235, 3250, 3504, 3969, 3994, 4720, 4891

Below are redshift vs date plots for these fibers:

FIBER 466
BGS
![image](https://github.com/desihub/desispec/assets/16765087/485f0f1e-7801-4af4-9a98-dc8d41dd031a)

FIBER 551
BGS
![image](https://github.com/desihub/desispec/assets/16765087/cf70cb5a-fd05-4084-ad32-cd0ac4136233)

FIBER 552
BGS
![image](https://github.com/desihub/desispec/assets/16765087/bf44a8e7-d795-47c8-8e58-c573dd49cb09)
LRG
![image](https://github.com/desihub/desispec/assets/16765087/4d203e21-56cf-4d95-af52-6d1cfc356529)

FIBER 553
BGS
![image](https://github.com/desihub/desispec/assets/16765087/44553552-a3b6-4b2d-bf1c-594b8c2f6824)
LRG
![image](https://github.com/desihub/desispec/assets/16765087/d919c3d1-8f1a-4e12-9117-75f477449766)

FIBER 725
LRG
![image](https://github.com/desihub/desispec/assets/16765087/2ea5d4af-c3ff-46d2-a460-ac15af4a3e53)

FIBER 1008
BGS
![image](https://github.com/desihub/desispec/assets/16765087/de6a1122-e6fe-42df-9aa3-18d6e14d3aa7)
LRG
![image](https://github.com/desihub/desispec/assets/16765087/d25df717-ecdb-47f4-af07-54d30fa3346f)

FIBER 1098
BGS
![image](https://github.com/desihub/desispec/assets/16765087/43d77c74-fc09-4cb0-8b56-2eca47d50ed6)

FIBER 3234
BGS
![image](https://github.com/desihub/desispec/assets/16765087/a8c4aa1c-9dc6-4762-9365-2151e7511fd5)
LRG
![image](https://github.com/desihub/desispec/assets/16765087/b9274a57-e053-4018-820e-e972cbcb639c)

FIBER 3235
BGS
![image](https://github.com/desihub/desispec/assets/16765087/a5968c7f-0e97-4219-9804-c5917bd6c2b8)
LRG
![image](https://github.com/desihub/desispec/assets/16765087/4bbe86ed-ee0b-4ba6-bf8e-9897c0c5feee)

FIBER 3250
BGS
![image](https://github.com/desihub/desispec/assets/16765087/b8977aca-5c4d-4e86-9d5f-774f4f0e141a)
LRG
![image](https://github.com/desihub/desispec/assets/16765087/da63cc20-ab19-47ea-aefb-540b68e76d4c)

FIBER 3504
BGS
![image](https://github.com/desihub/desispec/assets/16765087/9368560b-8376-4104-97c6-b19eb5ca5a30)
LRG
![image](https://github.com/desihub/desispec/assets/16765087/da6766ad-92bd-4514-be8f-ee25ed753463)

FIBER 3969
BGS
![image](https://github.com/desihub/desispec/assets/16765087/7ca9c252-6c80-46cc-b736-45c5e2746e76)
LRG
![image](https://github.com/desihub/desispec/assets/16765087/a2176408-b1a6-4edf-942d-ba71c14c661c)

FIBER 3994
BGS
![image](https://github.com/desihub/desispec/assets/16765087/003479f9-294d-4b8e-a264-e7467ceb1a0a)
LRG
![image](https://github.com/desihub/desispec/assets/16765087/ff291439-e79b-40f9-a6f9-5687267b26eb)

FIBER 4720
BGS
![image](https://github.com/desihub/desispec/assets/16765087/2a711cf5-a945-42b1-a04a-7489e8b1d17f)

FIBER 4891
BGS
![image](https://github.com/desihub/desispec/assets/16765087/81370c5d-23c8-4e5e-b602-a7cb140fe7b8)

**Comment by rongpu** [comment]
If I run the same test on the ELGs without the OII quality cuts, the K-S test finds 129 fibers with p-value below the (more restrictive) threshold of 2e-6. This large number of "bad" fibers are perhaps expected since 20-30% of the ELG targets are low-S/N featureless spectra, and their redshifts can be sensitive to subtle CCD defects (which can otherwise be ignored for any spectrum with reasonable S/N). Still there might be useful information in their redshift vs date plots, and they can be found here:
https://data.desi.lbl.gov/desi/users/rongpu/redshift_qa/nz_ks_test/bad_fibers_from_nz-elg-zcatalog.html

Alternatively we can simply look at ELG spectra that pass the OII cuts (here instead of zcatalog, I use Ashley's LSS catalog which includes the OII columns). This flags 10 fibers with p-value<1e-4:
551, 1261, 1269, 1295, 1659, 1971, 1972, 2246, 3234, 3359
Since the OII cuts already removed most of the spurious redshifts, this list is almost certainly an incomplete list of fibers with low ELG redshift efficiency. The redshift vs date plots can be found here: https://data.desi.lbl.gov/desi/users/rongpu/redshift_qa/nz_ks_test/bad_fibers_from_nz-elg-lss_catalog.html

**Comment by rongpu** [comment]
Julien and I have looked into some of the fibers. Here are the preliminary conclusions:

**466**: already flagged in Y1. Nothing obvious. ~20% low flat field.
**551-553**:  The beginning of a CTE charge trap (tracked by [this issue](https://github.com/desihub/desispec/issues/2286)).
**725**: z1 CTE in CCD_X range 543:2057 and fiber at X=1878 (should have affected other fibers if caused by CTE). No redshift outliers in 2024 after we replaced the CCD. This issue is not understood yet.
**3234-3254**: r6 CTE first detected on May 21, 2023; we switched to 2-amp mode on March 25, 2024. Software correction for CTE in place with simple sector offset; this correction might be not sufficient. CCD_X range of CTE correction: 1905-2057; this corresponds to fibers 3234-3253(?). We also see the CTE pattern in the dark.
**3504**: appears to be a bad column in the dark at CCD_X=177:178 (the fiber is centered at 174) in r7; the two bad columns have no signal in the flats (see below). The resulting spurious redshifts first appeared after summer 2022. **Action item: mask the two bad columns.**
Below: Left: dark; right: flat
![image](https://github.com/user-attachments/assets/f59808d9-57d3-41c1-a674-5424c446d3b5)

**3969**: Also at the beginning of a CTE charge trap (similar to fibers 551-553) in z7 amp B (as has already been documented). CCD_X=2057:3724 (the fiber is centered at 3719).

**Summary: all the above issues were related to charge traps, except for fibers 725 (unknown issue) and 3504 (due to unmasked bad columns).**

Remaining fibers to look at (all of them were also identified in the Y1 iron): 466, 1008, 1098, 3994, 4720, 4891. Need to understand fiber 725 too.

**Comment by rongpu** [comment]
Julien and I have gone through all the fibers. Here are our findings (and the fixes that we have implemented for some of the fibers). Some of the information might be redundant with my previous post.

**466**: already flagged in Y1. Nothing obvious. ~20% low flat field.
Good PSF, spectra trace, nothing wrong in bias, dark, pixel flat, pixel mask, fiber flat
Can’t be variation of fiber tip alignment because it would be mostly achromatic and we see a rather strong chromatic effect in the blue. This fiber is on the edge of the focal plane but the neighboring fiber 465 does not have any issue.
Example BGS spectrum:
![image](https://github.com/user-attachments/assets/fbf14de7-bf7e-4592-babd-9db474916958)
(jura/tiles/cumulative/20946/20221205/coadd-0-20946-thru20221205.fits)

**551-553**: The beginning of a CTE charge trap (tracked by https://github.com/desihub/desispec/issues/2286).

**725**: the fiber trace lies on top of a vertical band of excess charge (~15 elec) in z1 amplifier A that we see in master bias frames (probably induced by the parallel clocking at the transfer gate?). This excess charge is fluctuating a bit during the night causing offsets in the spectra. We don’t think it requires masking out the CCD column. We suggest only flagging the fiber for the LSS catalog.
![image](https://github.com/user-attachments/assets/6ec71872-5837-420d-a32f-d8934b372319)

**1008**: charge trap along the parallel at CCD_X=190, CCD_Y=1901 that was not sufficiently masked. We have now fixed this by extending the size of the mask. This fix has been pushed to SVN.

**1098**: symptom: discontinuity between blue and red caused by excess flux in blue (see example spectrum below). No signal of any problem in bias,dark,flat,psf. Related to TPCORR parameter in BLUE which could be the cause or another symptom.
We could test this by rerunning the sky modeling without the tpcorr.
Example BGS spectrum:
![image](https://github.com/user-attachments/assets/aac9a754-7d03-43b6-975a-e38bd18c4564)
(jura/tiles/cumulative/21315/20231125/coadd-2-21315-thru20231125.fits)

Seen as outlier in TPCORR blue only (see below for other cases)
![image](https://github.com/user-attachments/assets/da25f988-ea38-4193-aa6a-09f475e52bb4)

**3234-3254**: r6 CTE first detected on May 21, 2023; we switched to 2-amp mode on March 25, 2024. Software correction for CTE in place with simple sector offset; this correction might be not sufficient. CCD_X range of CTE correction: 1905-2057; this corresponds to fibers 3234-3254. We also see the CTE pattern in the dark.
Possible correction using the complex CTE model from Eddie (or we simply flag the fibers in LSS catalog).

**3504**: appears to be a bad column in the dark at CCD_X=177:178 (the fiber is centered at 174) in r7; the two bad columns have no signal in the flats (see below). The resulting spurious redshifts first appeared after summer 2022. We masked the two bad columns and committed in SVN.

**3969**: Also at the beginning of a CTE charge trap (similar to 551-553) in z7 amp B (as has already been documented). CCD_X=2057:3724 (the fiber is centered at 3719).

**3994**: we suspect that it's a problem with tpcorr, because this fiber is an outlier in tpcorr parameters in R camera but not in B camera (and we expect them to be consistent as the tpcorr correction should be achromatic).
![image](https://github.com/user-attachments/assets/5bdabfb4-926c-4852-ab69-baebed2bc0aa)
We could rerun sky subtraction without tpcorr.
Example BGS spectrum:
![image](https://github.com/user-attachments/assets/37524a27-e42a-43c9-8449-adcad167332f)
(jura/tiles/cumulative/24983/20220313/coadd-7-24983-thru20220313.fits)

**4720, 4891**: We are also finding large TPCORR values for those fibers. For 4891, the values are mostly identical for all cameras. For 4220, we find a large TPCORR value only in r band. 
- For those 3 fibers (including 3994), a possible cause is that the tip the fiber is such that the amount of light collected in the fiber varies from exposure to exposure.
- Or, the tpcorr parameters have some noise that we could probably fix.
![image](https://github.com/user-attachments/assets/2ee808af-b31a-45f0-ae8c-808f3ecb6983)
Note that he steps we see as a function of fiber correspond to a smooth radial variation in the focal plane:
![image](https://github.com/user-attachments/assets/0dd90433-ee8f-43f0-b468-7970f3377129)

**Comment by sbailey** [comment]
Summary from @rongpu's 2024-07-23 data telecon presentation, slightly augmented from discussion
* CTE-related and not-yet-fixed
  * 551-553, 3969: Edge effects; add a new FIBERSTATUS bit
  * 3234-3254: Try turning on Simplified Regnault model, OFFCOLS -> CTECOLS
* Suspected TPCORR issue: 1098, 3994, 4720, 4891 - add new FIBERSTATUS bit
* Fixed since jura: 3504 (bad column; now masked); 1008 (insufficient masking of CTE in jura)
* Cannot be fixed: 725 (hot column)
* Causes unknown: 466

**Comment by julienguy** [comment]
Fiber 466 is among the fibers with the largest spatial throughput correction 'TPCORR' ( achromatic throughput correction as a function of positioner move x,y). I see the correction is exactly the same in B,R,Z. But maybe it shouldn't?

![Screenshot from 2024-07-23 14-03-24](https://github.com/user-attachments/assets/fed0ebee-3189-4b20-9e83-37045be60bf1)

**Comment by rongpu** [comment]
@schlafly pointed out that there are problems with fibers 918-921 that were identified from Tertiary 37. It's also causing spurious LRGs redshifts starting ~Jan 2024 (see below). They were not flagged by the K-S test presumably because only a small portion of the data was affected.

FIBER 918
![image](https://github.com/user-attachments/assets/8ccbf543-1afd-4675-b46d-10baa5927d68)

FIBER 919
![image](https://github.com/user-attachments/assets/76e8763c-b3e1-4ea1-9662-07467c14f75e)

FIBER 920
![image](https://github.com/user-attachments/assets/4f25f490-0ee3-41d2-8761-3ffee134ab12)

FIBER 921
![image](https://github.com/user-attachments/assets/1428609a-1d71-4939-bf09-099e59e82f8b)

**Comment by araichoor** [comment]
I ve not followed all the details in this ticket, but if useful / complementary:
I ve generated for all jura exposures these diagnosis plots using the sky spectra, and looking for offsets between amplifiers.
(presented here: https://github.com/desihub/desispec/issues/2193#issuecomment-1993045663)

those 918-921 fibers likely are the "spike" in red dots here, for 20240304 (reaching the y=1 line):
<img width="1293" alt="Screenshot 2024-07-25 at 4 20 54 PM" src="https://github.com/user-attachments/assets/1567ad9b-9c8f-4e13-b97d-58d046cc4c39">

@rongpu: it may be worth it to check few fibers around those values, as this "918-921" comes from tertiary37, where the stats are not great.

pdf files here (those are heavy, 100-400M each!):
https://data.desi.lbl.gov/desi/users/raichoor/spectro/jura/peramp-medians/peramp-median-jura-sv.pdf
https://data.desi.lbl.gov/desi/users/raichoor/spectro/jura/peramp-medians/peramp-median-jura-main-y1.pdf
https://data.desi.lbl.gov/desi/users/raichoor/spectro/jura/peramp-medians/peramp-median-jura-main-y2.pdf
https://data.desi.lbl.gov/desi/users/raichoor/spectro/jura/peramp-medians/peramp-median-jura-main-y3.pdf

**Comment by forero** [comment]
@rongpu

Building upon your [previous work on fiber outlier detection](https://data.desi.lbl.gov/desi/users/rongpu/redshift_qa/nz_ks_test/bad_fibers_from_nz-elg-lss_catalog.html), I've identified three additional fibers that exhibit atypical behavior in their LRG redshift distributions. These fibers were not previously mentioned in this issue, so I'm reporting them for further investigation.

**Newly Identified Atypical Fibers:** 
- 650
- 675
- 1754

I've attached plots for each fiber showing:
- Percentile curves compared to the mean
- Time series of redshift measurements
- Redshift distribution histograms

The full analysis notebook is available [here](https://github.com/forero/fiber-outlier/blob/aa0c27f36cfd66835c5b8cc9dd26217ee832665c/nb/fiber_percentile.ipynb).

Do you think these fibers warrant further investigation? 

Are there any known issues or characteristics of these specific fibers that might explain their behavior?


![Screen Shot 2024-08-09 at 12 23 58 PM](https://github.com/user-attachments/assets/e31173ef-7f4e-4875-8780-d9d304945db5)
![Screen Shot 2024-08-09 at 12 24 14 PM](https://github.com/user-attachments/assets/40bec0b9-5489-428b-a7b9-4f7275a2fcc0)
![Screen Shot 2024-08-09 at 12 24 45 PM](https://github.com/user-attachments/assets/01e31405-6df2-41ba-870c-6afa205accaa)

**Comment by schlafly** [comment]
650, 675 are hit by the z1 CTE.  I would guess that 700, 725, and potentially 750 are also affected.  Because they're the first fiber in a block of 25 they are more sensitive to the trap modeling than the others; apparently the fit isn't doing a good job there.  z3C has a serious CTE which vaguely matches that date range.  That looks like it might be roughly the last fiber affected by the problematic region, which I wouldn't have thought was as special of a case (i.e., it lies right on the amp boundary).

**Comment by rongpu** [comment]
Thanks @forero! These fibers have somewhat low p-values in my K-S test but still above the 1e-4 threshold.
These fibers also have low overall success rates (see https://github.com/desihub/desispec/issues/2297).

Is fiber 1754 also a CTE issue? I spot checked a few of its z=~1.7 spectra (see an example below), and there's nothing obviously wrong –– it seems that this fiber simply have more featureless spectra than the other fibers.

![image](https://github.com/user-attachments/assets/71d3c65f-c55d-4946-8c8e-221e18f308c8)

**Comment by rongpu** [comment]
For convenience I have created PDFs that includes the per-fiber redshift QA plots for all 5000 fibers:
https://data.desi.lbl.gov/desi/users/rongpu/redshift_qa/per_fiber_qa/jura/per_fiber_redshifts_bgs_any_zcatalog.pdf
https://data.desi.lbl.gov/desi/users/rongpu/redshift_qa/per_fiber_qa/jura/per_fiber_redshifts_lrg_zcatalog.pdf

**Comment by sbailey** [comment]
Tracking has been moved to spreadsheet (don't post link here since this is too public).
