### ISSUE TITLE
problematic spectra from fibers 2027,2028

### ISSUE THREAD

**Issue by abrodze** [desihub/desispec#2287]
The spectra from fibers 2027 and 2028 show clear artifacts from a defect on z4 between 20230427 and 20230821. The defect is consistent throughout this timeframe yet not uniformly flagged (esp. concerning 2028). When not flagged, the unmasked regions result in increased classification failures.

Example of the artifact in spectra from fiber 2028 during this time period where z was not (fully) flagged:
![unknown](https://github.com/desihub/desispec/assets/59992122/1acaa3a4-6ecf-4c2d-959d-46ec00703a3a)
![unknown](https://github.com/desihub/desispec/assets/59992122/e02d6766-79f4-4ac0-89a3-b03135514a72)
![unknown](https://github.com/desihub/desispec/assets/59992122/5caa81a3-b376-47c6-bfbd-0082a69c83c5)

**Comment by sbailey** [comment]
@abrodze provided new sm1-z.yaml file flagging 2027,2028 as bad for 20230427 through 20230821.  I added this to desi_spectro_calib and committed to svn.
