### ISSUE TITLE
Check z7=sm8z BADCOLUMNFIBERS; maybe too many masked

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2288]
Just before Jura, @julienguy and @Waelthus updated the z7=sm8z PIXMASK since it appeared that the previous mask was masking columns that were no longer bad in newer data.  However, the BADCOLUMNFIBERS list is still quite long and is possibly extra-masking fibers that could now be fine:
```
BADCOLUMNFIBERS: 3615,3616,3696,3697,3698,3699,3700,3701,3702,3750,3751,3752,3753,3756,3757,3802,3803,3804,3805,3811,3812,3813,3817,3818,3819,3820,3821
```

Check that and update list if needed.  Thanks to @schlafly for noticing that we are still masking lots of fibers despite updating the pixmask.

**Comment by sbailey** [comment]
I checked the latest mask (ccd/pixmask-sm8-z7-20240324.fits.gz) and some recent darks (preproc/20240325/00232302/preproc-z7-00232302.fits.gz, preproc/20240701/00240946/preproc-z7-00240946.fits.gz) and it appears that all of these BADCOLUMNFIBERS are now good.

At the time of ccd/pixmask-sm8-z7-20221129.fits.gz, comparing to preproc/20221129/00155639/preproc-z7-00155639.fits.gz, it appears that the mask and the BADCOLUMNFIBERS list are appropriate for that epoch.

However, there are 3 intermediate masks between those two where the situation is more subtle.  e.g. inspecting ccd/pixmask-sm8-z7-20230620.fits.gz and preproc/20230620/00186046/preproc-z7-00186046.fits.gz, it looks like fiber 3615,3616 could be restored as good but fibers 3698,3699 should stay bad, and maybe 3696,3697,3700,3701,3702 should stay bad as well.  3750,3751 look ok, but 3752,5753,3756,3757 are polluted by extra-noisy columns that are no longer masked.  3802 might be ok, but 3803-3805 should remain masked.  3811-3813 and 3817-3821 appear to be ok.

For now, I propose to remove the BADCOLUMNFIBERS only for the latest config so that daily processing will no longer mask them, but I wait until after the collaboration meeting when @julienguy and I can review these cases in more detail with more eyes on it.  @schlafly heads up.

**Comment by julienguy** [comment]
I used commands like
```plot_fiber_traces -i $DESI_SPECTRO_REDUX/daily/calibnight/20230620/psfnight-z7-20230620.fits  --fibers 3615,3616,3696,3697,3698,3699,3700,3701,3702,3750,3751,3752,3753,3756,3757,3802,3803,3804,3805,3811,3812,3813,3817,3818,3819,3820,3821 --image $DESI_SPECTRO_CALIB/ccd/pixmask-sm8-z7-20230620.fits.gz --vmin 0 --vmax 0.9```
to find fiber traces close to masked columns in the CCD.

For questionable cases, I also looked at calibrated frames of >1000s in dark time.

I came up with the following changes that I committed to ```$DESI_SPECTRO_CALIB/spec/sm8/sm8-z.yaml```

```
old:
for MASK: ccd/pixmask-sm8-z7-20221129.fits.gz BADCOLUMNFIBERS: 3615,3616,3696,3697,3698,3699,3700,3701,3702,3750,3751,3752,3753,3756,3757,3802,3803,3804,3805,3811,3812,3813,3817,3818,3819,3820,3821
for MASK: ccd/pixmask-sm8-z7-20230511.fits.gz BADCOLUMNFIBERS: 3615,3616,3696,3697,3698,3699,3700,3701,3702,3750,3751,3752,3753,3756,3757,3802,3803,3804,3805,3811,3812,3813,3817,3818,3819,3820,3821
for MASK: ccd/pixmask-sm8-z7-20230620.fits.gz BADCOLUMNFIBERS: 3615,3616,3696,3697,3698,3699,3700,3701,3702,3750,3751,3752,3753,3756,3757,3802,3803,3804,3805,3811,3812,3813,3817,3818,3819,3820,3821  ????

new:
for MASK: ccd/pixmask-sm8-z7-20221129.fits.gz BADCOLUMNFIBERS: 3616,3696,3697,3698,3699,3700,3701,3702,3750,3751,3752,3753,3756,3757,3802,3803,3804,3805,3811,3812,3813,3817,3818,3819,3820,3821
for MASK: ccd/pixmask-sm8-z7-20230511.fits.gz BADCOLUMNFIBERS: 3697,3698,3699,3750,3751,3752,3753,3756,3757,3803,3804,3805,3811,3812,3813
for MASK: ccd/pixmask-sm8-z7-20230620.fits.gz BADCOLUMNFIBERS: 3697,3698,3699,3804,3805
```
(Stephen already edited the latest mask entries ```MASK: ccd/pixmask-sm8-z7-20240324.fits.gz``` without any BADCOLUMNFIBERS)

I think we can mark this issue as resolved for now. We could reopen it if we find bad fiber redshifts in the next test run.
