### ISSUE TITLE
Update redrock prior widths to be wider than QuasarNET "wiggles" in redshift

### ISSUE THREAD

**Issue by dylanagreen** [desihub/desispec#2293]
QuasarNET uses a grid based system (called boxes) to estimate line positions which causes unphysical "wiggles" in the N(z) distribution due to an unphysical centering of estimated line positions in these boxes, see the following plot near the peak of the distribution:

![z_comp](https://github.com/user-attachments/assets/967d32d8-2d06-4fe6-9fc5-2b5a886bfaa9)

Currently after running QuasarNET we rerun redrock with a redshift prior centered at the QuasarNET redshift and QSO templates only in order to recover these quasars with updated redshifts. The current redrock prior width is $\Delta z = 0.1$, which we have since discovered is narrower than the width of the wiggles in the QuasarNET N(z). 

However, we can analytically calculate the required width of the redrock prior necessary to remove the wiggles in the final redshift catalog. We do this by calculating the width of each output QuasarNET box in redshift space and using this as the associated width of the redrock prior. This width is calculated assuming the QuasarNET has correctly estimated the "coarse" position of the line (it got the right box assignment) but is inaccurate in its "fine" estimation, possibly centering the line unphysically in the center of the box. Using the width of the box as a prior should allow redrock to correct the redshift and remove the wiggles.

Using a logarithmic output grid, which QuasarNET uses in Iron, creates a linear dependence of box width on estimated QuasarNET redshift:
![box_width_log](https://github.com/user-attachments/assets/7b5f3bab-02eb-4a62-a7d3-4b0964bf13dc)

Fitting the linear dependence provides the following equation: 
$$\Delta z = 0.07842467 * z + 0.07842494$$ 

It is probably sufficient to round this to three or four decimal places.

**Comment by akremin** [comment]
Closed with PR #2298
