### ISSUE TITLE
QuasarNET afterburner only uses HIZ template results in overlap region

### ISSUE THREAD

**Issue by dylanagreen** [desihub/desispec#2299]
When rerunning redrock the qos-qn afterburner runs the HIZ and LOZ templates separately due to the way RR accepts priors. The intention in the code is to then compare the two results in the overlap region, and keep the one with the lower chi^2 (this is normally done internally in redrock). 

When running the two templates separately the afterburner initializes global variables:
https://github.com/desihub/desispec/blob/e9ac85427046f6e475a3b11ee8a468fbecf9c773/py/desispec/scripts/qsoqn.py#L198

When aggregating the output the results are compared to the global variables, and if the fit has a better chi^2 than the globally stored chi^2 variable the fit is accepted and updated in the global variables:

https://github.com/desihub/desispec/blob/e9ac85427046f6e475a3b11ee8a468fbecf9c773/py/desispec/scripts/qsoqn.py#L251-L256

However, the loop neglects to update the global chi2 variable, so line 253 above is always comparing against `np.inf * np.ones(targetid.size)` as initialized in line 198. The effect of this is that since the HIZ templates are run _after_ the LOZ templates the HIZ results will always overwrite the LOZ results in the overlap region, regardless of whether the fit is better or at a different redshift than the LOZ templates. 

This is probably a one line fix, adding

```python
chi2[best_chi2] = chi2_tmp[best_chi2_tmp]
```

to update the global chi2 variable. after L256 should solve this issue, although validating this might take a little bit of effort. Reminder that the overlap region is 1.4 < z < 1.6.

**Comment by sbailey** [comment]
Good catch.  An arguably better long term solution is to update `rrdesi --templates` to accept more than one template.  Then the afterburner can call Redrock once, let Redrock sort out which HIZ/LOZ is best by its standard algorithm, and then the after burner just uses that.  It feels like a lot of the complication / fragility here is that rrdesi currently does not allow you to specify more than one template unless you give it a full directory worth of templates (which then brings in templates that the afterburner doesn't want to use).

**Comment by abrodze** [comment]
Stephen's suggestion should already be possible since Redrock can take a text file for the --templates argument. 

https://github.com/desihub/redrock/blob/main/py/redrock/templates.py#L298-307

I'll play around with the qnqso.py script to get it up to speed with this "new" redrock feature.

**Comment by sbailey** [comment]
Fixed by PR #2402; closing
