### ISSUE TITLE
logging usage

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#23]
Add python logging.DEBUG, .INFO, .WARN, .WARNING, .ERROR, .CRITICAL, .FATAL to desispec.log module to make it easier to log.get_logger(log.INFO) without having to import both desispec.log and logging just to get the log level to pass into log.get_logger().

Add support for an optional $DESI_LOGLEVEL environment variable in log.get_logger() to override the log level.  This will let scripts temporarily turn on debugging by setting an environment variable without having to change any code.

grep for "print" in all code and consider whether each would be better as a log call instead.

**Comment by julienguy** [comment]
I am doing the edition of desispec.log

**Comment by julienguy** [comment]
See pull request Improve logger #25

**Comment by weaverba137** [comment]
In the function `desispec.pipeline.core.runcmd()`, is there a particular reason for the print statements there?  Seems like that's an overly complicated method of writing `log.debug()`.

**Comment by tskisner** [comment]
You (or I) can probably delete the entire pipeline directory and start 
over.  That is all legacy sandbox code before we had developed *any* of 
our agreed upon standards, logging, etc.

Not only that, but I had intended to eventually use the saga package for 
interfacing with PBS.  Unfortunately that is python 2.x only, and NERSC 
will be switching to SLURM.

So we should definitely take a step back and think about what tools we 
want for interfacing with schedulers.

-Ted

**Comment by weaverba137** [comment]
We will also have to delete some scripts.  For example, `desi_dailytest.py` looks like it is just a copy of the `desispec.pipeline.core` code.

**Comment by tskisner** [comment]
ok, I see Stephen put some stuff in the pipeline module, so I no longer 
can speak for it.  I was referring to the "Machine" classes, which need 
to be replaced by a re-think of what we want to do.

-Ted

**Comment by sbailey** [comment]
print statements in `desispec.pipeline.core.runcmd()`:  the code comment says "Use log.level to decide verbosity, but avoid long prefixes".  i.e. I only wanted to list the input/output files if logging DEBUG was turned on, but in this particular case I wanted to preserve the formatting without a bunch of leading code names and line numbers.  Thus the `if log.level <= desispec.log.INFO` followed by normal print statements.

`desi_dailytest.py` is indeed a leftover from a previous refactor -- now that is in `desispec.test.integration_test` with a wrapper bash script for cron jobs in `etc/cron_dailytest.sh`.  I'll delete it in an upcoming pull request.

**Comment by sbailey** [comment]
Addressed with pull request #42 ; closing issue.
