### ISSUE TITLE
Update z4=sm1z pixmask and dark starting 20230427

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2301]
Short version: Review and update the z4=sm1z pixmask and dark starting on 20230427.

There was a CCD warm up even on 2023-04-25.  After we recovered, there was a new set of bad pixels on z4=sm1z around x\~350 y\~1200-2100, e.g. looking at jura/preproc/20230427/00177795/preproc-z4-00177795.fits.gz

![image](https://github.com/user-attachments/assets/4724e494-c088-4deb-82e6-b2e0bc32ed2c)

This seemed to get better with time, and/or the dark model for later dates accommodated it better, but there is still some effect near those pixels, e.g. jura/preproc/20230816/00190827/preproc-z4-00190827.fits.gz

![image](https://github.com/user-attachments/assets/a1c90811-354f-4f34-ac50-4e147cdd2e50)

(zoomed by hand, not exactly same x/y/z scale).

@Waelthus and @julienguy please review the pixmask and dark model for z4 starting on 20230427 and update as needed.

Related: Allyson first noticed this problem by studying columns and fibers that were flagged as bad; see #2287.  She added the two most impacted fibers to the BADCOLUMNFIBER list, but we should update the underlying pixmask / dark as well.

**Comment by julienguy** [comment]
Added new pixmask-sm1-z4-20230427.fits.gz and edit calibration parameters.
Details:

```
desi_compute_pixmask --firstnight 20230427 --lastnight 20240409 --input-specprod jura --specprod-dir /global/cfs/cdirs/desicollab/users/jguy/pixmask-sm1-z4-20230427 --save-preproc --camera z4 --old-mask /global/cfs/cdirs/desi/users/jguy/teststand/desi_spectro_calib/ccd/pixmask-sm1-z4-20210901.fits.gz -o pixmask-sm1-z4-20230427.fits.gz

cp pixmask-sm1-z4-20230427.fits.gz $DESI_SPECTRO_CALIB/ccd

# edit $DESI_SPECTRO_CALIB/spec/sm1/sm1-yaml

desi_preproc -i ~/data/20230427/00177795/desi-00177795.fits.fz --cam z4 --zero -o preproc-z4-00177795-new-zero-masked.fits

ds9  ~/redux/jura/preproc/20230427/00177795/preproc-z4-00177795.fits.gz pixmask-sm1-z4-20230427.fits.gz preproc-z4-00177795-new-zero-masked.fits
```
left: jura preproc image , center: new mask , right: new preprocessing with masked pixels set to 0

![Screenshot from 2024-08-14 11-21-12](https://github.com/user-attachments/assets/40adbba2-5481-445e-ab83-4f84afcff7f6)
