### ISSUE TITLE
Add FIBERSTATUS bits for VARIABLETHUR and NEARCHARGETRAP

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2304]
Several tasks for adding new non-fatal but problematic bits to FIBERSTATUS:

* [x] Add new FIBERSTATUS bits in [desispec.maskbits](https://github.com/desihub/desispec/blob/main/py/desispec/maskbits.py#L56):
  * `VARIABLETHRU` - fibers 1098, 3994, 4720, 4891 (re)identified in #2283
  * `NEARCHARGETRAP` - edge effects of CTE corrections, fibers 551-553, 3969, see #2286
(Alternate bit name suggestions are welcome.)

* [x] Add bookkeeping in [desispec.calibfinder](https://github.com/desihub/desispec/blob/main/py/desispec/calibfinder.py) to identify which fibers should be masked based upon new optional entries in desi_spectro_calib yaml files.

* [x] Add those new entries to desi_spectro_calib yaml files.

* [x] Add code to [desispec.io.fibermap.assemble_fibermap](https://github.com/desihub/desispec/blob/main/py/desispec/io/fibermap.py#L516) to set those bits based upon calibfinder.

* [x] Review functions in [desispec.fiberbitmasking](https://github.com/desihub/desispec/blob/main/py/desispec/fiberbitmasking.py) for how these should be treated.  We should *not* set ivar=0 for these bits, but we should probably not use them for sky and stdstar/fluxcalib calculations.  It's not clear to me whether the current set of functions supports that case.

In the future there may be additional FIBERSTATUS bits for cases like this; problematic but not fatal.

**Comment by julienguy** [comment]
- See PR #2313 for the changes to the code.
- I have also updated the yaml files for fibers 551,552,553. See issue #2286

**Comment by julienguy** [comment]
Added ```NEARCHARGETRAPFIBERS: 3969``` to some configs of ```$DESI_SPECTRO_CALIB/spec/sm8/sm8-z.yaml ``` . Tested with ```assemble_fibermap(night=20240213, expid=225329)```.

**Comment by julienguy** [comment]
Added ```VARIABLETHRUFIBERS: 4891``` to ```$DESI_SPECTRO_CALIB/spec/sm3/sm3-b.yaml``` (equivalent to editing any other camera), which is a fiber we will probably never fully recover (see issue #2305). I am waiting for the end of the study on improvements to the TPCORR parameters before flagging other fibers.

**Comment by sbailey** [comment]
Bits have been added to both the code and desi_spectro_calib yaml files.  In the end we have been fairly conservative for when to set the bit so that we don't over-mask.  Even if NEARCHARGETRAP is strictly informative, many users instinctively require FIBERSTATUS=0 and would discard mostly ok spectra, so we only set it for the worse cases.
