### ISSUE TITLE
r6 / sm7r CTE try simplified_regnault model

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2307]
Spinning this from #2283 into a separate ticket:

> fibers 3234-3254: r6 (sm7r) CTE first detected on May 21, 2023; we switched to 2-amp mode on March 25, 2024. Software correction for CTE in place with simple sector offset; this correction might be not sufficient. CCD_X range of CTE correction: 1905-2057; this corresponds to fibers 3234-3254. We also see the CTE pattern in the dark.
Possible correction using the complex CTE model from Eddie (or we simply flag the fibers in LSS catalog).

Detail: current spec/sm7/sm7-r.yaml has `OFFCOLSA: '0:1905,1905:2057'`, i.e. more than just 1905-2057.  Double check 0:1905 range and why the correction is split in two.

@schlafly suggested switching `OFFCOLSA` to `CTECOLSA` to trigger using the simplified_regnault model instead.  Will require a mini-prod to test.

**Comment by sbailey** [comment]
@schlafly and @julienguy confirmed that we should test
```
OFFCOLSA: '0:1905'
CTECOLSA: '1905:2057'
```
i.e. fitting a simple offset for 0:1905 and the simplified_regnault model for 1905:2057.

**Comment by schlafly** [comment]
I've started running 20240304 with this change to see if it helps.

**Comment by schlafly** [comment]
I have had a bunch of time outs and misconfigurations here.  The most recent run is in the queue again; eventually these will propagate into DESI_SPECTRO_REDUX/schlafly.  The needed updates to DESI_SPECTRO_CALIB are in DESI_SPECTRO_REDUX/schlafly/desi_spectro_calib/trunk.

**Comment by schlafly** [comment]
Prod is here:
https://data.desi.lbl.gov/desi/spectro/redux/schlafly/nightqa/20240304/
It's an improvement but r6 is also still not good following the change.  I could try the more complicated "regnault" model to see if it's a win but I'm pessimistic.

My suggestion would be to use the updates in DESI_SPECTRO_REDUX/schlafly/desi_spectro_calib/trunk but also to mask some number of fibers.

See, e.g.:
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20240304/skyzfiber-20240304.png
https://data.desi.lbl.gov/desi/spectro/redux/schlafly/nightqa/20240304/skyzfiber-20240304.png

**Comment by schlafly** [comment]
Ugh, I was staring at the skyzfiber but had mistaken the issue on P7 for the issue on r6, which may have been why this didn't look like an improvement.

e.g., comparing the sframes on r6 you do see an improvement with the right amount of squinting:
![image](https://github.com/user-attachments/assets/f9b7fa31-ba6a-4ac8-af69-4d5418c5aba7)
![image](https://github.com/user-attachments/assets/0285ae41-7571-4435-87cc-a8b98b114dd8)
You have to focus on the small white plume under the 6, which is the narrow CTE-affected region.

@rongpu , you should be able to find the new night in DESI_SPECTRO_REDUX/schlafly.  There is a new night in there from 20240304 which should be relevant for assessing r6 issues, and a new night in July after r6 was moved to two-amp mode which shouldn't be valuable for the r6 issue any longer.

**Comment by rongpu** [comment]
Here are the LRG redshifts from the new reduction compared to daily, with fibers 3234-3254 highlighted:
![image](https://github.com/user-attachments/assets/dfd1ec29-338f-4002-9b13-c493a80f7224)
Out of the 19 LRGs in these fibers, 3 has different redshifts (and they are assigned spuriously high redshifts in either daily or the new reduction). The sample is too small to say anything conclusive.

The change in petal 7 is more significant –– 8 out of 220 LRGs have different redshifts (I haven't check which reduction is more correct).

Only 1 BGS target was observed by fibers 3234-3254, and its redshift did not change.

**Comment by schlafly** [comment]
Can you name a particular night you would like to see re-reduced to test R6?

**Comment by rongpu** [comment]
We can try 20240114, which has a lot of observations from the three fibers flagged by the N(z) test.
![image](https://github.com/user-attachments/assets/5b717c9c-80ac-4342-ac56-e6cc73c8d671)

**Comment by schlafly** [comment]
I've run 20240114, which is in the same directory.  Note that I feel like all of the fibers from 3234 - 3250 should be affected by the CTE, albeit with the ones at the trap edge being the worst, and the least likely to be dramatically helped by this PR.

**Comment by rongpu** [comment]
Here is the same redshift comparison plot for 20240114, and the redshift distributions for fibers 3234-3254. The new reduction significantly reduces the spurious pileup of redshifts at z=~0.5. (Most of these spurious redshifts in daily are from the 3 fibers, 3234, 3235, 3250, which is why I only showed them in my previous comment.)
![image](https://github.com/user-attachments/assets/8944f241-53a1-493b-8df0-4ebb2d4cebe6)
![image](https://github.com/user-attachments/assets/2e1bd1ec-634e-4e9d-a7d3-7c2bc649395b)

**Comment by akremin** [comment]
Thank you both. It sounds like this does help things. Are we happy with this level of improvement or do you want to keep experimenting @schlafly ?

**Comment by schlafly** [comment]
Yes, I'm happy, let's declare victory.

**Comment by schlafly** [comment]
Yes, these are all in; I think this was this post?  https://desisurvey.slack.com/archives/C01HNN87Y7J/p1723122081176099

**Comment by akremin** [comment]
Ah yes, I was focused on the r1 update for daily processing and didn't fully digest that you had committed r6 as well. Perfect, thank you. I will close this ticket, though we should keep it in memory for assessing the K1 test prod and Kibo.
