### ISSUE TITLE
test_bootcalib is trying and failing to download remote data.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#231]
In a recent Travis test, tests failed because test_bootcalib.py tried to download files from portal.nersc.gov.  See https://travis-ci.org/desihub/desispec/jobs/140607436

It is not clear why the http access timed out, although it is entirely possible that after many, many tests, NERSC has decided that the Travis IP range is abusive.

Also, we really should be using requests, not urllib2.

**Comment by sbailey** [comment]
Can you followup with NERSC to find out if this was a temporary failure or if they are really blocking us?

If NERSC portal access for downloading test data is problematic, we could consider alternatives such as creating a desispec-testdata repo similar to desisim-testdata for the purposes of holding test data files.

**Comment by weaverba137** [comment]
The latest test passed, so it may well have been a momentary glitch.  I have added IP number checking to the Travis tests.
