### ISSUE TITLE
tertiary tiles PROGRAM=other -> dark/bright

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2324]
From @araichoor on Slack:

I notice that ~all the tertiary programs in jura have survey=“special” (good), but program=“other”.
ie the “program” is not informative, though we can easily say if it s “dark” or “bright”.
though we can recover it from the fiberassign file header => would we want to do that for kibo, ie ?
I acknowledge that it may “break” things w.r.t. to previous releases (ie a tile previously classified “other” would now be “dark” or “bright”)... in case, I post in reply a code snippet to recover the observing conditions.

example of code snippet to recover if a program is “dark” or “bright”.
this parse the fiberassign file in the data folder, and looks for the GOALTYPE header keyword.
and assumes that all tiles from a given FAFLAVOR has a single obsconds.
```python
d = Table.read("/global/cfs/cdirs/desi/spectro/redux/jura/exposures-jura.csv")

d = d[(d["SURVEY"] == "special") & (d["PROGRAM"] == "other")]

for faflavor, count in zip(*np.unique(d["FAFLAVOR"], return_counts=True)):

    i = np.where(d["FAFLAVOR"] == faflavor)[0][0]
    night, expid, tileid = d["NIGHT", "EXPID", "TILEID"][i]
    tileidpad = "{:06d}".format(tileid)
    fn = "/global/cfs/cdirs/desi/spectro/data/{}/{:08d}/fiberassign-{:06d}.fits.gz".format(night, expid, tileid)
    obsconds = fitsio.read_header(fn, 0)["GOALTYPE"]
    print("{}\t{}\t{}".format(faflavor, obsconds, count))
```

**Comment by sbailey** [comment]
Output from the script above:
```
specialm31	DARK	9
specialodin	DARK	8
specialtertiary1	DARK	17
specialtertiary10	BRIGHT	1
specialtertiary11	DARK	3
specialtertiary12	BRIGHT	1
specialtertiary13	BRIGHT	28
specialtertiary14	DARK	31
specialtertiary15	DARK	31
specialtertiary16	DARK	19
specialtertiary18	DARK	13
specialtertiary19	BRIGHT	4
specialtertiary20	BRIGHT	27
specialtertiary23	DARK	29
specialtertiary24	BRIGHT	32
specialtertiary25	DARK	5
specialtertiary26	DARK	40
specialtertiary27	DARK	30
specialtertiary28	BRIGHT	12
specialtertiary29	BRIGHT	16
specialtertiary30	BRIGHT	31
specialtertiary31	DARK	12
specialtertiary32	BRIGHT	22
specialtertiary33	BRIGHT	25
specialtertiary34	BRIGHT	6
specialtertiary35	DARK	6
specialtertiary36	BRIGHT	42
specialtertiary37	DARK	29
specialtertiary38	DARK	41
specialtertiary5	DARK	6
specialtertiary6	BRIGHT	6
specialtertiary7	DARK	4
specialtertiary8	BRIGHT	6
```

@araichoor could you add this to the special cases in `desispec.io.meta.faflavor2program` and submit a PR?

I see that there are some gaps (specialtertiary2-4, 21-22, ...)  If the correct dark/bright is known for those cases even if they weren't observed for Jura, please add that too.

**Comment by araichoor** [comment]
ps, about the "gaps": I ll try to make the code working in a general way. but for context, those "gaps" correspond to tertiary programs that we designed but never observed (2,3,4,9,17,21,22,39); see e.g. here: https://data.desi.lbl.gov/desi/users/raichoor/tertiary-status/tertiary-status.html.

**Comment by araichoor** [comment]
@sbailey, for info (don t know if that should be in a new ticket or not):

PR https://github.com/desihub/desispec/pull/2325/ provides a "temporary" fix, in the sense that it will no longer "work" when new tertiary programs will be added, i.e. those new tertiary programs will have `program="other"`.

a couple of ways I could think of to have this "automatically" updated:

first:
- have the information from `faflavor2program()` in a file (e.g. `main/py/desispec/data/faflavor2program.dat`), which would list the {faflavor, program} values;
- such a file could then be updated via a script, which we would basically do what I wrote in the PR, ie parse the fiberassign files in `/global/cfs/cdirs/desi/survey/fiberassign/special`, and update the `faflavor2program.dat` file with any new tertiary program existing there;
- that script could be run as part of the daily `tsnr_afterburner`, before updating the `{exposures,tiles}-daily.csv` file.

second (maybe better?):
- in the `surveyops/tertiary` svn folder, I create a new file listing those {faflavor, program} values for the tertiary programs;
- `faflavor2program()` would read that file to get the correct values.

it would then be on my side to update that file when I design new tertiary programs.

would any of that make sense?

**Comment by sbailey** [comment]
Thanks for the quick fix for the purposes of Kibo.  I'm going to move this to "done" for Kibo but keep the ticket open to think more about the options for better maintainability in the future.
