### ISSUE TITLE
rename TYPE -> CLASS

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#233]
Problem: The imaging surveys use "TYPE" to categorize whether a photometric object is PSF-like, extended with an exponential or de vaucouleurs profile, etc.  The spectroscopic pipeline has been using "TYPE" for the redshift fitter output object type, e.g. GALAXY or QSO. 

Proposal: rename TYPE to CLASS (and SUBTYPE to SUBCLASS) in the redshift finder output.  This also has the advantage of going back to the naming used by SDSS/BOSS.  I'm not sure why I switched in the first place.

This would require updates to redshift fitter I/O wrappers, redshift fitting QA code, and quickcat.

Name changes are a pain, but better sooner than later.  Register your objections, support, or alternative suggestions now...

**Comment by cballand** [comment]
Alternative choices could be TARGET_TYPE and TARGET_SUBTYPE, but CLASS and SUBCLASS are fine. When we all agree on names, I'll do the update.

**Comment by moustakas** [comment]
I'm personally fine with CLASS and SUBCLASS.

**Comment by sbailey** [comment]
Another consideration: `type` is a builtin function but you can still use it as a variable name, e.g. as we do with `ZfindBase.type`.  In contrast, `class` is a reserved keyword which means that you can't use that as a variable name.  We could still have a FITS column named CLASS, but internally to the python code it would have to be something like `zclass` or `class_` or `klass`.

I kind of like `zclass` or `ztype` since it hints that this is the classification/type assigned during redshift fitting, without the ambiguity of pure `type` and `class` that got us into the name collision with the imaging surveys in the first place.  Should the FITS file column also be `ZCLASS` or `ZTYPE`?  I find `TARGET_TYPE` too long to type.

On one hand this choice doesn't matter at all; on the other hand this will be a very commonly used variable by analyzes and let's pick something that isn't subtly irritating for years to come.  I'll implement some choice as part of a Pipeline 2016b cleanup pass early next week.

**Comment by julienguy** [comment]
What about ITYPE for targeting based on imaging and STYPE for spectroscopic type.

**Comment by sbailey** [comment]
I like @julienguy's suggestion, though for once I'll advocate for a longer variable name than Julien: how about SPECTYPE?  I think that is clear, short, reasonably easy to say, and avoids the double letter tripping of SPECCLASS.  I'll proceed with a PR using SPECTYPE.  The data telecon tomorrow can be the last chance to advocate for alternatives.
