### ISSUE TITLE
Missing columns in QuasarNET afterburner catalog

### ISSUE THREAD

**Issue by rongpu** [desihub/desispec#2375]
Currently only the best-fit redshift, redshift error and template coefficients are saved in the QuasarNET afterburner catalogs `qso_qn-*.fits`, and some of the important columns, such as `SUBTYPE` and `ZWARN`, are missing. Since we are using these QN redshifts for science analyses, I think I would be useful to at least save the redrock output for the best-fit solution.

The relevant QN code: https://github.com/desihub/desispec/blob/97b174838a2e951a32aa719f19da07e184585c39/py/desispec/scripts/qsoqn.py#L262

**Comment by akremin** [comment]
This was resolved in https://github.com/desihub/desispec/pull/2402
