### ISSUE TITLE
desi_purge_tilenight should remove future redshift jobs from processing tables

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#2389]
desi_purge_tilenight should remove future redshift jobs from processing tables so that they can be resubmitted. It already removes the directories, so it should remove the entry from the processing table.

desi_purge_tilenight should also remove the dashboard caches for the current night and any future nights with redshifts that are removed.

**Comment by sbailey** [comment]
implemented in PR #2424.  Closing.
