### ISSUE TITLE
desi_make_dark_tables crash with pre-existing tables

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2397]
Running desi_make_dark_tables to update a pre-existing $DESI_SPECTRO_DARK/dark_table.csv crashes:
```
$> cd /global/cfs/cdirs/desi/spectro/desi_spectro_dark/latest
$> desi_make_dark_tables -i . -o .
Traceback (most recent call last):
  File "/global/common/software/desi/perlmutter/desiconda/20240425-2.2.0/code/desispec/main/bin/desi_make_dark_tables", line 62, in <module>
    outarr[:,:-1], names=["FILENAME", "DETECTOR", "CCDCFG", "CCDTMING"],
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

It does work to send the output to a different blank directory and then copy the results back.

@Waelthus please inspect.  It is possible that I'm running it in a different mode than you do, but I think this case is supposed to work and at minimum shouldn't crash with this dimensionality error.

**Comment by Waelthus** [comment]
it looks like this would happen if there are no new files to be added, cannot really check retroactively what happened there as files are changed already. Did you generate new files with modified headers, not add them to the tables and then run the routine? 
For me whenever there were new files a simple `desi_make_dark_tables` worked (the `-i . -o .` should have the same effect assuming you launch from $DESI_SPECTRO_DARK).
Anyway, will raise a more useful error...
