### ISSUE TITLE
desi_compute_bias requires unsetting $DESI_SPECTRO_DARK

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2399]
To create a new bias with desi_compute_bias, you first have to `unset DESI_SPECTRO_DARK`, or otherwise it fails due to not finding the bias file that you are trying to create in the first place.

I did not find this procedure documented, but I have a vague memory of @julienguy mentioning needing to do this.  We should fix this so that "missing" biases and darks are only fatal if the processing is actually needs that bias/dark.

**Comment by Waelthus** [comment]
I confirm the issue, and I think it was introduced when we disallowed calibfinder to run with darks in DESI_SPECTRO_CALIB for normal analyses. So I guess the PR above will fix this behaviour by allowing a fallback.
