### ISSUE TITLE
add option to nightqa to reprocess everything except darks

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#2401]
Recently, nightqa has become much more variable in run time, likely correlated with the recent Perlmutter instabilities. For reference, a recent attempt to run nightqa on 20241015 took over 30 minutes before I killed the script.

Rerunning by hand shows that it is hanging when running preproc. Since we often run nightqa after manipulating only science data, it would be nice to have a simple option to tell it to reproduce all files except the darks, which wouldn't change in such circumstances and would avoid the issue of preproc occasionally hanging.

We should also investigate why nightqa hangs and improve that, but the above proposal could be implemented much faster.

**Comment by sbailey** [comment]
nightqa could also use `desispec.util.runcmd(desispec.scripts.preproc.main, args, inputs=..., outputs=...)` so that if the dark preproc outputs already exist, it wouldn't re-generate them.

**Comment by akremin** [comment]
Resoved in PR #2418
