### ISSUE TITLE
update templates to use for flux calibration

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#264]
Spinning this off of PR #263:

Flux calibration currently uses the rather old /project/projectdirs/desi/spectro/templates/star_templates/v1.1/star_templates_v1.1.fits templates by default.  This could be updated.

Consider whether the step of matching standard star targets to templates should use all stellar templates that match the target colors (with buffer for flux errors) or whether we should only consider a restricted subset of FSTD, WD, etc.

Assigning to @moustakas as our template expert, though any tests and code changes don't necessarily have to come from him.

**Comment by moustakas** [comment]
This ticket is stale / obsolete; closing.
