### ISSUE TITLE
Header argument is not actually optional in BrickBase objects.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#267]
In desispec.io.brick, BrickBase objects can be initialized with an optional header argument.  However, the `__init__()` method will immediately raise ValueError if the header argument is None or if it does not contain the BRICKNAM keyword.

**Comment by sbailey** [comment]
Fixed docstring in commit 092339b9a0c813fdd4dcb8a4021f68b316fe1e0d.  For the record:
* `header` is required when creating a new brick file and it must contain BRICKNAM.
* `header` is ignored if opening a pre-existing brick file.
