### ISSUE TITLE
Consider using json.dumps() instead of repr() for serializing redmonster subtype data.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#271]
In `desispec.zfind.redmonster`, line 132:

```python
        self.subtype = np.asarray([repr(self.zpicker.subtype[i][0]) for i in range(nspec)])
```

I am pretty sure that `repr()` is not a *standard* way to serialize dictionary data.  It is not even particularly safe.  Supposing that one of the values has a representation that is not easy to convert back into an object of that type (a lot of objects representations do have nice representations, but a lot don't; this is suggested but not enforced by the Python standard). Converting this back into a dictionary would also require an `eval()` call which is also potentially dangerous (or `ast.literal_eval()` which looks safer).

Encoding the dictionary as JSON would not only be a safer way to serialize the data, it would also be compatible with other languages!

**Comment by sbailey** [comment]
This is a good idea.  I will include it in an upcoming PR of tweaks to the redmonster wrapper.

At the same time, dumping the entire redmonster subtype dictionary into the subtype column and taking up a bunch of characters to do so is a temporary hack.  It's a long lived "temporary", but we shouldn't view these as the final values that will be used for the subtype column of the redshift catalog.

**Comment by tskisner** [comment]
FYI, this issue just bit me running an end-to-end test (bootcalib through zfind) of a subset of the madrone production with python 3.5.  Looks like something in zpicker (inside redmonster) is not serializable.

  File "/scratch2/scratchdirs/kisner/software/git/desi/desispec/build/lib/desispec/scripts/zfind.py",
 line 244, in main                                                                                   
    nproc=args.nproc,npoly=args.npoly)                                                               
  File "/scratch2/scratchdirs/kisner/software/git/desi/desispec/build/lib/desispec/zfind/redmonster.p
y", line 133, in __init__
    self.subtype = np.asarray([json.dumps(self.zpicker.subtype[i][0]) for i in range(nspec)])
  File "/scratch2/scratchdirs/kisner/software/git/desi/desispec/build/lib/desispec/zfind/redmonster.p
y", line 133, in <listcomp>
    self.subtype = np.asarray([json.dumps(self.zpicker.subtype[i][0]) for i in range(nspec)])
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/json/__init__.py",
line 230, in dumps
    return _default_encoder.encode(obj)
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/json/encoder.py", l
ine 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/json/encoder.py", l
ine 256, in iterencode
    return _iterencode(o, 0)
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/json/encoder.py", l
ine 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 230 is not JSON serializable

WARNING: VerifyWarning: Error validating header for HDU #5 (note: Astropy uses zero-based indexing).
    'ascii' codec can't decode byte 0xbb in position 19: ordinal not in range(128)

**Comment by tskisner** [comment]
More info:  the error message above is actually complaining that the *integer* 230 is not json serializable.  Likely this is actually a np.int64.  These posts discuss this:

http://stackoverflow.com/questions/11942364/typeerror-integer-is-not-json-serializable-when-serializing-json-in-python
http://stackoverflow.com/questions/27050108/convert-numpy-type-to-python/27050186#27050186
http://stackoverflow.com/questions/9452775/converting-numpy-dtypes-to-native-python-types

Perhaps we should just disable subtype writing for now, especially since the output JSON string is currently getting trunctated to 20 characters when writing to the FITS table- so it is effectively corrupted and useless.

**Comment by weaverba137** [comment]
How did the tests pass if the serialization did not work?  Or do we not have unit tests for this code?

**Comment by sbailey** [comment]
Curious (and irritating).  On python 2.7:
```
In [2]: json.dumps(np.int64(230))
Out[2]: '230'
```
But on python 3.5:
```
In [3]: json.dumps(np.int64(230))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-36841a1caa5c> in <module>()
----> 1 json.dumps(np.int64(230))

/Users/sbailey/anaconda/envs/py3/lib/python3.5/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    228         cls is None and indent is None and separators is None and
    229         default is None and not sort_keys and not kw):
--> 230         return _default_encoder.encode(obj)
    231     if cls is None:
    232         cls = JSONEncoder

/Users/sbailey/anaconda/envs/py3/lib/python3.5/json/encoder.py in encode(self, o)
    196         # exceptions aren't as detailed.  The list call should be roughly
    197         # equivalent to the PySequence_Fast that ''.join() would do.
--> 198         chunks = self.iterencode(o, _one_shot=True)
    199         if not isinstance(chunks, (list, tuple)):
    200             chunks = list(chunks)

/Users/sbailey/anaconda/envs/py3/lib/python3.5/json/encoder.py in iterencode(self, o, _one_shot)
    254                 self.key_separator, self.item_separator, self.sort_keys,
    255                 self.skipkeys, _one_shot)
--> 256         return _iterencode(o, 0)
    257 
    258 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

/Users/sbailey/anaconda/envs/py3/lib/python3.5/json/encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(repr(o) + " is not JSON serializable")
    180 
    181     def encode(self, o):

TypeError: 230 is not JSON serializable
```
The redmonster wrapper is not yet covered by the unit tests; redmonster is slow enough to install and run that it would take a little bit of work to make that viable.  I thought I had run the integration test after this change, but perhaps I only ran it before this change or perhaps it didn't cover the case of a numpy integer being included in the subtype list...

@tskisner please go ahead and just turn off storing the subtype from redmonster and proceed with your pipeline py3 tests, and then submit a PR with that and anything else that needed to be fixed along the way.  As you noted, a truncated string of a dictionary isn't actually of much use.  If we really want to use the full redmonster subtype information, we'll need a datamodel update to accommodate that.
