### ISSUE TITLE
NIST arc files have non-ascii characters

### ISSUE THREAD

**Issue by tskisner** [desihub/desispec#289]
(Opening after offline communication with Stephen)

The files that bootcalib uses cause a read error with the latest python3.5 version of the desi-conda stack at NERSC.  Stephen noted that this is due to the non-ascii Angstrom symbol.  To reproduce:

>>> from desispec import bootcalib                                        
>>> bootcalib.load_arcline_list('b0', vacuum=True)
      
INFO:bootcalib.py:547:parse_nist: reading NIST file /scratch2/scratchdirs/kisner/software/desi-dev/desispec/pipeout-01321ba/lib/python3.5/site-packages/desispec-0.11.0.dev1033-py3.5.egg/desispec/data/arc_lines/CdI_vacuum.ascii                                                                                                  
Traceback (most recent call last):                                                                          
  File "<stdin>", line 1, in <module>
  File "/scratch2/scratchdirs/kisner/software/desi-dev/desispec/pipeout-01321ba/lib/python3.5/site-packages/desispec-0.11.0.dev1033-py3.5.egg/desispec/bootcalib.py", line 624, in load_arcline_list
    tbl = parse_nist(iline, vacuum=vacuum)
  File "/scratch2/scratchdirs/kisner/software/desi-dev/desispec/pipeout-01321ba/lib/python3.5/site-packages/desispec-0.11.0.dev1033-py3.5.egg/desispec/bootcalib.py", line 548, in parse_nist
    nist_tbl = Table.read(nist_file, format='ascii.fixed_width')
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/site-packages/astropy/table/table.py", line 2332, in read
    return io_registry.read(cls, *args, **kwargs)
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/site-packages/astropy/io/registry.py", line 351, in read
    data = reader(*args, **kwargs)
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/site-packages/astropy/io/ascii/connect.py", line 37, in io_read
    return read(filename, format=format, **kwargs)
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 289, in read
    table = fileobj.read()
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 613: ordinal not in range(128)

**Comment by sbailey** [comment]
Yay.  github is back.

Setting the environment variable `LANG=en_US.UTF-8` is a workaround, but I'm not familiar with the consequences of setting LANG to some value if some other program or file is expecting a different encoding.  NERSC does *not* set LANG by default

These files appear to be directly from NIST (e.g. [here](http://physics.nist.gov/cgi-bin/ASD/lines1.pl?spectra=Ar+I&low_wl=&upp_wn=&upp_wl=&low_wn=&unit=0&submit=Retrieve+Data&de=0&java_window=3&java_mult=&format=1&line_out=0&en_unit=0&output=0&bibrefs=1&page_size=15&show_obs_wl=1&show_calc_wl=1&order_out=0&max_low_enrg=&show_av=2&max_upp_enrg=&tsb_value=0&min_str=&A_out=0&intens_out=on&max_str=&allowed_out=1&forbid_out=1&min_accur=&min_intens=&conf_out=on&term_out=on&enrg_out=on&J_out=on)), though perhaps they were cut-and-pasted and comment # prefixes added (it is quite the homebrew format...).  Alas, selecting an output format of "ascii (text)" on the NIST webpage returns a table with non-ASCII characters...

Requesting them from NIST with units of nm would be another way to preserve the original tables without having the non-ascii characters.  Or perhaps if we are having to add # comment prefixes anyway, doing another step of replacing Å with A isn't so bad...

I'm not aware of a way to tell astropy Tables or python file readers in general what encoding to use.

I've added @profxy as the person who got these tables in the first place, and @weaverba137 for his general knowledge about standards and the right way to doing tricky things.

**Comment by weaverba137** [comment]
See desihub/desimodel#26 for a closely-related issue.

**Comment by weaverba137** [comment]
Is the reading of these files covered in a unit test?  If so, does Travis actually set `LANG` so that this unexpectedly succeeds?

**Comment by sbailey** [comment]
> Is the reading of these files covered in a unit test? If so, does Travis actually set LANG so that this unexpectedly succeeds?

[coveralls.io says that this function is included in the tests](https://coveralls.io/builds/8436727/source?filename=py%2Fdesispec%2Fbootcalib.py), which I think must mean the Travis is setting $LANG.

**Comment by weaverba137** [comment]
This is slightly off-topic, but isn't reading this line file a form of IO, and as such it should be in desispec.io, not desispec.bootcalib?

**Comment by weaverba137** [comment]
I checked this out with the astropy folks.

1. If you want to discuss this with the astropy developers, the place to do it would be astropy/astropy#2923.
2. A suggested workaround that doesn't involve setting the LANG variable:

   ```python
   import locale
   locale.setlocale(locale.LC_ALL, str(‘en_US.utf8’))
   ```
