### ISSUE TITLE
sphinx build errors should trigger Travis sphinx build failures

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#309]
PR #308 highlighted that we can have significant sphinx build failures without it triggering any Travis failures that something is wrong.  Can we update Travis or "python setup.py build_sphinx" or something such that syntax errors in docstrings and similar sphinx build problems will actually trigger a failure so that these will be noticed and fixed immediately?

I'm filing this under desispec, but the general concept probably applies to all our repos.

Further notes:

* To build the docs, developers need to have sphinx installed, which we do not have by default in our NERSC conda environment.  Should we add that to assist with getting documentation right when developing directly at NERSC?
* On a local machine with sphinx installed (e.g. `conda install sphinx`), developers can build the docs with `python setup.py build_sphinx` or `cd doc; make clean; make html`.  But even if there are build failures the return code is 0, so you still have to (gasp) actually read the logs that go scrolling by to see if anything went wrong.

**Comment by weaverba137** [comment]
astropy has actually solved this problem, but only by hacking the Python build system so that the normal output of `python setup.py build_sphinx` gets written to a temporary file which is then parsed to look for warning or error messages, and then sets the error code appropriately.

**Comment by weaverba137** [comment]
@sbailey take note!

I have what is hopefully a very easy solution to this.  Recent versions of sphinx add the `--warning-is-error` option.  You can see it in operation [here](https://travis-ci.org/desihub/desisim/jobs/214048616).  It doesn't print every error, but it should at least tell us that something is wrong, and then one can run `build_sphinx` in a checkout to see everything that is wrong.

**Comment by dkirkby** [comment]
FWIW, the setup.py `build_sphinx` target implemented in astropy_helpers changed recently to `build_docs`.

**Comment by sbailey** [comment]
Thanks, @weaverba137 !  Let's try this out on a couple of our more active repos like desisim and desitarget, and if it works the way we want in practice, we can propagate it out to other repos too.

**Comment by weaverba137** [comment]
Already done for desisim.  I'll add this to desispec momentarily.
