### ISSUE TITLE
move desispec.brick elsewhere

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#310]
**Summary**: move `desispec.brick` to desimodel, desitarget, or desiutil to avoid the dependency loop introduced in desihub/desitarget#112 .

`desispec.brick` contrains some utility functions for calculating the mapping from RA,dec to brickname for various sized bricks, but it isn't actually used anywhere in desispec itself, which just propagates the input bricknames without questioning them.

It is used by desisim when generating fake input data, and recently it is also used by desitarget.mocks when generating mock input catalogs.  This creates a dependency loop since desispec depends upon desitarget (to get mask bit definitions) and now desitarget depends on desispec (to get brick info).  Ugh.

Candidate locations to move it would be desitarget (it is related to targeting), desimodel (analogous to keeping footprint and tiling info), or perhaps desiutil.

Related: At the same time we should consider refactoring it into using a brick definition file from the imaging surveys rather than recalculating the ra,dec vs. brickname from scratch.  The current implementation has some rounding differences with the IDL version used by the imaging surveys resulting in slightly different brick definitions.

Also related: the imaging surveys continue to use 0.25x0.25 deg2 bricks, while we have been optimistically assuming that they will eventually switch to 0.5x0.5 deg2 bricks that have a better match for number of spectra per file and inode limits.  With each imaging data release that looks less and less likely.  We may have to break our organizational dependency upon imaging survey bricks if they continue to use the tiny bricks.  We will have to face that at some point, but let's not let that issue become a blocking factor for moving this module to avoid the desitarget/desispec dependency loop.

**Comment by moustakas** [comment]
```
Also related: the imaging surveys continue to use 0.25x0.25 deg2 bricks, while we have been 
optimistically assuming that they will eventually switch to 0.5x0.5 deg2 bricks that have a better 
match for number of spectra per file and inode limits. With each imaging data release that looks less 
and less likely. We may have to break our organizational dependency upon imaging survey bricks if 
they continue to use the tiny bricks. We will have to face that at some point, but let's not let that 
issue become a blocking factor for moving this module to avoid the desitarget/desispec 
dependency loop.
```
@dstndstn should comment, but for (the forthcoming, ~Jan 2017) DR4 we should be able to more easily "repackage" the Tractor catalogs into larger-sized bricks. 0.5x0.5 deg2 bricks may be back on the table!

**Comment by djschlegel** [comment]
John: Yes, part of the reason for the code refactorization in legacypipe was to make it easier to then generate the files in the format desired for DESI.  Let's still assume that will happen, and DR4 should be a good opportunity to test that.

**Comment by weaverba137** [comment]
An additional issue.  In addition to `desispec.brick.Bricks`, there is also `desispec.io.database.Brick`.  The latter is intended for a simple object-relational mapping to a row in a brick table.

**Comment by weaverba137** [comment]
For reference, could someone add a link to "the IDL version used by the imaging surveys"?

**Comment by weaverba137** [comment]
Also is there sample code that demonstrates the differences between the IDL & Python versions?

**Comment by moustakas** [comment]
While this issue is being dealt with, could someone also examine the overhead associated with ```desispec.brick.Bricks.brickname```?  Do we really need to *loop* on every element in the input sample?  

This is being raised as part of https://github.com/desihub/desitarget/pull/146.

**Comment by geordie666** [comment]
Fixed via https://github.com/desihub/desiutil/pull/70. If @moustakas comment about overhead associated with `brick.Bricks.brickname` is still an issue, let me know and I'll open a new ticket in `desiutil`

**Comment by moustakas** [comment]
The overhead / slowness was tackled in https://github.com/desihub/desispec/pull/343 and isn't too totally reasonable now.
