### ISSUE TITLE
Integrate raw data metadatabase with pipeline processing

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#323]
Maybe this is already mostly done, but make sure that the raw data metadatabase is actually being used in the pipeline processing.  In addition:

* "Dust off" the code, make sure it still works robustly.  This may include adding some unit tests.
* Make sure the code is fully documented.
* Try, as much as possible, to make the database interface database-agnostic (see also #321).

**Comment by tskisner** [comment]
The pipeline planning code currently uses functions in desispec.io.meta for all querying of raw data.

There is also the question of using a database in pipeline productions.  In previous discussion (more than a year ago), I believe our plan was to copy the raw data sqlite database into the production directory, and then use that database to track the state of pipeline output products.  This is the "plan" I have been keeping in mind during work on the pipeline.  Currently the dependency graph and state of all pipeline outputs is tracked in memory as a python dictionary and read/written as yaml files.  I had punted on this work until we were dealing with more than one night of data :-)  That will be coming very soon.

Obviously if we are not using sqlite, we'll have to abstract the "copy the database" operation.  Then we would need to figure out the schema for all the pipeline output products.  Anyway, good to have this issue so we don't lose track of things.

**Comment by weaverba137** [comment]
Good.  Please see #320 for more details on the type of database we are talking about.  This was a significant aspect of the full-survey data challenge that was presented at OSU.  This is more about tying redshifts back to targets than tracking pipeline processing steps.

**Comment by weaverba137** [comment]
Adding this to project 18.6, since now that the pipeline actually has a processing database, it can be integrated with the raw data metadatabase.  Maybe that's already done in fact.

**Comment by sbailey** [comment]
Punting to 18.9.  It sounds like @tskisner, @weaverba137, and myself need to have a chat about whether this is done, needed, or defunct.

**Comment by sbailey** [comment]
Dropping from release critical path until @tskisner @weaverba137 and I can chat about it and make a plan.  This is low priority since it isn't a blocking factor for how things currently work.

**Comment by tskisner** [comment]
In the current paradigm, the data transfer process triggers the pipeline for a particular exposure.  The metadata for that raw exposure (e.g. fibermap info) is ingested into the production DB directly from the FITS files.  I don't think anything else is needed, and am fine if we want to just close this issue as irrelevant.
