### ISSUE TITLE
desispec.test.test_binscripts.py throws AttributeError

### ISSUE THREAD

**Issue by gdhungana** [desihub/desispec#324]
Below are the final lines while running this test (tested at NERSC and my laptop). Looks like the submodules inside scripts are not correctly imported.

```
Wrote QA SkyRes file: qa-ac0a582c5a2f409a861bcf1af50ed01e.pdf
INFO:sky.py:75:main: successfully wrote sky-ac0a582c5a2f409a861bcf1af50ed01e.fits
INFO:util.py:97:runcmd: Thu Jan  5 13:51:38 2017
INFO:util.py:111:runcmd: SUCCESS: /global/common/edison/contrib/hpcosmo/hpcports_gnu-9.0/python-2.7.12_acfb6440-9.0/bin/python /global/u1/g/govinda/Desi/softwares/desispec/bin/desi_compute_sky --infile frame-ac0a582c5a2f409a861bcf1af50ed01e.fits --fiberflat fiberflat-ac0a582c5a2f409a861bcf1af50ed01e.fits --outfile sky-ac0a582c5a2f409a861bcf1af50ed01e.fits --qafile qa-data-ac0a582c5a2f409a861bcf1af50ed01e.yaml --qafig qa-ac0a582c5a2f409a861bcf1af50ed01e.pdf
E
======================================================================
ERROR: test_compute_fiberflat (__main__.TestBinScripts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_binscripts.py", line 173, in test_compute_fiberflat
    args = desispec.scripts.fiberflat.parse(cmd.split()[2:])
AttributeError: 'module' object has no attribute 'fiberflat'

======================================================================
ERROR: test_compute_fluxcalib (__main__.TestBinScripts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_binscripts.py", line 207, in test_compute_fluxcalib
    args = desispec.scripts.fluxcalibration.parse(cmd.split()[2:])
AttributeError: 'module' object has no attribute 'fluxcalibration'

======================================================================
ERROR: test_compute_sky (__main__.TestBinScripts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_binscripts.py", line 229, in test_compute_sky
    args = desispec.scripts.sky.parse(cmd.split()[2:])
AttributeError: 'module' object has no attribute 'sky'

----------------------------------------------------------------------
Ran 3 tests in 16.453s

FAILED (errors=3)
```

**Comment by tskisner** [comment]
All tests passed (with python3) in early December (as of 63c451aaa2d315561167ee7577784b2c3cb3837c), and there have only been 3 commits since.  It looks like you are using python 2.7 from hpcports.  Any reason to not use python 3.5 from desi-conda?

**Comment by gdhungana** [comment]
Hi @tskisner Thanks for reminding of desi-conda. I also thought that tests must have passed last time. With python 3.5 also, I get the same message even after using desi-conda. I can not import the submodules by just importing desispec.scripts. See below.

govinda@edison07:~/Desi/softwares/desispec/py/desispec/test> which python
/global/common/edison/contrib/desi/conda/conda_3.5-20160913/bin/python
govinda@edison07:~/Desi/softwares/desispec/py/desispec/test> python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import desispec.scripts
>>> dir(desispec.scripts)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'division', 'print_function']
>>> 
But if I specifically do this, I can see the submodule, as expected. 

>>> import desispec.scripts.sky
>>> dir(desispec.scripts)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'division', 'print_function', 'sky']
>>> 

The test does the first approach and thus does not see those submodules, that are called inside. Isn't there a need to import explicitly if  __init__.py does not have them?

**Comment by gdhungana** [comment]
Please ignore the lines on top of characters. git is using default settings for comments. I should have checked that. Hopefully it is still understandable.

**Comment by gdhungana** [comment]
Sorry, it seems like I was not correctly setting up. Also, tests have passed in a separate branch and I also didn't see such a Failure in PR @tskisner submitted earlier today. So closing this now. Thanks @sbailey for editing my comment in the right format.
