### ISSUE TITLE
preprocessing : write a script to measure gains and saturation

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#332]
- Gains and saturation can be measured by comparing images taken in the same conditions.
 - A good candidate set of observations are LED data from the teststand.
 - Gains and saturation would be measured by analysing the commonly called "Photon Transfer Curve (PTC)" which is the rms of flux as a function of flux in CCD pixels.

**Comment by julienguy** [comment]
Implemented in teststand package. will be moved to desispec when stable (after technote validated).

**Comment by sbailey** [comment]
In desispec master now.  Closing issue.
