### ISSUE TITLE
desispec.log does not contain timestamps.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#346]
The `desispec.log` system does not print timestamps in the log messages.  This would be a simple change to the configuration & would be very nice for timing long-running processes.

Also, is `desispec` even the right place for the logging infrastructure?  It seems like something that every DESI package would want to use, so `desiutil` might be better for it.

**Comment by weaverba137** [comment]
I have already implemented an *optional* timestamp on `desispec.log.get_logger()` that does not change existing functionality.  So you can ignore that part of the question.  That still leaves open whether `desispec.log` should actually be in desispec at all.

**Comment by sbailey** [comment]
I agree that desispec.log should be moved to desiutil.  I will open a separate ticket about that (after digesting the other recent traffic about logging in #348).
