### ISSUE TITLE
"Phantom" calls to desispec.log.get_logger()?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#348]
Theoretically, when I initially start a Python program, `desispec.log.desi_logger` should be `None`.  It becomes defined the first time `desispec.log.get_logger()` is called.  However, what I'm finding is that `desispec.log.desi_logger` is already defined when a program starts up.  In particular:

```python
assert desispec.log.desi_logger is None
```

throws an AssertionError before the first time I call `get_logger()`.  Until this is solved, I can't implement an optional timestamp in the log infrastructure because `desi_logger` is already formatted.

**Comment by weaverba137** [comment]
I temporarily forced `desispec.log.get_logger()` to raise an exception if it was called with settings I didn't like.  Turns out it is being called by `desispec.frame` at import time.

This is a great reason why you should import inside functions, not inside modules.

```
Traceback (most recent call last):
  File "/home/weaver/Documents/Code/git/desihub/desispec/bin/desi_load_quicksurvey", line 3, in <module>
    from desispec.io.quicksurvey import main
  File "/home/weaver/Documents/Code/git/desihub/desispec/py/desispec/io/__init__.py", line 20, in <module>
    from .frame import read_frame, write_frame
  File "/home/weaver/Documents/Code/git/desihub/desispec/py/desispec/io/frame.py", line 16, in <module>
    from ..frame import Frame
  File "/home/weaver/Documents/Code/git/desihub/desispec/py/desispec/frame.py", line 15, in <module>
    log = get_logger()
  File "/home/weaver/Documents/Code/git/desihub/desispec/py/desispec/log.py", line 42, in get_logger
    raise ValueError("I got called prematurely!")
ValueError: I got called prematurely!
```

**Comment by weaverba137** [comment]
O, and it gets even better!  `desispec.frame` was importing and calling `desispec.log.get_logger()` at the module level, **AND THEN NOT EVEN USING IT!**

Sloppy code, people, sloppy code.

**Comment by weaverba137** [comment]
`get_logger()` was also being called at the module level in:

* `desispec.io.frame` (and only one of the functions in that module uses the log)
* `desispec.io.qa`
* `desispec.qa.qa_exposure` (and wasn't using it at all)
* `desispec.qa.qa_frame` (only one small method in the module uses it)
* `desispec.qa.qa_prod`
* `desispec.preproc`
* `desispec.io.raw`

In other words, just so I could see timestamps, I had to remove or move `get_logger()` in all these modules.  There could be others!

This also points to the fact that we're doing **A LOT** of unnecessary imports.  We *do not* need to import every single function we've ever written in `__init__.py` files.

**Comment by tskisner** [comment]
While I agree that we should minimize unneeded imports, once a module is imported it is cached and future imports do nothing.  The main pipeline executable (desispec.scripts.pipe_run.py) uses the logging facilities.  So if you are running the pipeline, the logging gets imported very early in the process (right after initializing MPI).  All future imports of logging should just used the cached module.  I only raise this point to emphasize that there is no performance penalty for multiple imports of the same module.  Of course the code is easier to read and cleaner if only the needed import statements are included...

**Comment by weaverba137** [comment]
I agree that extra imports are not necessarily going to adversely affect *performance*.  But this is clearly a case where unneeded imports are causing *side-effects*.

**Comment by sbailey** [comment]
To be specific, I think @weaverba137 is objecting to our common practice of using this as module-level code:
```python
from desispec.log import get_logger
log = get_logger()
```
The motivation is to avoid having boilerplate `log = get_logger()` inside every function that wants to use the logger.  I don't think this prevents reformatting the logging, e.g. to add timestamps.  Following the ideas in:

http://stackoverflow.com/questions/11581794/how-do-i-change-the-format-of-a-python-log-message-on-a-per-logger-basis

you can add timestamps to a previously existing `log` object with something like:
```python
import logging
formatter = logging.Formatter('%(asctime)s:%(levelname)s:%(filename)s:%(lineno)s:%(funcName)s: %(message)s')
old_handler = log.handlers[0]
new_handler = logging.StreamHandler()
new_handler.setFormatter(formatter)
log.removeHandler(old_handler)
log.addHandler(new_handler)
```

We could add utility functions in `desispec.log` or to the `log` object itself to add/remove timestamps from our format so that this could be turned on/off on the fly as needed (i.e. we shouldn't expect the end-user of the logging to have to repeat that recipe to turn on/off timestamps).

i.e. let's fix @weaverba137's original timestamp problem by adding utility functions to the logger rather than refactoring everywhere that we've been using logging.

@weaverba137 also noted that we should move logging to desiutil.  I agree and have been thinking about that for awhile but it apprently never bubbled up into a ticket.  #349 is now that ticket.

**Comment by weaverba137** [comment]
@sbailey, I don't actually agree with your recommendation here.  I'm already thinking much bigger picture than just configuring the logging object.

These module-level function calls create *side-effects*.  I cannot think of a case in my experience where side-effects are anything but bad.  You are basically promoting a programming model where arbitrary code can be executed without even explicitly importing modules.

Here is the scenario:

1. I import `main()` from `desispec.io.quicksurvey`.
2. In order to load `desispec.io.qucksurvey.main()`, `desispec/io/__init__.py` has to be evaluated.
3. `desispec/io/__init__.py` imports a whole bunch of modules for no other reason than to second-guess the `desispec.io` namespace. (In other words, why is it so important to be able to import `write_raw()` from `desispec.io` when it is *already* available from `desispec.io.raw`?)
4. As `desispec/io/__init__.py` imports functions from modules, the module-level code gets executed, even if it is not being explicitly imported by `__init__.py`.
5. Potentially large amounts of module-level functions have now been executed before my `main()` function even starts.

I feel that this causes nothing but pain for both developers and end-users.  This will only get worse if we add additional module-level "boilerplate".  I am advocating for a model where we *both* maintain a clean namespace *and* avoid side-effects.

**Comment by weaverba137** [comment]
The changes to the logging infrastructure have made this ticket moot.  Also at least some of the imports mentioned in here have gone away by necessity to fix things like broken documentation builds.
