### ISSUE TITLE
desi_make_bricks rigid calling sequence

### ISSUE THREAD

**Issue by ngbusca** [desihub/desispec#354]
Unlike other scripts (fiberflat, sky suctraction, etc.) desi_make_bricks has a rigid calling sequence that expects a certain directory tree organization of inputs. 

@sbailey Does anyone mind if I add more flexible options keeping the current functionality?

**Comment by ngbusca** [comment]
I see @dkirkby is to blame for many lines of this code, so I pipe the question to him too ;^)

**Comment by sbailey** [comment]
Go ahead and add more flexible options to override the default choices of the current script.

**Comment by sbailey** [comment]
`desi_make_bricks` is gone; closing ticket.
