### ISSUE TITLE
fiber numbers

### ISSUE THREAD

**Issue by ngbusca** [desihub/desispec#355]
In many places (e.g. l.70 in  scripts/makebricks.py: fibers = np.mod(brick_data['FIBER'],500)) the code assumes that fibers are numbered from 0...4999 and that there are 500 per frame. Is this a requirement?

I'm asking this because in boss2desi I am currently keeping the BOSS fiber numbering (which starts at 1), and then of course things break with the assumption the code above is making.

**Comment by sbailey** [comment]
Old ticket that we never answered.  Answering (perhaps unhelpfully) and then closing:
* yes it is a requirement that the fiber numbering start at 0 not 1 for the DESI pipeline
* in theory we should parameterize "500", but pragmatically I'm ok with some hardcoded "500"s floating around in desispec (though some future self will probably curse me; I'm guessing that David never thought the SDSS spectro pipeline would be upgraded to BOSS with a different number of fibers per spectrograph...)
