### ISSUE TITLE
are we keeping just the "best" redshift or N possible redshifts/classifications?

### ISSUE THREAD

**Issue by moustakas** [desihub/desispec#362]
The redshift (`zbest`) output [data model](http://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_REDUX/PRODNAME/bricks/BRICKNAME/zbest-BRICKNAME.html) only seems to accommodate a single "best" redshift.  

However, for our own retrospection of our redshift fitting and some science applications (specifically the Galaxy and Quasar Physics Working Group, which is just getting off the ground), we'll want to measure and keep the first ~N peaks of the P(z, type) probability distribution function, where N could be of order 3-5.  

Is this in a document somewhere and we just haven't implemented it?

**Comment by sbailey** [comment]
We definitely intend to keep the N best fits; that just isn't documented and implemented for our outputs from redmonster.  redrock keeps the 3 best fits from each spectral type in its hdf5 file as well as the full chi2 vs. z for each template type.  When it gets fully integrated with DESI, we will keep a "zbest" with just the best fits, and "zall" with multiple fits.  chi2 vs. z is certainly useful for debugging redshift fitting but takes a bunch of disk space so we should decide if we really need it for production running.
