### ISSUE TITLE
Executable bits set on package files

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#363]
The files `desispec/scripts/pipe_prod.py`, `desispec/scripts/pipe_run.py`, `desispec/scripts/pipe_status.py` have the executable bit set in the git repository.  If this is not necessary, I can remove the executable bit in my branch.

**Comment by sbailey** [comment]
Please go ahead and remove those executable bits.  I think those were added by my editor trying to be helpful but screwing up.  I have since turned off that "feature" but those may have slipped through.

**Comment by tskisner** [comment]
Yes, by all means change that...

**Comment by weaverba137** [comment]
OK Done.  For the record, here's an easy way to do this with a minimum number of commands:

```
find py -type f -perm +00111 -exec git update-index --chmod=-x \{\} \;
find py -type f -perm +00111 -exec chmod -x \{\} \;
```

Note how this changes both the files on disk and the git repository.

Also note that `-perm +00111` is macOS-specific (technically, the BSD version of `find`).  On GNU/Linux, you could use `-executable` or `-perm /ugo+x`.
