### ISSUE TITLE
Implement radial variation of sky brightness

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#368]
Fiber flat-fielding will have a residual radial pattern (see https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=2761 ) that has to be accounted for during the sky model fit.

**Comment by julienguy** [comment]
There are actually three different topic here
 1) calibration of the dome screen non-uniformity w.r.t. sky. this will be done during commissioning using dome flats and  blank sky exposures, and saved as a new fiberflat calibration file (TBD). We expect this to be stable, because it's a geometric effect (but we'll check during commissioning).
 2) sky non-uniformities which have no reason to follow a fov radial pattern. this has to be implemented as a polynomial of fov coordinates when computing the sky model.
 3) throughput variations due to FRD variation with fiber flexure that cannot be calibrated out, and that we have to absorb in sky subtraction. we should prepare the code for this eventuality as an option in sky subtraction (coefficient correction per fiber).

**Comment by julienguy** [comment]
The point 3. above has been implemented in branch skysub.
 - When subtracting the sky spectrum, an achromatic throughput correction can be fit.
 - This is based on 2 parameter fit around each sky line; 1 normalization factor for the sky line + 1 constant to account for the target spectrum.
 - The width of the wavelength region around each sky line has been tuned on simulations and found to be +- 4A.
 - The normalization coefficients of all sky lines are optimally combined, there is an outlier rejection loop per fiber to discard lines potentially affected by cosmics or target emission line.

A test run on one exposure/spectrograph (dark program, with LRG,ELG,STD stars...) gives encouraging results a with precision better than 0.1% rms on the (sky) throughput correction. Worse case is a 2% error. There is no significant bias with target brightness. The figure below shows the coefficient for each fiber (b,r and z from top to bottom).

![corr](https://user-images.githubusercontent.com/5192160/35589892-11cd8fba-05ba-11e8-9495-a0a415b099a9.png)

**Comment by sbailey** [comment]
Please spot check the ~2% outliers to see why the outlier rejection of the normalization coefficients didn't work as well as we might expect.  Would a simple median of the normalization coefficients do better?  What causes enough of the normalization coefficients to be wrong to result in a 2% overall incorrect answer?

**Comment by julienguy** [comment]
A median is too noisy compared to a weighted average (sky lines have varying intensities, and we have few of them, especially in the blue camera), I tested this. I improved the outlier rejection, and changed the order of the different processing steps in procexp.py when we are both subtracting sky with varying throughput and rejecting cosmic rays.
The resulting throughput correction rms and max deviation on a dark exposure **with** cosmic rays are 
b: rms= 0.006 , max err= 0.014        
r: rms= 0.004 , max err= 0.013        
z: rms= 0.002 , max err= 0.006 

So if we expect random variations of throughput of ~2% due to FRD, refitting the throughput on sky lines would be an improvement  (we still have to check the impact of this procedure on the redshift efficiency).

![corr-2](https://user-images.githubusercontent.com/5192160/35597977-d25c5eda-05d5-11e8-96da-6513ab49b177.png)

**Comment by julienguy** [comment]
Mistake in the max error in the above message. It's 
b: rms= 0.006 , max err= 0.026
r: rms= 0.004 , max err= 0.013
z: rms= 0.002 , max err= 0.006

**Comment by julienguy** [comment]
- point 3 (achromatic FRD variation correction per fiber) is merged.
 - point 2 ( sky non-uniformities) implemented in branch nonuniform_sky. The computation time is too slow for now (~5 minutes per process and frame for a degree 1 fit). This is dominated by the computation of the covariance matrix because the system is quite large (n_wave * n_polynomial_coef). Need some approximation for the sky model error propagation.

**Comment by julienguy** [comment]
Non-uniform sky fit implemented in branch non_uniform_sky.

 - Three routines are implemented in desispec.sky:
  1) ```compute_uniform_sky``` 
SkyFlux_fiber = R_fiber SkySpectrum

  2) ```compute_polynomial_times_sky``` 
SkyFlux_fiber = R_fiber Polynomial_3D(x_fiber,y_fiber,wave) SkySpectrum

  3) ```compute_non_uniform_sky``` 
SkyFlux_fiber = R_fiber [ SkySpectrum_0 + x_fiber SkySpectrum_1 + y_fiber SkySpectrum_2 ... ]

- ```compute_sky``` calls one of the 3 depending on the parameters ```angular_variation_deg``` and ```chromatic_variation_deg```

**Comment by julienguy** [comment]
Item 1)  moved to new ticket #518 
Closing this issue because 2) and 3) are implemented.
