### ISSUE TITLE
desispec.parallel tests broken on edison login nodes

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#397]
desispec.parallel unit tests are failing on edison login nodes:
```
[edison06 master] python py/desispec/test/test_parallel.py 
.[Mon Jun 12 12:12:03 2017] [unknown] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(525): 
MPID_Init(228).......: channel initialization failed
MPID_Init(601).......:  PMI2 init failed: 1 
Aborted
```
They pass on my laptop which does not have mpi4py installed.  I suspect this came in via Ted's pipeline refactor in PR #394 and is caused by some check that tries to use mpi4py if it is installed or a fake communicator otherwise.  NERSC login nodes are in an evil middle ground: mpi4py is installed but will crash if you try to load it since it tries to initialize MPI and that is forbidden on the login nodes.

@tskisner please investigate and fix.  Getting our tests working again for the collaboration meeting is high priority.

**Comment by tskisner** [comment]
Why are we running the unit tests on the login nodes?  That basically means that we can't run any unit tests that use MPI.  I always run unit tests from an interactive session on a compute node.  If this is being done by a cron job, we should launch them with a batch script.

**Comment by sbailey** [comment]
I hit this via the nightly cronjob that updates and tests the master copy of all our packages on edison.  Batching them could be reasonable to get more coverage though the full suite across all packages takes longer than the 30 minute debug queue so it would take several jobs.  But even if batch testing covers more, we shouldn't break tests on the login nodes.

**Comment by sbailey** [comment]
To clarify (hopefully):  The requirement isn't that MPI should be tested on edison login nodes (which is impossible given the login node configuration), but rather that if someone does run "python setup.py test" then it will test whatever it can and not crash.  If the currently problematic function is intended to work on non-MPI systems (e.g. by falling back to rank=0, size=1 or a fake MPI communicator class), then it should also do that for NERSC login nodes.  If the function only makes sense in the context of an MPI-enabled node, then ok to just skip those tests.

**Comment by tskisner** [comment]
I do not know (without poking into undocumented Cray environment variables, etc) any way to distinguish a NERSC login node from a NERSC compute node.  Both of them define NERSC_HOST.  Both of them have mpi4py / MPICH installed.  The hostnames follow a different pattern, but that seems silly to hardcode into our source.  Deep in Cray's MPICH library, when MPI_Init is called it decides (somehow) whether this is a login node.

For now, I'm disabling the unit test that brought in this MPI import.  We can revisit it later.

**Comment by moustakas** [comment]
What about spawning a tiny 2-node MPI script with mpi4py in a try, except
block?

**Comment by tskisner** [comment]
I would be in favor of just using a separate test runner command (like "python setup.py test_mpi") that ran a superset of the tests, including ones that needed MPI.  Let's punt on this until we have more unit tests that are impacted.

**Comment by tskisner** [comment]
pull request #399 is open, and I'll merge it once tests complete.
