### ISSUE TITLE
spectra metadata

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#406]
Currently the spectra regouping augments the fibermap metadata with NIGHT and EXPID.  Several additional requests:

fibermap columns:
* TILEID: so that redrock can count NUMTILES from the spectra files themselves without having to go back into other files to look up the (NIGHT,EXPID) -> TILEID mapping.
* HPXPIXEL: eventually this will come as part of the target catalog propagated into the fibermap, but until we have that input chain going we could add it to the output at the regrouping step.
  * Note: after discussion with Adam, we agreed to keep this as a column even though all entries would be the same for a given spectra file.  This makes it easier to propagate forward into a redshift catalog that does have different HPXPIXEL values, or to consider alternate groupings of spectra ("here are my 100 favorite crazy objects...")

header keywords (optional for the user-generated "random grouping" case)
* HPXNSIDE: so that it is derivable from the file contents and not just from the file name
* HPXNEST = True: just to be really clear that this is NEST not RING

I was going to try to implement these today and rerun, but Adam wisely warned me off that and recommended a post-facto updating of the dc17a files so that people can see what we will do, but without going through an actual reprocessing (limited more my redrock rerunning than spectral regrouping)

**Comment by tskisner** [comment]
I can certainly make these changes if you like.  Also, recall that the Spectra class defines its fibermap columns independent of the main fibermap definition.  Originally these were defined by copying the fibermap definition and then appending columns.  There was a circular dependency here, and duplication was a quick fix.  However, the best solution is to put the fibermap specification into its own file that can be sourced in multiple places.  Lets do that at the same time as augmenting the columns.

**Comment by tskisner** [comment]
@sbailey , do you mind if I combine this change with the promotion of wavelengths to double precision in #469 (since they both impact the spectra class)?

**Comment by sbailey** [comment]
That's fine, but let me finish my branch on this first (I think you have plenty to do on daily scripts and progress DB without needing to work on this; ping me offline if that is wrong).

**Comment by sbailey** [comment]
Extra columns / keywords added in PR #473.  Closing.
