### ISSUE TITLE
desispec.io.read_spectra failing for large spectra file

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#430]
Problem to read the  largest spectra file from the DC 2% challenge at NERSC, on cori.
It's apparently not an issue with the file system. I can read an hdu in the file without problem with astropy.io.fits. But the following hangs with a memory leak 
```
from desispec.io import read_spectra
spectra = read_spectra("/project/projectdirs/desi/datachallenge/dc17a-twopct/spectro/redux/dc17a2/spectra-64/327/32723/spectra-64-32723.fits")
```

**Comment by julienguy** [comment]
More details
- I can read the file with desispec.io on the cori login node
- I cannot read the file on an interactive node (process on disk wait + memory leak)
- If I first copy the file to $SCRATCH , I can read it on the interactive node

So,
- we have to think about how to catch this kind of I/O issue in the pipeline (this would certainly block a MPI run).
- we'd better copy fits files on $SCRATCH before reading them

**Comment by tskisner** [comment]
I'm not sure how to advertise that fact for the whole collaboration, but /project should only be used as a staging / archive area.  All working datasets should be on $SCRATCH, with the exception of small files that are read by one process.

For example, for "real" data processing, we will likely need to keep the most recent "N" days of data copied to scratch, so that the nightly processing uses that data.

**Comment by sbailey** [comment]
I don't see how project vs. scratch could trigger vs. avoid a memory leak.  They should only differ in performance.  How did you determine memory leak vs. just slow?  If project is really causing user code to do something different, we should escalate this with NERSC.

That being said, `astropy.io.fits` does evil things under the hood while trying to do memmapping such that closing the file doesn't necessarily actually close the file.  Using `astropy.io.fits.open(..., memmap=False)` within `read_spectra()` might fix the problem.  Can you try that Julien?

Although I agree with @tskisner that $SCRATCH should be used for production runs for efficiency, we absolutely must be able to use `desispec.io.read_spectra` to load data from project, including from small batch jobs.

**Comment by julienguy** [comment]
As is often the case with I/O issues, I cannot reproduce the bug. I can now read this spectra file on an interactive node with read_spectra without any change to the function ...

**Comment by tskisner** [comment]
This sounds like it was a transient filesystem issue.  Closing for now, but feel free to re-open if you see it again.
