### ISSUE TITLE
tune job allocation times

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#443]
desi_pipe is considerably overallocating the job wall time requests.  Perhaps it is currently tuned for KNL and not Haswell?  e.g. from a minitest for the fiberflat-calibrate steps:

night | exposures | nodes | requested time | actual time
-----|------------|-------|----------------|-------------
20200315 | 19 | 25 | 1:05:00 | 00:05:16
20200316 | 13 | 14 | 1:05:00 | 00:05:00
20200318 | 12 | 12 | 1:05:00 | 00:04:33
20200319 | 13 | 14 | 1:05:00 | 00:04:57
20200320 | 7 | 2 | 1:05:00 | 00:06:05
20200321 | 7 | 2 | 1:05:00 | 00:06:19
20200322 | 7 | 2 | 1:05:00 | 00:06:14

Review this for all steps and fix the time requested per job.

**Comment by tskisner** [comment]
Yes, currently the script generation is not specific to a particular machine.  That needs to be changed since the timing is vastly different between the systems.

**Comment by julienguy** [comment]
Job allocation time has been tuned for edison in branch running_a_month_of_data.
The pipeline with this setup is running smoothly from CCD images to calibrated frames on edison.
 - PSF, 3 exposures, 8.30 min on 151 nodes, job allocation = 15min 
 - PSF combine, 1 min on 2 nodes, job allocation = 2min
 - Extraction (17 exposures), 26 min on 213 nodes,  job allocation = 30min
 - Fiber flat / sky / calibration (14 exposures), 9 min on 36 nodes, job allocation = 24min

**Comment by sbailey** [comment]
please also update the numbers for the spectral regrouping (desi_group_spectra) and redrock, and then I think we can close this issue.

**Comment by tskisner** [comment]
We should either leave this open or open a new issue to track moving of per-machine timing information into a separate config file.

**Comment by julienguy** [comment]
I am waiting for the implementation of the spectral grouping and redshift per night before tuning those for edison.

**Comment by tskisner** [comment]
In the new pipeline, all tasks provide a run_time() method which returns the minutes for a single task running on edison at the max number of processes.  One exception is redshift fitting, which is overly conservative right now, especially once we are updating only a few spectra per pixel per night.  We have a separate issue tracking that (#524).  @julienguy, Ok to close this issue then?

**Comment by julienguy** [comment]
yes
