### ISSUE TITLE
extractions run slower on more recent desiconda versions

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#452]
We have a performance regression for spectral extractions when using  the more recent installations of desiconda at NERSC.  Using the same version of desispec, the newer versions of desiconda run ~30% slower than the default 20170613-1.1.4-spectro.  Figure out why and fix that for future desiconda installations.

Versions compared:
* /global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro:
  current default used by desimodules/17.9 and desimodules/master
* /global/common/cori/contrib/desi/desiconda/20170818-1.1.12-spec:
  I think this came along for the ride while making a new release for the imaging folks;
  I don't think we've used it.
* /global/common/software/desi/cori/desiconda/20170920-1.2.0-spec:
  Experimental new install using Intel Distribution Python, Intel compilers, latest MKL,
  etc.  It also comes with a coriknl version.

Here are the library versions and runtimes for desi_extract_spectra for 25 spectra x 1500 wavelengths:
```
            1.1.4       1.1.12      1.2.0
python      Ana 3.5.3   Ana 3.5.4   IDP 3.6.2
numpy       1.11.3      1.13.1      1.13.1
scipy       0.19.0      0.19.1      0.19.1
astropy     1.3.3       2.0.1(!)    2.0.1(!)
mkl         2017.0.1    2017.0.3    2018.0.0
Time in seconds to extract 25 spec x 1500 wavelengths:
Haswell     98.5        117.5       131.2
KNLx3       701.7       ---         852.0      
```

The KNL tests were slow enough that I actually just ran 500 wavelengths and then multiplied the timing by 3.

What I ran:
```
#- One of these to get an interactive job:
salloc -N 1 -t 1:00:00 -C haswell --qos interactive
salloc -N 1 -t 1:00:00 -C knl --qos interactive

#- Then one of these to pick the version:
module use /global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/modulefiles
module use /global/common/cori/contrib/desi/desiconda/20170818-1.1.12-spec/modulefiles
module use /global/common/software/desi/cori/desiconda/20170920-1.2.0-spec/modulefiles
module use /global/common/software/desi/coriknl/desiconda/20170920-1.2.0-spec/modulefiles

#- Actually load desiconda
module load desiconda

#- Configure desispec, using my checkouts of desiutil, desispec, and specter since those aren't installed systemwide for every version of desiconda
module load desiconda
module load desiutil/sjb
module load desispec/sjb
module load specter/sjb

#- Run a wakeup job x3 to revive the disk, etc. until timing is stable
#- First run often has more overhead
time desi_extract_spectra \
    -i pix-r0-00000002.fits -f fibermap-00000002.fits \
    -p psf-r0-00000000.fits -o blat.fits --nspec 25 -w 6000,6100,1

#- Then run the larger test for timing
time desi_extract_spectra \
    -i pix-r0-00000002.fits -f fibermap-00000002.fits \
    -p psf-r0-00000000.fits -o blat.fits --nspec 25 -w 6000,7500,1
```

The fix will likely be on the desiconda side, but I'm filing it here in desispec because it impacts `desi_extract_spectra` and we tend to pay more attention to this repo than the desiconda repo.

**Comment by tskisner** [comment]
Interesting.  So the changes are numpy / astropy / mkl versions and the fact that IDP has numpy / scipy built with icc instead of gcc (they build python itself with gcc).  We may have to time the individual pieces of the extraction a little more fine-grained to see which piece slowed down.  I can look at this a bit when I am doing the test runs for #443 (after https://github.com/desihub/redrock/issues/36)

**Comment by tskisner** [comment]
I believe this is closed by switching back to anaconda in desihub/desiconda@7337c8238f38b0b95b424427d7250250e7adcbe4

@sbailey , please re-open if you disagree.
