### ISSUE TITLE
single node extraction MPI scaling

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#453]
If OMP_NUM_THREADS=1, I was expecting that if I could extract 1 bundle in X minutes using 1 core, then I could extract M bundles in ~X minutes using M cores.  i.e. that the MPI extraction ranks work independently and wouldn't slow each other down.

Instead, I see that 20 bundles with 20 cores is ~35% slower than 1 bundle with 1 core.
I tested this by adding timing print statements around just the extraction portion of `desispec.scripts.extract.main_mpi` so that it does *not* count the startup time which does get slower with more ranks because more processes are reading the input files, loading python modules, etc.

It would be helpful to understand why the ranks are interfering with each other and if anything can be done to improve this scaling of otherwise completely independent operations.

![bundle-scaling](https://user-images.githubusercontent.com/218471/32078740-eea9498c-ba5c-11e7-91bc-9174b35f79e6.png)

Example commands on a cori interactive node, changing the `srun -n` parameter and the `desi_extract_spectra --nspec` parameter so that there is an equal amount of work per MPI rank in both cases.
```
cd /global/cscratch1/sd/sjbailey/desi/dev/extract/
srun -n 1 -c 2 --cpu_bind=cores desi_extract_spectra \
    --mpi -i pix-r0-00000002.fits -f fibermap-00000002.fits \
    -p psf-r0-00000000.fits -o blat-r0.fits --nspec 25 -w 6000,7000,1
```
vs.
```
srun -n 20 -c 2 --cpu_bind=cores desi_extract_spectra \
    --mpi -i pix-r0-00000002.fits -f fibermap-00000002.fits \
    -p psf-r0-00000000.fits -o blat-r0.fits --nspec 500 -w 6000,7000,1
```

**Comment by tskisner** [comment]
One thought off the top of my head- since the PSF class is not serializable (or at least it wasn't a year or so ago last I tried), we are not able to read and broadcast that.  Instead, every process opens and reads the same PSF file.  This would be another candidate data object for reading into MPI shared memory.

**Comment by samikama** [comment]
Hi @sbailey, There can be many reasons. With single core you probably get turbo boost on, which is lost on many cores. Also your operations are usually on large matrices. For single core, more of these may fit in the cache and access to memory is reduced. Once you start multiple processes you start to hit the memory more often and then memory bandwidth is saturated. Also when you start multiple cores, unless you pin them, they usually move around the slots which worsen the situation. Moreover when numpy is linked to MKL, it will make use of all cores for linalg operations. Depending on number and scale of such operations many processes will affect each other from minimal to extreme levels.

Of course these are all speculations. One has to profile and look at the results.

Cheers,
Sami

**Comment by sbailey** [comment]
Thanks for the ideas.  A few comments:

> One thought off the top of my head- since the PSF class is not serializable (or at least it wasn't a year or so ago last I tried), we are not able to read and broadcast that. Instead, every process opens and reads the same PSF file. This would be another candidate data object for reading into MPI shared memory.

This timing test specifically starts *after* loading the PSF and other input files; it is just testing the timing of the extractions and writing out each bundle, but not the initial data loading (which does take longer as more ranks are reading in the same files, but that is less surprising).  It also doesn't include the time to merge the bundles.

>With single core you probably get turbo boost on, which is lost on many cores.

I'm not familiar with that feature, but the trend is smooth with increasing cores, without some cliff with turbo boost on/off.
 
> Also your operations are usually on large matrices. For single core, more of these may fit in the cache and access to memory is reduced. Once you start multiple processes you start to hit the memory more often and then memory bandwidth is saturated.

Certainly possible.  Seems like the most likely candidate, and a hard one to solve.

> Also when you start multiple cores, unless you pin them, they usually move around the slots which worsen the situation.

I thought MPI took care of locking down the CPU affinity for me, so I don't think this is an issue for this case.

>  Moreover when numpy is linked to MKL, it will make use of all cores for linalg operations. Depending on number and scale of such operations many processes will affect each other from minimal to extreme levels.

I used OMP_NUM_THREADS=1 and MKL_NUM_THREADS not set, so the MKL operations should be restricted to a single core per rank and not fan out to all cores.

**Comment by sbailey** [comment]
No action item here so closing ticket.
