### ISSUE TITLE
Generate per-night spectral grouping scripts

### ISSUE THREAD

**Issue by tskisner** [desihub/desispec#455]
The spectral grouping code already has a parameter to process a single night (or several nights) of data.  In that case, the existing spectra files touched by exposures on that night are opened and loaded into memory.  Then the cframe files are read and the spectra for those frames are updated or appended.  The the modified files are written back out.

When desi_pipe creates the slurm scripts, currently it just creates a single large script that regroups everything.  We need to also generate nightly regrouping scripts.

**Comment by julienguy** [comment]
Done in PR #523 , by construction.
