### ISSUE TITLE
failing coadds

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#46]
@dkirkby : Branch test-coadds introduces some basic unit tests of the coadditions using the coaddition.Spectrum class.  These fail, choking on the `self.Cinv += other.Cinv` accumulation: apparently csc_matrix supports `x + y` but not `x += y`.

It is possible that I'm just misunderstanding how Spectrum should be used since I thought I previously had successfully run coadds, though I don't see how those could have worked given the current problem.

**Comment by weaverba137** [comment]
Is the test-coadds branch still active?

**Comment by sbailey** [comment]
This appears to have been an effect from different numpy versions.  It has been fixed in the code for recent versions of numpy for awhile now.  Closing issue.
