### ISSUE TITLE
desi_pipe --fakepix shouldn't generate PSF steps

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#460]
`desi_pipe --fakepix` shouldn't generate job scripts for steps bootstrap, psf, or psfcombine, since these can't be run without the pixel level data.  It does skip the extract step (good).

Having these script is mostly harmless, but it does mean that we currently can't use run/scripts/run_slurm.sh to launch N>>1 nights of jobs because it launches jobs that are going to fail and thus block the fiberflat-calibrate*.slurm jobs that should succeed.  The workaround is to individually launch the run/scripts/{NIGHT}/fiberflat-calibrate_{NIGHT}.slurm scripts individually.

Context: `desi_pipe --fakepix` is used when quickgen or fastframe directly generate frame files and then we want to continue with spectro pipeline processing.  In this case pixel-level raw data isn't available and so steps prior to fiberflat can't be run.

**Comment by tskisner** [comment]
The pipeline is now completely re-written, and job scripts are generated on demand.  Also, the DB is used to track the state of objects.  If some external script generates objects in the production, we need a way to mark them as "done" in the database.  This can be done with
```
desi_pipe sync [--nights]
```
which will look at all tasks in the DB and check their state on the filesystem.  However, in reality this will not work fully until we close #530.  I will leave this open until then.

**Comment by tskisner** [comment]
This ticket is now irrelevant.  After generating random files, the ```desi_pipe create --force``` command can create a production over top of an existing directory.  If simulation tools are used to create any files in the production, ```desi_pipe sync``` can be used to bring the database into line with the files that exist.
