### ISSUE TITLE
Missing factor and a typo in resolution.Resolution object

### ISSUE THREAD

**Issue by samikama** [desihub/desispec#468]
Hello,

During the calculation of _gauss_pix(), centroid scaling for erf in line 171, 
`     x = (np.asarray(x, dtype=float) - mean) / sigma`
a sqrt(2) factor for sigma seems to be forgotten. I believe it should be
`     x = (np.asarray(x, dtype=float) - mean) / (sigma*np.sqrt(2))`

Also during the calculation of bin boundaries from bin centers in line 176,
`    edges = np.concatenate([x-dx/2, x[-1:]+dx/2])`
leads to incorrect calculation of bin boundaries. It should be
`    edges = np.concatenate([x+dx/2, x[-1:]-dx/2])`

Could you please check and verify if these are correct?

**Comment by julienguy** [comment]
- yes for ``` x = (np.asarray(x, dtype=float) - mean) / (sigma*np.sqrt(2))```
 - no for the change to ``` edges = np.concatenate([x+dx/2, x[-1:]-dx/2]) ```

I tested this routine. Fixed in PR 499.
I am opening another issue on the Resolution constructor.
