### ISSUE TITLE
Wavelengths in spectra-* output files are single-precision

### ISSUE THREAD

**Issue by djschlegel** [desihub/desispec#469]
The spectra-NSIDE-PIXNUM.fits have HDUs B_WAVELENGTH,R_WAVELENGTH,Z_WAVELENGTH which are single-precision floating-point vectors.  This is consistent between the Data Model and the output files.  However, we likely would prefer these to be double-precision, otherwise using these values to convert to fnu units or whatever would introduce IEEE rounding errors up to 0.1% at the longest wavelengths.  Avoid this problem by storing these vectors as double-precision floats; the file sizes would only be minimally larger.

I suppose another possible solution would be to appropriately choose BZERO,BSCALE keywords, and in that case the data vector could be 16-bit integers.  But that seems like a fragile solution.

**Comment by sbailey** [comment]
Wavelengths float -> double implemented in PR #473.  Closing this ticket.
