### ISSUE TITLE
Use a database to track production state

### ISSUE THREAD

**Issue by tskisner** [desihub/desispec#472]
Currently the state of all objects in the processing is dumped to a yaml file at the end of each processing step and queried from the filesystem at the start of each processing step.  This is slow and inefficient.  Using the sqlalchemy package that is used for the raw data DB, replace the code in https://github.com/desihub/desispec/blob/master/py/desispec/pipeline/state.py with code that loads / saves objects and their state to a DB.

**Comment by julienguy** [comment]
Done in PR #523 . Both sqlite and postgres are supported, tested at scale at NERSC.
