### ISSUE TITLE
Merge database modules

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#475]
We currently have two Python modules that load pipeline outputs into a database: `desispec.database.spectra` and `desispec.database.datachallenge`.  The first one is focused on the results of `quicksurvey`, while the second is focused on data challenge outputs, and, most recently, the minitest notebook outputs.

These should be merged when the data model of `quicksurvey` and the main pipeline (as run in data challenges, minitest, etc.) converges, but I don't know if this has happened yet.

@sbailey, do you know the answer to this?

**Comment by sbailey** [comment]
They have not converged, but please focus on the outputs of the minitest as that is closest to what the final outputs should be, and is the direction toward which the convergence should happen.

**Comment by weaverba137** [comment]
Yes, will do.

**Comment by sbailey** [comment]
Let's not use `desispec.database.pipeline` since there is another database for tracking the progress of the spectroscopic pipeline.  `desispec.database.redshift` is ok.

**Comment by weaverba137** [comment]
Very good.
