### ISSUE TITLE
make preproc a pipeline step

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#483]
Currently we run preprocessing on the raw data files at the time we simulate them, and the preprocessed pix files are written alongside the raw data.  Although this has been convenient, preprocessing should actually be a pipeline step and the pix files should be kept in the redux output instead of the raw data input.  e.g. different versions of the pipeline could have different cosmic ray finder algorithms and thus different pix files.

Pragmatic notes: The pix files are huge.  We may need to experiment with when to keep vs. delete vs. regenerate them to balance the convenience of having them for debugging vs. the pain of disk allocations and moving large files around.  Preproc takes ~20 sec per frame, dominated by the cosmic ray finding iterations.

For consideration: extractions and PSF fitting could generate them on-the-fly as needed, but we should also have a pipeline-generated script that can rerun just preproc step in case we need to delete them to save disk space, but later want to get them back for debugging.

**Comment by julienguy** [comment]
Done in PR #523.
