### ISSUE TITLE
spectra summary / QA info into new frame file table

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#484]
Add a new table to c/frame files with some basic info about each spectrum, to be propagated and augmented from frame –> cframe -> spectra -> zbest, e.g.

Could be derived from initial frame file:
* COUNTS_RAW_[BRZ]: integrated uncalibrated raw counts for each spectrum
* MEDIAN_RAW_[BRZ]: median raw counts for each spectrum
* SN_MEDIAN_[BRZ]: median of S/N per Angstrom
  * per Angstrom so that the metric remains comparable across extractions on different wavelength grids

Requires calibration:
* COUNTS_OBJ_[BRZ]: integrated fiberflat-fielded sky-subtracted counts
* MEDIAN_OBJ_[BRZ]: integrated fiberflat-fielded sky-subtracted counts
* COUNTS_SKY_[BRZ]: integrated sky counts
* MEDIAN_SKY_[BRZ]: integrated sky counts
* SPECTRO_FLUX_[UGRIZ]: integrated flux

Requires redshift fitting:
* MODEL_FLUX_[UGRIZ]: integrated flux of the best fit model

Other?

TBD: the `_[BRZ]` or `[_UGRIZ]` suffixes represent wavelength ranges over which the sum/median occurs, matching the >50% max throughput wavelengths for filters of those names.  Competing goals:
* metrics should come from a single camera (brz) and not have to combine information across frames
* metrics should match standard photometric filters

Photometric g and r nicely fit within our spectrograph b and r coverage.  Photometric z has a long tail but the >50% region fits within spectrograph z.  Photometric i spans spectrograph r,z.  It would also be handy to have metrics tied to whatever filter is used for the sky monitor cameras.

**Comment by julienguy** [comment]
Done in PR 492.
