### ISSUE TITLE
update desispec to astropy 2.x

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#486]
Update desispec to be astropy 2.x compatible.  Maintain astropy 1.3.x compatibility if possible.

**Comment by weaverba137** [comment]
Just had an encounter with astropy/astropy#5267.

**Comment by weaverba137** [comment]
I also noticed that we're still running Travis tests against speclite 0.5.  Is there a particular reason for that?

**Comment by sbailey** [comment]
Sometimes we test against the oldest known version of package X that will work so that it makes it obvious when something changes that would require a newer version of a dependency.  And sometimes in practice all the dependency versions get updated to some more recent set of known reference versions that work together.

i.e. if speclite 0.5 still works for desispec, let's leave it at that unless there was a known non-backwards compatible change in 0.6 or 0.7 that we want to check.  Or if there is some other reason to upgrade for travis (e.g. maybe speclite 0.5 doesn't work with astropy 2.x?), then it is fine to upgrade.

Somewhat beyond the scope of the original question, but our core dependency policies are:
* master version of everything should always work together
  * i.e. don't merge something into master of X if it depends upon a branch of Y; wait for the merge of Y first.
* the latest tags of everything should always work together
  * i.e. don't tag X if it still depends upon master of Y; tag Y first.
* don't depend upon the absolute latest version of an external package if you don't really have to
  * i.e. try to avoid constantly having to upgrade external packages

Travis dependencies shouldn't be in conflict with those policies, but we haven't used Travis for strictly checking/enforcing them either.

**Comment by weaverba137** [comment]
OK, but speclite 0.7 is installed in desiconda at NERSC.  So we're not running Travis tests against the version at NERSC.  I don't disagree with the policy, but the policy should at least reflect the versions that we're actually using in the production environment.

**Comment by sbailey** [comment]
OK, updating Travis to speclite 0.7 is fine.
