### ISSUE TITLE
add desi_compute_trace_shifts to pipeline

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#487]
Add `desi_compute_trace_shifts` to the DESI pipeline processing.  The code exists, it just needs to be added as a pipeline step.  This involves expanding the datamodel so that the psfnight is adjusted and re-written as a new PSF file with the new x-y-wavelength solution for each science exposure.  Subsequent extractions then use the per-exposure PSF instead of the psfnight.

**Comment by julienguy** [comment]
Implemented in branch traceshift_pipeline
