### ISSUE TITLE
Refactor to support easier running of pipeline pieces

### ISSUE THREAD

**Issue by tskisner** [desihub/desispec#488]
Adding notes here from a whiteboard discussion on 2018-01-11.  There are many use cases (such as small test jobs during commissioning, data exploration, debugging, etc) which we would like to enable by making it trivial to specify a given object to generate and calling 1-2 simple functions to get all the dependencies needed for that object and write out a slurm / bash script which would do the work.

The main performance hold-up for this is #472 .  Once that is implemented, there are some pieces of the current code which are irrelevant and will disappear.  There are other pieces that should be made more modular.  Here I want to lay out a "two stage" refactor to achieve this with minimal down time.

## Stage 1

- Create a new desispec.pipeline.db module which is focused on a simple schema using sqliteDB for now.  We can switch to sqlalchemy later as needed.  I will keep details about that under #472.
    - Simple class for creating tables and providing the raw connection handle for advanced use cases.
    - Trivially support an in-memory DB too
    - Method to update the DB based on raw data (essentially look for any new fibermaps).
    - Move existing helper functions from graph.py that split / join object names into their properties (object type, band, spec, expid, etc).
    - Add trivial function to get input dependencies given an object name.
    - graph.py is dead and removed.
- state.py is dead and replaced by the db module above
- Some other rearranging of functions in the source files.

At the end of this work, a user could manually get the inputs for a given task and call the run() method of a worker on it.  Obviously that is clunky, but will be addressed in Stage 2.

## Stage 2

- Move much of the script-generation logic from desispec.scripts.pipe_prod into a module inside desispec.pipeline.  This is to better support users generating their own scripts.
- Merge redundant code in pipeline.run.run_step() and pipeline.run.retry_task() in a single "run_task" function called by both.
- helper function that takes an object and its inputs (returned by function in db module) and calls the "run_task" function on it.
- New desi_pipe_run_task (or similar) script which runs a single task.  This simply calls the function above.
- New entry point script which takes a list of objects.  This script can use either an existing DB to check state or read the filesystem on the fly.  It then calls the function to get the object dependencies, and generates slurm or bash scripts which run a single task.  

After this work, other tasks become easier.  Users can immediately generate scripts to run single tasks, with or without creating a production directory.  The "nightly" scripts (#304) become simpler entry points that generate transient slurm scripts which are run and thrown away- those scripts don't need to live as part of the production.

**Comment by julienguy** [comment]
Some comments 

 - I agree with the stage 1 / stage 2 splitting.
 - stage 1 "Add trivial function to get input dependencies given an object name."
It should be simple to add a new object type (or pipeline task) with its dependencies without touching the rest of the code. For instance, the easiest for me would be to have one python file per task instead of a single task.py file with all of them. If the class name matches the object name, the code could automatically instantiate the class with getattr() function.
 - "At the end of this work, a user could manually get the inputs for a given task and call the run() method of a worker on it." That's not totally obvious for me what you mean here. An example would be useful.

**Comment by tskisner** [comment]
For your second bullet, after this change, adding new objects should be a matter of editing some lists / dictionaries of the names of the object types.  As for adding pipeline tasks, that would require also adding that to a list of valid steps and then providing a "worker" class for that type of task.  We could definitely autodetect the worker class to use based on file names.  However, what happens in the case of multiple workers for a given task?  Currently that is controlled by the options.yaml file when working with a production, but perhaps that could also be specified on the command line in the case of running a task outside of a production.  Something to discuss more.

**Comment by tskisner** [comment]
The multiple stages proved challenging, so I am prototyping a wholesale refactor of desispec pipeline to address the previous whiteboard discussion.  Also some other requested features that make it easier to add new pipeline steps (preprocessing, QA, etc).

Some features:

One class per pipeline task.  Example stub for psf: https://github.com/desihub/desispec/blob/tsk_dbprod/py/desispec/pipeline/tasks/psf.py

**Comment by tskisner** [comment]
Questions:

1.  Creating a "production" will now just create the directory layout and the DB.  Do we want to generate any task lists or scripts at that time?

2.  In "manual" mode, a user should be able to
- generate a task list
- edit that if desired
- generate a shell / slurm script to run those tasks
- run / submit the script

3.  In normal production runs, do we want to generate the task list and slurm script on the fly and submit it?  This would be instead of pre-creating every
possible combination of slurm script.

So imagine:

desi_pipe_tasks psf 20190910
  (looks up all psf tasks for that night, writes to file)

desi_pipe_check_tasks <file>
  (reads task file, checks status in DB)

desi_pipe_run_tasks <file>
  (runs the tasks in the file)

desi_pipe_run psf 20190910
  (creates task list and slurm script, dumping those to a log directory, then
  submits the slurm script)

desi_pipe_run_night 20190910
  (submits chain of jobs for all task types)

For discussion on our phone call...

**Comment by tskisner** [comment]
This was finally fully implemented in the pipeline refactor.  Closed by 8daf6f0059735e819734db4e0c76019f6e6bbe7e
