### ISSUE TITLE
Create `io.findfile()` function

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#49]
We need a `io.findfile()` function that will:

* Be aware of the DESI file hierarchy.
* Work at NERSC & on someone's laptop.
* Download files as needed, using `io.download` (see #48).
* Optionally, accept a file *type*, with parameters, rather than a full file name.

**Comment by sbailey** [comment]
Note that desispec.io.findfile already exists.  The functionality for this ticket should be to just add a download=True/False option that would use io.download() (See ticket #48) to get the data if it doesn't already exist locally.  It even has a placeholder "fetch" option in the docstring, though perhaps that should be renamed to "download" instead.

**Comment by weaverba137** [comment]
OK, I see it.  That brings up a question though.  Currently, desispec.io.findfile is designed to find exactly *one* file, not a set of files.  So do we want findfile to find *sets* of files, then download them all with one call to download(), or do we want findfile to find *one* file and call download() one time for every file?

**Comment by sbailey** [comment]
io.download() should definitely support downloading multiple files at once.

OK if io.findfile(..., download=True) only downloads a single file at a time.

It would be handy if the syntax of io.download() could accept a set of paths generated by io.findfile for bulk downloads, e.g.

    for spectrograph in range(10):
        for channel in ['b', 'r', 'z']:
            camera = channel+str(spectrograph)
            filenames.append(io.findfile('frame', night='20191031', expid=234123, camera=camera))

    io.download(filenames)

Note: in my comment on the io.download() ticket #48, I advocated for the filenames to be relative to $DESI_SPECTRO_REDUX/$PRODNAME; this example here is actually passing full local paths to io.download().  We'd probably want an option to io.findfile to only return relative paths (could be handy for scripting too), or a utility function that knows how to strip $DESI_SPECTRO_REDUX/$PRODNAME off of an absolute path.

We also want a function that can do query-like operations to return multiple files that could then be passed to io.download(), but it feels like feature-creep for io.findfile() to be that query code too.  That query function should be the topic of a separate ticket.

**Comment by sbailey** [comment]
Just had an in-person chat with Ben.  I think we converged upon:

  * io.findfile() will continue to return full filepaths
  * a new io.filepath2url() function will know how to convert that into a URL for downloading, including stripping off leading $DESI_SPECTRO_REDUX/$PRODNAME/
  * io.download() will accept either filepaths or urls and know how to download them and put them locally
    * this implies a io.url2filepath() too...
