### ISSUE TITLE
fix frame BUNIT; check usage

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#493]
Gack.  frame files have BUNIT='photon/bin' but its actually 'electron/Angstrom' since specter.extract.ex2d converts to [X]/Angstrom as the last step before returning the extracted spectrum.

Fix frame file BUNIT keyword and review our flux calibration etc. code to see if it is assuming electrons/bin or electrons/Angstrom.

This lead to a misunderstanding in scores calculations in PR #492, which will also need to be fixed.  This could be done as part of that PR to make sure everything is self-consistent.

**Comment by julienguy** [comment]
fixed in branch spec_score
