### ISSUE TITLE
NaNs in output files

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#498]
From desihub/redrock#97: /global/cscratch1/sd/jguy/sim2017/redux/month5/spectra-64/59/5925/spectra-64-5925.fits ended up with NaNs in the output.  Track down why, and instead of outputing NaN set flux=0 ivar=0 mask=something.

**Comment by julienguy** [comment]
- Inf values in frame.flux , fiber 160 of  
```/global/cscratch1/sd/jguy/sim2017/redux/month5/exposures/20191004/00003637/frame-r0-00003637.fits```
 - so it's at the extraction level.
 - wrong flux found in two fibers 160,161 in waves 5870 - 5920, neighboring fibers are ok, see figure below
 - nothing particular in CCD image (see other figure). psf and traces are ok.
 - so,  ... it's a mystery to be solved ...
![frame-r0-00003637](https://user-images.githubusercontent.com/5192160/35700404-be6aa06c-0747-11e8-9217-2705850a20bb.png)
below, FLUX,IVAR,MASK from top left to bottom right, zoom of preprocessed image pix-r0-00003637.fits, 
![pix-r0-00003637](https://user-images.githubusercontent.com/5192160/35700461-e5fbfbd0-0747-11e8-9b73-2ada5a43e653.png)

**Comment by sbailey** [comment]
Closing this old issue on simulated data, but see #2134 about NaNs in output extractions.
