### ISSUE TITLE
make QA faster

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#504]
Make `desi_qa_prod` and `desi_qa_skyresid` faster.  They currently take ~30 minutes each on the minitest notebook, which only has 18 exposures of 10 tiles (i.e. less than half a night of DESI observing).  We need something much much faster to be viable for full production running.

The I/O could be made much faster (e.g. with fitsio and not reading the resolution matrix that isn't used for QA), but even that doesn't appear to be the dominant factor.  A simple loop over all 540 frame files calling `desispec.io.read_frame` was able to read all of them in 2.8 minutes.

**Comment by profxj** [comment]
Sufficiently addressed by PR #593 (for now)
