### ISSUE TITLE
Allow write_bintable to set EXTNAME on other HDUs

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#522]
When using `desispec.io.util.write_bintable()` to write to a *new* file, the function allows EXTNAME to be set on the HDU that contains the binary table.  However, it does not allow EXTNAME to be set on HDU0, so the primary HDU has no EXTNAME.  In the DESI data model, the convention we've used so far is that empty HDU0 has EXTNAME 'PRIMARY', so it would be simple to at least *default* to this for `write_bintable()`.

**Comment by sbailey** [comment]
punting to 18.6
