### ISSUE TITLE
What code creates versions.json?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#539]
The [data model specifies](http://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_REDUX/SPECPROD/versions.json.html) that there should be a versions.json file in `$DESI_SPECTRO_REDUX/$SPECPROD`.  However, I could not find any code in desispec that creates this file.

**Comment by tskisner** [comment]
We have never created such a file before (to my knowledge).  I think that would require importing every desi package just to get its version string at prod creation time, correct?  And of course there is nothing stopping someone from loading a different software stack and working on an existing production.  I would vote for having the version strings of the software used encoded in the output data files from each piece of software.  That seems more traceable.  Just my $0.02 of course!

**Comment by weaverba137** [comment]
But we already get the versions for every package in order to set those in the FITS headers (via `desiutil.depend`), so the versions.json file would simply be a slightly more human-readable version of this information.

**Comment by tskisner** [comment]
I routinely (when doing development) run part of a production with one version of the code, then make changes to the code, update my install, and continue running the rest of the production.  The FITS headers hopefully reflect exactly the version used to create each file.

What versions should go in the single versions.json file for the production?  

What about during real operations when we find bugs in the code and need to keep running nightly data reductions?  Do we only switch code versions when going back and doing a re-processing from the beginning?  Or do we just swap in fixed code to the nightly processing and not worry about consistency until the next time we have a DR and go reprocess from the beginning?

These are all interesting questions for discussion...

**Comment by weaverba137** [comment]
All good questions, but let me emphasize that the point of this ticket is simply that the data model says that versions.json should exist, and currently it does not.  Maybe the resolution is to remove versions.json from the data model, but let's just focus on the existence or non-existence for now.

**Comment by sbailey** [comment]
`versions.json` was part of the original pipeline design (DESI-0893) that never got implemented; the relevant text is quoted below.  For now let's just remove it from the desidatamodel.

It might be useful to restore that for data assembly runs which should have a single version for any given package, but as @tskisner notes it is ill-defined for incremental development runs that might mix versions of a single package.

In the meantime, versions strings are already stored in the fits headers (good).

From DESI-0893:

> versions.json contains the versions of code, calibration libraries, and any other versioned input that went into this production. These versions should also be stored in the headers of the data files, but versions.json provides a single location for defining the code that went into this production.
>
> Note: this conceptually replaces the $RUN2D and $RUN1D directory structure of the BOSS pipeline. DESI has more pipeline steps that we want to individually version, and a directory structure 5 versions deep seems unwieldy.
>
> Interesting idea: Dustin said that the photometric processing will include module files for each production, such that loading that production would automatically load all the inputs used for that production.

**Comment by weaverba137** [comment]
OK, versions.json will be removed by desihub/desidatamodel#42.
