### ISSUE TITLE
Discrepancies in the merged yaml files for individual cameras

### ISSUE THREAD

**Issue by Srheft** [desihub/desispec#541]
This is one last critical check/change that needs to be done before I add the functionality that converts all yamls to jsons and creates a GENERAL_INFO block:

1.
As I mentioned before, there are 3 RA/DEC blocks in the merged file that are coming from the last three steps of the pipeline. The first two of these three RA/DE blocks have the size of 5000 as opposed to only include the 500 coordinates for the fibers assigned to that camera. The last of the three RA/DEC blocks contains 500 which is what it's supposed to be. If we are going to be releasing one json file for every camera, then we should only include the 500 coordinates from the fframe. If we are going to have the merged ALL cameras for each ARM, then we should have one block of 5000 coordinates up top in the general_info. Right now, there are two blocks of 5000 RA/DEC and one block of 500 RA/DEC in each of the merged files. @rkehoe: converge on this matter and follow up until sizes are unified.

2.
 The merged dictionary structure is designed as though there is going to be ONE merged file for a number of exposures and for ALL cameras in those exposures. Is this going to be ever the case or we will always have one merged json file for each of the 30 cameras? 

3.
In the current structure of the merged dictionary [in merger.py]  informational keys such as EXPID, NIGHT, FLAVOUR are placed such that they appear at the end of the file as opposed to the beginning. This is going to change together with the general_info block appearance. 

NOTE:
merger.py leaves some dictionary keys [such as PROGRAM] out of the merged yaml file and it shouldn't.

**Comment by sbailey** [comment]
Regarding (2) about the QA file merging: they should be structured such that *any* combination of exposures and cameras can be merged, even if there is a single standard way to do it.  e.g. commissioning will start before all spectrographs arrive; sometimes there will be a missing camera in the data stream; and custom debugging QA might want to package up a particular combination of exposures or cameras or spectrographs into a JSON file to study separately.

**Comment by Srheft** [comment]
Thank you for the note @sbailey; 
Given what you mentioned:
To keep the merging features such that any number of exposures and cameras could co-exist, we will have the GENERAL_INFO section in the same level as CAMERAS so that each camera would have its own info section for the coordinates, fiber mags, etc. Attached, are:

1- One merged json file with old format 
[ql-mergedQA-b0-00003880.json.gz](https://github.com/desihub/desispec/files/1823792/ql-mergedQA-b0-00003880.json.gz)

2- One merged with the new format (note the 35% size reduction). 
[ql-mergedQA-b0-00003880_newFormat.json.gz](https://github.com/desihub/desispec/files/1823820/ql-mergedQA-b0-00003880_newFormat.json.gz)

3- There is also a skeleton that shows the structure of the new merged json file containing GENERAL_INFO block up top. 
[newFormat_skeleton.txt](https://github.com/desihub/desispec/files/1823831/newFormat_skeleton.txt)
Any combination of the cameras and exposures should be merged just fine. 

@profxj could you compare this format with the jsons that are created in the offline pipeline? 

Just a note that the QL still outputs individual yaml files for each QA and merged yaml files.  But to keep the size of the outputs for each exposure to a minimum,  after the format is confirmed we may need to drop stop producing the individual yaml files as the QLF only digests the merged files.

**Comment by rkehoe** [comment]
@Srheft  Thanks for this issue.  

In terms of your initial point #1, I recommend just to have each QL instance produce merged QA files which record the RA/Dec corresponding to the 500 fibers in that camera.  Additional RA/Dec from other cameras can be added when they are merged.

For point 2: the merged structure we are using is also a schema for the offline structure.  There, multiple exposures, and even nights or further, will be put into the same dictionary.  it is valuable to keep the schema for offline and online QA dictionaries compatible, so we do want to keep the ability to support this.

**Comment by rstaten** [comment]
@Srheft Other than adding sky continuum to the general block, the skeleton and information looks good. Once the outstanding comments are resolved and implemented, and the QL_yaml2json is in master; I will update the ql_snr branch to include these changes.

**Comment by rkehoe** [comment]
@Srheft  The skeleton's look good for the general_info.  I prefer that we keep with the original hierarchy you had proposed.  This puts GENERAL_INFO in each camera, so below the 'CAMERA' keyword and parallel to PIPELINE_STEPS.  In this way, each block contains its 500 fibers worth of information.  So CAMERA would come back out of GENERAL_INFO and sit directly under CAMERAS.  This will be transparent for making merged QA files per camera, as QL does, but can be further merged across one or more exposures downstream.  This will also maintain the schema hierarchy shared with offline.

I don't see other questions for this issue, so you can probably finish the relevant branch.  It would be useful to compare skeletons for this implementation with offline, but I think they will look very similar with the exception of the GENERAL_INFO block.
