### ISSUE TITLE
pipeline DB: group several tasks in a NERSC job

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#553]
It would be more efficient to group several tasks to be run sequentially in the same NERSC job.
This of course would work only for tasks with similar concurrency, or very simple tasks that can be run by a single node in less than a minute. Possible groupings
- psf+psfnight
- fiberflat + fiberflatnight 
-  fluxcalib + cframe
maybe all the 1d calibration : fiberflat + fiberflatnight + sky + starfit + fluxcalib + cframe

**Comment by tskisner** [comment]
From offline discussion with @sbailey:  compute the job size for all pipeline steps to be grouped.  Choose the largest concurrency and then sum the wall times.  This will be wasteful if some steps are small and run for a long time.  In such a case, the user can always choose a smaller concurrency with the ```--nersc_maxnodes``` option to desi_pipe script / run / chain.

**Comment by tskisner** [comment]
I ran into deficiencies testing a prototype of this, and the result would be much cleaner and easier rolling in #599 to this work.
