### ISSUE TITLE
pipeline DB:  Move many functions from desi_pipe into package

### ISSUE THREAD

**Issue by tskisner** [desihub/desispec#555]
The scripts/pipe.py file is large, and some of the functionality there needs to be used in other places (nightly scripts, integration test, etc).  We should move all the general functionality into a new module under desispec/pipeline.  Then the desi_pipe entrypoint can call those functions.

**Comment by tskisner** [comment]
As a prerequisite to this, establish a larger integration test that takes some number of exposures and does the processing both in "batch mode" across many exposures, and also in a "fake DTS" mode where the exposures are queued one at a time.

**Comment by sbailey** [comment]
I think the @tskisner is close to finishing this in a branch, but he is away right now and we don't have time to converge prior to the 18.6 release, so punting this to 18.9 (but let's finish it much before then).
