### ISSUE TITLE
minimizing job walltime instead of nodes

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#572]
The current `desi_pipe script` node allocation logic is basically:
* minimize the number of nodes while not exceeding a maximum runtime (`--nersc_runtime`)

For some cases (like the minitest notebook), it would be helpful to have the reverse:
* minimize the runtime while not exceeding a given number of nodes

@tskisner notes
> The heart of this calculation is done by this function:
>
> https://github.com/desihub/desispec/blob/master/py/desispec/pipeline/scriptgen.py#L251
>
> So we would just need to change that and also propagate options from the desi_pipe commandline down into this.

**Comment by tskisner** [comment]
Closed by #588
