### ISSUE TITLE
study pipeline job runtimes

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#575]
Below is a plot of the runtimes and number of simultaneous running tasks for the fiberflat step of a minitest notebook reference run.  These were 360 single core tasks that take ~1 minute each, yet the total job time was ~4 minutes with something throttling the maximum number of running tasks to 155.  This was run with
```
srun -A desi -t 15:00 -C haswell --qos interactive -N 12 -n 360 -c 2  \
  desi_pipe_exec_mpi --tasktype fiberflat \
  --taskfile /global/cscratch1/sd/sjbailey/desi/dev/end2end/spectro/redux/mini/run/minitest/fiberflat.tasks
```

![ff-runtime](https://user-images.githubusercontent.com/218471/38393744-a244b11e-38e0-11e8-9cea-8ffebaac7066.png)

Was this run limit due to sqlite database update contention?  Or maybe something in the rank / task distribution logic reserving more cores than needed?  Why wasn't the job able to effectively use the 12*32 = 384 physical cores to process the 360 tasks in parallel and finish in ~1 minute instead of ~4 minutes?

**Comment by julienguy** [comment]
This is very likely the sqlite dead time.
Can you rerun this test with a postgres db?

**Comment by sbailey** [comment]
Indeed, using postgres as the backend, I had 360 tasks running in parallel within 2 seconds and then they finished 50-70 seconds later.
![ff-runtime](https://user-images.githubusercontent.com/218471/38395030-bb205314-38e5-11e8-81c9-56a3a49e0b52.png)
For kicks, it worked great to swap a production from sqlite to postgres.  Starting from within the `$DESI_SPECTRO_REDUX/$SPECPROD` dir with the previous environment setup:
```
[remove desi.db*; may not have been needed]
desi_pipe create --force --db-postgres
source setup.sh
desi_pipe sync
```
