### ISSUE TITLE
1 of 7: Obtaining Bias and ReadNoise from the header of the preproc file

### ISSUE THREAD

**Issue by Srheft** [desihub/desispec#578]
The existing desispec.preproc performs bias and read noise measurement for every exposure.  QuickLook will utilize this information in place of existing calculations of these quantities by taking these two quantities from the header of the preproc-camera-EXPID.fits for each exposure. The process should be such that the object and header is read once and kept for the remainder of the processes in QuickLook algorithm. 
Inclusion of the row-by-row calculation of the noise or bias to diagnose pattern noise (currently called NOISE_ROW or BIAS_ROW metrics) is up for debate due to their > 8k sizes.  A remaining question is whether a drill down metric which has a granularity at amp-level instead of the level of thousands of rows is desired instead, eg. an rms of row-by-row bias or noise.

**Comment by rkehoe** [comment]
@sbailey et al., as we look at this ticket, there are a small number of concise metrics that haven't gotten a lot of attention, but merit consideration as to whether to include them going forward.  These are all BOSS-inspired metrics, and go to helping characterize the noise distribution without a lot of long arrays.  The metrics as currently named are:

- DIFF1SIG:  The number of counts separating the 1 sigma percentiles in the noise distribution (from the overscan region)
- DIFF2SIG, DIFF3SIG:  The number of counts separating 2 or 3 sigma in the noise distribution
- DATA5SIG:  The number of pixels more than 5 sigma below bias level

These metrics are concise (one value per amp), and give sufficient information to compactly describe the noise distribution beyond the scalar metrics at this QA level.  They are potentially useful as drill down metrics in the context of monitoring during observing.  We would retain these metrics.

Comments welcome.

**Comment by Srheft** [comment]
@sbailey: The bias per amp values in the preproc header are not divided by the exposure time. For the comparison to other exposures, it might be beneficial to divide them by exposure time and then write it in JSONs. There is just this question of whether there was any benefit of having them in preproc header not normalized to the exptime. EXptime is also written in JSON so the divison could be made by the user, etc.
