### ISSUE TITLE
Implement co-addition

### ISSUE THREAD

**Issue by dkirkby** [desihub/desispec#6]
There are two stages:
1. Co-add observations of the same object within a per-band [brz] brick file to write a coadd file with the same structure as the input brick file. This step preserves the input wavelength grid. How should we record the (NIGHT,EXPID) provenance of each co-add in the coadd file? Would we ever not use all the available exposures in the input brick files?  What is the maximum number of possible exposures? (needed to set a FITS table array size).
2. Combine co-adds of each band [brz] into a single spectrum, rebinned to an arbitrary (nominally log-lambda) wavelength grid.  Does this need to repeat the HDU4 table info of the previous step?

Unless there are objections, the co-add outputs will go into:
1. `$DESI_SPECTRO_REDUX/$PRODNAME/bricks/{BRICKID}/coadd-{BAND}-{BRICKID}.fits`
2. `$DESI_SPECTRO_REDUX/$PRODNAME/bricks/{BRICKID}/coadd-{BRICKID}.fits`

**Comment by sbailey** [comment]
If any exposures are to be dropped, I think that should be done at the brick collection stage.  i.e. it seems fine for the coadd to use exactly the exposures in the brick file.  No more, no less.  Of course it should use the ivar for those exposures, and in a particularly insidious case I suppose every bin could have ivar=0 which is equivalent to not using that spectrum.

Maximum number of exposures: experience indicates that it will be larger than anything that seems reasonable today.  Is it possible to structure the data to not require a maximum number?  e.g. maybe storing in a separate HDU table with (targetid, expid, fiber) entries?

HDU4 table of previous step: this is the metadata such as targetid?  I'm inclined to pass that forward even though it replicates data.  That enables the coadd file to be independently useful, without also having to carry about the other type of coadd too.

Output locations:  On the input imaging side, they are adding another layer to the hierarchy to avoid having 14k BRICKID directories in a single parent directory, i.e. if BRICKID = RRRR{pm}DDD then bricks/RRR/RRRR{pm}DDD/coadd* .  This is a good idea and we should coordinate with them to follow the same standard (which isn't yet reflected in our data model).

**Comment by sbailey** [comment]
Should we close this issue?  The code has been merged, though I found it too slow and memory hungry to be practical for the dogwood production that didn't require coadds.  We should compare faster coadd options and/or look for optimizations to this code, but perhaps that is a different issue.

**Comment by dkirkby** [comment]
I'm closing this issue since we now have a working and documented first implementation.  Resource usage and optimization / tradeoffs deserves a new issue.
