### ISSUE TITLE
NameError: name 'skyivar' is not defined

### ISSUE THREAD

**Issue by ricardogando** [desihub/desispec#614]
Hi all,

we are testing latest desispec tag with new dataset and the skyivar variable is not defined.
Actually, it is commented a bit above on the code.

https://github.com/desihub/desispec/blob/66cb122976c32ec0362fb7f141cffa170f38021f/py/desispec/quicklook/quicksky.py#L172

However, it does work with the old two exposures dataset, so probably
        if skyfibers.shape[0] > 1:
on line 161 is not being satisfied. 

Thanks,
Ricardo

**Comment by Srheft** [comment]
@ricardogando : while I'm waiting on past QL members to recall the need to commenting that line,  could you let me know whether you get compute sky failure?  I don't get any failure so I did not catch if there is any missing name.

**Comment by rstaten** [comment]
@ricardogando Ricardo, what is the new dataset you are using? I also suspect the condition you mention in line 161 is not being satisfied, so it would be nice to know what is being used as input.

**Comment by ricardogando** [comment]
@rstaten is the one @Srheft made available a while ago. 
In particular it was tested 
night: 20191001
exposure: desi-00003574.fits.fz
Below is the reference for the email @felipeaoli  used to access data

``` Big thanks to Ryan, there are 20 nights of data available on NERSC here:
/project/projectdirs/desi/spectro/data/QL

with the raw files and fibermap files in:

/project/projectdirs/desi/spectro/data/QL/[night; for instance 20191001]
The fiberflat files are in:

/project/projectdirs/desi/spectro/redux/QL/calib2d/[night; for instance 20191001]

and the psfboot files are in:

/project/projectdirs/desi/spectro/redux/QL/calib2d/psf/[night; for instance 20191001]```

**Comment by Srheft** [comment]
@ricardogando @felipeaoli 
The commented line in quicksky.py you mentioned is also commented in my branch and it does not give me any error. Are you certain that a science configuration file is not being used for a flat, etc? 
We will change that line soon to accommodate consistency.
And, yes, Json that I shared a while ago are of course different than the ones we have now. We should think of a mapping that would report the changes.

**Comment by rstaten** [comment]
@ricardogando As @Srheft mentioned, I will provide a simple update that fixes this in the current ql_flexure branch. If you need this implementation in a version of desispec that is consistent with what you are now using, we can provide that as well. However, the exposure that you mention is a flat exposure. Could you try running on exposure 3577 (dark survey) to see if you get the same results?

**Comment by ricardogando** [comment]
Ahah! Of course. yes, 3577 seems to be working! Thanks!
