### ISSUE TITLE
correct for telluric absorption?

### ISSUE THREAD

**Issue by moustakas** [desihub/desispec#620]
Are there plans to correct the DESI spectra for telluric absorption?  In `fluxcalibration` we mask the telluric bands but we could / should be building a mean profile (or something more complicated using PCA) that we then use to correct individual spectra.

Are there any plans along these lines?

**Comment by julienguy** [comment]
In the current implementation of the flux calibration:
 - we mask the telluric absorption features when fitting for the stellar models
 - but then, the telluric absorption features are part of the calibration vectors, defined by the ratio  (measured counts) / (model stellar flux)
- so I don't think we really need a model. we also expect those features to vary with time (in particular the water vapor absorption lines), which would make the modeling more complex.

**Comment by moustakas** [comment]
Excellent, thanks.
