### ISSUE TITLE
redshift DB loading errors

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#637]
The desispec integration test (python -m desispec.test.old_integration_test) is generating non-fatal error messages related to redshift DB loading:

```
ERROR:redshift.py:529:load_zcat: (sqlite3.IntegrityError) NOT NULL constraint failed: zcat.coeff_0 [SQL: 'INSERT INTO zcat (targetid, chi2, z, zerr, zwarn, npixels, spectype, subtype, ncoeff, deltachi2, brickname, numexp, numtile) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ((185670190927646600, 7720.9840676784515, 0.9347282742773337, 2.4721931985478964e-05, 0, 7650, 'GALAXY', '', 10, 406.79132664203644, '3350p205', 1, 1), (445603930984159622, 2523.589103899896, 0.7152646488307819, 0.0004004767718361138, 4, 7646, 'GALAXY', '', 10, 0.5871839812025428, '3350p207', 1, 1), (1292730898444268586, 2471.687471103649, 0.01429586432758536, 0.00013395120602628793, 4, 7674, 'GALAXY', '', 10, 0.6003796133172727, '3350p205', 1, 1), (2250805110042921454, 7715.686710610986, 0.9995244913002634, 9.898407386153824e-05, 4, 7685, 'GALAXY', '', 10, 0.4147386010736227, '3352p207', 1, 1), (2667388932819333481, 332.10182214248744, 0.0003372087377787315, 4.016325143348069e-06, 0, 9118, 'STAR
 ', 'F', 5, 1078.5971626589799, '3353p205', 1, 1))] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by weaverba137** [comment]
The integration test appears to be loading from the zbest files instead of the rolled-up final zcatalog file.  In the integration test, is a zcatalog file created?  If it is, the database should be loaded from that.  If only the zbest files are available, that's not hard to fix though.

**Comment by weaverba137** [comment]
Never mind, I took a look, and it's clear that the zcatalog file never gets created.

**Comment by sbailey** [comment]
Indeed.  Can you add that to the integration test, and update the DB loading as needed to match that?  Possible hiccup: the desispec integration test starts directly from exposures and doesn't have an input targets table.  If that is a problem for the DB loading (which might reasonably expect a targets table to exist...) let's just drop DB loading from the desispec integration tests and leave it to the end2end minitest notebook for full testing including the DB.

Some other cleanup while we're at it: desispec/bin/desi_load_quicksurvey and desispec/bin/desi_load_datachallenge are out of date.  Let's make a single command line wrapper like "desi_load_redshiftdb" that works with "real" data (i.e. no special cases for data challenges or quicksurvey not matching the output of the minitest output), and we'll make future quicksurvey and data challenge runs match that.

**Comment by weaverba137** [comment]
It is not a problem that there is no target data.  However, it *is* a serious problem that the zbest files do not contain the same columns as the zcatalog file. Should I just fill in all missing data with zero?

Yes, I'll fix up the scripts.

**Comment by weaverba137** [comment]
I may have misunderstood.  Do you want the integration test to create the zcatalog file, and load the database from that, or just continue to load the database from the zbest files (which is what I've been working on)?

**Comment by sbailey** [comment]
> It is not a problem that there is no target data. However, it is a serious problem that the zbest files do not contain the same columns as the zcatalog file. Should I just fill in all missing data with zero?

The zcatalog gets its extra columns from using `desi_zcatalog --match {targets.fits}` to cross match to an input targets catalog, which the desispec integration test doesn't have.

> I may have misunderstood. Do you want the integration test to create the zcatalog file, and load the database from that, or just continue to load the database from the zbest files (which is what I've been working on)?

I meant for it to create the zcatalog file and then load from that.  But if the missing columns are fundamentally problematic, we can just drop DB loading from the desispec integration test while keeping it in the full minitest end2end integration test.

**Comment by weaverba137** [comment]
I can still load the database from the zbest files, I'm already running a test of that now.  It's not really a fundamental problem because the missing columns can be safely filled in with zeroes.
