### ISSUE TITLE
scripts shouldn't end in .py

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#65]
This proposed change is embarrassingly minor, but it could create confusion for anyone trying to use pipeline code, so advertising it via an issue prior to implementation:

Our coding guidelines say that command line scripts should *not* end with .py (code you import ends in .py; scripts you run do not).  I'd like to fix this for all our scripts prior to documenting the next major pipeline production and prior to writing the pipeline wrapper code that will be calling all these scripts.

**Comment by weaverba137** [comment]
Since we're also thinking about how to increase the test coverage of scripts, now is a good time to think about moving all the actual code into the desispec package, and only having the thinnest possible wrapper as the script itself.

**Comment by dkirkby** [comment]
One way to encourage / enforce this is to use the entry_points mechanism in setup.py, or are you already doing this?

**Comment by weaverba137** [comment]
I strongly endorse the entry_points mechanism, but we haven't implemented that yet.

**Comment by sbailey** [comment]
For the most part the algorithms and I/O are already factored out into
packages and testable and reusable independent of the script.  The
difficulty with testing the scripts isn't whether they live in bin/ or
whether they live in a package with a main() function that starts with
argument parsing.  The tricky part is setting up appropriate input files
that are light weight enough for testing but still realistic.  Moving the
code into a package or using entry_points doesn't help with that issue at
all.

I find that entry points tend to obfuscate which scripts exist and what
those scripts do.    I advocate for scripts like

[parse args]
data = io.read_something(args.input)
results = some_algorithm(data)
io.write_outputs(args.output, results)

the algorithms and I/O are still independently usable and testable, the
script is lightweight but still shows the basic concept of what it does.

Regards,

Stephen

**Comment by moustakas** [comment]
+1

**Comment by weaverba137** [comment]
Responding to: 

> The difficulty with testing the scripts isn't whether they live in bin/ or whether they live in a package with a main() function that starts with argument parsing.  The tricky part is setting up appropriate input files that are light weight enough for testing but still realistic.  Moving the code into a package ...

That is actually very easy to do if you move *both* the scripts *and* the test files into the package.  There are many examples of this in the astropy packages, and you can see simple example in the desiutil and desidatamodel packages as well.

**Comment by sbailey** [comment]
Agreed.  The only issue is that the naive version of some of the input files are several GB of data which we don't want to keep in the repo.  So there is work to be done to trim those into tiny files that are viable to keep in the repo but are also realistic enough to test the codes.

An alternative that works in some cases (but not all) is used by the desispec tests: it generates fake frame files on the fly to test code that needs a frame file as input.  But in other cases (like needing spectral templates) we will need to have mini data files available.

**Comment by tskisner** [comment]
Hi folks,

I'm going to start this reorganization.  So far in this thread, I think we have consensus on:

1.  Each processing step will have a "main" function, located at a suitable place in the desispec package.  For example, desispec.bootcalib.main
  
2.  The main() will call one function to parse sys.argv, and then will call another function (or very very small number of functions) to "do something".

Do we agree on this so far?  Then the question is:  do we define our executables simply as entry points in setup.py?  Or do we keep around thin scripts in bin/ that pass sys.argv to main()?

I would like to make sure we continue to support both "python setup.py install", and "python setup.py develop".  In the develop case, I assume that setup.py entry points are still installed as thin scripts, correct?

**Comment by dkirkby** [comment]
> I assume that setup.py entry points are still installed as thin scripts, correct?

Yes, correct.  More explicitly:
```
% cd specsim
% python setup.py develop
% which quickspecsim
/Users/david/anaconda/bin/quickspecsim
% cat /Users/david/anaconda/bin/quickspecsim
#!/Users/david/anaconda/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'specsim','console_scripts','quickspecsim'
__requires__ = 'specsim'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('specsim', 'console_scripts', 'quickspecsim')()
    )
```

**Comment by weaverba137** [comment]
* If you consistently use `argparse.ArgumentParser` there is no need to actually pass `sys.argv`. It just knows what to do.
* Although I support entry point scripts in general, we do a lot of work out of git checkouts, & as far as I'm aware nobody actually uses `python setup.py develop`. The problem is that it sometimes modifies the system Python installation in undesirable ways. If I have that wrong, please feel free to write up the detailed documentation on how to run `develop` in such a way that it only ever modifies the git clone not the system.

**Comment by tskisner** [comment]
I pretty much *only* use the python setup.py develop mode, except when specifically running a production with a tagged version...  I install it with the --prefix option to a location of my choosing (usually a virtualenv on my laptop, or a fixed location at NERSC for development).

**Comment by tskisner** [comment]
Here are my proposed specific changes:

standardize all code on optparse, argparse, click, or something else 
    for parsing the commandline.

desi_bootcalib.py:  move code to 2 functions (parse and main) in 
    desispec.bootcalib

desi_compute_fiberflat.py:  move to 2 functions (parse and main) 
    in desispec.fiberflat

desi_compute_fluxcalibration.py:  move to 2 functions (parse and main) 
    in desispec.fluxcalibration

desi_compute_sky.py:  move to 2 functions (parse and main) in 
    desispec.sky

desi_extract_spectra.py:  move to 2 functions (parse and main) in 
    new file desispec.extract

desi_fit_stdstars.py:  move to 2 functions (parse and main) in new 
    file desispec.stdstars

desi_inspect.py:  move to 2 functions (parse and main) in new file 
    desispec.inspect

desi_load_metadata:  This is already a thin script...

desi_make_bricks.py:  move to 2 functions (parse and main) in 
    desispec.brick.  Move existing test code in that file to a unittest.

desi_merge_bundles.py:  move to 2 functions in desispec.extract

desi_pbs.py:  stale file.  delete.

desi_pipe:  move to several functions in new file desispec.pipeline.production

desi_pipe_* and desi_plan_*:  these will be replaced by new serial and MPI
    running code in the pipedev branch, after this refactor.

desi_process_exposure.py:  move to 2 functions in new file desispec.calibrate.
    suggestions for alternate names welcome!

desi_reject_cosmics.py:  move to 2 functions in desispec.cosmics

desi_update_coadds.py:  move to 2 functions in desispec.coaddition

desi_zcatalog:  move to small functions in desispec.zfind

desi_zfind.py:  move to small functions in desispec.zfind

Create entrypoints or thin scripts for all these current tools.  In the case
    of explicitly making scripts, remove the "*.py" suffix.

**Comment by sbailey** [comment]
Julien and I work out of direct git checkouts which we have added to PATH and PYTHONPATH, so I definitely want to maintain the lightweight wrapper scripts in bin/ .  The problem that I have had with `python setup.py develop` is that it hardcodes the version string into the installed scripts.  If I later do a `git pull` that brings in an updated version string, then all of the installed develop scripts break.  I see that this is *not* the case for David's example above, but for example with desispec:
```
% python setup.py develop
...
% which desi_reject_cosmics.py
% cat /Users/sbailey/anaconda/envs/blatfoo/bin/desi_reject_cosmics.py
#!/Users/sbailey/anaconda/envs/blatfoo/bin/python
# EASY-INSTALL-DEV-SCRIPT: 'desispec==0.5.0.dev762','desi_reject_cosmics.py'
__requires__ = 'desispec==0.5.0.dev762'
__import__('pkg_resources').require('desispec==0.5.0.dev762')
__file__ = '/Users/sbailey/temp/desispec/bin/desi_reject_cosmics.py'
exec(compile(open(__file__).read(), __file__, 'exec'))
```
I also find that a pain to mentally parse and immediately know what the script is actually going to do.

**Comment by tskisner** [comment]
ok, how about I create thin scripts for now (replacing the current ones), and then later we can move to something else if desired.  The proposed changes earlier in this thread would basically be transparent for the end user, except that the ".py" suffix is removed.  I will move forward with that plan.

**Comment by sbailey** [comment]
For the record: my spidey-sense is screaming that this refactor is going in the wrong direction of maintainability, even if its goal is to make it more maintainable to keep the pipeline parallel wrappers and the non-pipelined scripts in sync.  Let's work out once case and inspect that before launching into refactoring them all.

@tskisner I don't quite understand the motivation for a `main` calling a separate `parse` function and then calling algorithm functions.  I was thinking that the sys.argv parsing would be in `main()` itself just prior to calling the algorithm functions, similar to how the current bin scripts are supposed to be.  What would the parser function return?  An `argparse.ArgumentParser` object?  Other?

**Comment by tskisner** [comment]
Well, do we ever want to call the top-level "do stuff" main function passing in directly objects and options without going through sys.argv?  If not, then we could certainly put the parsing inside the main function.

As an aside- some code uses optparse and other code uses argparse.  It would be nice to pick one.  I personally use argparse, but I am willing to be convinced that optparse is superior if there are reasons...

**Comment by dkirkby** [comment]
optparse is deprecated since py2.7 so should not be used in new code (and we may want to replace it with argparse when we migrate to py3.x).

**Comment by dkirkby** [comment]
Another wrinkle is that argparse is only included in the stdlib in py>=2.7 and >=3.2.  Since astropy affiliated packages are supposed to work with 2.6 - 3.x, they use a bundled backwards compatible version of argparse via:
```
from astropy.utils.compat import argparse
```

**Comment by sbailey** [comment]
DESI code does not need to support python 2.6, so it is ok to use the
standard lib argparse for desispec, desisim, desiutil, ....  External
packages that want to be astropy affiliated can use
astropy.utils.compat.argparse, but let's not do that for our standard desi*
packages.

I'm probably the source of many of the optparse cases because that is what
I started with and haven't switched, but it is fine to standardize on
argparse now as part of the prep for the python 3 transition.

**Comment by sbailey** [comment]
@tskisner that's a reasonable point about at least having the option of
calling the top level "do stuff" function with normal arguments.  Please
refactor one of the scripts in the manner you propose and let's take a look
before launching into the rest.  A tangible example will help me sort out
the details.  Thanks.

**Comment by tskisner** [comment]
@sbailey, after thinking about this some more, I actually agree with your original point of view.  The critical piece is that the main() function take an array of strings, obtained from either sys.argv or from yaml, etc.
