### ISSUE TITLE
cosmic ray rejection

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#66]
Hi,
I am starting a branch for cosmic ray rejection.
This will contain py/desispec/cosmics.py and a binary code.
I am implementing the SDSS routine and testing new algorithmes.

**Comment by julienguy** [comment]
the branch is called 'cosmics'

**Comment by julienguy** [comment]
I have committed in the branch a library file and script that reproduces what has been done so far for SDSS.
We should now try it with a more consequent set of dark images.

**Comment by julienguy** [comment]
Need to pass a better PSF model to the cosmic ray finder that masks some lines for arc exposures.
This requires some work on the pipeline infrastructure (we need reference PSFs for all cameras).

**Comment by sbailey** [comment]
Basic cosmic finder done with PR #75.
