### ISSUE TITLE
desispec.io.write_fibermap broken on interactive batch nodes

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#668]
@weaverba137 can you take a look at this?

The following works on Cori login nodes but not Cori interactive batch nodes (via `salloc -N 1 -C haswell -t 01:00:00 -q interactive`):
```python
import desispec.io
fm = desispec.io.empty_fibermap(500)
desispec.io.write_fibermap('blatfoo.fits', fm)
```
This is the case for both 18.6 and 18.3, so it's not new (and I'm surprised that we haven't caught this earlier; Julien just reported it to me).

On the interactive batch nodes it gives the traceback:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-c9274a36cd80> in <module>()
----> 1 ispec.io.write_fibermap('blatfoo.fits', fm)

NameError: name 'ispec' is not defined

In [4]: desispec.io.write_fibermap('blatfoo.fits', fm)
   ...: 
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/util.py in _free_space_check(hdulist, dirname)
    871     try:
--> 872         yield
    873     except OSError as exc:

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _writeto(self, fileobj, inplace, copy)
    658         with _free_space_check(self, dirname):
--> 659             self._writeto_internal(fileobj, inplace, copy)
    660 

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _writeto_internal(self, fileobj, inplace, copy)
    718         elif copy:
--> 719             datsize = self._writedata_direct_copy(fileobj)
    720 

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _writedata_direct_copy(self, fileobj)
    640         """
--> 641         raw = self._get_raw_data(self._data_size, 'ubyte', self._data_offset)
    642         if raw is not None:

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _get_raw_data(self, shape, code, offset)
    479         elif self._file:
--> 480             return self._file.readarray(offset=offset, dtype=code, shape=shape)
    481         else:

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/file.py in readarray(self, size, offset, dtype, shape)
    269                     memmap = Memmap(self._file, mode=MEMMAP_MODES[self.mode],
--> 270                                     dtype=np.uint8)
    271 

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/numpy/core/memmap.py in __new__(subtype, filename, dtype, mode, offset, shape, order)
    263         array_offset = offset - start
--> 264         mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
    265 

OSError: [Errno 38] Function not implemented

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-4-f864956bce5d> in <module>()
----> 1 desispec.io.write_fibermap('blatfoo.fits', fm)

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/0.22.1/lib/python3.6/site-packages/desispec-0.22.1-py3.6.egg/desispec/io/fibermap.py in write_fibermap(outfile, fibermap, header)
    130         warnings.simplefilter("ignore")
    131         write_bintable(outfile, fibermap, hdr, comments=fibermap_comments,
--> 132             extname="FIBERMAP", clobber=True)
    133 
    134     return outfile

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/0.22.1/lib/python3.6/site-packages/desispec-0.22.1-py3.6.egg/desispec/io/util.py in write_bintable(filename, data, header, comments, units, extname, clobber, primary_extname)
    210                 else :
    211                     log.debug("adding HDU {} to {}".format(extname,filename))
--> 212                     fx.append(hdu)
    213     else :
    214         log.debug("writing new file {}".format(filename))

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in __exit__(self, type, value, traceback)
    395 
    396     def __exit__(self, type, value, traceback):
--> 397         self.close()
    398 
    399     @classmethod

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in close(self, output_verify, verbose, closed)
    916             if (self._file and self._file.mode in ('append', 'update')
    917                     and not self._file.closed):
--> 918                 self.flush(output_verify=output_verify, verbose=verbose)
    919         finally:
    920             if self._file and closed and hasattr(self._file, 'close'):

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/utils/decorators.py in flush(self, output_verify, verbose)
    869             name = func.__name__
    870 
--> 871         func = make_function_with_signature(func, name=name, **wrapped_args)
    872         func = functools.update_wrapper(func, wrapped, assigned=assigned,
    873                                         updated=updated)

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/util.py in wrapped(*args, **kwargs)
    254 
    255         try:
--> 256             func(*args, **kwargs)
    257         finally:
    258             if single_thread:

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in flush(self, output_verify, verbose)
    795 
    796         elif self._file.mode == 'update':
--> 797             self._flush_update()
    798 
    799     def update_extend(self):

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in _flush_update(self)
   1211             # the hdulist to the file.
   1212             if self._resize or self._file.compression:
-> 1213                 self._flush_resize()
   1214             else:
   1215                 # if not resized, update in place

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in _flush_resize(self)
   1249 
   1250                 for hdu in self:
-> 1251                     hdu._writeto(hdulist._file, inplace=True, copy=True)
   1252                 if sys.platform.startswith('win'):
   1253                     # Collect a list of open mmaps to the data; this well be

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _writeto(self, fileobj, inplace, copy)
    657 
    658         with _free_space_check(self, dirname):
--> 659             self._writeto_internal(fileobj, inplace, copy)
    660 
    661     def _writeto_internal(self, fileobj, inplace, copy):

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/util.py in _free_space_check(hdulist, dirname)
    887             hdu._close()
    888 
--> 889         raise OSError(error_message + str(exc))
    890 
    891 

OSError: [Errno 38] Function not implemented
```

**Comment by weaverba137** [comment]
What is the situation on edison?

**Comment by sbailey** [comment]
Edison has a maintenance today so I can't login to test it there.

**Comment by weaverba137** [comment]
This could take a while:
```
bweaver@cori06[998]: salloc -N 1 -C haswell -t 01:00:00 -q interactive
salloc: Pending job allocation 13811737
salloc: job 13811737 queued and waiting for resources
salloc: error: Unable to allocate resources: Connection timed out
```
In the meantime:

1. Are you writing to a filesystem where you have free space?
2. Are you absolutely certain that the environment is the same on the login node and the interactive node?

**Comment by sbailey** [comment]
> 1. Are you writing to a filesystem where you have free space?

Yes ($HOME).

I can write the fibermap via `fm.write('blatfoo.fits')` as a workaround for now so it isn't that I/O is completely broken.  `write_fibermap` has other convenience wrapper stuff of adding dependencies to the header and in the future could do datamodel checking.

> 2. Are you absolutely certain that the environment is the same on the login node and the interactive node?

I do the test on an login node, and then run `salloc -N 1 -C haswell -t 01:00:00 -q interactive` to get the interactive batch node, and then repeat the exact same test with no other configuration steps in between.  Presumably there must be some difference, but it is not from something that I am explicitly running.

**Comment by weaverba137** [comment]
@tskisner, I was thinking something similar:  are we quite certain that numpy was installed correctly in this version of desiconda?  Here's a possible scenario:  on *both* the login node *and* the interactive node, an error is being thrown because of a problem in `numpy/core/memmap.py`.  However, for reasons yet to be determined, the code on the login node is able to handle the error successfully.

**Comment by weaverba137** [comment]
PS, I'm still not able to start an interactive job, so someone else might have to reproduce this.

**Comment by tskisner** [comment]
There is a strange error at the top "ispec not defined", is that just a copy / paste error when running the command (i.e. the "des" got cut off the front of "desispec")?

As for the memmap issue, the error seems to indicate that the filesystem does not support memmap...

As for, "are we quite certain that numpy was installed correctly in this version of desiconda?", I did not do that install, but the scripts just do "conda install numpy", so there is not much room for changing that.

We could test this with an older version of desiconda (like the one from January).

**Comment by weaverba137** [comment]
Another thing to test: are you removing the file created on the login node before creating the file on the batch node?  Here's something weird.  Even though `desispec.io.util.write_bintable()` appears to be called with `clobber=True`, when I run the snippet with `$DESI_LOGLEVEL` set to `DEBUG`, I see:
```
bweaver@cori06[1003]: python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import desispec.io
>>> fm = desispec.io.empty_fibermap(500)
>>> desispec.io.write_fibermap('blatfoo.fits', fm)
DEBUG:util.py:208:write_bintable: replacing HDU FIBERMAP in blatfoo.fits
'blatfoo.fits'
>>>  
```

**Comment by weaverba137** [comment]
Actually, that is the correct behavior of `desispec.io.util.write_bintable()`.  If the file exists, and `clobber=True`, then it does not replace the *file*, it replaces the HDU *within* the file.  I could see ways in which this could interfere with memory-mapped objects.

**Comment by weaverba137** [comment]
Ah, interesting.  I finally got an interactive job on cori.  When I ran the snippet, making sure that `blatfoo.fits` did not exist, I still got an error, but a different traceback:
```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import desispec.io
>>> fm = desispec.io.empty_fibermap(500)
>>> desispec.io.write_fibermap('blatfoo.fits', fm)
DEBUG:util.py:214:write_bintable: writing new file blatfoo.fits
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/0.22.1/lib/python3.6/site-packages/desispec-0.22.1-py3.6.egg/desispec/io/fibermap.py", line 132, in write_fibermap
    extname="FIBERMAP", clobber=True)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/0.22.1/lib/python3.6/site-packages/desispec-0.22.1-py3.6.egg/desispec/io/util.py", line 247, in write_bintable
    fx.flush()
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 871, in flush
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/util.py", line 256, in wrapped
    func(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 797, in flush
    self._flush_update()
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1205, in _flush_update
    hdu._prewriteto(checksum=hdu._output_checksum, inplace=True)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 478, in _prewriteto
    return super(_TableBaseHDU, self)._prewriteto(checksum, inplace)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 492, in _prewriteto
    self._update_checksum(checksum)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 552, in _update_checksum
    datasum_keyword=datasum_keyword)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 1248, in add_checksum
    datasum_keyword=datasum_keyword)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 1198, in add_datasum
    cs = self._calculate_datasum(blocking)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 829, in _calculate_datasum
    return super(BinTableHDU, self)._calculate_datasum(blocking)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 1387, in _calculate_datasum
    self._data_offset)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 480, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 270, in readarray
    dtype=np.uint8)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
OSError: [Errno 38] Function not implemented
```

**Comment by tskisner** [comment]
Hmmm, it is unlikely that the $HOME filesystem was suddenly changed to no longer support mmap.  More likely this is a problem with astropy or our use of it.  

Relevant file:

https://github.com/astropy/astropy/blob/master/astropy/io/fits/file.py

Looks like they test for mmap support before trying to use it...

Do we see this same error if the file in question is located in $SCRATCH?

**Comment by weaverba137** [comment]
@tskisner, you are clearly onto something.

1. On the interactive node, when I wrote the file to $SCRATCH instead of $HOME, the operation succeeded.
2. `desispec.io.util.write_bintable()` has a slightly unusual mode of operation.  First the data is written to the file.  Then the file is opened a second time and comments and metadata are rewritten to the file.  The traceback I encountered occurred during this second write attempt.

**Comment by tskisner** [comment]
Ok.  I wonder if mmap *ever* worked on $HOME?  It does not seem to support memmap right now at least.  Here is what happens:

1.  astropy checks that mmap is supported by creating a temp file.  The default temp space is $SCRATCH, so thist test works.

2.  when we try to mmap a file in $HOME it does not work.

I never use $HOME for data I/O, so would not have noticed this in the past.

**Comment by weaverba137** [comment]
Interesting.  I strongly suspect this was noticed because someone was running a notebook on $HOME, and writing to the notebook directory instead of $SCRATCH.

**Comment by tskisner** [comment]
There was a recent cori maintenance.  Maybe something about the $HOME mount options changed?

Possible options:

1. Don't write any astropy.io.fits files in $HOME when memmap option is True.

2. In the desispec code which uses the memmap=True option, add a manual check that we can mmap a temp file in the same directory as the file we want to write.  Put this helper in the utils module to check for mmap support in a given directory.

3.  See if it is possible for NERSC to change this feature on $HOME

**Comment by sbailey** [comment]
Is this understood well enough that we can turn it into a simple numpy+astropy example that doesn't depend upon desispec, desiutil, etc.?  Then we could pass it off to NERSC and see if they consider this to be a feature or a bug in how $HOME is mounted.

**Comment by weaverba137** [comment]
@sbailey I agree, but let's test this on edison first to see if $HOME is mounted differently there.

**Comment by weaverba137** [comment]
I confirm that edison has the same problem.  On a batch node, the file is written successfully on $SCRATCH but not $HOME.

**Comment by weaverba137** [comment]
Here are the mount options for $HOME on a cori batch node:
```
/global/u2 /global/u2 dvs rw,nosuid,nodev,relatime,blksize=131072,nodename=c1-0c2s1n1:c7-0c0s1n1:c11-0c0s1n1:c1-0c1s0n1:c7-0c2s1n1:c0-0c1s0n1:c1-0c0s1n1:c0-0c0s1n1:c9-0c0s1n1:c8-0c0s1n1:c11-0c2s1n1:c6-0c0s1n1:c4-0c0s1n1:c7-0c1s0n1:c3-0c0s1n1:c2-0c2s1n1:c9-0c2s1n1:c9-0c1s0n1:c5-0c2s1n1:c0-0c2s1n1:c8-0c1s0n1:c3-0c2s1n1:c5-0c1s0n1:c10-0c1s0n1:c2-0c0s1n1:c5-0c0s1n1:c11-0c1s0n1:c10-0c0s1n1,nodefile=/proc/fs/dvs/mounts/5/nodenames,statsfile=/proc/fs/dvs/mounts/5/stats,attrcache_timeout=1,nodwfs,nodwcfs,noparallelwrite,nomultifsync,nocache,nodatasync,noclosesync,retry,failover,userenv,clusterfs,killprocess,noatomic,nodeferopens,no_distribute_create_ops,noro_cache,noloadbalance,maxnodes=1,nnodes=28,magic=0x47504653,nohash_on_nid,hash=fnv-1a 0 0
```
Compare the mount options for $SCRATCH:
```
10.100.104.4@o2ib4000:10.101.104.5@o2ib4001:/snx11168 /global/cscratch1 lustre rw,nosuid,nodev,flock,lazystatfs 0 0
```

**Comment by weaverba137** [comment]
In order to make progress on this ticket, we can choose to do one or more of the following:

1. Don't write files to $HOME, and document why.
2. Raise the issue with NERSC.
3. Try to detect when the pipeline tries to write to $HOME, and raise a warning/error if anyone tries to do so.

Clearly item 3 is more work than both 1 and 2, but I don't think this is necessary.  "Don't write to $HOME" seems easy enough to me.

**Comment by sbailey** [comment]
I just tested this again and it also fails for writing to /project, which is more concerning.  "Don't write to $HOME" would be ok, but "Don't write to /project" is more problematic (even if writing to $SCRATCH is how we normally would run the pipeline).

Has anyone succeeded in isolating this into a simple test case that doesn't require DESI code?  We could bring that to NERSC for help.  We may need to find a different implementation of `write_bintable` for updating the header keyword comments of an existing file.

**Comment by weaverba137** [comment]
Question submitted.

**Comment by weaverba137** [comment]
Initial response from NERSC is that 'DVS' is a Cray-specific data IO forwarding system.  Apparently it provides some level of caching.  They also reiterate that $HOME should never be used for IO on batch nodes.

**Comment by sbailey** [comment]
For interacting with NERSC, we should focus on the problems writing to /project rather than $HOME, and try to get it into a state where we can say "Hey this snippet of python code crashes when writing to /project but not to $SCRATCH, can you help us find a workaround?".

**Comment by weaverba137** [comment]
Indeed, I'm working on that.

**Comment by weaverba137** [comment]
@sbailey, did you notice the problem writing to /project on both cori *and* edison?

**Comment by sbailey** [comment]
I only tested from a cori batch node

**Comment by weaverba137** [comment]
PS, on both cori and edison, the batch nodes also use dvs to mount /project and /projecta. And I confirmed that edison batch nodes also throw the same error with that snippet.

**Comment by weaverba137** [comment]
Well, I haven't heard back from NERSC yet, but according to this [DVS administration guide, page 39](https://manualzz.com/doc/12737309/dvs-administration-guide), memory mapping is only supported in read-only mode, at least for version ~5 of DVS.  That's probably what NERSC is using.

**Comment by weaverba137** [comment]
And, NERSC confirms what I just said.  Theoretically, it might be possible to work around this by passing different flags to the low-level C `mmap()` function, in particular the `MAP_SHARED` flag should *not* be used.  However, it's not clear where in the chain of desispec -> astropy -> numpy -> Python mmap -> C mmap it would be easy, or even possible to change the flags.

An alternative would be to detect this specific error in `write_bintable()` and then try to open the FITS file with `memmap=False` if it is detected.  That sounds much, much easier to me, though I don't know what the performance consequences would be.

**Comment by sbailey** [comment]
To be clear: from our side we're not memmapping on purpose because we somehow felt that it was necessary to achieve performance or something.  We're just trying to write a binary table to a FITS file including comments on the column keywords so that the file is semi self-documenting, and some underlying library is memmapping.  If that can be done without memmapping or by some other workaround, great.

**Comment by weaverba137** [comment]
For the record, here is Cray's official caveat on memory mapping on DVS filesystems: https://pubs.cray.com/content/S-0005/CLE%206.0.UP02/xctm-series-dvs-administration-guide-cle-60up02-s-0005/dvs-caveats

Note that the caveats above also mentions `flock()`, which is known to affect HDF5 files: http://www.nersc.gov/users/data-analytics/data-management/i-o-libraries/hdf5-2/hdf5/#qa3
