### ISSUE TITLE
copy of classes : should be use copy.deepcopy(class instance)?

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#67]
it is useful to make copies of data in codes.
I am doing for now 
import copy
tmpimg=copy.deepcopy(img) 
where img is a desispec.Image for instance

I am not sure it's the correct way to do

**Comment by sbailey** [comment]
Yes, that is correct.  copy.deepcopy(img) will return you a new Image class that has also copied new versions of the underlying pix, ivar, mask, etc. arrays.  If you used copy.copy() it would be a new object, but tmpimg.pix would reference the same array as img.pix and changes to one would affect the other, which is probably not what you want.

If this answer is clear and complete, please go ahead and close the issue.
