### ISSUE TITLE
pipeline bug when running integration test 

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#678]
The call to desispec.scripts.pipe._check_nersc_host which alters the argument args.nersc if None
depending on the env. variable NERSC_HOST is breaking at NERSC calls to:
```desi_pipe tasks --tasktypes preproc | desi_pipe script```

as a nersc slurm job will be written instead of a shell script.

This makes the integration test fail. I submit an issue because I don't remember why we needed to automatically change this script argument.

Another issue is with a wrong arg in call to control.script (user instead of db_postgres_user arg) has been directly committed and pushed in master.

**Comment by tskisner** [comment]
Ok, the addition of using NERSC_HOST to automatically detect the target machine was a convenience requested by @sbailey, to avoid having to specify the --nersc option.  We could easily revert that, since it is true that it makes it impossible to determine whether the user wants a bash script or simply did not bother to specify the --nersc option.

**Comment by moustakas** [comment]
I'm just getting around to running the pipeline myself, and very much like having the scripts machine-agnostic (or deterministic).  One alternative would be to add an explicit `--shell` True/False argument.

**Comment by tskisner** [comment]
Ok.  How about:

1.  If --nersc specified, use it to generate slurm scripts.

2.  If --shell specified, generate bash shell scripts.

3.  If nothing specified, then 
    - If $NERSC_HOST == edison, generate slurm scripts for edison
    - If $NERSC_HOST == cori, generate slurm scripts for cori-haswell
    - If $NERSC_HOST not defined, generate bash shell scripts.

Is that acceptable to @julienguy ?

**Comment by julienguy** [comment]
yes. and this means either changing internally the default args.nersc value in ```desi_pipe script```
or changing the integration tests to have calls like ```desi_pipe script --shell```

**Comment by tskisner** [comment]
I have fixed this and will open a PR soon.  I also noticed that the desispec.qproc package does not contain an __init__.py, which means it does not get installed by setuptools.  Anyone running from the source tree would not notice this ;-)

I'll include that fix too.
