### ISSUE TITLE
Flux calibration for North vs. South input photometry

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#680]
To be done after dkirkby/speclite#11 (add BASS/MzLS filters to speclite) and #679 (update fibermap format):

Update flux calibration code to use PHOTSYS='N' vs. 'S' to load BASS/MzLS vs. DECAM filters.  Currently it uses DECAM for everything.  Note that a tile could span the N/S boundary and thus have standards from both photometric systems.

**Comment by moustakas** [comment]
A choice for the north-south split is being discussed (by me, with myself) in https://github.com/desihub/desitarget/issues/353.

**Comment by sbailey** [comment]
Implemented in PR #717
