### ISSUE TITLE
Use the QFrame object in quick look pipeline

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#685]
- The quick look pipeline performs a boxcar extraction giving one flux value per CCD row per fiber.
- The natural output from this algorithm is a QFrame (see https://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/qframe-CAMERA-EXPID.html).
- However the quick look pipeline currently uses internally a Frame object (see https://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/frame-CAMERA-EXPID.html). The drawbacks of this approach are: 
  - a ill-defined, made-up resolution matrix
  - correlated fluxes due to the resampling of fiber spectra to the same wavelength grid
  - CPU/mem. inefficiencies because of all of this
  - an unnecessary and misleading modification to the Frame data model with an optional wsigma HDU, and a dependency in the Frame class to the QuickResolution function, see https://github.com/desihub/desispec/blob/42982e43bab9e5f085f40cd786a2428fed5655ee/py/desispec/frame.py#L132
 
It would be better to use the QFrame object in quick look.

**Comment by julienguy** [comment]
Yes. sigma is the LSF sigma in pixel units. This is described in the docstring of the init function and in the data model https://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/qframe-CAMERA-EXPID.html . But, I admit a more explicit name for this parameter might be better. Feel free to change this.

**Comment by julienguy** [comment]
yes, and please the datamodel accordingly

**Comment by rkehoe** [comment]
@julienguy, @sbailey. Now that PR #734 is merged, I would like to close this Issue later today.  Let me know if you prefer to keep this open and what question you feel has yet to be resolved.
