### ISSUE TITLE
Heliocentric redshift

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#703]
David S. reminded me we have to implement a heliocentric redshift correction in the pipeline.
This would be trivial if applied after the redshift fit but we cannot do this. We have to scale the wavelength, because observations of the same target can be several month apart. It is also important for Lyman-alpha. 

- the wavelength correction has to happen **after** flux calibration because we define the instrument calibration in the observer frame. this means the std stars peculiar velocities have to be corrected after the fit.
- this is an important change because it means we need to either resample the spectra to the same wavelength grid (ideally with spectroperf 1D which is CPU intensive) or have different wavelength per spectrum in the spectra files (I don't think we want that).

**Comment by sbailey** [comment]
Documenting a lunch conversation: another option is to extract each frame on a custom grid such that after the heliocentric correction is applied it ends up back on the common grid.  The uncalibrated frame files would all be on different grids, but the calibrated cframe files would be heliocentric corrected and on a common grid.  There is a second order effect of variation of the correction across the field, but I think that is tiny (should confirm).

**Comment by sbailey** [comment]
Implemented in PR #790.  Closing this issue.
