### ISSUE TITLE
QL CHECKHDUS: does it report missing HDUs?

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#708]
The purpose of the quicklook CHECKHDUS metric should be to check whether any expected cameras are missing from the input data (which would be really really bad).  Several questions:
* where in the QL config files do we set which cameras are expected?  During normal ops it will be all 30, but during early commissioning it will be less than that, and we don't want quicklook to be raising alarms for data that we know are supposed to be missing.
* If a camera is unexpectedly missing, how can we tell from the QL output which cameras were there and which are missing?  I only see `"CHECKHDUS_STATUS": "NORMAL"`.  If it wasn't normal, how would I know what was wrong?

@rkehoe @rstaten @Srheft

**Comment by Srheft** [comment]
@sbailey 
> where in the QL config files do we set which cameras are expected? 

 You suggested to get a CAMLIST in issue #579 [579](https://github.com/desihub/desispec/issues/579) but then we went for checking whether the individual camera exists. QL operates on single camera so if we only have b0 and r5 on a given night, when QL goes through cameras, it gets ALARM for 28 cameras and NORMAL for the 2 cameras that actually exist in the exposure. Shall I switch to CAMLIST now?

**Comment by sbailey** [comment]
@Srheft ok to keep this as per-camera (i.e. not a CAMLIST).  I keep forgetting that the "mergedQA" is merged across steps, but still one file per camera.

However, have you tested that if a camera is missing will QL still get far enough to generate a mergedQA file for the missing camera?  And in the case where a camera is supposed to be missing (e.g. during commissioning before all spectrographs have arrived), how can we tell QL which cameras to expect?

**Comment by rkehoe** [comment]
@sbailey, @srheft. I don’t know if you cleared these questions elsewhere.  The answer to your first question is the QL quits if the HDU is not there, (@srheft can correct me if I misremember).  As to how to communicate to QL which cameras to expect, this is done at execution.  When one runs QL, one has to specify which camera to run on (i.e. What in the input desi- file to look at).  All QL instances require this at execution time.  When QLF invokes QL, it provides this information.  So the way to do this would be fore QLF to be aware of which cameras are operating — then it will only spool off QL’s for those cameras.  

I reference @felipelm as a heads up on this.  I don’t know if currently QLF handles <30 cameras gracefully.  It would be good to know if some implementation is necessary there.

**Comment by rkehoe** [comment]
@sbailey, @srheft. I should have included in my last post that on the first point, QL probably needs to be modified so that it will produce a mergedQA file despite the fact that it did not run any QA or PA algorithms.  QLF may need to be told which cameras are operating, but if it runs QL and that camera has no HDU, then QL needs to communicate to the outside world that it is missing.  It does this via the mergedQA file.  It could just be a stub file with only the CHECKHDUs metric and nothing else.  @srheft, do you see a better way to do this?

**Comment by Srheft** [comment]
> However, have you tested that if a camera is missing will QL still get far enough to generate a mergedQA file for the missing camera? And in the case where a camera is supposed to be missing (e.g. during commissioning before all spectrographs have arrived), how can we tell QL which cameras to expect?

Currently, if QL doesn't find the camera that it is told to process, it crashes and **does not** move any further in QL algorithm to generate anything including a merged JSON. 

I *think* going back to the CAMLIST idea is the quickest way forward for the commissioning phase during which a subset of cameras are present. QL then takes the list from the config file and just skips  the QA calculations for the **absent cameras** and spits out an empty merged JSON. If this is what you like to happen, I can apply this change.

**Comment by sbailey** [comment]
There are four possible cases to track:
* camera wasn't expected and wasn't in the raw data (ok, maybe show as gray)
* camera was expected and was in the raw data (good, green)
* camera was expected but wasn't in the raw data (error, red)
* camera wasn't expected but was in the raw data (that's strange, maybe yellow warning)

Fleshing out the CAMLIST idea to make sure we agree what that means:
* A config file would contain the list of cameras to expect
* QLF would always spawn 30 QL processes, one per camera, not matter what
* If a QL process was requested to run on a camera that wasn't expected, it would output a nearly empty merged JSON file and exit (and return a non-zero error code, but not completely crash)
  * Note: an empty json file isn't a valid json file, so it should at lease have something in it acknowledging that that camera wasn't expected
* QLF display would learn from the merged JSON which cameras were expected or not

Alternatively, QLF could own the concept of what cameras to expect and only call QL on the ones that should be there.  This could be ok as long as it distinguishes between the cameras that currently are enabled, vs. historical exposures which may have had more or less cameras and we would still want to be able to see their QA.

Either way, observers should have the ability to update the list of cameras that are working.  They will have to do this for ICS anyway and it would be preferable if they didn't have to do it in two places.  That would require coordinating with Klaus/ICS for how to get that information, which might be easier for QLF to do than the lower-level QL algorithms that we want to be able to run elsewhere.

**Comment by rkehoe** [comment]
@srheft. I think this idea of QL having the camlist has merit.  But my concern was along lines @sbailey has also raised, namely that QLF will then need to spawn 30 QLs for all exposures no matter what.  It does not appear this will present a major problem, but thinking about the logistics for observers he mentions makes it seem that more straightforward for the camlist to be with QLF.  In general, QL only cares about each camera and not an array of them.  In this case, QL just reports when a HDU is missing, and is never called for a camera that is not expected.  

It might be worth bringing @felipelm here in case there is some item to consider from the QLF side.  I believe you can proceed to implementation, though I would suggest waiting until the qproc2 PR is merged, and build off that.

**Comment by felipelm** [comment]
> I reference @felipelm as a heads up on this. I don’t know if currently QLF handles <30 cameras gracefully. It would be good to know if some implementation is necessary there.

@rkehoe We open one process for each camera and monitor the logs for each. So if an error happen we mark that stage in red. Usually QL quits with the error if not we continue the flow and try to ingest the mergedQA file.

> Alternatively, QLF could own the concept of what cameras to expect and only call QL on the ones that should be there. This could be ok as long as it distinguishes between the cameras that currently are enabled, vs. historical exposures which may have had more or less cameras and we would still want to be able to see their QA.

This could be configured on the docker-compose environment variable. Right now we still need to restart the container. We were going to make the configuration screen editable but we thought it would be a good idea to keep a history of what went wrong for each camera. Should we reprioritize this feature @sbailey ?

> Either way, observers should have the ability to update the list of cameras that are working. They will have to do this for ICS anyway and it would be preferable if they didn't have to do it in two places. That would require coordinating with Klaus/ICS for how to get that information, which might be easier for QLF to do than the lower-level QL algorithms that we want to be able to run elsewhere.

We could get and use this information using our PYRO connection to ICS we only need to agree on a function to call and a result to expect. A list of string of camera names (b0, r7..) would be fine.

> It might be worth bringing @felipelm here in case there is some item to consider from the QLF side. I believe you can proceed to implementation, though I would suggest waiting until the qproc2 PR is merged, and build off that.

We can always run all cameras and log the errors, make the configuration editable or talk to Klaus to get the ICS available cameras. Whatever works best.

**Comment by sbailey** [comment]
From emailsdiscussions, the conclusion was basically to drop CHECKHDUs, since ICS will be handling the equivalent alarm condition of missing data.

The consequence for QLF:
* it should check the input raw data file desi*.fits.fz for which cameras exist, and spawn QL only for those cameras
* any cameras that are not in the input files should just be grayed out for the display
* QLF should cache the results of what it found for each exposure, so that it doesn't have to re-read the desi*.fits.fz file just to know what cameras should be gray vs. displayed every time the webpage is loaded.

Note: it will be possible that 1 or 2 cameras for a spectrograph will exist, even if the 3rd camera is broken, e.g. having b2 and z2 but not r2.

**Comment by sbailey** [comment]
I migrated the QLF actions to new qlf ticket desihub/qlf#293.  The remaining action for QL is to remove the CHECKHDUs metric.

**Comment by rkehoe** [comment]
@sbailey. This will be done in PR #725.  Should we close this issue when that is merged?

**Comment by rkehoe** [comment]
@sbailey  This issue, at least, I think I can close as it has moved to QLF and we have just finished the QL removal in PR#725, which was just merged.  I'll check in about an hour in case you rather hold on this.
