### ISSUE TITLE
consolidate DESI SVN servers

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#719]
Filing under desispec for lack of a better place.

Currently DESI svn usage is split across DESI servers (desi.lbl.gov/svn) and repos hosted at NERSC accessed via svn+ssh, e.g. /global/project/projectdirs/desi/spectro/calib/svn/ccd_calibration_data.  AFAIK the NERSC repos as not regularly backed up (they aren't really a NERSC-provided service; we are just putting SVN repos on /project disk that we are responsible for backing up ourselves).

Review usage of DESI SVN repositories and consolidate as needed.  Ensure that all svn repositories are backed up.

**Comment by weaverba137** [comment]
At this point, I think all existing svn repositories that we had at NERSC have been moved.  Is there any reason to keep this open?  Can we clean up the old repositories at NERSC?

**Comment by weaverba137** [comment]
Closing because all the repositories are set up.  Open a new issue if there are problems.
