### ISSUE TITLE
fluxcalib usage of basis templates

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#724]
Previously, both flux calibration and spectral simulations used `$DESI_BASIS_TEMPLATES/star_templates_*.fits`.  With version v3.0, however, the number of stars increased by 6.5x which caused both memory and speed problems for flux calibration.

For the 18.11 release, I ended up punting by creating a temporary link from `basis_templates/v3.0/stdstar_templates_v2.2.fits` -> `basis_templates/v2.6/star_templates_v2.2.fits` and having the pipeline look for `stdstar*.fits`.  Although pragmatic for getting the release out, this is bad at multiple levels:
* I forgot that basis_templates is in svn, and adding links to exported copies doesn't fix it for anywhere except exactly where I made the links.
* I retroactively updated a tagged version (with an addition, not a change, but still...)
* links between versions is clumsy

So: cleanup my mess for the next version of basis_templates.  We either need to keep star templates separate from stdstar templates (preferably with a documented algorithmic way to trim star -> stdstar if that is how the stdstar list is generated), or we need to update the flux calib code to do its own trimming and sub-selecting on the fly to not blow memory and speed).

Note: the previous star_templates_v2.2.fits were well studied and completely sufficient for our flux calibration needs (at least until we get real on sky DESI data to prove otherwise).  The denser grid in v3.0 was not needed by flux calibration, which interpolates on the grid it receives.

Mentioning @moustakas and @julienguy who would be in the loop on this.

**Comment by moustakas** [comment]
Just a note that we're in the middle of moving the basis templates to their new home in [https://desi.lbl.gov/svn/data/basis_templates](https://desi.lbl.gov/svn/data/basis_templates), so changes to the templates used for flux-calibration should happen there.

@sbailey are you going to be working on this soon?  If not I can take a look toward the end of the week.

**Comment by sbailey** [comment]
This is fixed in the basis_templates trunk release candidate for 3.1 by including stdstar_templates_v2.2.fits as a separate file.  Good for this ticket.

**Comment by moustakas** [comment]
I think we should consider keeping this ticket open, but just bumping it from 18.12.  There's a clean solution to the issue you've identified, @sbailey, we just haven't had the time to work on it!

Also, can you please update the documentation here:
https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/Laptop#SimulatingDESIdata

I know the calibration data are being reorganized, and I changed the instructions for the basis templates, but I think we can safely remove these lines, right?
```
scp -r edison.nersc.gov:/project/projectdirs/desi/spectro/templates/star_templates/v2.1 $DESI_ROOT/spectro/templates/star_templates

# Alas, the integration test hardcoded an old version; to be fixed...
scp -r edison.nersc.gov:/project/projectdirs/desi/spectro/templates/star_templates/v1.1 $DESI_ROOT/spectro/templates/star_templates
```
