### ISSUE TITLE
update desi_pipe job times

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#726]
Review and update job time allocations for each pipeline step.  Consider adding a minimum of 5 or 10 minutes to every job script.  Examples:

Running `desi_pipe chain --tasktypes traceshift, ...` on edison resulted in a 1 minute batch job for 60 traceshifts.  The job wake up time took longer than that and the job was killed before anything substantive ran.

On the positive side, extractions are now much faster (thanks @lastephey!) and maybe could request less job time.  Don't be too aggressive with job time optimization though -- the impact of under-estimating the time is much more than over-estimating.

**Comment by tskisner** [comment]
Revisiting this now as part of general updated testing on cori.  I am planning to do the following:

1.  Always have a minimum "floor" in the job run time to cover startup costs.

2.  Add a "scale factor" to each machine specification to give the approximate relative runtime difference.  Obviously this depends on the particular pipeline step, but I think even just rough numbers like 2x or 3x will be good enough.

3.  Run a standard production with sufficient work to get per-task numbers on KNL (conveniently I have @sbailey's SVDC dataset here).  Set the per-task times based on this and set the KNL scale factor to "1".  Then run the same production on haswell and confirm that we can use a single number and what that number should be.

4.  When set the runtime in generated job scripts, apply the per-machine factor to the estimated run time.
