### ISSUE TITLE
fiberflat problems when both resolution and throughput vary

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#76]
When the input to compute_fiberflat() varies by both throughput and resolution, then there are edge effects which cause the output fiberflat to not be ~1 * throughput.  Attached is an example plot, and below is the code demonstrating this.  If you only vary the resolution but not the throughput, it does not have this problem.

![screen shot 2015-09-30 at 5 35 26 pm](https://cloud.githubusercontent.com/assets/218471/10210276/aa22b162-6799-11e5-9648-0c7c75635d22.png)

```
from desispec.resolution import Resolution
from desispec.frame import Frame
from desispec.fiberflat import FiberFlat
from desispec.fiberflat import compute_fiberflat, apply_fiberflat

#- Setup sine wave shaped fiber flats with differing throughput
nspec = 10
nwave = 100
wave = np.linspace(0, np.pi, nwave)
y = np.sin(wave)
flux = np.tile(y, nspec).reshape(nspec, nwave)
ivar = np.ones(flux.shape)
mask = np.zeros(flux.shape, dtype=int)

flux[1] *= 1.1
flux[2] *= 1.2
flux[3] /= 1.1
flux[4] /= 1.2

#- Setup resolution matrix data with a varying sigma
sigma = np.linspace(2, 10, nwave*nspec)
ndiag = 21
xx = np.linspace(-ndiag/2.0, +ndiag/2.0, ndiag)
Rdata = np.zeros( (nspec, len(xx), nwave) )
for i in range(nspec):
    for j in range(nwave):
        kernel = np.exp(-xx**2/(2*sigma[i*nwave+j]**2))
        kernel /= sum(kernel)
        Rdata[i,:,j] = kernel

#- Convolve with the resolution matrix
convflux = np.empty_like(flux)
for i in range(nspec):
    convflux[i] = Resolution(Rdata[i]).dot(flux[i])

#- Run the fiberflat code
frame = Frame(wave, convflux, ivar, mask, Rdata, spectrograph=0)
ff = compute_fiberflat(frame)

%pylab
plot(wave, ff.fiberflat[0])
plot(wave, ff.fiberflat[1] / 1.1)
plot(wave, ff.fiberflat[2] / 1.2)
plot(wave, ff.fiberflat[3] * 1.1)
plot(wave, ff.fiberflat[4] * 1.2)

subplot(211)
for i in range(5):
    plot(wave, convflux[i])

subplot(212)
for i in range(5):
    plot(wave, ff.fiberflat[i])
ylabel('fiber flat')
    
for y in (1/1.2, 1/1.1, 1.0, 1.1, 1.2):
    axhline(y, ls=':', color='0.5')
```

**Comment by julienguy** [comment]
i checked the bug fix of error propagation is ok and had a look at the new tests that show indeed a problem.
it's actually a feature that can be fixed by iterating the fit of mean spectrum and smooth fiber flat. It happens only when we have "very" different throughput and resolution. I am now fixing this in branch   fiberflat_enhancement.

**Comment by julienguy** [comment]
I can reach a flat field accuracy of 10^-10 on the test set up by stephen. there is now a argument "accuracy" in the routine compute_fiberflat its default is 10^-4.

**Comment by julienguy** [comment]
I am closing this issue which has been fixed and merged in master
