### ISSUE TITLE
Unit tests don't clean up QA fits files automatically

### ISSUE THREAD

**Issue by lastephey** [desihub/desispec#774]
I discovered that if you are running the full unit test suite in desispec, i.e.

python setup.py test

and you quit the tests partway through, several QA tests fail when you run the unit tests again. This is because there are residual files left behind that are not automatically deleted at the beginning of the tests. These files are:

test-pix-abcde.fits
test-raw-abcde.fits
test_arc.fits.gz
test_flat.fits.gz

which are written in the top directory of desispec. 

If these leftover files exist at the beginning of the unit tests, errors like these occur:

ERROR: testCountPixels (desispec.test.test_ql_qa.TestQL_QA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/cscratch1/sd/stephey/git_repo/desispec/py/desispec/test/test_ql_qa.py", line 148, in setUp
    desispec.io.write_raw(self.rawfile,rawimg,hdr,camera=self.camera)
  File "/global/cscratch1/sd/stephey/git_repo/desispec/py/desispec/io/raw.py", line 198, in write_raw
    raise ValueError('Camera {} already in {}'.format(camera, filename))
ValueError: Camera z1 already in test-raw-abcde.fits

**Comment by weaverba137** [comment]
I asked a very similar question a while ago, and at that time `test_(arc|flat).fits.gz` were meant to be cached between tests.  However, `test-(pix|raw)-abcde.fits` files are new to me.  Have you seen failures related to the presence of the `test_(arc|flat).fits.gz` files or only `test-(pix|raw)-abcde.fits` files?

**Comment by sbailey** [comment]
Fixed in PR #776.

@weaverba137 FYI the test_(arc|flat).fits.gz files are big and auto-downloaded, and tests still work if they are left behind.  The test*-abcde.fits files were created on the fly and would cause problems if they were leftover from a previously crashed test (because the auto-creation would step on itself and fail).
