### ISSUE TITLE
qproc --auto on flavor=ZERO and DARK

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#816]
`desi_qproc --auto ...` tries to do the "right" think based upon the FLAVOR keyword.  It doesn't have a special case for handling ZERO and DARK exposures and thus tries to perform boxcar extractions.  I think this is harmless but should be cleaned up.  I noticed because it failed when trying to process a ZERO exposure for a new spectrograph that didn't have a PSF calibration file yet so that boxcar extraction failed.

**Comment by julienguy** [comment]
not relevant any more now that we have OBSTYPE
