### ISSUE TITLE
BUG in coaddition.coadd(spectra, cosmics_nsig=0)

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#817]
There is a bug in coaddition.coadd(spectra, cosmics_nsig) for cosmics_nsig > 0.

**Comment by sbailey** [comment]
@julienguy do you remember what the bug was or at least its symptoms?

Our recent reductions (minisv2, daily) have *not* used the --nsig option.

**Comment by julienguy** [comment]
solved in PR #1113 .
