### ISSUE TITLE
consolidate scripts.extract.main and main_mpi

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#827]
Technical debt strikes back!  `desispec.scripts.extract.main` and `main_mpi` are nearly identical but different.  PR #825 is the latest example of updating one while forgetting to update the other.  I'll submit a separate PR to make the emergency hack to get MPI extractions working on CMX data without fibermaps, but slightly longer term let's clean this up and consolidate those two mains into a single maintainable code.

**Comment by tskisner** [comment]
Mea culpa.  The extract script was the first one I converted to use MPI years ago, and did not want to stomp all over the serial version.  A poor choice in hindsight.

**Comment by sbailey** [comment]
main and main_mpi were merged by @akremin in PR #943.  Closing this ticket.
