### ISSUE TITLE
fiberflat convergence problems with real data

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#830]
Using files in /global/cscratch1/sd/sjbailey/desi/spectro/redux/test/exposures/20191022/00019960/frame*.fits, desi_compute_fiberflat is having trouble converging:
```
desi_compute_fiberflat \
    -i frame-b3-00019960.fits -o fiberflat-b3-$expid.fits
```
is up to iter 37 and still trying.

The flat from exposure 00019960 is more wiggly than our sims:
![image](https://user-images.githubusercontent.com/218471/67347434-e3a6c380-f4f6-11e9-8900-cb8319ab787d.png)

I also haven't checked the extracted spectra for artifacts yet, in particular I skipped the xytraceshift step which may have caused problems too.  Dumping this into a ticket to get other eyes on it too.

Extractions were performed with the branch in PR #829.

**Comment by julienguy** [comment]
A lot of pixels have the mask value BAD2DFIT.
Those pixels are ignored in the flat fielding.

**Comment by julienguy** [comment]
The BAD2DFIT issue is only  for the blue camera. For the others, we might have an issue with residual cosmics. I suggest we first do a clipped average of several exposures.

**Comment by julienguy** [comment]
The bad chi2 and band extraction in general are due to trace shifts. Try first 
```
desi_compute_trace_shifts -i preproc-b3-00019960.fits --psf $DESI_SPECTRO_CALIB/spec/sp3/psf-sm4-b-science-slit-20191015.fits --continuum -o psf-b3-00019960.fits
```
Then extract with the shifted PSF.
