### ISSUE TITLE
desi_proc failed to reduce 5 arc exposures on 20191212

### ISSUE THREAD

**Issue by zkdtc** [desihub/desispec#854]
The exposure numbers are 31353, 31354, 31355, 31356, 31357. 
The  commands and error message are below. The "Segmentation fault (core dumped)" usually means the failure of compiled codes in SPECX. 

srun -N 10 -n 320 -q realtime -C haswell -t 00:30:00 /global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/bin/desi_proc  -n 20191212 -e 31353 —mpi

 error message:

INFO specex::PSF_Fitter::FitSeveralSpots inc. signal in w=0, npix footprint = 58310
WARNING cannot measure flux of spot 347 at x=1633.29 y=2367.45
INFO specex::PSF_Fitter::FitSeveralSpots inc. signal in w=0, npix footprint = 57625
slurmstepd: error: *** STEP 26811659.0 ON nid00533 CANCELLED AT 2019-12-16T10:27:24 ***
srun: error: nid00536: tasks 251-255: Segmentation fault
srun: error: nid00535: tasks 128-139: Terminated
srun: error: nid00540: tasks 314-315: Terminated
srun: error: nid00538: tasks 310-311: Terminated
srun: error: nid00534: tasks 100,120-127: Terminated
srun: error: nid00539: tasks 312-313: Terminated
srun: error: nid00541: tasks 316-317: Terminated
srun: error: nid00542: tasks 318-319: Terminated
srun: error: nid00533: task 33: Terminated
srun: error: nid00535: task 148: Terminated
srun: error: nid00536: tasks 240,242,244,246,248-250: Terminated
srun: error: nid00537: tasks 267,269,273,275,280-299,303: Terminated
srun: error: nid00533: tasks 19,22: Terminated
srun: error: nid00534: task 116: Terminated
srun: error: nid00536: tasks 204,208,217,236: Terminated
srun: error: nid00533: tasks 2,4: Terminated
srun: error: nid00537: tasks 260-266,268,270-272,274,276-279,300-302,304-309: Terminated
srun: error: nid00533: task 55: Terminated
srun: error: nid00535: tasks 140-147,149-191: Terminated
srun: error: nid00536: tasks 192-203,205-207,209-216,218-235,237-239,241,243,245,247: Terminated
srun: error: nid00534: tasks 64-99,101-115,117-119: Terminated
srun: error: nid00533: tasks 0-1,3,5-18,20-21,23-32,34-54,56-63: Terminated
srun: error: nid00537: task 258: Segmentation fault (core dumped)
srun: Force Terminated job step 26811659.0

**Comment by sbailey** [comment]
The r6 images for these exposures are completely junk; no light at all.  Maybe VCCD wasn't on.  It would be nice if we crashed more gracefully, but specex can't do anything useful with images like this.
