### ISSUE TITLE
enable heliocentric corrections

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#874]
From @julienguy, replying to Sergey Koposov about heliocentric corrections:

> We just have to add the option --heliocentric-correction to desi_extract_spectra in desi_proc (and then debug ...).

I think the necessary data is now in the headers from `assemble_fibermap`, but I forgot to enable heliocentric corrections before the latest catchup run.  Check, test, run.

**Comment by julienguy** [comment]
done in PR #879
