### ISSUE TITLE
Implement classification & redshift fitting

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#9]
Experimenting with opening an issue ahead of time for comment before I start coding it.

Implement classification and redshift fitting by writing a desispec wrapper for redmonster.  The first version of this will only use the redmonster fast loglamda mode.  Since coadds aren't in loglambda, I'll have to rebin the spectra on the fly.  Current coadd code is a bit slow and memory hungry, so I plan to start with using desispec.interpolation.resample_flux() even though that introduces covariance.  After the redshift fitting itself is worked out, we can come back to the coadded loglambda inputs.

**Comment by moustakas** [comment]
There's also Bolton's spline resampling code, although I don't know if it's better behaved wrt introducing pixel-to-pixel covariances.

**Comment by sbailey** [comment]
This was merged in a week ago; I forgot to associate this ticket with the pull request and merge to version hash 3ce719a.

**Comment by sbailey** [comment]
I tried closing this issue with a comment that this was implemented with merge 3ce719a.  But github still thinks it is open?  With no comment?  Trying again.
