### ISSUE TITLE
move fiber blacklist parsing into calibfinder

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#915]
Followup to PR #913:

Move the fiber blacklist parsing from desispec.io.raw() into calibfinder itself, e.g.
```
#- get list of integer fiber numbers % 500 that have been backlisted
cfinder = CalibFinder([header,primary_header])
blacklist = cfinder.fiberblacklist()
```

Remove the similar parsing from desispec.fiberflat and have that code reject FIBERSTATUS != 0 fibers instead.

**Comment by akremin** [comment]
Do we want FIBERSTATUS !=0, or an explicit list of fibermask.XXXX that we want to compare against? @julienguy @sbailey

**Comment by sbailey** [comment]
I was thinking something different.  I was thinking it would return the list of fibers that are blacklisted in the $DESI_SPECTRO_CALIB yaml files, completely independently of what we chose to do with those wrt for fiberstatus.  i.e. saving the end user(s) the error prone checking for string, splitting by commas, etc.

**Comment by akremin** [comment]
Hi Stephen,

You were clear on that, and I completely agree with your line of thinking.
I implemented that in one of my commits to the fiberstatus branch.
My question would have been better placed in the PR for that branch. I was
wrt the fiberstatus branch edits, what philosophy we would take for
checking if FIBERSTATUS is good or not.

**Comment by akremin** [comment]
This was completed with PR #916
