### ISSUE TITLE
Add scores to coadded spectra

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#918]
It's all in the title.

**Comment by sbailey** [comment]
SCORES are already in coadds as of PR #900, including in minisv2.  If you don't see them there, point to which file has them missing.

**Comment by julienguy** [comment]
Indeed. For instance in `/global/cfs/cdirs/desi/spectro/redux/minisv2/tiles/70003/20200219/coadd-0-70003-20200219.fits`
