### ISSUE TITLE
desi_zfind.py option to limit what classes are considered

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#92]
currently desi_zfind.py wraps redmonster and it runs all templates on all objects.  That can be overkill for testing and doesn't make sense for running QSO templates (slow!) on BGS and MWS targets that are super bright and almost certainly not a QSO.  Maybe something like:

desi_zfind.py ... --templates galaxy,qso,star

**Comment by moustakas** [comment]
Running over a narrower or coarser redshift grid will also speed things up considerably, even if it's over all the template classes.

**Comment by sbailey** [comment]
Currently desi_zfind.py hardcodes what range of redshifts to consider per-template class.  This could be added to desi_zfind.py as options.  Let's consider future options on a case-by-case basis and be cautious to not add every possible debugging/development option that we can think of to desi_zfind.

**Comment by julienguy** [comment]
the redshift step of the scan can also be adapted depending on the class of objects tested.
we don't need a very fine grid for QSO spectra for instance.
j

**Comment by moustakas** [comment]
I think we can safely close this issue based on the current version of ```desispec.scripts.zfind```.  The template classes to consider can be controlled by the ```objtype``` optional input, and the redshift ranges of the classes were included in PR #196.  Let's open a separate issue if we think we still need to control the redshift binning/interval for each object type.
