### ISSUE TITLE
bad spectrum: step in calibrated spectrum

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#922]
in the elg 67142 tile, redrock (wrongly) reports few z>5 qso, which I
visually inspected: most of them present suspicious spectra, like the
attached one, with a clear drop at 6700-7700 A.
<img width="1004" alt="tmp" src="https://user-images.githubusercontent.com/5192160/76991774-5df13d80-6907-11ea-8ffd-a7a6fefb3514.png">

**Comment by araichoor** [comment]
from the same set of reduction:
/global/cfs/cdirs/desi/spectro/redux/daily/tiles/67142/20200315/
/global/cfs/cdirs/desi/spectro/redux/daily/tiles/67230/20200314/
/global/cfs/cdirs/desi/spectro/redux/daily/tiles/67230/20200315/

spectro #4 fibres often present an excess of flux at 6800 - 7600 A.
example for fibre 2104:
<img width="1006" alt="tmp 67142 fiber2104" src="https://user-images.githubusercontent.com/61986357/76998720-d7b01800-6955-11ea-82ef-ee0f6584113f.png">

spectro #9 fibres often present have negative flux at 4800 - 5800 A.
example for fibre 4715:
<img width="1004" alt="tmp 67142 fiber4715" src="https://user-images.githubusercontent.com/61986357/77000102-134be180-6958-11ea-91b5-d1bac570c993.png">

**Comment by julienguy** [comment]
For the first example (targetid=35185917962485834 , fiber=2474), there is a step in the extracted spectra at the amplifier boundary in the red camera (r4).
 - it is not a simple gain fluctuation because the spectrum of a bright star fiber=2472 is continuus.
 `plot_frame -i $DESI_SPECTRO_REDUX/daily/exposures/20200315/00055639/cframe-r4-00055639.fits --fiber 2474,2472 --legend`
![Figure_1-1](https://user-images.githubusercontent.com/5192160/77198082-8dd54800-6aa3-11ea-9968-874e503895e1.png)
![Figure_1](https://user-images.githubusercontent.com/5192160/77198090-94fc5600-6aa3-11ea-9ac4-5dd9e47164d5.png)

 - it is not a bad pedestal subtraction. But one can see some (subtle) extra pixel correlation in the upper right quadrant
`ds9  $DESI_SPECTRO_REDUX/daily/preproc/20200315/00055639/preproc-r4-00055639.fits -zscale`
![Screenshot from 2020-03-20 12-05-28](https://user-images.githubusercontent.com/5192160/77198209-c412c780-6aa3-11ea-8d05-df28d10cd439.png)

 - the spectral profile is continuous across the amplifier boundary for high counts (star fiber 2472) but not at low counts (!). 
 - I am afraid there is a non-trivial low count pixel to pixel correlation.
```
import fitsio
img=fitsio.read("/project/projectdirs/desi/spectro/redux/daily/preproc/20200315/00055639/preproc-r4-00055639.fits")
prof0=np.mean(img[4128//2-10:4128//2,:],axis=0)
prof1=np.mean(img[4128//2:4128//2+10,:],axis=0)
plt.plot(prof0)
plt.plot(prof1)
```

![Figure_3](https://user-images.githubusercontent.com/5192160/77198275-e9073a80-6aa3-11ea-8694-89e50bde8ecc.png)
![Figure_3-1](https://user-images.githubusercontent.com/5192160/77198285-ee648500-6aa3-11ea-8e0e-903b9764f9ed.png)
(the same comparison on the left side of the CCD does not show this discontinuity of the spectral trace profiles)

**Comment by julienguy** [comment]
A positive step like in the example of fiber 2104 above is present for half of the fibers in r4 (fibers 2000:2250). It is the result of the combination of the negative step in the other half (fibers 2250:2500) and sky subtraction.

**Comment by julienguy** [comment]
The negative flux in spectro #9 are due to another CCD issue in the blue camera. There is an unusual noise pattern in the images for the amplifier C (top left).
`ds9 /global/cfs/cdirs/desi/spectro/redux/daily/preproc/20200315/00055641/preproc-b9-00055641.fits`
![Screenshot from 2020-03-23 09-27-00](https://user-images.githubusercontent.com/5192160/77339270-c154e400-6ce8-11ea-8bb7-fd142c648195.png)

**Comment by julienguy** [comment]
The extra convolution in camera r4 is visible in many images. It's been reported as an hardware issue in DESI ticket 593. https://desi.lbl.gov/trac/ticket/593

**Comment by sbailey** [comment]
Hardware problem with tickets in trac.  Closing this.
