### ISSUE TITLE
Bad spectrum: spike at blue/red arm transition

### ISSUE THREAD

**Issue by nathalieGit** [desihub/desispec#924]
There are a bunch of spectra on tile 68001 (March 15), with a large spike at the wavelength of transition between the blue and red arms. Examples attached below. They seem to be coming from spectrograph #2 fibers between 1000 and 1250.
A sublist of some targetIDs impacted:
35191266715109057
35191266710916172
35191266715107978
35191266715108867
35191266715109057
35191266719302563
Maybe this is already a known issue, but if not it’d be something to look into.
Thanks!
![PastedGraphic-1](https://user-images.githubusercontent.com/16261908/77013719-eeb03380-6970-11ea-9cd7-10d425c2576c.png)
![PastedGraphic-2](https://user-images.githubusercontent.com/16261908/77013727-f374e780-6970-11ea-8b1f-7414763a91a9.png)

**Comment by julienguy** [comment]
This is the same glow in the RED CCD of SM5 we had since the first light. We won't try to fix it by software. This CCD will be replaced after the shutdown. In the coming reductions we will flag those spectra as bad using a mask bit in the 'FIBERSTATUS' column of the fibermap table.

**Comment by sbailey** [comment]
This is a hardware problem that will be "fixed" by replacing the CCD.  Closing ticket.
