### ISSUE TITLE
Package dependencies in desispec

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#94]
I'm analyzing the dependencies of desispec in order to determine what packages need to be installed during Travis tests.

1. Is matplotlib strictly necessary for the functioning of the package?
2. How do we install redmonster in order to run tests requiring that package?

**Comment by sbailey** [comment]
matplotlib is needed for the QA plots (py/desispec/qa/qa_plots.py).  It looks like we don't have any coverage for that in the tests, but we should.  If installing matplotlib is a limiting factor for the future tests, we could use unittest.skipIf(...) to skip tests if it can't load matplotlib.

Installing redmonster for tests
1. git clone https://bitbucket.org/redmonster/redmonster
2. export PYTHONPATH=\`pwd\`/redmonster/python:$PYTHONPATH
3. export REDMONSTER_TEMPLATES_DIR=\`pwd\`/redmonster/templates
We don't use any of the scripts in redmonster/bin.
