### ISSUE TITLE
inconsistent EXPTIME in different HDUs

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#964]
/global/cfs/cdirs/desi/spectro/redux/andes/exposures/20200308/00054491/frame-z1-00054491.fits has EXPTIME=60 in HDU 0 (FLUX) but EXPTIME=15 in HDU 5 (FIBERMAP).

HDU 0 is correct; I suspect that HDU FIBERMAP is inheriting the keyword from one of the other input files used to generate the fibermap, e.g. the GFA acquisition exposure.  Track that down and fix so that wherever EXPTIME appears it correctly matches the spectroscopic exposure EXPID from the desi*.fits.fz raw data.

**Comment by djschlegel** [comment]
Possibly related to this ICS ticket: https://desi.lbl.gov/trac/ticket/539
