### ISSUE TITLE
update bad pixel masks

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#979]
Update bad pixel masks in desi_spectro_calib.

There was work on this from @biprateep in PR #946, but we didn't use those masks in the andes run because of some outstanding problems with what was / was not masked.  Revive that QA, fix problems as needed, update masks, and put into desi_spectro_calib for next production.

**Comment by biprateep** [comment]
Hi sorry for the lull on this issue. I had updated the masks after receiving feedback. But I am now going over them again. In the meantime I have written [this](https://desi.lbl.gov/trac/wiki/Pipeline/HowTo/CreatePixmask) wiki page detailing everything. The table of input thresholds is incomplete as of now and will update them in a day or two after I visually go through the masks again. Let me know if you have any comments about the wiki.

**Comment by sbailey** [comment]
Hi @biprateep @julienguy .  What is the status of these updated pixel masks?  IIRC you had some updated masks that almost made it into the andes run, but there were some outstanding requested changes (by email, not this ticket).

I'm adding this to the SV-start project for higher priority tracking.

**Comment by biprateep** [comment]
@sbailey Just wanted to give an update on it. I had created the masks a while back but recently have looked at all of them and incorporate minor tweaks based on @julienguy 's previous suggestions.  All the inputs used are documented in the wiki above and all the steps should be easily reproducible.

**Comment by julienguy** [comment]
I have visually verified the pixmasks. They are now committed in the DESI_SPECTRO_CALIB repository. Note the documentation in https://desi.lbl.gov/trac/wiki/Pipeline/HowTo/CreatePixmask
Thanks for this.
